- README.mediawiki
Also set the document title with the top level header, and place the TOC below the header text.
> Create a header for the spec

- README.mediawiki
General tweaks based on feedback from various channels.
> spec: change limit-limit rate. two minconfs. clarifications and cleanup

- spec/README.mediawiki
Allow mutliple pubkeys and signatures on UTXOs to make multi-sig possible.
> spec: allow multiple pubkeys and signatures with utxos

- server/asset/ltc/go.mod
- server/asset/ltc/go.sum
Resolving https://github.com/decred/dcrdex/issues/57
The real solution is to update ltcd.
> replace the invalid ltcutil pseudo-version

- server/order/order.go
rename base to quote in prefix struct
> server/order: rename Base to Quote in prefix

- spec/README.mediawiki
A few things I thought looked odd going through the spec.
I normalized the descriptions.  Not sentences, but still periods dividing thoughts...
The atomic swap explanation is really great and easy to understand! Nice exchange rate too. Looking ahead I see.
> specification: Fix grammar

- server/swap/swap.go
Comparing a `time.Time` (a struct) to another has the gotcha that the location can break the comparison.  This changes swap to use `time.Time.IsZero` instead, which only checks the Time's internal integer fields, not the location.
> swap: Use time.Time.IsZero and other tweaks

- dex/msgjson/types.go
- spec/fundamentals.mediawiki
- spec/orders.mediawiki
Some minor tweaks to the routes and their effects for order book subscriptions. Draft PR while I work through #62.
> spec: tweaks to order book subscription protocol

- server/swap/swap.go
I won't admit how long this took to figure out.
> swap: fix rounding bug

- server/asset/btc/btc_test.go
- server/swap/swap_test.go
> btc_test: Fix data race

- server/comms/comms_test.go
> comms_test: Fix data race

- client/db/bolt/db.go
- client/db/bolt/db_test.go
- client/db/db.go
- client/db/interface.go
- client/db/test/dbtest.go
- client/db/test/types_test.go
- client/db/types.go
- dex/btc/config.go
- dex/encode/encode.go
- dex/encode/encode_test.go
- dex/order/order.go
- dex/order/order_test.go
- dex/order/serialize.go
- dex/order/test/helpers.go
- dex/order/test/serialize_test.go
- go.mod
- go.sum
- server/auth/auth_test.go
- server/auth/registrar.go
- server/market/bookrouter.go
- server/market/epoch.go
- server/market/market_test.go
- server/market/orderrouter.go
- server/market/routers_test.go
- server/swap/swap.go
- server/swap/swap_test.go
It's not very full-featured yet, but all the parts are there.
> client: add bbolt-based client database

- client/core/types.go
- dex/msgjson/types.go
- server/dex/dex.go
- server/market/market.go
Pre-encode the config response as a json.RawMessage on DEX construction.
> dex: config response handler

- client/asset/dcr/dcr_test.go
Resolving client/asset/dcr data race in https://github.com/decred/dcrdex/issues/157
> client/asset/dcr: fix test data race

- client/core/core.go
- client/core/core_test.go
> client/core: fix synchronization issues

- dex/encode/encode.go
- dex/encrypt/encrypt.go
- dex/encrypt/encrypt_test.go
New **encrypt** package uses argon2id and xchacha20poly1305.
Resolves #151
> encrypt: key derivation and encryption

- README.md
Also removes the outdated project structure.
> readme: add build and contributing instructions

- client/cmd/dexc/main.go
- client/cmd/dexc/ui/config.go
- client/cmd/dexc/ui/config_test.go
- client/cmd/dexc/ui/widgets.go
- client/rpcserver/rpcserver.go
- client/rpcserver/rpcserver_test.go
Ensure that core.Core satisfies the clientCore interface. Add fields
needed to set up the rpcserver to configuration.
> client/rpcserver: Update

- spec/comm.mediawiki
- spec/fundamentals.mediawiki
- spec/orders.mediawiki
Resolves https://github.com/decred/dcrdex/issues/126
Code changes are in PR https://github.com/decred/dcrdex/pull/129
> spec: update config route response with market variables

- client/rpcserver/rpcserver_test.go
- client/webserver/webserver.go
- client/webserver/webserver_test.go
Stopping the listeners abruptly kills the server. Instead use
http.Server.Shutdown to close gracefully without interrupting active
connections.
Also fix TestClientMap in webserver.
> client/webserver: use http.Server.Shutdown to stop

- client/core/core.go
`client/core.extractError` always referred to the `'connect'` route, however it is used for several routes.
> client/core: extractError displays message for appropriate route

- client/core/core_test.go
- client/db/bolt/db.go
- client/db/bolt/db_test.go
- client/db/bolt/log.go
- client/db/interface.go
> client: add client database backup.

- client/core/core.go
The prereg timer must be stopped in Register if it is running.
Also, `reFee` seemed to be lacking a call to `dc.acct.pay()` and `c.authDEX` after a successful `notifyFee`.
> client/core: stop and nil the prereg timer on Register

- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
Dust and min fee checks should be against `reservoir` and `subtractee`, added in recent work, instead of `changeOutput` and `remaining`. `TestWithdraw` is modified to run with available balance = withdraw amount.
> client/asset: fix bug with dcr withdraw

- README.md
I believe this is the correct command here.
> readme: Fix psql command.

- client/core/core_test.go
This adds tests for the `MatchProof` and `EpochOrder` message handlers.
> core: add missing handler tests.

- server/admin/api.go
- server/admin/server.go
- server/admin/server_test.go
- server/cmd/dcrdex/main.go
- server/dex/dex.go
I have some server suspend/resume work that builds on these changes.  Cherry picked them here since they are otherwise unrelated to the other work, and the other PR might not be up for a couple days.
> server/admin: test apiPing, writeJSON, and writeJSONWithStatus

- spec/admin.mediawiki
Resolves #124. Corrects previous omission. No substantive changes.
> spec: add broadcast timeout to admin exchange variables section

- spec/orders.mediawiki
> spec: describe commitment restrictions

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/wallets.tmpl
I think I put this in there for debugging once and forgot about it. 
Incrementing the js and css "versions" while I'm here.
> app: remove misplaced html

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/btc/regnet_test.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/simnet_test.go
- client/asset/driver.go
- client/asset/interface.go
- client/core/core.go
- client/core/core_test.go
- client/core/notification.go
- client/core/trade.go
- client/core/wallet.go
- client/db/types.go
- client/webserver/webserver.go
Startup wallet logging:
> [INF] CORE: Loaded btc wallet configuration. Account "gamma", Deposit address = mfXVDp5eZx6QxZgHuB9aM7gNcW71AMwv9u
> [INF] CORE: Loaded dcr wallet configuration. Account "default", Deposit address = SsfWraUBDUtU2dKAhBAYcb8HVTEupAnj9ta
Connect/unlock wallet logging:
> [INF] CORE: Connected to and unlocked dcr wallet. Account "default" balance available = 6533918787426 / locked = 0, Deposit address = SsfWraUBDUtU2dKAhBAYcb8HVTEupAnj9ta
> [INF] CORE: Connected to and unlocked btc wallet. Account "gamma" balance available = 8400000000 / locked = 0, Deposit address = mfXVDp5eZx6QxZgHuB9aM7gNcW71AMwv9u
Negotiation logs (client here is maker and taker):
```
[DBG] WEB: poke: Order placed: buying 1.00000000 dcr (1f4a62f5)
[DBG] WEB: poke: Preimage sent: match cycle has …
```
> client: logging with core, webserver, and asset

- client/rpcserver/rpcserver.go
- client/rpcserver/rpcserver_test.go
- client/rpcserver/types.go
- client/rpcserver/types_test.go
> client/rpcserver: Correctly check uint args.

- client/core/core.go
> client/core: Connect to wallets if not connected.

- server/asset/dcr/dcr.go
Because the client does not accept a context or error on a disconnection,
the app will not shut down properly, waiting for the request to return
indefinitely. This will shut down the RPC client in a separate go
routine which will cause the client to return an error and the app to
continue shutting down.
closes #321
> asset/dcr: Shut down the RPC client in a goroutine

- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/doc.js
- client/webserver/site/src/js/markets.js
> Handle not known asset

- client/core/types.go
- client/rpcserver/handlers.go
- client/rpcserver/handlers_test.go
- client/rpcserver/rpcserver.go
- client/rpcserver/rpcserver_test.go
>  client/rpcserver: Add exchanges route.

- client/webserver/webserver_test.go
In the TestClientMap tests, a goroutine was running that accesses the logger without waiting for it to shutdown, but any following test with `newTServer` would try to write to the package-level `log` causing a data race.
Also remove `enableLogging` since the `Server` constructor sets it.
For future work, get rid of the package level logger.
> client/webserver: fix log race

- server/market/market_test.go
Resolves https://github.com/decred/dcrdex/issues/387
We weren't supervising a testing goroutine in `TestMarket_Suspend_Persist`, but we were in `TestMarket_Suspend`.
Also use `mkt.waitForEpochOpen` in place of sleeps in that test.
> market: supervise feed receiver and use waitForEpochOpen

- client/core/core.go
- client/core/core_test.go
- client/core/trade.go
- dex/msgjson/msg_test.go
- dex/msgjson/types.go
- server/auth/auth.go
- server/auth/auth_test.go
- server/auth/registrar.go
- server/market/orderrouter.go
- server/swap/swap.go
> msgjson: remove error return value from Serialize methods

- client/webserver/site/src/js/app.js
- client/webserver/site/src/js/charts.js
- client/webserver/site/src/js/markets.js
- client/webserver/site/src/js/register.js
- client/webserver/site/src/js/wallets.js
Resolves https://github.com/decred/dcrdex/issues/398
> fix url=>host name change in js, typos

- client/webserver/site/src/js/login.js
> app: display login error on submit

- client/comms/wsconn_test.go
> client/comms: ensure server goroutine runs before attempting ws conns

- client/core/bookie.go
- client/core/core.go
- client/core/core_test.go
- client/core/notification.go
- client/core/trade.go
- client/core/types.go
- client/db/bolt/db.go
- client/db/bolt/db_test.go
- client/db/test/dbtest.go
- client/db/test/types_test.go
- client/db/types.go
- client/rpcserver/handlers.go
- client/rpcserver/rpcserver.go
- client/rpcserver/rpcserver_test.go
- client/rpcserver/types.go
- client/rpcserver/types_test.go
- client/rpcserver/websocket.go
- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/app.js
- client/webserver/site/src/js/markets.js
- client/webserver/site/src/js/register.js
- client/webserver/site/src/js/wallets.js
- client/webserver/types.go
- client/webserver/webserver_test.go
- client/webserver/websocket.go
`Addr` is used for user input that's not clean yet. `Host` is used everywhere else. Many fields named `DEX` are also changed to `Host`. Corresponding JSON tags -> javascript properties are `addr` and `host`.
> multi: finish converting url to addr, host

- client/webserver/site/src/js/doc.js
- client/webserver/site/src/js/markets.js
Disable wheel increment/decrement action on number inputs to resolve https://github.com/decred/dcrdex/issues/376.
> app: disable mouse wheel on number-type inputs

- client/core/core.go
- client/webserver/api.go
- client/webserver/site/src/css/market.scss
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/html/settings.tmpl
- client/webserver/site/src/js/settings.js
- client/webserver/webserver.go
> Settings add additional DEXes

- server/cmd/dcrdex/config.go
- server/cmd/dcrdex/main.go
> dcrdex: add adminsrvpass config option

- client/comms/wsconn_test.go
Since SetPongHandler used t.Log, the connection needs to be closed
before the test can return or go fatal.  After server Shutdown, Close
each hijacked connection and wait for their in/out handlers to return.
Also make the http handler that does the upgrade non-blocking
since the request handler isn't supposed to live as long as the
upgraded connection.
This resolves the race observed in https://github.com/decred/dcrdex/runs/740180782#step:5:151
> comms: fix test pong handler log race

- dex/ws/wslink.go
- server/auth/auth.go
- server/comms/link.go
- server/market/market.go
Resolving (partially) https://github.com/decred/dcrdex/issues/446, the unknown order ID error.
> market: preimage collection fixes

- server/swap/swap.go
- server/swap/swap_test.go
Resolves https://github.com/decred/dcrdex/issues/425
> swap: sign audit, redemption, and revoke_match requests

- client/core/core.go
- client/core/core_test.go
- client/core/errors.go
Resolves #467
Fixes bugs and adds coverage. Adds coded errors that can be used for ID.
> core: fix register test

- dex/dcr/script.go
- server/asset/dcr/dcr.go
- server/asset/dcr/dcr_test.go
- server/auth/auth.go
- server/dex/dex.go
might resolve https://github.com/decred/dcrdex/issues/392
> auth,server/asset/dcr: Add dcr.FeeCoin, an auth.FeeChecker

- client/core/core.go
- client/db/bolt/db_test.go
- client/db/types.go
- client/webserver/site/src/js/markets.js
Resolves #473
Fixes a bug where the exchanges map wasn't loading from the DB.
Small refactor to store the balance data more often.
> core/db: fix balance bugs

- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/doc.js
- client/webserver/site/src/js/wallets.js
> app: update wallet status text on wallets view

- client/core/core.go
Looking through client and server, these were the only two spots I could find where the coinID was not being formatted for logs.
closes #480
> client/core: Use coinIDString everywhere.

- server/cmd/dcrdex/main.go
> cmd/dcrdex: Stop loading swap state on shutdown signal.

- client/webserver/site/src/css/market.scss
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/markets.js
> app: Order preview show quote amount

- client/comms/wsconn.go
- client/comms/wsconn_test.go
Resolving https://github.com/decred/dcrdex/issues/450
The initial read deadline was not set for a `client/comms.wsConn`, only in the pong handler.  This means that in `TestWsConn`, the connection never actually timed out and reconnected in `reconnectAndPing` because the server never sent an initial ping that would have set the read deadline.
This PR sets an initial read deadline in `(*wsConn).connect`, just after `Dial`ing the peer (server).  Without this, the client would never timeout and disconnect/reconnect if the server never sent an initial ping.  Now the test logs show the reconnect that was not previously happening:
```
[ERR] Debug: read error (read tcp 127.0.0.1:56968->127.0.0.1:43971: i/o timeout), attempting reconnection
[INF] Debug: Attempting to reconnect to …
```
> client/comms: add a missing initial read deadline

- client/asset/btc/btc.go
- client/asset/btc/walletclient.go
- client/asset/dcr/dcr_test.go
- client/webserver/site/src/js/wallets.js
- server/asset/btc/btc.go
- server/asset/btc/btc_test.go
Resolves https://github.com/decred/dcrdex/issues/545
> server/asset/btc: round, not trunc, on btc->sat

- client/core/core.go
- dex/msgjson/types.go
- dex/testing/dcrdex/README.md
- dex/testing/dcrdex/harness.sh
- server/admin/api.go
- server/admin/server.go
- server/admin/server_test.go
- server/dex/dex.go
- spec/admin.mediawiki
> admin: Add notifyall endpoint.

- client/cmd/dexc/main.go
- client/core/core.go
> Prevent shutdown with active orders

- client/asset/btc/btc.go
- client/asset/dcr/dcr.go
To troubleshoot an issue for now, but will polish and merge eventually. This will print the raw transaction hex when `signrawtransaction` fails.
> add log output for dcr signrawtransaction errors

- client/asset/btc/btc.go
- client/asset/dcr/dcr.go
- client/core/core.go
- client/core/core_test.go
- dex/msgjson/types.go
- server/market/orderrouter.go
- server/swap/swap.go
A somewhat random collection of logging and error detail improvements and fixes.
> multi: various logging and error detail fixes

- client/core/core.go
- client/core/notification.go
- client/rpcserver/handlers.go
- client/rpcserver/handlers_test.go
- client/rpcserver/rpcserver.go
- client/rpcserver/rpcserver_test.go
- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/site/src/js/app.js
- client/webserver/site/src/js/wallets.js
- client/webserver/webserver.go
- client/webserver/webserver_test.go
- client/websocket/websocket.go
- client/websocket/websocket_test.go
- dex/logging.go
- server/cmd/dcrdex/config.go
- server/cmd/dcrdex/go.mod
- server/cmd/dcrdex/log.go
- server/cmd/dcrdex/signal.go
- altered context passing
- waitgroups for launched websocket handlers
- notify of wallet lock/unlock/close/create from Core
> client websocket refactoring

- client/comms/wsconn.go
- client/core/core.go
- client/core/core_test.go
- client/core/trade.go
- server/comms/link.go
- server/market/market.go
- server/swap/swap.go
Resolves https://github.com/decred/dcrdex/issues/629
> client/core: less spammy logging

- server/auth/auth.go
- server/market/market.go
Count all errors from `RequestWithTimeout` in `collectPreimages` as a miss,
no longer trying to forgive the user based on unknown errors that
might indicate server connectivity trouble.
This simplifies the function, and avoids misuse of the `piChan`.
This also uses a new `dex.ErrorKind` in `auth`, `ErrUserNotConnected`,
to communicate to the caller of `RequestWithTimeout` where the error
occurred. This just helps logging for now.
This addresses a case where a user has two orders requiring preimages in
the same epoch, but the user is disconnected, and the first request for that
user correctly results in `[DBG] MKT: Preimage request failed: client gone.`
and a recorded "miss", but the second request results in
`[WRN] MKT: Preimage request failed: unknown user` because the auth
manager has …
> server/{auth,market}: any preimage request error is a miss

- client/core/core_test.go
Fee and balance notes may be sent from concurrent goroutines, and may thus come in any order.  Fix test to work with this.
> client/core: fix tests for fee and balance notes in any order

- server/asset/btc/btc_test.go
Fixes data race as in https://github.com/decred/dcrdex/runs/1043851813#step:5:121
> server/asset/btc: [TEST] fix data race on testChain block

- spec/orders.mediawiki
To match the implementation in #660.
> spec: simplify match_status payload

- client/webserver/site/src/js/app.js
- client/webserver/site/src/js/ws.js
A compliment to #664. That should go in first.
> app: add log timestamp and websocket logging

- client/core/core.go
I don't think we have an issue for this, but it has come up multiple times.
> core: attempt to connect and retrieve balance from all wallets on log in

- client/core/core.go
- client/core/core_test.go
A more targeted synchronization pattern to solve the ordering-preimage race. The old pattern would hold up all preimage requests if any order was processing.
> core: refactor ordering-preimage sync

- client/webserver/site/src/js/markets.js
> app: load wallet defaults on markets view new wallet form

- client/core/core.go
- client/core/core_test.go
- client/core/trade_simnet_test.go
- client/core/types.go
- client/core/wallet.go
- client/rpcserver/handlers.go
- client/rpcserver/types.go
- client/webserver/live_test.go
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/forms.js
- client/webserver/site/src/js/wallets.js
- dex/testing/btc/base-harness.sh
- server/admin/prompt.go
Resolves #591. Also enables some upgrades I want to make to the simnet harness.
> core: allow empty password to signify unencrypted wallet

- client/core/core.go
- client/core/errors.go
- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/app.js
- client/webserver/site/src/js/wallets.js
- client/webserver/webserver.go
- client/webserver/webserver_test.go
This should probably sneak into the release branch.
> core, ui: enable generation of new deposit addresses

- client/webserver/live_test.go
- client/webserver/site/src/css/main.scss
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/markets.js
- client/webserver/site/src/js/register.js
- client/webserver/site/src/js/settings.js
- client/webserver/site/src/js/wallets.js
> ui: add close buttons to modal dialogs

- client/asset/btc/btc.go
- client/asset/dcr/dcr.go
- client/comms/wsconn.go
Release branch version of #813.
> release-0.1: align 64-bit fields for atomic

- client/webserver/middleware.go
- client/webserver/webserver.go
Resolves https://github.com/decred/dcrdex/issues/839
> client/webserver: webkit CSP connect-src workaround

- spec/admin.mediawiki
Adds forgive_match and resume information. Also updates suspend to
explain the possible arguments.
> spec/admin: Add missing endpoints.

- client/core/core.go
Resolves https://github.com/decred/dcrdex/issues/894
> client/core: fix OrderFilter offset length check

- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- dex/networks/dcr/script.go
Resolves https://github.com/decred/dcrdex/issues/812
> fix change handling in sendWithReturn when subtracting from existing out

- client/webserver/site/src/css/market.scss
- client/webserver/site/src/css/market_dark.scss
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/markets.js
This diff differentiates between Sell/Buy orders by using associated colors scheme
in order confirmation modal.
Closes #888
> ui: differentiate between Buy/Sell orders in confirmation modal

- client/core/core.go
This resolves the following shutdown error message that we've been ignoring with remarkable conviction since forever:
```
[INF] CORE: DEX client core off
[ERR] CORE: refreshUser: error checking if app is initialized: database not open
[INF] DEXC: Exiting dexc main.
```
The error comes from a `refreshUser` called from `(*Core).handleConnectEvent` via a `dexConnection's` `ConnectEventFunc` (see `(*Core).connectDEX`), which fires on disconnect too, such as on shutdown.
Resolves https://github.com/decred/dcrdex/issues/417
> start db first and stop it last

- client/webserver/site/src/js/app.js
- client/webserver/site/src/js/markets.js
> dexc: sync GUI orders list when placing an order via dexcctl

- client/webserver/site/src/js/register.js
> client: show correct error message on Add a Dex register form

- client/webserver/site/src/js/markets.js
> ui: fix verify order form for market orders.

- client/core/core.go
It looks like this was changed from a map to slice at some point and the log here was overlooked.
> core: Fix active orders log.

- run_tests.sh
The go mod tidy check should only be done for the latest supported Go version since they may have different ideas about how to format or manage the go.{mod,sum} files.
> ci: go mod tidy only on latest, shellchecks

- server/market/bookrouter.go
Although market suspend with persist=false was purging the book both in
Market's in-memory book and in the DB, the outgoing BookRouter's msgBook
was not resetting its orders map.  You can observe the bug without this change
by doing a suspend?persist=false, notice the book and chart clearing, but then
refreshing or restarting dexc brings the book back even though the market
really has no booked orders.
This change reinitializes the msgBook.orders map on purge.
This also moves a bit of repetative code out of the main runBook loop.
> server/market: suspend with purge needs to clear BookRouter

- dex/testing/btc/base-harness.sh
- dex/testing/btc/harness.sh
- dex/testing/dcr/harness.sh
Mostly so that I can use the harness from my laptop on the couch, but also enables btc block filters.
> testing: open up simnet harnesses to network

- client/webserver/site/src/css/application.scss
- client/webserver/site/src/css/market.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/charts.js
- client/webserver/site/src/js/markets.js
Final Result:
https://user-images.githubusercontent.com/10324528/111234218-be888880-85f6-11eb-9057-a71a471bf40f.mp4
Closes #997.
> responsive GUI

- spec/README.mediawiki
- spec/fundamentals.mediawiki
> spec: Add apiver to server config response.

- dex/testing/dcrdex/harness.sh
The dex/test/dcrdex/harness.sh script builds a dcrdex binary with short lock times for testing, but it also installs the binary to `${GOPATH}/bin` which is a little dangerous and also inconvenient. The harness would also start the binary without an absolute path, assuming that `${GOPATH}/bin` would be on the top of the user's `PATH`.  This modifies the harness to generate a dcrdex build into the `~/dextest/dcrdex`, which is also the `--appdata` folder for the harness.
> build dcrdex harness bin to dextest folder

- client/core/trade_simnet_test.go
> trade_simnet_test: Fix balance errors.

- AUTHORS
- README.md
- docs/release-notes/release-notes-0.1.0.md
- docs/release-notes/release-notes-0.1.1.md
- docs/release-notes/release-notes-0.1.2.md
- docs/release-notes/release-notes-0.1.3.md
- docs/release-notes/release-notes-0.1.4.md
- docs/release-notes/release-notes-0.1.5.md
- docs/release-notes/release-notes-0.2.0.md
- go.mod
- go.sum
- server/cmd/dcrdex/config.go
Final details and release notes for 0.2 ([preview](https://github.com/decred/dcrdex/blob/de241b08c11af1a4f1435aee5d5878d42321b3b1/docs/release-notes/release-notes-0.2.0.md)).
Resolves https://github.com/decred/dcrdex/issues/790
> draft 0.2 release notes and other release details

- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- go.mod
- go.sum
The value has been added to the verbose block header. Retrieve it from
there.
> asset/dcr: Remove calcPastMedianTime.

- client/core/core.go
- client/core/core_test.go
- client/core/trade.go
I didn't try to deploy DEX locally and test this change manually (yet), do we have some basic automatic smoke tests that would uncover issues (if any) with changes similar to these ?
Closes https://github.com/decred/dcrdex/issues/1020.
> Client should properly validate match commit checksum upon match_proof message.

- README.md
> Add information about fees to readme. 

- README.md
- server/cmd/dcrdex/sample-markets.json
- spec/README.mediawiki
- spec/admin.mediawiki
Adds some more details to per asset variables, removes some bad white spaces, and adds an eth example to the example markets.json
> spec: Add eth server details.

- client/cmd/dexc/main.go
- client/core/core.go
> mulit: Move shutdown prompt to app.

- client/webserver/site/src/js/markets.js
> order form: hide by default and show iff wallets are set.

- client/webserver/site/src/js/charts.js
> Fix precision out of range when redrawing chart

- client/core/bookie.go
This diff was made by @chappjc in order for newer clients to still have older servers compatibility.
This still open for discussion if needed.
> Check LotSize and RateStep for older servers compatibility

- client/webserver/locales/en-us.go
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/localized_html/en-US/forms.tmpl
> ui: Update cancel popup text to respect cached password.

- client/core/trade.go
Resolves https://github.com/decred/dcrdex/issues/1158
This prevents the `isRefundable` check from logging expiry times with negative remaining time-to-expiry.  This is not quite as good as "the estimated time that it will be able to be refunded", as suggested by the linked issue, but that would require a bunch of backend work and modifying the `client/asset.Wallet.LocktimeExpired` method for each asset to return more details with such an estimate, which would presumably be based on the current median time and the asset's target block interval.  It would be a wild guess at best, so I'm not sure we ever want to go that route.
Log before locktime is reached:
> [INF] CORE: Contract for match 1ef2eb2... with swap coin efe2d6...:0 (DCR) **expires at 2021-08-31 16:19:15 +0000 UTC (28s).**
Log …
> client/core: do not log negative expiry duration

- .gitignore
- server/cmd/usermatches/main.go
- server/db/driver/pg/pg.go
This creates a new CLI app called **usermatches** for directly retrieving match data from the DB.
This also modifies server/db/driver/pg with a new constructor, `NewArchiverForRead`, for accessing the `Archiver` in a read-only mode.
> introduce server/cmd/usermatches

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- server/asset/eth/common.go
> eth/client: PreSwap

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
> client/eth: PreRedeem

- client/core/core.go
- client/core/core_test.go
> client: remove obsolete auto account disable

- server/market/market.go
"execute" any epoch orders in DB that may be left over from unclean shutdown.  Whatever epoch they were in will not be seen again.
> server/market: drop epoch order on startup

- client/webserver/site/src/js/markets.js
Resolves https://github.com/decred/dcrdex/issues/1294
> client/webserver/site: clicking rate uses conversion factor

- client/webserver/site/package-lock.json
https://github.com/advisories/GHSA-93q8-gq69-wqmw
https://github.com/advisories/GHSA-rp65-9cf3-cjxr
> client: update node deps

- server/market/orderrouter.go
> [backport/release-v0.4] server/market: fix wrong asset for RequiredOrderFunds on market-buy

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
Allow the gas fee limit for the wallet to be configured.
> client/eth: Configure gas fee limit

- server/asset/eth/eth.go
- server/asset/eth/eth_test.go
Use decred's secp256k1 package.
closes #1154
> server/eth: Implement ValidateSignature.

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
> client/eth: Implement PayFee.

- client/core/notification.go
In testing 0.4 a bunch in different configurations, it became clear that the `spots` note logging was very spammy and completely uninformative for the console.
It gets especially bad when you have numerous markets and DEXs.  e.g.
```
2021-12-22 21:58:32.024 [TRC] CORE: notify: |DATA| (spots)
2021-12-22 21:58:32.024 [TRC] CORE: notify: |DATA| (spots)
2021-12-22 21:58:33.023 [TRC] CORE: notify: |DATA| (spots)
2021-12-22 21:58:36.024 [TRC] CORE: notify: |DATA| (spots)
2021-12-22 21:58:40.023 [TRC] CORE: notify: |DATA| (spots)
2021-12-22 21:58:40.025 [TRC] CORE: notify: |DATA| (spots)
2021-12-22 21:58:40.025 [TRC] CORE: notify: |DATA| (spots)
```
This change just makes a special case in the `Core` note logging method to skip certain note types, namely `NoteTypeSpots`, but other notes in the …
> client/core: do not log certain notes

- client/core/core.go
- client/core/trade.go
> client/core: use fee suggestion for Withdraw

- client/webserver/site/src/js/wallets.js
Do not localize available max amount when populating the Amount field in the withdraw UI.  Fixes #1386
> Withdraw max amount field value fix

- client/asset/btc/btc.go
Resolves https://github.com/decred/dcrdex/issues/1415
> client/asset/btc: watchBlocks panic fix

- client/core/core.go
possibly resolving discussion in https://github.com/decred/dcrdex/pull/1398#issuecomment-1011641305
> client/core: track connection on discover via Register

- dex/testing/dcr/harness.sh
With the switch to spv for the beta node, some functions cannot complete
through wallet. Add a direct rpc link to the dcrd beta node.
On master you will probably see:
```
$ ./mine-beta 
-9: RPC passthrough requires dcrd RPC synchronization
-9: RPC passthrough requires dcrd RPC synchronization
```
> testing/dcr: Add node control script.

- client/cmd/dexc/main.go
In production, if there is a panic that kills dexc, the stack that gets dumped is often lost to the terminal window which is often closed when dexc dies.  This adds a recover in `mainCore` to log the panic and the stack.
> dexc: recover and log panic in main

- client/asset/btc/btc.go
- client/asset/btc/spv.go
- client/asset/interface.go
- client/core/core.go
- client/core/wallet.go
- client/webserver/http.go
- client/webserver/live_test.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/wallets.js
- client/webserver/site/src/localized_html/en-US/wallets.tmpl
- client/webserver/site/src/localized_html/pl-PL/wallets.tmpl
- client/webserver/site/src/localized_html/pt-BR/wallets.tmpl
- client/webserver/site/src/localized_html/zh-CN/wallets.tmpl
- client/webserver/webserver.go
- client/webserver/webserver_test.go
Adds a link to the wallet page to download the neutrino log file for the BTC SPV wallet.
Closes #1437
> client/webserver/core: Link to wallet log file

- client/core/core_test.go
In order to avoid importing specific assets, create fake ones modeled
after actual assets.
closes #1477
> core/test: Use generic drivers.

- client/asset/btc/spv.go
Resolves https://github.com/decred/dcrdex/issues/1491
```
When sendRawTransaction returns with a non-nil error, even if we hit the
PublishTransaction timeout (defaultBroadcastWait), we still need to
unlock the outpoint in the wallet.
Although listunspent no longer returns the spent outpoint, the
lockedSats computations reference the locked outpoints listed by
listlockunspent, and they are not removed when spent.
```
> client/asset/btc: unlock outpoint on sendRawTransaction

- client/db/bolt/db.go
Fixes a panic introduced by #1475
> client/db: Do not check cancel's trade.

- client/cmd/dexc/version/version.go
- client/cmd/dexcctl/version.go
- pkg.sh
- server/cmd/dcrdex/version.go
This begins the v0.5 release cycle.  Hopefully this will be changed to
v1.0 before the release.
> bump to v0.5.0

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/markets.js
- client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pl-PL/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl
- client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl
Resolves https://github.com/decred/dcrdex/issues/1521
> ui: fix disconnected icon js error

- client/webserver/site/src/css/main.scss
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/html/register.tmpl
- client/webserver/site/src/html/settings.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/localized_html/en-US/forms.tmpl
- client/webserver/site/src/localized_html/en-US/markets.tmpl
- client/webserver/site/src/localized_html/en-US/register.tmpl
- client/webserver/site/src/localized_html/en-US/settings.tmpl
- client/webserver/site/src/localized_html/en-US/wallets.tmpl
- client/webserver/site/src/localized_html/pl-PL/forms.tmpl
- client/webserver/site/src/localized_html/pl-PL/markets.tmpl
- client/webserver/site/src/localized_html/pl-PL/register.tmpl
- client/webserver/site/src/localized_html/pl-PL/settings.tmpl
- client/webserver/site/src/localized_html/pl-PL/wallets.tmpl
- client/webserver/site/src/localized_html/pt-BR/forms.tmpl
- client/webserver/site/src/localized_html/pt-BR/markets.tmpl
- client/webserver/site/src/localized_html/pt-BR/register.tmpl
- client/webserver/site/src/localized_html/pt-BR/settings.tmpl
- client/webserver/site/src/localized_html/pt-BR/wallets.tmpl
- client/webserver/site/src/localized_html/zh-CN/forms.tmpl
- client/webserver/site/src/localized_html/zh-CN/markets.tmpl
- client/webserver/site/src/localized_html/zh-CN/register.tmpl
- client/webserver/site/src/localized_html/zh-CN/settings.tmpl
- client/webserver/site/src/localized_html/zh-CN/wallets.tmpl
> ui: line break long error messages

- client/asset/btc/btc.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/externaltx.go
- client/asset/dcr/simnet_test.go
- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/interface.go
- client/core/core.go
- client/core/core_test.go
- client/core/trade.go
Resolves https://github.com/decred/dcrdex/issues/1516 and https://github.com/decred/dcrdex/issues/1484
> client: no error from FeeRate

- client/asset/btc/spv.go
Resolves https://github.com/decred/dcrdex/issues/1546
> client/asset/btc: balance should consider untrusted UTXOs

- server/asset/btc/btc.go
- server/asset/btc/rpcclient.go
- server/asset/dcr/dcr.go
This diff:
1. checks if  `-txindex` is enabled for bitcoind 
2. checks if  `--txindex` is enabled for dcrd.
Closes #1535
> server/asset: Check if txindex is enabled.

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/markets.js
- client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pl-PL/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl
- client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl
Bugfixes from https://github.com/decred/dcrdex/pull/1534
Also included on the 0.4.3 staging branch: https://github.com/decred/dcrdex/tree/staging-v0.4.3
> [0.4.3] ui: backport JS bug fixes from typescript migration

- client/comms/wsconn.go
- go.mod
- go.sum
Allow context cancellation to cancel dialing the server without having to wait HandshakeTimeout
> client/comms: use DialContext

- client/asset/dcr/config.go
This diff expands dcr wallet rpc cert.
> expand dcr wallet rpc cert

- client/webserver/site/src/js/app.ts
Prevents a couple of the errors we see when logging in.
> app: ignore balance and spot notifications during login

- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/register.ts
- client/webserver/site/src/js/settings.ts
- client/webserver/site/src/localized_html/en-US/forms.tmpl
- client/webserver/site/src/localized_html/pl-PL/forms.tmpl
- client/webserver/site/src/localized_html/pt-BR/forms.tmpl
- client/webserver/site/src/localized_html/zh-CN/forms.tmpl
> client: fix confirm when adding new dex server

- client/webserver/locales/en-us.go
- client/webserver/site/src/css/wallets.scss
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/wallets.ts
- client/webserver/site/src/localized_html/en-US/wallets.tmpl
- client/webserver/site/src/localized_html/pl-PL/wallets.tmpl
- client/webserver/site/src/localized_html/pt-BR/wallets.tmpl
- client/webserver/site/src/localized_html/zh-CN/wallets.tmpl
Adds a disappearing message confirming that the deposit address has been copied.
> ui: Copy deposit address alert

- dex/testing/loadbot/go.mod
- run_tests.sh
First commit was the test: https://github.com/decred/dcrdex/runs/7025445062?check_suite_focus=true#step:5:482
Will squash on merge.
> CI: build and tidy loadbot

- client/webserver/live_test.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/basepage.ts
- client/webserver/site/src/js/dexsettings.ts
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/order.ts
- client/webserver/site/src/js/register.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/settings.ts
- client/webserver/site/src/js/wallets.ts
- client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pl-PL/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl
- client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl
I've wanted to do this for a while, but its need became more apparent in #1622. This prevents the need to pass notifications to forms.
> app: refactor frontend notification flow

- client/asset/btc/btc.go
> client: fix native btc wallet creation with fee limit smaller than 1sat/B

- client/webserver/locales/en-us.go
- client/webserver/locales/pl-pl.go
- client/webserver/locales/pt-br.go
- client/webserver/locales/zh-cn.go
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/localized_html/en-US/forms.tmpl
- client/webserver/site/src/localized_html/pl-PL/forms.tmpl
- client/webserver/site/src/localized_html/pt-BR/forms.tmpl
- client/webserver/site/src/localized_html/zh-CN/forms.tmpl
Resolves https://github.com/decred/dcrdex/issues/1631
> ui: clarify disable_irreversible action

- client/asset/btc/spv.go
-Add dust value check for btc spv wallet send and withdraw. Closes #1703
> check dust withdraw/send value for btc spv wallet

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
This diff increases the gas fee cap for redemptions to 2x base fee if the base fee > the fee suggestion. If the wallet does not have enough available funds for this, then the funds that are available will be used.
> client/eth: Increase gas fee cap for redemptions when base fee is too high

- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/markets.ts
I don't know how these have evaded us for so long.
> ui/markets: banish 1e8 for good

- server/db/driver/pg/orders.go
- server/market/market.go
Resolves https://github.com/decred/dcrdex/issues/1697
When a revoked order (not match) has an active swap complete without the user being at fault, it should not grant order completed status for accounting purposes.  This makes the changes so that revoked orders are handled similar to canceled orders by removing the order ID from the `settling` map, which is the established pattern when there is no longer a need track to settling quantity for `SwapDone`'s accounting. (See other calls to `book.Remove{UserOrders}` and `m.unbookedOrder`.)
> server: revoked orders do not get completion credit

- client/core/simnet_trade.go
> simnet_trade_tests: Fix eth and doge.

- client/asset/dcr/spv.go
- client/asset/dcr/spv_test.go
Resolves https://github.com/decred/dcrdex/issues/1755
> client/asset/dcr: fix SPV AccountOwnsAddress for foreign addrs

- .github/workflows/build.yml
- client/comms/wsconn.go
- client/core/simnet_trade.go
- client/core/trade.go
- client/db/types.go
- client/rpcserver/handlers.go
- dex/calc/convert.go
- dex/encode/encode.go
- dex/encode/passbytes.go
- dex/encode/passbytes_test.go
- dex/networks/zec/addr.go
- server/asset/dcr/live_test.go
- server/book/orderpq.go
- server/db/interface.go
- server/market/market.go
See https://github.com/decred/dcrd/pull/2976 and https://go.dev/doc/comment
> go 1.19 formatting and CI

- client/Dockerfile
Updated builder/base images to latest stable versions.
> Docker build update

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/order.ts
- client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pl-PL/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl
- client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl
Resolves https://github.com/decred/dcrdex/issues/1775
Tested in Decrediton with a modified https://github.com/decred/decrediton/pull/3791
> ui: window.location on order form closers

- client/cmd/dexc/version.go
- client/cmd/dexcctl/version.go
- pkg.sh
- server/cmd/dcrdex/version.go
This start the 0.6 dev cycle, which should become 1.0 closer to release.
> start the 0.6 dev cycle

- docs/wiki/Simnet-Testing.md
This diff updates the `Simnet-Testing` wiki with how to acquire simnet funds. [#1688 (comment)](https://github.com/decred/dcrdex/pull/1688#discussion_r948481148)
> wiki : update simnet wiki

- client/webserver/site/src/js/forms.ts
> site: set autocomplete for dynamically-generated rpc password fields

- client/webserver/template.go
Otherwise, you have to refresh twice to see the changes.
> client/webserver: use reloaded page template

- client/asset/btc/btc.go
- client/asset/btc/rpcclient.go
- client/asset/btc/spv.go
- client/asset/dcr/config.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/rpcwallet.go
- client/asset/dcr/simnet_test.go
- client/asset/dcr/spv.go
- client/asset/dcr/wallet.go
- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/interface.go
- client/core/core.go
> client:{dcr,eth}: Live wallet reconfiguration

- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/dexsettings.ts
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/register.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/settings.ts
- client/webserver/site/src/js/wallets.ts
> site: remove api errors from bell notification

- client/asset/btc/btc.go
This PR is a continuation of: #1618
depends on #1654
> Add external api fallback fee for btc rpc wallet

- client/asset/bch/bch.go
- client/asset/btc/btc.go
- client/asset/btc/rpcclient.go
- client/asset/doge/doge.go
- client/asset/zec/zec.go
> client: add positional fee rate param

- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/wallets.ts
> client: hide "load from file" if needed

- pkg.sh
This modifies the packaging script to make use of a TARGETS variable to control which platforms are built rather than having to manually specify the OS and ARCH multiple times for each command.
This should be less error prone when modifying the target platforms and is certainly easier to add/remove platforms as desired.
> build: Use targets and loop in pkg.sh.

- server/db/driver/pg/tables.go
> server: fix purge markets with wrong name

- client/webserver/site/src/js/forms.ts
> client: show "load from file" if needed

- dex/candles/candles.go
> [v0.5] dex/candles: delta overflow bug

- dex/candles/candles.go
- dex/candles/candles_test.go
> dex/candles: delta overflow bug

- client/cmd/dexcctl/main.go
- client/rpcserver/types.go
> dexcctl: remove unnecessary password requirement for togglewalletstatus 

- client/core/core.go
Trying to recover an unconnected wallet panics at `RecoverWallet`. This fixes the issue there and also allows disabled wallets to be recovered. Closes #1881.
> client: recover wallet even if disabled or not connected

- client/cmd/simnet-trade-tests/main.go
> client/tests: Check test names.

- client/webserver/site/src/js/markets.ts
> client: hide accelerate button after first maker's swap

- client/asset/btc/spv_test.go
I've studied code related to this test and think the issue happens due to this line not executing "in time":
```go
// Prime the sync target to avoid the syncStatus tip send here.
atomic.StoreInt32(&spv.syncTarget, 1)
```
since [notification comes in concurrently]((https://github.com/decred/dcrdex/blob/bcfe43c8ef7c7917bb1dcce40f7ce8a63cbd9ca6/client/asset/btc/spv_wrapper.go#L552-L554)) to it, it is not guaranteed to execute before it.
Possibly closes https://github.com/decred/dcrdex/issues/1933.
> asset/btc: make spv test more robust

- client/webserver/site/package-lock.json
Severity: critical
Prototype pollution in webpack loader-utils - https://github.com/advisories/GHSA-76p3-8jx3-jpfq
Just running `$ npm audit fix`
> js: Update loader-utils.

- client/core/core.go
- client/core/core_test.go
- client/core/locale_ntfn.go
- client/core/notification.go
- client/core/types.go
- client/rpcserver/handlers.go
- client/rpcserver/types.go
- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/locales.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/orderutil.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/webserver.go
- client/webserver/webserver_test.go
- dex/errors.go
This enables support for order queueing only for orders placed from the client UI. Closes #1862
> multi: implement order queueing

- README.mediawiki
- spec/comm.mediawiki
spec/comms: Update connect response.
README: Remove mediawiki version.
Part of #1641
> spec/comms: Update connect response.

- client/core/bond.go
Resolves https://github.com/decred/dcrdex/issues/1989 and https://github.com/decred/dcrdex/issues/1999
> client/core: handle nil cfg in refundExpiredBonds

- client/webserver/api.go
> webserver: Zero key after storing.

- dex/msgjson/types.go
- spec/fundamentals.mediawiki
- spec/references.mediawiki
Update the config response and replace fees with bonds.
part of #1641
Can be seen at https://github.com/JoeGruffins/dcrdex/blob/updatingspecstuff/spec/fundamentals.mediawiki
> spec: Update fundamentals.

- client/Dockerfile
- Run frontend build on Node 19
- Run smaller base images
> Optimized Docker base images

- client/asset/eth/multirpc.go
> eth/multirpc: add timeouts to requests

- README.md
> docs: add guide to integrate new asset to readme

- client/asset/eth/eth.go
I've started experimenting with using `-race` when building `dexc` binary (when playing around with different stuff) and one race jumped at me right away:
```
Write at 0x00c0001f42d0 by goroutine 303:
decred.org/dcrdex/client/asset/eth.(*TokenWallet).Connect()
/Users/norwnd/dcrdex/client/asset/eth/eth.go:827 +0x89
decred.org/dcrdex/dex.(*ConnectionMaster).Connect()
/Users/norwnd/dcrdex/dex/runner.go:122 +0xc4
decred.org/dcrdex/dex.(*ConnectionMaster).ConnectOnce()
/Users/norwnd/dcrdex/dex/runner.go:153 +0x44
decred.org/dcrdex/client/core.(*xcWallet).Connect()
/Users/norwnd/dcrdex/client/core/wallet.go:341 +0xb4
decred.org/dcrdex/client/core.(*Core).connectWalletResumeTrades()
/Users/norwnd/dcrdex/client/core/core.go:1859 +0x7d …
```
> eth: ctx initialization race

- client/Dockerfile
Keep only build artifacts in the final image, don't keep sources and modules.
> [docker] Final image optimization

- client/webserver/site/src/js/dexsettings.ts
- client/webserver/site/src/js/doc.ts
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/locales.ts
- client/webserver/site/src/js/order.ts
- client/webserver/site/src/js/settings.ts
- client/webserver/site/src/js/wallets.ts
This removes a handful of statics strings and adds them to the `Locale` map.
> client: add static strings to translation

- docs/wiki/Simnet-Testing.md
With changes in this PR: https://github.com/norwnd/dcrdex/blob/docs-replace-weird-symbols/docs/wiki/Simnet-Testing.md
Resolves https://github.com/decred/dcrdex/issues/2099.
> docs: replace weird symbols

- dex/testing/loadbot/go.mod
- dex/testing/loadbot/go.sum
- go.mod
- go.sum
https://github.com/decred/dcrd/pull/3047
This fixes 100% CPU use on testnet SPV after a day or so.
> deps: update addrmgr for node selection fix

- .github/workflows/release-docker.yml
Github workflow to build and push docker image to Docker Hub.
This requires the below variables to be added to [Github Secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets):
```
DOCKER_USERNAME
DOCKER_PASSWORD
```
> [docker] Build/push Docker image

- client/asset/eth/eth.go
Replaces https://github.com/decred/dcrdex/pull/2118
I think we've come to understand some of the live estimate failures better, and such an error is likely to be suggestive that the transaction could fail, which we don't handle well.  Also, retries will generally be resolved as provider's errors tend to be transient.  Thus, the live estimate errors remain fatal to `Swap`.  This PR just does:
- Before failing to Swap on account of insufficient reserves, use the the realistic gas limit when it is a batch swap.
- Actually include any non-zero redeem gas estimate.  See `initGasEstimate`
- When a token is not approved, we return our known gases, but this change now also ensures we return the correct `nSwap` in the new case of `n > w.maxSwapsInTx`
> client/asset/eth: batched gas limit fallback

- .github/workflows/release-docker.yml
Added missing docker login and chappjc's bug fixes
> Docker release builder hotfix

- .github/workflows/release-docker.yml
Added missing docker login and chappjc's bug fixes
> Docker release builder hotfix (0.5)

- .github/workflows/release-docker.yml
- client/Dockerfile.release
Added Dockerfile.release that skips running webpack build on releases
Optimized GH action workflow
> Docker production build optimizations

- client/core/bookie.go
- dex/candles/candles.go
Addresses a part of https://github.com/decred/dcrdex/issues/2188 specifically pertaining to candles issue: https://github.com/decred/dcrdex/issues/2168.
> client/dex: resolve candles race

- client/core/trade.go
This resolves https://github.com/decred/dcrdex/issues/2173.
When the match cards on the order details page became fully dynamic, a new match notification was added for the cancel match.  However, the match was sent as `Active=true` and with `Status=order.NewlyMatched`.  This does not agree with the matches that get listed by `(*Core).coreOrderFromMetaOrder` (which serves the `/api/order` and `/api/orders` endpoints) because they pull the match data from the DB, which was patched in the `*db.MetaMatch` when storing it.
This resolves the bug by using the `*db.MetaMatch` in `(*trackedTrade).negotiate` when constructing this match ntfn.
Side note: the `trackedTrade.matches` map intentionally does not include cancel matches, and thus the `core.Order`s returned by …
> client/core: fix cancel match ntfn being active/new

- client/core/bookie.go
- dex/candles/candles.go
- dex/candles/candles_test.go
- server/apidata/apidata.go
> candles: Respect the cursor location when copying.

- client/core/core.go
When an order involving a token was cancelled, the locked amount in the parent's balance would not be updated. Now, in `updateBalances`, when a token's balance is update is parents is also updated.
This also moves the updates for the parent asset's balances from `sendTradeRequest` to `prepareTradeRequest`.
> client/core: Update token parent balances

- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/markets.ts
The price displays at the top of the market page and in between the order books were not being updated. This fixes them.
Closes #2212
> app: Fix price displays

- client/core/core.go
- client/core/locale_ntfn.go
- client/core/notification.go
This should supersede #2024.
UI view: wording changed though.
> client: send notification for unstable websocket connection

- dex/testing/loadbot/go.mod
- dex/testing/loadbot/go.sum
- go.mod
- go.sum
Resolves https://github.com/decred/dcrdex/issues/2267
> deps: update ltcsuite/ltcd for wire deserialization fixes

- client/webserver/site/src/js/markets.ts
Resolves https://github.com/decred/dcrdex/issues/2249.
> ui: fix color for percent change

- client/webserver/template.go
> webserver: Log error when we fail to re-parse HTML template

- client/core/bond.go
This changes no functionality, just extracts the login in rotateBonds into multiple smaller functions.
It was a bit daunting to add the logic for updating existing ETH bonds. This will make it simpler.
> client/core: Refactor rotateBonds

- client/asset/dcr/simnet_test.go
> client/dcr/testing: Expect spent for SPV.

- client/asset/btc/btc.go
- client/asset/btc/rpcclient.go
- client/asset/zec/zec.go
- client/cmd/dexcctl/simnet-setup.sh
- client/core/simnet_trade.go
- dex/networks/zec/addr.go
- dex/networks/zec/block.go
- dex/networks/zec/params.go
- dex/networks/zec/tx.go
- dex/testing/dcrdex/harness.sh
- dex/testing/loadbot/loadbot.go
- docs/wiki/Client-Installation-and-Configuration.md
- server/asset/btc/tx.go
- server/asset/zec/zec.go
> Fix Zcash typo

- client/asset/eth/eth.go
- client/asset/interface.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/css/forms.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/wallets.ts
Resolves https://github.com/decred/dcrdex/issues/2245, https://github.com/decred/dcrdex/issues/2246.
There are 2 providers now there ^ (with 2nd commit) actually, screenshot taken based on 1st commit from this PR).
> ui/eth: wallet setup hints

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/externaltx.go
- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/interface.go
- client/core/core_test.go
- client/core/trade.go
- client/webserver/site/src/js/wallets.ts
> client/assets: Add redeem confirms to utxo assets.

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/order.ts
Resolves https://github.com/decred/dcrdex/issues/2335
> ui: zcash block explorer urls

- client/core/core.go
This diff implements @chappjc suggestion in https://github.com/decred/dcrdex/issues/1960#issuecomment-1523409226. part of #1960.
I think we should reject `tipChange` and `peerChange` function calls if `core`'s context has already been cancelled.
> core: track `tipChange` and `peerChange` function calls in `core`

- client/asset/kvdb/kvdb.go
> [0.6.2] kvdb: recover from badger db truncation error

- client/asset/kvdb/kvdb.go
See also https://github.com/dgraph-io/badger/issues/744. Probably a Windows thing. Adopting the fix from https://github.com/decred/dcrdata/pull/955.
> kvdb: recover from badger db truncation error

- .github/workflows/build.yml
- client/webserver/site/bust_caches.sh
- client/webserver/site/cache_utilities.bash
- client/webserver/site/ci_tests.sh
- client/webserver/site/src/html/bodybuilder.tmpl
- run_tests.sh
Take it or leave it. Add script to update cache busters. Set cache busters to a hash of the relevant directory. Ensure cache busters are current in run_tests.sh.
> site: add cache buster utilities and test

- dex/testing/polygon/harness.sh
Delete `NODES_ROOT` at start of script. Add nodekey file. Fix some bor.toml settings. Prepare files of test data for compatibility testing.
> polygon harness: add second node, connect, mine

- client/cmd/dexc-desktop/main.go
- client/core/core.go
Resolves https://github.com/decred/dcrdex/issues/2366
> dexc-desktop: checkbox to persist after window close

- server/auth/auth.go
Relates to https://github.com/orgs/decred/projects/2?pane=issue&itemId=2420755
This is a step toward considering bond strength for user limits.
This also addresses a practical issue for v0.6 users where they can have a non-zero tier, but also have a low or even negative `UserSettlingLimit` because bond strength/tier is was not considered in computation of the limit.  This happens when a user fails swaps causing their tier to drop, and then the "target tier" maintenance code posts additional bond, pushing their account back into the green.  In this case, they have a positive tier and are allowed to submit orders, but their orders get blocked because their total bonding tier/strength was not considered in the order size checks.
The essence of the fix is to multiply the "base" order limit …
> server/auth: base order limit scales with bond strength

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/app.ts
> app: Don't show accelerate button for revoked matches

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/wallets.ts
> client/UI: Add fiat value to token approvals.

- client/asset/btc/btc.go
- client/asset/dcr/coin_selection.go
- client/asset/dcr/coin_selection_test.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/interface.go
- client/core/core.go
- client/core/core_test.go
Implements FundMultiOrder in the DCR wallet. Also removes the MultiOrderFunder interface because all of the wallets now implement MultiTrade.
> client/dcr: MultiTrade

- client/asset/btc/livetest/livetest.go
Fixes issue raised in https://github.com/decred/dcrdex/pull/2424#discussion_r1266144600
> client/btc: set livetest datadir

- README.md
See [rendered version](https://github.com/norwnd/dcrdex/tree/readme-add-website-link).
> readme: add website link

- client/asset/dcr/coin_selection_test.go
- client/asset/dcr/config.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/spv_test.go
- client/asset/dcr/vspd_http_test.go
- client/asset/interface.go
... so that users can select a voting service provider through the dexc GUI.
> asset: add ListVSPs method to TicketBuyer

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/app.ts
> ui: reset menu display after page load

- server/admin/api.go
- server/admin/server.go
- spec/admin.mediawiki
- spec/fundamentals.mediawiki
- spec/orders.mediawiki
This diff updates admin.mediawiki and fixes broken links in fundamentals and orders `.mediawiki` pages.
> spec: Update admin.mediawiki

- dex/testing/firo/README_ELECTRUM_HARNESSES.md
- dex/testing/firo/README_HARNESS.md
- dex/testing/firo/electrum.sh
- dex/testing/firo/test/README.md
Update typos and improve the documentation readbility
> firo:testing: Typos in documentation

- client/webserver/site/src/js/app.ts
> ui: remove stray console.log

- client/asset/dcr/dcr.go
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/wallets.ts
This PR modifies the staking stats box so that it updates the current ticket price when a new block is received via `TipChange` notifications.
Closes #2497
> staking,ui: Live staking info UI updates 

- client/webserver/site/src/css/forms.scss
> ui: Fix jitter on bond view

- client/webserver/site/src/js/wallets.ts
> site: update stake panel after wallet creation

- client/asset/dcr/config.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/native_wallet.go
- client/asset/dcr/rpcwallet.go
- client/asset/dcr/spv.go
- client/asset/dcr/spv_mixing.go
- client/asset/dcr/spv_test.go
- client/asset/dcr/wallet.go
- client/asset/interface.go
- client/core/core.go
- client/core/wallet.go
- client/webserver/site/src/html/forms.tmpl
Basic support for funds mixing with dcr. Core bits and rpc + web controls will come later.
> client/asset: add FundsMixer wallet trait and implement for dcr

- client/asset/driver.go
- client/asset/eth/eth.go
- client/asset/interface.go
- client/asset/polygon/polygon.go
- client/webserver/site/src/css/wallets.scss
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/wallets.ts
- dex/asset.go
> multi: Show ETH/Polygon token addresses on wallet page

- client/webserver/site/src/css/main.scss
> ui: Don't change checkbox labels' font-weight on hover

- client/webserver/http.go
- client/webserver/webserver.go
Change the login flow so that the user is not forced to registration after login, they will be redirected to the Wallets page instead.
Closes #2606
> webserver: Don't force registration after login

- client/core/core.go
closes #2579
I guess the answer is this simple. Processing the preimage should happen after sending the trade not just after creating it, correct? Or at least after `dc.trades[tracker.ID()] = tracker` happens.
> core: Process preimage request after trading.

- client/core/core.go
- client/core/locale_ntfn.go
- client/core/notification.go
Improve legibility of "quantity exceeds current trade limit" notification.  (Referenced in #2624)
> core: Simplified notification when order qty too high

- dex/testing/btc/README.md
- dex/testing/btc/base-harness.sh
- dex/testing/btc/harness.sh
> harness/btc: Enable deprecated dbd database.

- client/webserver/site/src/css/main.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/app.ts
Discussed in https://github.com/decred/dcrdex/pull/2624#issuecomment-1840376465
> ui: Show relative time only for pokes

- client/core/core.go
- client/core/locale_ntfn.go
- client/core/notification.go
- client/webserver/site/src/js/app.ts
> Fix bond wallet panic in core.initializeDEXConnections

- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/login.ts
- client/webserver/site/src/js/register.ts
> ui: fix app.user bug

- client/asset/dcr/dcr.go
This fixes a bug happening when the DCR wallet tried to load unconfirmed transactions from the transaction history db.
> client/asset/dcr: Fix load pending transactions

- client/webserver/site/src/css/main.scss
- client/webserver/site/src/css/main_dark.scss
- client/webserver/site/src/css/wallets.scss
- client/webserver/site/src/css/wallets_dark.scss
- client/webserver/site/src/html/dexsettings.tmpl
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/html/mm.tmpl
- client/webserver/site/src/html/mmsettings.tmpl
- client/webserver/site/src/html/orders.tmpl
- client/webserver/site/src/html/settings.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/locales.ts
- client/webserver/site/src/js/wallets.ts
Normalize styling. Make responsive.
Purge most sans-light. Will do entire front end in a followup.
https://github.com/decred/dcrdex/assets/6109680/56441495-73ee-4bee-bf0e-529b9279d2f3
> refactor wallets ui

- client/core/core.go
- client/core/core_test.go
- client/core/notification.go
- client/db/bolt/db.go
- client/db/bolt/db_test.go
- client/db/interface.go
- client/db/test/dbtest.go
- client/rpcserver/handlers.go
- client/rpcserver/rpcserver.go
- client/rpcserver/rpcserver_test.go
- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/webserver.go
- client/webserver/webserver_test.go
Depends on #2624
Supersedes #2660
> Cache pokes in core

- client/asset/btc/txdb.go
- client/asset/eth/txdb.go
Lowers severity of Info and Debug logs by one level.
> client/asset/{eth,btc}: Quiet transaction db logs

- client/asset/eth/chaincfg.go
- client/asset/eth/cmd/deploy/main.go
- client/asset/eth/cmd/getgas/README.md
- client/asset/eth/eth.go
- client/asset/eth/multirpc.go
- client/asset/eth/multirpc_live_test.go
- client/asset/eth/node.go
- client/asset/eth/nodeclient_harness_test.go
- client/asset/polygon/multirpc_live_test.go
- client/asset/polygon/polygon.go
- client/core/core.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/css/utilities.scss
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/coinexplorers.ts
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/wallets.ts
- dex/networks/eth/params.go
- dex/networks/eth/tokens.go
- dex/networks/polygon/genesis_config.go
- server/asset/eth/eth.go
- server/asset/eth/rpcclient.go
- server/asset/eth/rpcclient_harness_test.go
- server/asset/polygon/polygon.go
> client/eth: provide default providers for eth and polygon

- client/mm/mm_arb_market_maker.go
- client/webserver/live_test.go
- client/webserver/site/src/css/colors.scss
- client/webserver/site/src/css/components.scss
- client/webserver/site/src/css/forms.scss
- client/webserver/site/src/css/main.scss
- client/webserver/site/src/css/market.scss
- client/webserver/site/src/css/mixins.scss
- client/webserver/site/src/css/mm.scss
- client/webserver/site/src/css/order.scss
- client/webserver/site/src/css/orders.scss
- client/webserver/site/src/css/utilities.scss
- client/webserver/site/src/css/wallets.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/dexsettings.tmpl
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/html/mmlogs.tmpl
- client/webserver/site/src/html/mmsettings.tmpl
- client/webserver/site/src/html/orders.tmpl
- client/webserver/site/src/html/settings.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/charts.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/mmsettings.ts
Refactor UI to create more defined sections, marked up and styled via the `<section>` element.
> ui: refactor ui

- client/cmd/testbinance/main.go
Binance debits the balance as soon as the withdrawal is made, not when the funds are sent. This changes the testbinance to match this.
> testbinance: Immediately debit balance after withdrawal

- client/mm/libxc/binance.go
Balance updates for polygon were not being handled.
> libxc/binance: Ensure upper case when converting binance to dex symbol

- client/core/core.go
Closes #2757 
I was able to reproduce and debug the issue. The problem was that `asset.TipChangeNote` notification might be received by `core` before the wallet exists. 
There are just two such notifications `asset.TipChangeNote` and `asset.BalanceChangeNote` and we already check for an existing wallet for `asset.BalanceChangeNote` before proceeding. 
@JoeGruffins please confirm if you can still reproduce with this PR. I got a log when debugging the issue.
<details>
```
2024-05-05 21:47:36.369 [INF] DEXC: dexc version 0.7.0-pre+522d86aaa (Go version go1.22.2)
...
2024-05-05 21:47:57.750 [INF] CORE: notify: |SUCCESS| (security) Don't forget to back up your application seed - A new application seed has been created. Make a back up now in the settings view.
2024-05-05 21:48:00.774 [DBG] …
```
> core: Update balance for only existing assets on tip change

- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/native_wallet.go
- client/asset/dcr/rpcwallet.go
- client/asset/dcr/spv.go
- client/asset/dcr/wallet.go
Tested on testnet. Ticket shows as queued while mixing is negotiated as expected.
> dcr: mixed tickets

- client/cmd/testbinance/main.go
- client/cmd/testbinance/wallets.go
- client/mm/exchange_adaptor.go
- client/mm/libxc/binance.go
- client/mm/libxc/interface.go
- client/mm/libxc/orderbook.go
- client/mm/mm.go
- client/mm/mm_test.go
- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/webserver.go
- dex/testing/dcrdex/genmarkets.sh
Also fixes a bug with fakebinance orderbook level spacing where rate was being multiplied multiplied in two places.
> mm: add fakebinance usdc market. add cex order book getter

- client/asset/zec/transparent_rpc.go
- client/asset/zec/zec.go
- client/asset/zec/zec_test.go
- dex/testing/dcrdex/genmarkets.sh
- dex/testing/loadbot/loadbot.go
- dex/testing/loadbot/mantle.go
- dex/testing/zcl/harness.sh
- dex/testing/zec/harness.sh
Copies a lot of code from #2748
> zec: Satisfy WalletHistorian.

- server/swap/swap.go
> server/swap: Do not increase reputation on self-match

- client/asset/eth/eth.go
This causes a bug in the missing nonce detection.
> client/eth: Do not store ETH receiving transactions

- client/core/core.go
- client/core/wallet.go
Closes https://github.com/decred/dcrdex/issues/2779
> core: Skip locking wallet if not unlocked 

- client/cmd/bisonw-desktop/app_darwin.go
- client/cmd/bisonw-desktop/go.mod
- client/cmd/bisonw-desktop/go.sum
- client/webserver/jsintl.go
Part of https://github.com/decred/dcrdex/issues/2828
> bisonw-desktop: Finish rebrand for darwin

- client/asset/btc/btc.go
- client/asset/btc/electrum.go
- client/asset/btc/electrum/wallet_methods.go
- client/asset/btc/electrum/wallet_types.go
- client/asset/btc/electrum_client.go
- client/asset/btc/wallet.go
- client/asset/zec/zec.go
- client/webserver/site/package-lock.json
Implements #2813 for electrum and zec as well
closes #2741
> electrum: Satisfy WalletHistorian.

- client/mm/libxc/binance.go
- client/mm/libxc/interface.go
- client/mm/mm_arb_market_maker.go
- client/mm/mm_arb_market_maker_test.go
The VWAP call to the CEX was checking the wrong side of the market.
> mm: Fix Arb-MM CEX VWAP bug

- client/asset/dcr/native_wallet.go
- client/asset/interface.go
- client/core/core.go
- client/core/wallet.go
- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/webserver.go
- client/webserver/webserver_test.go
> mixing: Unlock wallets first.

- client/webserver/site/src/js/coinexplorers.ts
Polygon coin explorer was not working properly.
> app: Fix polygon coin explorer

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/eth/txdb.go
- client/core/trade.go
- client/mm/mm.go
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/mm.ts
- client/webserver/site/src/js/mmarchives.ts
- client/webserver/site/src/js/mmlogs.ts
- client/webserver/site/src/js/mmutil.ts
- client/webserver/site/src/js/registry.ts
> mm: make txdb a connector. normalize marketwithhost json tags

- client/asset/btc/btc.go
- client/asset/btc/electrum.go
- client/asset/btc/electrum/wallet.go
- client/asset/btc/electrum/wallet_methods.go
- client/asset/btc/electrum_client.go
- client/asset/firo/firo.go
- client/asset/ltc/ltc.go
- dex/semver.go
- dex/testing/btc/electrum-base.sh
- dex/testing/btc/electrum.sh
- dex/testing/btc/electrumx.sh
> electrum: Use wallet version 4.5.5 and up.

- client/mm/libxc/binance.go
Firo and Zcash on use special addresses on binance global. We haven't implemented them yet.
> mm: disable firo and zec on binance global

- client/mm/exchange_adaptor.go
- client/mm/libxc/binance.go
- client/mm/libxc/orderbook.go
- client/mm/mm.go
Fixes of mutex use in market making code.
> mm: Audit mutexes

- client/mm/config.go
- client/mm/exchange_adaptor.go
- client/mm/mm_basic.go
- client/mm/mm_basic_test.go
- client/webserver/live_test.go
- client/webserver/site/src/html/mmsettings.tmpl
- client/webserver/site/src/js/mmsettings.ts
- client/webserver/site/src/js/registry.ts
Using the market mid-gap, especially on low liquidity markets causes problems. Options to do this are removed.
> mm: Basic MM basis only determined by oracles

- client/app/config.go
- client/cmd/bisonw-desktop/app.go
- client/cmd/bisonw-desktop/app_darwin.go
- client/cmd/bisonw/main.go
- client/mm/mm.go
- client/rpcserver/handlers.go
- client/webserver/api.go
- client/webserver/http.go
- client/webserver/live_test.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/mm.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/webserver.go
- dex/asset.go
- dex/testing/walletpair/walletpair.sh
- Remove experimental flag. MM for everybody.
- Fix bug just introduced in #2877 with transfer units
- Try to connect to cexes on startup but ignore errors
> mm: remove experimental flag. a couple other mm things

- client/webserver/site/src/js/mm.ts
Probably closes #2888. Check it out if you have time, @JoeGruffins.
> mmui: only specify rebalance config for arb bots

- client/cmd/testbinance/main.go
Balances on testbinance were not being updated due to orders being placed and filled.
> mm: Fix testbinance balance updates

- client/mm/libxc/binance.go
The orderbook sync did not account for the first update to the orderbook straddling the last update ID of the snapshot.
> libxc/binance: Fix orderbook sync

- client/core/core.go
I was seeing `Server no longer supports 2147483647 as a bond asset!`. Also the `bondTier` variable is not used.
> client/core: Stopping logging warning for prepaid bond

- client/webserver/site/src/css/forms.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/html/mm.tmpl
- client/webserver/site/src/html/mmsettings.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/mm.ts
- client/webserver/site/src/js/mmsettings.ts
- client/webserver/site/src/js/wallets.ts
- Adjust notifications display for small screens (closes #2906)
- Fix conversion and unit for max send fees (closes #2903)
- Add link to repo in hamburger menu (closes #2898)
- Disable bots when no fiat exchange rates (closes #2893)
- Fix CSS specifier for reputation meter score (closes #2842)
> ui: assorted touchups

- client/webserver/site/src/js/mm.ts
> mmui: Fix error if no placements on one side of basic MM cfg

- dex/networks/polygon/params.go
As far as I can tell, this is the only thing that we **have** to do. Leaving in draft until we can look closer though.
> change native polygon asset from MATIC to POL

- docs/wiki/Client-Installation-and-Configuration.md
- docs/wiki/DEX-Trading-Account-Management.md
- docs/wiki/Ethereum.md
> docs: Silence markdown-lint 

- client/webserver/api.go
- client/webserver/webserver_test.go
> webserver: Ensure sub forms are not nil.

- client/webserver/site/src/js/markets.ts
> app: Fix market page daily high/low rate

- client/asset/firo/firo.go
- docs/wiki/Client-Installation-and-Configuration.md
Update for consensus change hard fork
> client/wiki: Update minimum Firo version to 0.14.14.0

- dex/testing/dcrdex/harness.sh
- dex/testing/walletpair/walletpair.sh
walletpair simnet only: taker 3m, maker 6m
dcrdex (simnet):        taker 3m, maker 6m
> dex/testing: Set short htlc locktimes for testing on simnet.

- client/core/trade.go
When sending inits and redemptions, if the server does not know about the
match, assume revoked and stop sending.
closes #3022
> client/core: Recognize missing trades.

- client/comms/wsconn.go
> comms: double the default websocket request timeout

- pkg.sh
Also makes the systray flavor the default flavor for Windows.
> pkg: add more platforms for binary builds

- client/webserver/site/package-lock.json
https://github.com/decred/dcrdex/security/dependabot/87
> webserver: upgrade webpack for vulnerability fix

- client/webserver/site/src/js/markets.ts
> app: Avoid error on RunStatsNote

- client/asset/btc/btc.go
> client/btc: Store correct tx history refund hash.

- dex/lexi/db_test.go
- dex/lexi/index.go
> lexi: fix backwards iteration with prefix

- client/db/bolt/db.go
- client/db/bolt/upgrades.go
- client/mm/exchange_adaptor_test.go
- client/mm/libxc/binance.go
- client/mm/mm_basic.go
> chore: fix some typos in comment

- server/dex/dex.go
- tatanka/tatanka_messages.go
fix some function names in comment
> chore: fix some function names in comment

- client/cmd/bisonw-desktop/app.go
> windows: Shorten systray tooltip

- client/webserver/middleware.go
- client/webserver/site/src/html/init.tmpl
- client/webserver/site/src/html/wallets.tmpl
Updates the Feature-Policy header to a Permissions-Policy header.
Also adds hidden username fields to some forms to suppress console warnings.
> webserver: update feature-policy header

- tatanka/client/orderbook/orderbook.go
- tatanka/client/orderbook/orderbook_test.go
- tatanka/tanka/swaps.go
Adding the orderbook as a map. Currently built on top of ~#3165~ and ~#3176~ Part of #3115
> tatanka: Add orderbook map

- client/asset/btc/coinmanager.go
- client/asset/btc/electrum/wallet_methods.go
- client/asset/btc/rpcclient.go
make function comment match function name
> chore: make function comment match function name

- dex/lexi/lexi.go
> lexi: Release idSeq before closing.

- .github/workflows/release-docker.yml
- client/Dockerfile
- client/Dockerfile.release
* Golang base image update to 1.24, 
* docker image rebrand -> `decred/bisonwallet`
> Docker build fix

- client/asset/btc/btc.go
closes #2419
Resurrected a commit from @dev-warrior777
> client/btc: More correct error return from ReturnCoins(coins)

- client/webserver/webserver.go
- server/coinlock/coinlocker.go
> chore: fix function name in comment

- .github/workflows/build.yml
- client/cmd/bisonw-desktop/app.go
- client/cmd/bisonw-desktop/go.mod
- client/cmd/bisonw-desktop/go.sum
- client/cmd/bisonw-desktop/icon.go
- client/cmd/bisonw-desktop/icon_linux.go
- client/cmd/bisonw-desktop/icon_windows.go
> webview: Use bisoncraft import.

- client/cmd/bisonw-desktop/README.md
- client/cmd/bisonw-desktop/pkg/pkg-debian.sh
Bumped libwebkitgtk2 lib dependency to 4.1.
> Update libwebkitgtk deps

- internal/adaptorsigs/dleq.go
remove duplicate package imports
> chore: remove duplicate package imports

- client/asset/dcr/dcr.go
- dex/testing/dcr/harness.sh
> harness: Add rejectnonstd to simnet dcrd args.

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- dex/ws/wslink_test.go
- server/asset/btc/btc_test.go
- tatanka/chain/utxo/btc.go
- tatanka/chain/utxo/dcr.go
- tatanka/client/mesh/mesh.go
- tatanka/client_messages.go
- tatanka/mj/types.go
1. Bug fixes
2. Typo fixes
3. Clean up
> multi: house cleaning and bug fixes

- dex/order/test/helpers.go
- server/coinlock/coinlocker.go
fix some minor issues in comments
> chore: fix some minor issues in comments

- client/webserver/site/src/js/mmsettings.ts
Removes a code duplication caused additional funds to be allocated to the CEX.
> mmui: Fix CEX surplus allocation bug

- client/core/core.go
Previously, `SingleLotFees` used the server rate for swap fees. For dynamic fee assets, the server provides the maximum fee rate, which led to excessively high spreads in the market making code due to inflated fees. This change updates `SingleLotFees` to use the wallet's fee rate for dynamic fee assets instead.
> core: Use wallet fee rate for dynamic fee assets in SingleLotFees

- dex/lexi/db_test.go
- dex/lexi/table.go
Introduced `WithTxn` and `WithGetTxn` options to allow specifying transactions for Set and Get operations.
> lexi: Add transaction support for Set and Get operations

- dex/networks/eth/params.go
- dex/networks/zec/script.go
> chore: fix problematic function name

- client/webserver/site/src/js/mmsettings.ts
> fix frontend bot configuration when using multiple bots
