- client/core/account.go
- client/core/core.go
- client/core/types.go
- client/rpcserver/handlers.go
- client/webserver/api.go
- client/webserver/webserver.go
In core methods and consumers, clear passwords, private keys, and seeds
when possible to protect against some memory scraping attacks.
lightly discussed in #1582
This pr makes it so the crypter cannot be used in goroutines. I think we're not doing so atm, but should be careful going forward.
> multi: Clear private data asap.

- client/asset/btc/livetest/regnet_test.go
- client/asset/eth/eth_test.go
- client/core/trade_simnet_test.go
- client/db/bolt/db_test.go
- client/db/bolt/upgrades_test.go
- client/rpcserver/rpcserver_test.go
- client/webserver/webserver_test.go
- dex/config/config_test.go
- server/admin/server_test.go
- server/asset/btc/btc_test.go
- server/asset/dcr/dcr_test.go
- server/cmd/dcrdex/key_test.go
- server/comms/comms_test.go
- server/market/market_test.go
A testing cleanup.
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
> test: use `T.TempDir` to create temporary test directory

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/interface.go
- client/cmd/dexcctl/simnet-setup.sh
Parse locktime as seconds because it is seconds and not milliseconds.
closes #1592
> client/asset/eth: Fix eth receipt locktime.

- client/asset/btc/btc.go
- client/asset/btc/rpcclient.go
- dex/networks/btc/script.go
- dex/networks/btc/script_test.go
- dex/networks/dcr/script.go
- dex/networks/dcr/script_test.go
- server/asset/btc/btc.go
- server/asset/btc/rpcclient.go
- server/asset/btc/testing.go
- server/asset/btc/utxo.go
- server/asset/dcr/live_test.go
- server/asset/doge/doge.go
Addressing issues revealed in https://github.com/decred/dcrdex/pull/1558#issuecomment-1095680799
This updates the DCR and BTC packages to understand P2PK outputs.
This also fixes the BTC client packages UTXO conversion code so that
unsupported output scripts in the listunspent result are merely skipped
instead of breaking the ability to select UTXOs at all.
> client/asset/{btc,dcr}: support p2pk and fix unsupported btc utxos

- client/core/trade.go
Because the return data cannot all be trusted if the method has an
error, return that error up to the caller rather than just logging and
returning with possibly false values.
For swaps using contracts it is ok for the swap to be status none, in
which case we cannot check the lock time or confirmations on chain yet.
Do not log an error in this case.
Checking the eth locktime would fail because expire was set to true even though checking the locktime failed. This error was not as helpful as the real error would have been. Also, there is no reason to log an error if the swap has not been mined because we cannot know anything about the counter party's swap without the on chain data.
> client/trade: Return counterPartyConfirms error.

- dex/networks/eth/params.go
- dex/networks/eth/tokens.go
- server/asset/eth/coiner.go
- server/asset/eth/coiner_test.go
- server/asset/eth/config.go
- server/asset/eth/eth.go
- server/asset/eth/eth_test.go
- server/asset/eth/rpcclient.go
- server/asset/eth/rpcclient_harness_test.go
- server/asset/eth/tokener.go
```
Convert Backend to AssetBackend that embed *baseBackend similarly to
the AssetWallet in PR 1399. Add interfaces to interact with token
and token swap contracts.
```
> server/asset/eth: token backends

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/estimation.go
- client/asset/eth/contractor.go
- client/asset/eth/contractor_test.go
- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/eth/fundingcoin.go
- client/asset/eth/nodeclient.go
- client/asset/eth/nodeclient_harness_test.go
- client/asset/interface.go
- client/core/core.go
- client/core/core_test.go
- client/core/trade.go
- dex/networks/eth/params.go
- dex/testing/eth/harness.sh
I've peeled a few other PRs off of this one, but I think I'll submit the rest as one. Lots of tests written or adapted and all are passing. Ready for a look.
```
Introduce tokenContractor interface to handle operations on the token
contract and token-bound swap contract.
Separate ExchangeWallet into baseWallet and AssetWallet.
Move contractor handling to AssetWallet. This simplifies the ethFetcher
and is a better division of labor, making future implementations of
EVM-family assets easier.
Implement detailed calculations of swap and approve gas, issuing
warnings when a configuration mismatch is detected.
dex/networks/eth,dex:
Simplify dex.Token and create dexeth.Token type to add gas and address
info. Move gas info to version-specific token data.
```
> client/asset/eth: finish client wallet tokens

- client/asset/eth/nodeclient_harness_test.go
If testnet is set to true, create a new folder and wallets in the user's
home directory and change set up to create testnet nodes. Testing is
done pointing at testnet and the testnet contract.
Tests currently often fail because a transaction randomly cannot be
found to retrieve its receipt. This should not be an issue for swaps as
we only check for txn in tests to verify gas used. It may, however, have
implications for checking RegFeeConfirmations, as that similarly must
find a tx.
Even waiting and trying many times to find some tx, they just seem to be randomly not existing. Maybe light nodes just can't be expected to find txn? See https://github.com/ethereum/go-ethereum/issues/24101
We should verify if this is normal or maybe we are doing something wrong. I'm guessing it's a problem on …
> client/eth: Allow harness testing on testnet.

- client/asset/eth/eth.go
- client/asset/eth/nodeclient.go
- client/asset/eth/nodeclient_harness_test.go
checkTxStatus would sometimes return a receipt on error, which caused a
panic in tests sometimes. Get the receipt separately to avoid this.
closes #1577
> client/eth: Get receipt before checking status.

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/core/trade_simnet_test.go
- dex/testing/doge/harness.sh
- run_tests.sh
client/testing: Make simnet tests modular.
Change the simnet harness tests to work with all currently supported
assets.
testing/doge: Add delta and gamma nodes.
Because doge does not distinguish between different wallets, it is
difficult to test balance changes when testing, especially if the node
is mining. Add two wallets that don't do anything special to use in
tests.
part of #1565
edit: Not sure if it closes the issue because it also mentions loadbot. Removed the closing phrase.
> client/testing: Make simnet tests modular.

- server/asset/btc/btc_test.go
- server/asset/btc/script.go
- server/asset/dcr/dcr_test.go
- server/asset/dcr/script.go
- server/auth/auth.go
- server/auth/auth_test.go
- server/swap/swap_test.go
This is stage 3 of the signature message truncation fix plan outlined in https://github.com/decred/dcrdex/pull/1526.
In these commits, server:
1. Begins signing the hashed messages
2. **Stops recognizing** the buggy signatures.
All clients must be running with the [stage 2 fix](https://github.com/decred/dcrdex/pull/1529) in v0.4.3 before this change can be deployed.
In the [next and final stage](https://github.com/decred/dcrdex/pull/1526), the client drops support for truncated message signatures from the server running at this point.
> server: sign and verify hashed messages (sig fix stage 3)

- client/core/wallet.go
- client/websocket/websocket.go
- dex/runner.go
- server/comms/server.go
This reverts e8fd8acab23fbb253b649a66a95a5a63d4be6b75, which broke the
reconnect loop that the dex.Connector implemented by
client/comms.(*wsConn) starts.
This also adds a call to Disconnect when the connector for a client
wallet returns a non-nil error so that the ConnectionMaster's On method
does not say true, which is what e8fd8ac had aimed to resolve.
> dex,client: restore dex reconnect loop

- client/asset/btc/btc.go
- client/asset/btc/spv.go
- client/asset/interface.go
- client/core/core.go
- client/core/core_test.go
- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/css/main_dark.scss
- client/webserver/site/src/css/wallets.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/wallets.ts
- client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl
- client/webserver/site/src/localized_html/en-US/wallets.tmpl
- client/webserver/site/src/localized_html/pl-PL/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pl-PL/wallets.tmpl
- client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pt-BR/wallets.tmpl
- client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl
- client/webserver/site/src/localized_html/zh-CN/wallets.tmpl
- client/webserver/webserver.go
- client/webserver/webserver_test.go
- dex/config/config.go
- dex/config/config_test.go
- server/market/orderrouter.go
Adds the ability to delete all the files from the BTC SPV wallet and recreate it from scratch.
- `client/asset/interface`: A `Recoverer` trait is added that includes three functions
- `GetRecoveryCfg`: Attempts to retrieve a `map[string]string` from the existing wallet that would help in putting the
wallet back to the state is was in before all the wallet files were deleted.
- `Destroy`: deletes all the wallet files
- `ApplyRecoveryCfg`: passes the settings that were retrieved using `GetRecoveryCfg` to a newly created wallet.
- `client/asset/btc`: Implements the `Recoverer` interface. The recovery configuration includes the number of internal and number of external addresses that the wallet generated. This amount of addresses are regenerated in the new instance of the wallet. If this was …
> client/ui/btc: Recover BTC SPV wallet

- server/asset/bch/bch.go
- server/asset/bch/live_test.go
- server/asset/btc/btc.go
- server/asset/btc/live_test.go
- server/asset/btc/rpcclient.go
- server/asset/btc/testing.go
- server/asset/doge/doge.go
- server/asset/doge/live_test.go
- server/asset/ltc/live_test.go
- server/asset/ltc/ltc.go
```
Add methods for calculating the median fee of the most recent block(s).
Ensure that there is sufficient data by requiring M transactions in the
last N blocks. If not enough data, fallback to a "no-competition" fee
rate. Implement a cache to prevent repeated scans between blocks.
Some chains provide the getblockstats RPC. Others require manual
scanning.
```
> server/asset/{btc,doge,ltc,bch}: median-fee based fee rate estimation backup

- dex/encode/encode.go
- dex/encode/encode_test.go
Relating to the issue hit in https://github.com/decred/dcrdex/issues/1105#issuecomment-1128595137, where the counter tx data was too large on account of the tx having many funding coins.
```
Retrofit the blob encoding and decoding to allow byte slices up to
0x00fe_ffff (16711679) long.  The decoding scheme detects a uint32
length when the top two bytes decoded as big endian uint16 indicate a
value less than 255.
```
This is a bit of a cludge, but it seems to be working, so I figure we could discuss it.
> dex/encode: allow data longer than 65535 bytes

- server/db/driver/pg/internal/markets.go
- server/db/driver/pg/markets.go
- server/db/driver/pg/matches.go
- server/db/driver/pg/orders.go
- server/db/driver/pg/pg.go
- server/db/driver/pg/upgrades.go
```
The base and quote ID columns in the server db markets table were
defined as INT2, too small for our uint32 asset IDs.
Also need to do some character replacement for schemas with our
new symbol scheme for tokens, since `.` is not an allowed character.
```
> server/db/driver/pg: increase size of asset ID column in markets table

- client/webserver/site/src/js/markets.ts
You would only see this if the server has a market with an asset that is not supported by the client, in which case `this.market.base` would be `null`.
> ui: prevent missing SupportedAsset error in setOrderBttnText

- client/cmd/dexc/main.go
- client/core/core_test.go
- client/core/trade.go
closes #1544
The function wasn't a problem on the default simnet, but when used with smaller lot sizes `isDust` does not scale well. You can try out the way in master here: https://go.dev/play/p/QNqo2EDUiUX
I think using the ratio of one lot to max lots and multiplying that times the max reserved is more straightforward.
Also adding a log for client to see the net and locktimes on start up.
> client: Base fraction unlocking on total lots.

- client/Dockerfile
Trying to build `dexc` with Docker I get the following error:
```
comment without // +build comment
```
I assume this started to happen after [go 1.18 update](https://github.com/decred/dcrdex/pull/1519)
with Golang 1.18 docker build works for me.
> dexc: update go version in Docker file

- client/core/core.go
- client/core/core_test.go
- dex/runner.go
See the discussion at https://github.com/decred/dcrdex/pull/1445#discussion_r803100088 for the motivation.
This redesigns `dex.ConnectionMaster`, adding a `Done() <-chan struct{}` method upon which the `On` and `Wait` methods are now based.
This also uses the new `Done` method in `(*Core).startWalletSyncMonitor` to quit if the wallet shuts down without an extra goroutine sitting on `Wait`.
> dex: redesign ConnectionMaster

- client/cmd/dexc/main.go
- client/cmd/dexcctl/config.go
- client/cmd/dexcctl/main.go
- client/rpcserver/handlers.go
- client/rpcserver/handlers_test.go
- client/rpcserver/rpcserver.go
- client/rpcserver/types.go
- dex/version/version.go
- dex/version/version_test.go
This adds new values to RPC server version return. Closes #1151 
- add dexc version to rpc server version return value
- add supported RPC version to dexcctl.
- change dexc RPC server version return to a json object
- Edit: update rpc version handler test
```
$ ./dexcctl version
{
"rpcServerVersion": {
"Major": 0,
"Minor": 2,
"Patch": 0
},
"dexcVersion": {
"versionString": "0.5.0-pre+9763b71bb",
"major": 0,
"minor": 5,
"patch": 0,
"prerelease": "pre",
"buildMetadata": "9763b71bb.go1-18"
}
}
```
```
$ ./dexcctl -V
dexcctl version 0.5.0-pre+9763b71bb (Go version go1.18 linux/amd64)
dexcctl required RPC server version: 0.2.0
```
> multi: check rpc semver compatibility

- client/webserver/site/src/js/markets.ts
> client: fix client forever loading when connecting to off server

- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/localized_html/en-US/forms.tmpl
- client/webserver/site/src/localized_html/pl-PL/forms.tmpl
- client/webserver/site/src/localized_html/pt-BR/forms.tmpl
- client/webserver/site/src/localized_html/zh-CN/forms.tmpl
This makes the button on the cancel form behave like the order submission button in that when clicked, the button is replaced with a spinner, and any error from the cancel request is shown on the form instead of the notification menu.
> site: make cancel button respond with spinner

- dex/meter/meterer.go
- dex/meter/meterer_test.go
- server/swap/swap.go
- server/swap/swap_test.go
```
Ethereum has very short block times. And just for conservation of
resources, tightly-grouped blocks need not trigger tightly-grouped
conf and penalty checks. This adds a minimum delay window to block
notifications. If blocks comes farther than the minimum delay apart,
nothing changes from the current behavior. If 1 or more blocks
arrives within the delay window of another, they will be collected into a
single block notification that occurs once the min delay has passed.
The newly implemented SignalMeterer is only used in the swapper for
block notifications for now, but might also be useful for the client.
```
> server/swap: metered block-triggered conf and penalty checks

- client/webserver/site/src/js/dexsettings.ts
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/wallets.ts
Some of the forms on the markets page would show an old error when opening the form. This is now fixed.
> ui: Hide old errors on market page forms

- dex/msgjson/types.go
- dex/wait/queue.go
- server/swap/swap.go
- server/swap/swap_test.go
Not super polished, but OK to review.
There is a lot of lock contention in the swapper, with mutexes locked during expensive operations that can time out like confirmations checks.  This starts fixing that.
There also appeared to be a memory leak with the coinlocker map with "premature" init requests from clients/
> server/swap: reduce lock contention and fix memory leak

- client/core/account.go
- client/core/account_test.go
- client/core/core.go
- client/core/core_test.go
- client/webserver/api.go
- client/webserver/http.go
- client/webserver/live_test.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/dexsettings.tmpl
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/js/dexsettings.ts
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl
- client/webserver/site/src/localized_html/en-US/dexsettings.tmpl
- client/webserver/site/src/localized_html/en-US/forms.tmpl
- client/webserver/site/src/localized_html/pl-PL/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pl-PL/dexsettings.tmpl
- client/webserver/site/src/localized_html/pl-PL/forms.tmpl
- client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pt-BR/dexsettings.tmpl
- client/webserver/site/src/localized_html/pt-BR/forms.tmpl
- client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl
- client/webserver/site/src/localized_html/zh-CN/dexsettings.tmpl
- client/webserver/site/src/localized_html/zh-CN/forms.tmpl
- client/webserver/webserver.go
- client/webserver/webserver_test.go
- server/cmd/dcrdex/main.go
DEX servers are able to advertise on multiple host names. This update gives users of the dex client the ability to switch between the different host names of the same dex.
- client/core: Add `UpdateDexHost` method which takes
a current dex host and a new host name, and if the dex
at both host names use the same dex pub key, the host
name is updated. Also, adding a dex with the same pub
key as a dex which is already registered is now blocked.
- ui: Adds a button on the dex settings page to allow updating
the dex host. The DEXAddressForm is reused for this purpose.
The DEXAddressPopup is also updated to not show known
exchanges that the user is already registered for.
> client: Update server host

- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/orderbook.ts
I've been chasing down the residual orders in the front-end order book and depth chart. The orders that we see are zero-quantity orders that appear to be related to orders that are booked and unbooked on the same match cycle. In that case, we receive a `book_order` update followed by an `unbook_order` update. The `book_order` update contains a `BookOrderNote` with a zero-quantity order, because by the time the `order.LimitOrder` gets translated by `BookRouter`, the `Remaining` is already zero.
I still haven't figured this out. I've put feelers around to try to catch a zero-quantity `book_order` update with no subsequent `unbook_order` update, but I haven't seen one yet, even though I still see residual orders. 
Oddly, these leftover orders only appear on the buy side. 
This PR is here …
> app: ignore zero-quantity book_order updates

- run_tests.sh
This ensures that code lines that fail golangci-lint check are displayed in the CI logs. Just me scratching my itch :)
> golangci-lint config update

- dex/testing/dcrdex/harness.sh
- dex/testing/loadbot/loadbot.go
- dex/testing/loadbot/mantle.go
- dex/testing/zec/harness.sh
zec will complain about double spends if sendtoaddress is used too soon
after mining a block. Use a mutex to make sure we always wait a second
after mining to send.
closes  #1683
> loadbot/zec: Avoid using the same outputs.

- client/asset/btc/btc_test.go
- client/asset/btc/spv_test.go
- dex/networks/erc20/contracts/updatecontract.sh
- dex/networks/erc20/contracts/v0/contract.go
- dex/networks/eth/txdata_test.go
- run_tests.sh
In catching up with recent PRs I noticed some churn because `gofmt` has a "simplify" option that removes some superfluous identifiers, but CI does not enforce its use and only some developers have it set.  I don't see a way to enforce "not simple" so this PR enforces simple for consistency.  This is done by enabling the `gofmt` linter in golangci-lint:
`gofmt: Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification [fast: true, auto-fix: true]`
Developers may choose to add that as well, or just add `-s` to their gofmt flags.
This also modifies the the erc20 updatecontract.sh script so that it reorders the imports after rewriting the import lines with perl.  Recent PRs have tried to modify contract.go, but since it is generated it …
> CI: enforce fmt simplification

- client/webserver/site/src/css/market.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl
- client/webserver/site/src/localized_html/en-US/markets.tmpl
- client/webserver/site/src/localized_html/pl-PL/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pl-PL/markets.tmpl
- client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pt-BR/markets.tmpl
- client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl
- client/webserver/site/src/localized_html/zh-CN/markets.tmpl
Fix search box mishappen on markets page. Closes #1527.
FireFox and chrome are now the same.
Search box width fixed.
> fix misshappen search box on markets page

- client/asset/eth/eth.go
- client/asset/interface.go
- client/core/core.go
- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/css/main.scss
- client/webserver/site/src/css/typography.scss
- client/webserver/site/src/css/wallets.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/wallets.ts
- client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl
- client/webserver/site/src/localized_html/en-US/wallets.tmpl
- client/webserver/site/src/localized_html/pl-PL/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pl-PL/wallets.tmpl
- client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pt-BR/wallets.tmpl
- client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl
- client/webserver/site/src/localized_html/zh-CN/wallets.tmpl
- client/webserver/webserver.go
- client/webserver/webserver_test.go
- dex/keygen/keygen.go
- `client/asset`: Adds a `WalletRestorer` interface which requires
the `RestorationInfo` method to be implemented. `RestorationInfo`
returns the wallet seed and instructions for the user to restore
the wallet in various external wallets.
- client/eth: Implements the `WalletRestorer` interface. Returns
information about how to restore the wallet in MetaMask.
- ui: Displays a new button on the wallet settings page if the wallet
implements `WalletRestorer`. The user is promped to copy a disclaimer
confirming that they understand the risks of restoring their wallet
in an external wallet software. After doing so, they are able to see
the information returned from the wallet's `RestorationInfo` function.
> client/eth/ui: Export ETH wallet to Metamask

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/btc/livetest/livetest.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/simnet_test.go
- client/asset/eth/eth.go
- client/asset/interface.go
- client/core/core.go
- client/core/core_test.go
- client/core/locale_ntfn.go
- client/core/notification.go
1. Add a peers restored message to match a peers lost message
2. Distinguish peers lost from unable to determine peer count (e.g. rpc timeout)
3. Fix a bug in the DCR block monitoring goroutine.  When native SPV was added, some code that made sense in its own function (defer and return) no longer worked properly when put directly into `monitorBlocks`.  The return was killing the wallet if connectivity was lost, instead of it being a temporary issue.  This fixes those issues.
> client: add peers restored message and improve error

- client/core/helpers.go
The percent filled/settled calculation for market buys was incorrectly using the "to" asset as the numerator. It is now updated to use the "from asset".
Closes #775
> core: Fix OrderReader percentage helper for market buys

- client/core/core.go
The asset config was not populated when calling `PreRedeem` in `MaxSell`. This was causing a panic.
> client/core: Popuplate AssetConfig on PreRedeem call

- README.md
Changes mentions of "javascript" to "JavaScript" in README.md
No reference to issue as the problem is too small to justify creating an issue.
> Update README.md to use consistent "JavaScript"

- client/webserver/site/package-lock.json
On master:
```
$ npm audit
terser  5.0.0 - 5.14.1
Severity: high
Terser insecure use of regular expressions before v4.8.1 and v5.14.2 leads to ReDoS - https://github.com/advisories/GHSA-4wf5-vphf-c2xc
fix available via `npm audit fix`
node_modules/terser
1 high severity vulnerability
To address all issues, run:
npm audit fix
```
> site: Run npm audit fix.

- client/asset/btc/btc.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/rpcwallet.go
- client/asset/eth/eth.go
- client/asset/interface.go
- client/core/core.go
- client/core/trade.go
This resolves https://github.com/decred/dcrdex/issues/1717, https://github.com/decred/dcrdex/issues/1515, and https://github.com/decred/dcrdex/issues/1718
```
In client/core, this updates trackedTrade's redeemFeeSuggestion field
as a new type, feeStamped, with a time stamp paired with the fee rate.
cacheRedemptionFeeSuggestion is made into a trackedTrade method (always
should have been), and now checks the time stamp on the
redeemFeeSuggestion before retrieving an updated rate from any of the
sources: wallet (may include external oracle request), best book fee
suggestion, and on demand fee_rate server RPC. This expiry check
resolves a long standing stale fee rate issue, and it throttles the
frequency with which we request fee rates from any source.
In client/asset/dcr, fee rates from an …
```
> client/{core,asset}: fee rate caching and expiry

- client/asset/eth/eth.go
- go.mod
Previously, the wallet seed from core was used as the master seed of the an HD wallet from which a private key was derived. Instead of this, the seed from core is used as an entropy for a BIP-39 mnemonic phrase, then the seed derived from the mnemonic phrase is used to derive the private key used in the wallet. The mnemonic phrase is currently not used for anything, but this will keep our options open for more features in the future.
This will come on top of #1648, d0f77dc22900b26c24226c2f347015a143581d94 is the diff for this PR.
> client/eth: Use wallet seed as entropy for BIP-39 mnemonic

- server/apidata/apidata.go
```
Fixes the calculation of 24 hour volume and price change. I was using
the same cache for every market before. duh.
```
> server/apidata: fix 24-hour calcs

- client/asset/btc/btc.go
- client/asset/btc/rpcclient.go
This PR upgrades bitcoin min version required from v0.19 to v0.21. It also adds a min descriptor version, if using descriptor wallets.
This was discussed at matrix.
> client: upgrade btc min version required

- server/auth/auth.go
- server/auth/auth_test.go
Closes https://github.com/decred/dcrdex/issues/1734.
> dcrdex/server/auth: TestHandleResponse is flaky

- client/asset/eth/nodeclient_harness_test.go
closes #1720
So, there was already a test! I guess @buck54321 or @martonp noticed the possible vulnerability before me. The commented out test just never registered for me....
Anyway, I tried this with a contract build with 0.7.5 and can confirm the init succeeds and test fails.
> eth/harness: Uncomment init overflow test.

- client/asset/btc/spv_test.go
Couldn't see any issues with the code being tested, however I think test waiting-intervals need to be tweaked (in master, `blockTicker / 2` is `2.5ms` in this test, which doesn't seem too generous for go-runtime to finish its business with handling go-routines / channels),
for tests relying on go-scheduler to "work in time" (like this one), I think, it's better to over-allocate waiting times (than under-allocate these), even at the cost of long-running tests (cause flakieness will distract devs); although, it's a trade-off ...
Maybe worth closing https://github.com/decred/dcrdex/issues/1330 and re-open it if  the issue reproduces with higher waiting-intervals.
> client/asset/btc: TestTryBlocksWithNotifier is flaky

- client/core/core.go
Noticed this while exploring `time.Timer` quirks [here](https://github.com/decred/dcrdex/pull/1742#discussion_r935345226).
Looks like we need a `Ticker` (not `Timer`), otherwise we'll throttle `refreshFiatRates` only once ?
> client/core: throttle with Ticker instead of Timer

- client/core/core.go
- client/core/core_test.go
- client/core/locale_ntfn.go
- client/core/wallet.go
Resolves https://github.com/decred/dcrdex/issues/1716
> client/core: omit TopicWalletPeersRestored on first report

- client/core/helpers.go
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/orders.ts
- client/webserver/site/src/js/orderutil.ts
Exclude canceled matches when displaying filled amount and percent on the order page and orders table. Closes #1608
> multi: exclude cancel matches for filled amount and percent on UI display

- client/asset/btc/btc.go
- client/asset/dcr/dcr.go
- client/asset/dcr/wallet.go
- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/interface.go
- client/cmd/dexc/main.go
- client/core/core.go
- client/core/core_test.go
- client/core/trade.go
We're clearly fighting some limitations of our `asset.Wallet` interface (no ctx args) and Go (no `context.Merge`), but there are some smaller things we can do.
The first commit adds some more context passing to avoid things getting hung and unable to cancel them.  Some sensible timeouts are also established.
The second commit is a bit of a hack to prevent shutdown from becoming impossible if an RPC or something hangs and causes deadlock on the `trackedTrade` mutex.
This PR is the basis for more extensive refactoring in https://github.com/decred/dcrdex/pull/1739
> address client wallet hanging issues

- client/asset/btc/spv.go
This resolves a useless nested `walletdb.View` that causes a reproducible deadlock with a concurrent  `Update`.
**Repro**: Get three DCR buy orders funded by BTC on the book, match a 3 lot DCR sell with those three orders.  When matched, this triggers `swapMatchGroup` to run all three BTC `Swap` calls concurrently (which by design).  I used a `-race` build with Go 1.19.
**Cause:**  In my tests, two of them are doing `Updates` like from `refundAddress` > `(*Wallet).NewAddress` (or similar for `changeAddress`), and another that does a `View` for `signTxAndAddChange`.  This is where the problem is since `(*walletExtender).signTransaction` does the nested `View`, where the inner `View` deadlocks with one of the other `Updates`.
This is [called out in the bbolt …
> client/asset/btc: avoid a bbolt deadlock with nested View

- client/asset/dcr/dcr.go
- client/core/core.go
- client/core/core_test.go
- client/core/notification.go
- client/core/status.go
- client/core/trade.go
Builds on https://github.com/decred/dcrdex/pull/1732.
This PR is https://github.com/decred/dcrdex/pull/1739/commits/7a76dc3066627d07f8f171664363324aba1ded8c
I don't think this should be for 0.5, but I wanted to put it up so we can start considering some refactoring that will alleviate some of the deadlock and lock contention issues we've been grappling with in `Core`.
This is a bigger change to core to deal with the deadlocks and lock contention with `trackedTrades`.  The main changes are:
- Only _read_ locking the `trackedTrade` mutex for the portion of `tick` where the checks are going on (with lots of wallet requests), and only write locking when actions are taken subsequently that may need to modify trade and/or match status and metadata.  This is the section of code that was causing …
> core: refactor tick and matchTracker access model

- client/webserver/site/src/js/wallets.ts
This diff modifies `createWalletSuccess` to reload `wallets` page as part of the success callback for wallet creation. Closes #1754 and maybe #1763.
> reload wallets page when new wallets are created

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
The fixes a regression in `client/asset/btc.(*baseWallet).FundingCoins` introduced in https://github.com/decred/dcrdex/pull/1607/files#diff-1b07e494f4bdd99b2a617ac110fbadc081e5b6ae1abf23f64032bbee5ebebef1
This error return made sense before because it meant it had found the UTXO in the `listunspent` results but it did not find the vout in the `gettransaction` result `details` array.
Now if you have reached this spot, it means you have successfully found the output and added it to `btc.fundingCoins[pt] = utxo`.
> client/asset/btc: remove incorrect error return

- client/db/bolt/db.go
`UpdateOrder` must store the asset versions for both to/from assets.
Otherwise we wait for the first `UpdateOrderMetaData` data to actually store the real values.
This can be bad for LTC where we are on v1 already when we switched to segwit.
This fix was pulled from the draft https://github.com/decred/dcrdex/pull/1653#discussion_r916910330, and in that PR I also remove a bunch of stuff from `UpdateOrderMetaData` that should not be written except on order creation by `UpdateOrder`, but I'm not doing that here.
> client/db/bolt: store asset versions with order

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/order.ts
- client/webserver/site/src/js/orderutil.ts
- client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pl-PL/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl
- client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl
Resolves https://github.com/decred/dcrdex/issues/1769
> ui: correct match status for revoked matches

- client/comms/wsconn.go
- client/core/trade.go
Quoting @chappjc 
> I think my last comment from a year ago was a reasonable and minimal change (a response without a handler, but with Error field set -> log the error as "unhandled response with error msg: X" because there's nothing to do anyway other than wait for and handle another request that retries the previous failed one)
Closes #456 && #1770
> client: handle unknown response error gracefully

- .github/workflows/build.yml
- client/cmd/dexc/config.go
- client/cmd/dexc/main.go
- client/cmd/dexc/sample-dexc.conf
- client/webserver/live_test.go
- client/webserver/template.go
- client/webserver/webserver.go
- client/webserver/webserver_test.go
- pkg.sh
This PR closes #1664
For testing can run `go install` in dexc directory and make sure that the folder `site` isn't in the go executable's directory or the working directory.
> client: get site from go:embed

- client/webserver/site/src/js/wallets.ts
Encountered this issue while testing the new wallets page on master. Creating a new issue wasn't necessary :)
> client: fix missing asset ID error when creating new wallet address

- README.md
- docs/wiki/Client-Installation-and-Configuration.md
- docs/wiki/Server-Installation.md
* Add some setup instructions to the README, with link to detailed setup guide in the wiki.  https://github.com/decred/dcrdex/blob/c5017744b21a52acb64f7c33926b5a6032e3197b/README.md
* Move the server install section from the README to the wiki.  https://github.com/decred/dcrdex/blob/c5017744b21a52acb64f7c33926b5a6032e3197b/docs/wiki/Server-Installation.md
> docs: move server install to wiki, add install back to README

- .github/workflows/build.yml
- .markdownlint.json
This sets up a [markdownlint-cli2 GitHub action](https://github.com/marketplace/actions/markdownlint-cli2-action) in a mode that only prints violations but **does not fail** the workflow.  It takes about 6 seconds to run in CI and is purely informative. See [this workflow run](https://github.com/decred/dcrdex/runs/7903558863?check_suite_focus=true#step:3:10), for example.
I chose this particular action because David Anson is the author of markdownlint (https://github.com/DavidAnson/markdownlint), although there are many other [similar Github Actions](https://github.com/marketplace?type=actions&query=markdown+lint+sort%3Apopularity-desc+).
Devs should either configure their editor (e.g. https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) or use a …
> markdownlint-cli2 action

- client/webserver/site/src/js/charts.ts
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/login.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/register.ts
Each time the markets page is loaded I see these errors. Some elements might not be made available if we run `app().loadPage('markets')` without `await` which will result in `notes` and other methods trying to access elements that are not available. Don't know if there is more to these errors.
EDIT:  Also this.
EDIT 2: Looks like noteFeeder is trying to access a property on an object that is not yet available. Just like in #1754. It goes away after a refresh. I think these errors are all related to not waiting for `app().loadPage('markets')`.
> client: fix markets page

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/charts.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pl-PL/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl
- client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl
This resolves the error `Uncaught TypeError: can't access property "setExtents", e.zoomOutBttn is undefined`, which happens often on DEX server reconnect events.  Probably more so if you have more than one server configured.
The best way to reproduce is:
- get the dex window opened to the markets page
- switch to another tab in the same window, effectively hiding the tab
- minimize the window for good measure, but neither of these steps are really required
- wait for a reconnect, or wait a minute or two and force a reconnect (e.g. restart tor, toggle vpn, etc).
The root of the issue seems to be that the parent constructor was not setting the zoom buttons as intended.  And the `requestAnimation` callback that actually was setting them via the `resized` reporter is not called until the …
> site: set zoom buttons in DepthChart ctor

- dex/meter/meterer.go
- dex/meter/meterer_test.go
Left a comment in the test describing the root cause (**edit**: see 1st commit in this PR; actually, this test can be easily re-designed to avoid having to deal with Go scheduler - which is the latest version of this PR, i.e. 2nd commit).
Closes https://github.com/decred/dcrdex/issues/1782.
> dex/meter: fix flaky TestDelayedRelay test

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/wallets.ts
- client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pl-PL/bodybuilder.tmpl
- client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl
- client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl
Quoting @JoeGruffins 
> There is another js error I see if I start not connected to the dex and navigate to the wallets page, since you are fixing all these. You don't have to fix in this pr though.
This resolves: 
To reproduce: start dexc without internet connection -> login -> wallets page. While here the first auto-selected wallet will only display the wallet detail table, while the markets table and recent activity table remain blank(selecting another wallet loads the markets table and recent activity table but still produce errors).
> site: fix wallet page JS errors

- docs/release-notes/release-notes-0.1.0.md
- docs/release-notes/release-notes-0.2.0.md
- docs/release-notes/release-notes-0.4.0.md
- docs/wiki/Client-Installation-and-Configuration.md
- docs/wiki/Client-applications.md
- docs/wiki/Contribution-Guide.md
- docs/wiki/Getting Started With Fuzzing.md
- docs/wiki/Home.md
- docs/wiki/Localization-and-Translation.md
- docs/wiki/Native-BTC-Wallet-Recovery-and-Rescanning.md
- docs/wiki/Server-Admin.md
- docs/wiki/Simnet-Testing.md
- docs/wiki/Test-App-Server.md
- docs/wiki/Testnet-Testing.md
This is a follow-up PR addressing the [discussion here](https://github.com/decred/dcrdex/pull/1766#issuecomment-1219647962) and typos. The wiki is formatted based on the rules add by #1796.
> wiki: fix wiki lint errors

- client/core/core.go
- client/core/core_test.go
Concurrent attempts take a short path when the existing one unblocks.
Subsequent attempts do full Login, as before.
> prevent concurrent login in Core

- server/auth/auth.go
- server/auth/auth_test.go
- server/auth/cancel.go
- server/auth/cancel_test.go
- server/db/driver/pg/internal/orders.go
- server/db/driver/pg/orders.go
- server/db/driver/pg/orders_online_test.go
- server/db/driver/pg/upgrades.go
- server/db/interface.go
- server/market/market.go
- server/market/market_test.go
- server/market/orderrouter.go
- server/market/routers_test.go
- server/swap/swap_test.go
```
server/db:
Add epoch_gap column to cancel order table. When set (not EpochGapNA),
the epoch_gap is the number of epochs between the limit order placement
and the cancel order placement. Update InsertEpoch method to accept an
epoch gap argument (or EpochGapNA).
server/auth:
RecordCancel now accepts an epoch gap argument. Epoch gap is loaded from
the db via ExecutedCancelsForUser with a modified return value.
(*latestOrders).counts now only counts cancel orders if 0 <= epochGap < 2.
server/market:
processOrder now reports the epoch gap to the AuthManager for matched
cancel orders.
```
> server/{market,swap,db}: free cancels

- client/webserver/site/src/js/doc.ts
I investigated the issue resulting in #1808 and found out firefox and chrome behave differently on `mousedown` events.
I think the issue lies in the fact that Firefox triggers 3 events (onmousedown, onmousedown, onchange) instead of 2 (onmousedown, onchange) like Chrome does. The last `onmousedown` will have the screen coordination value of the event set to zero(cause the last mouse `event`  is actually right in the `Element`?). Closes #1808.
Reference 1: [w3c uievents #201](https://github.com/w3c/uievents/issues/201)
> site: fix firefox bug

- client/core/account.go
When using `UpdateDEXHost`, it will panic if the DEX server has been down since startup since there is no `dc.cfg` (the config response).  Checking `dc.cfg != nil` is a practice throughout `Core`, just forgotten here.
> client/core: allow changing dex host for down dex

- client/webserver/template.go
- client/webserver/webserver.go
v0.5.0 on Windows is broken when using embedded files because as per the `embed` pkg docs:
> The path separator is a forward slash, even on Windows systems.
So doing `filepath.Join`, which is usually "the right thing", fails on Windows.  Surprising to say the least.  https://github.com/golang/go/issues/45230 https://github.com/golang/go/issues/44305 https://pkg.go.dev/io/fs#ValidPath
For an immediate patch.
> windows embed paths

- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/doc.ts
The previous update to `Doc.mouseInElement` broke the profile and notification dropdowns. Using the new `Doc.mouseInElementBounds` function, which is the original implementation of `Doc.mouseInElement`, fixes them.
> app: Fix profile and notification dropdowns

- client/asset/dcr/rpcwallet.go
- dex/semver.go
- server/asset/dcr/dcr.go
This allows dex to work with both the 1.7 release versions of dcrd+dcrwallet and the 1.8 prerelease version on master presently.
dcrd was bumped from 7.0.0 to 8.0.0 on account of [removed expired/missed ticket RPCs](https://github.com/decred/dcrd/pull/2911), but we don't use them.
dcrwallet bumped from [8.8.0](https://github.com/decred/dcrwallet/commit/305bed7bace07539de610cc4d2f340b4fb0d699d) to 9.0.0:
- 8.9.0: Removed ticket revoking RPCs we didn't use. https://github.com/decred/dcrwallet/commit/081e25d7c85e5f5b5d0125dc7527406e68c4390b
- 9.0.0: Updated for the dcrd 8.0.0 change and small modification to `getstakeinfo`, which we didn't use. https://github.com/decred/dcrwallet/commit/4c162c4f0db5550d1951a6db8a053b3482d2c3e9
> dcr: work with range of JSON-RPC versions

- client/webserver/site/src/html/wallets.tmpl
If going to the wallet page before the spot price being calculated, an error will be thrown:
This PR fixes it.
> client: fix error before spot price

- client/asset/driver.go
- client/core/core.go
- client/core/helpers.go
- client/webserver/http.go
- client/webserver/site/src/html/order.tmpl
Previously, swap fees were displayed in place of redemption fees. Also, for tokens, the token asset was displayed as the fee asset instead of the parent. Both of these issues are fixed. Also, in the exported orders CSV, two new columns are added, one for the base asset's fee asset, and one for the quote asset's fee asset.
Closes #1814
> core: Fix swap/redemption fee info

- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/doc.ts
#1811 resulted in unexpected behaviour that was addressed by #1823. This diff merges `mouseInElement` and `mouseInElementBounds` to reduce duplicate code ([comment](https://github.com/decred/dcrdex/pull/1688#issuecomment-1234331131)).
> site: redo js mouseInElement

- client/asset/btc/btc.go
these logs are rebase dirt and weren't supposed to be pushed.
> client: remove unnecessary logs

- docs/wiki/Server-Installation.md
> Switching between networks requires changing the `regfeexpub`, but the exported key is network-specific. 
This diff adds minor information to the `Server-Installation` docs, so server operators can easily use network-specific config values like the `regfeexpub`. Closes #239.
> docs: improve Server-Installation docs

- client/core/helpers.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/html/order.tmpl
- client/webserver/site/src/js/order.ts
- client/webserver/site/src/js/orderutil.ts
Previously, the orders page displayed the actions out of order if you were the taker, and did not display the pending future events. It is now updated to show each of the swap actions in the proper order.
Closes #1790
> client:{app,core}: Make order page more intuitive

- docs/wiki/Home.md
- spec/comm.mediawiki
spec/comm: Update connect result.
wiki: Simplify contribution instructions.
part of #1641
comm page can be viewed at https://github.com/JoeGruffins/dcrdex/blob/wikihelplesshelpful/spec/comm.mediawiki
> spec/comm: Update connect result.

- client/core/core_test.go
- client/core/locale_ntfn.go
- client/core/localetest/main.go
- client/core/notification.go
- docs/wiki/Localization-and-Translation.md
- run_tests.sh
This adds a tool to check for missing notification translations.
This also modifies `(*Core).formatDetails` to use the origin/english text when a translation does not exist instead of just `"translation error"`.
The current missing ones:
```
4 missing notification translations for pl-PL
[pl-PL] Translation missing for topic WalletPeersWarning
[pl-PL] Translation missing for topic QueuedCreationFailed
[pl-PL] Translation missing for topic WalletPeersRestored
[pl-PL] Translation missing for topic WalletCommsWarning
4 missing notification translations for pt-BR
[pt-BR] Translation missing for topic WalletCommsWarning
[pt-BR] Translation missing for topic WalletPeersWarning
[pt-BR] Translation missing for topic QueuedCreationFailed
[pt-BR] Translation missing for topic WalletPeersRestored
4 …
```
> client/core: add reporter for missing ntfn translations

- dex/market.go
- spec/admin.mediawiki
This diff ensures a market's epoch duration is set to the [spec-defined epoch duration](https://github.com/decred/dcrdex/blob/master/spec/admin.mediawiki#exchange-variables) if the config epoch duration is invalid. Closes #300.
> dex: use spec defined epoch duration if provided value is not valid

- dex/wait/queue.go
- dex/wait/queue_test.go
Stumbled upon this test failure on master, looks like `TestTaperingQueue` should be somewhat more resilient to go-scheduler.
```
--- FAIL: TestTaperingQueue (0.01s)
queue_test.go:123: wrong result order expected [+1 +3 +4 +2 +0], got [+1 +3 +4 +0 +2]
FAIL
FAIL	decred.org/dcrdex/dex/wait	0.824s
```
With the changes from in this PR, problematic test still runs in under 2.5 seconds on CI, which I think is ok for flakiness trade-off (although it could be tweaked of course).
Closes https://github.com/decred/dcrdex/issues/1671.
> dcrdex/dex/wait: intermittent test failure

- client/core/bookie.go
- client/core/types.go
- client/orderbook/orderbook.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/css/market.scss
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/registry.ts
- dex/msgjson/types.go
- server/market/bookrouter.go
- server/market/market.go
- server/market/market_test.go
This PR closes #1143 
I am adding a basic match struct into `MatchProofNote` so we can be notified on the client.
On the client I added a new recent matches table in our market page. Here how it looks right now:
This is how it looks right now:
smaller screen:
> multi: show recently matched orders

- client/asset/bch/bch.go
- client/asset/btc/btc.go
re: https://github.com/decred/dcrdex/issues/1618#issuecomment-1248122923
Turns out Litecoin wasn't an issue, because it wasn't using `btc.CommonConfigOpts`, but Bitcoin Cash was offering the option even though it's custom `CloneCFG.FeeEstimator` doesn't support it.
> client/asset/btc: only offer fee rate oracle for bitcoin

- client/core/core.go
Rebased on https://github.com/decred/dcrdex/pull/1530.  This PR is just the one final commit https://github.com/decred/dcrdex/pull/1526/commits/70ec51bddbe9760cc0e882eae66f595f724cbd63
This is stage 4 of the signature message truncation fix plan outlined below.
In these commits, client **stops accepting** sigs on the truncated messages.  All servers must be sending the correct sigs i.e. have deployed the [stage 3](https://github.com/decred/dcrdex/pull/1530) of the fix.
----
In some places we were signing and verifying unhashed messages, resulting in truncation of the data we intend to sign and verify.  Because the truncation was performed on both sides, we didn't have errors, but the full payloads were not part of the verified message.  This included the signatures created and verified in …
> client: stop accepting sigs on the truncated messages (sig fix stage 4)

- client/asset/btc/btc.go
- client/core/core.go
- client/core/trade.go
- server/market/market.go
When reconciling an order that was in epoch status when the connection was lost and not restored before the preimage request (a preimage miss), be sure to unlock the funding coins when reconciling the status of the order to revoked.
There are two variants of this failure mode:
- Client reconnects after that and the order status is already **revoked**.  The first commit that adds a missing `trade.maybeReturnCoins` to the `updateOrder` closure addresses this.
- Client reconnects while the preimage collection is still active and the order status is still **epoch**, but they've still missed their preimage request (server doesn't re-send it).  This is addressed by flagging epoch orders in handleReconnect for a status check after a delay.
This PR also adds some additional edge case handling to …
> client/core: order status sync after preimage miss 

- client/asset/btc/livetest/regnet_test.go
- client/asset/eth/contractor.go
- client/asset/eth/eth.go
- client/asset/eth/fundingcoin.go
- client/asset/interface.go
- client/cmd/dexc/log.go
- client/core/errors.go
- client/core/notification.go
- client/core/types.go
- client/core/wallet.go
- client/db/bolt/db.go
- client/db/bolt/db_test.go
- client/rpcserver/handlers.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/js/charts.ts
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/locales.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/wallets.ts
- client/webserver/site/src/js/ws.ts
- client/webserver/types.go
- client/webserver/webserver_test.go
This diff fixes some `client` typos and removes unused newDisplayID func.
> client: fix typos and remove unused newDisplayID func

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/eth/nodeclient.go
- client/asset/eth/nodeclient_harness_test.go
- client/asset/interface.go
- client/core/core_test.go
- client/core/simnet_trade.go
- client/core/trade.go
- client/db/types.go
- dex/networks/eth/txdata.go
Fees for some trades cannot be accurately calculated until after the tx
is mined. For those assets, start a go routine to check on the txn until
it can be found and the actual gas used be added to the swap and
redemption fees paid.
~depends on #1739~
> trade: Update dynamic fees after they are mined.

- client/core/bookie.go
- client/core/types.go
- client/orderbook/orderbook.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/registry.ts
- dex/msgjson/types.go
- server/market/bookrouter.go
- server/market/market.go
- server/market/market_test.go
This encoding preserves order. Matches are only binned if they occur sequentially.
> multi: encode recent matches to preserve order

- server/db/driver/pg/internal/orders.go
The resolves a bug where the preimage field may shift position during the move.
> server/db: Move cancel fields explicitly.

- client/webserver/locales/en-us.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/locales.ts
- client/webserver/site/src/js/wallets.ts
Quoting @chappjc.
>At least something. You could argue fully validated address, but really it should not go to confirm for an empty address because that's obviously crazy
Sorry, I know we've been over this, but in testing all the assets' Send functionality, this really stuck out as bad UX.  (Says "Provide a valid address" on the "Confirm" form where it's too late to provide a valid address, so you have to cancel and go back.  So why does not just just stop you from getting to "Confirm"?)
This address a UI concern and the issue on the image below.
I was trying to simulate ZEC's edge case with BCH and noticed send amount was not displayed properly.
> site: reject invalid address for send or withdraw tx

- client/webserver/site/src/css/dex_settings.scss
- client/webserver/site/src/css/forms.scss
- client/webserver/site/src/css/forms_dark.scss
- client/webserver/site/src/css/market.scss
- client/webserver/site/src/css/market_dark.scss
- client/webserver/site/src/css/typography.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/dexsettings.tmpl
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/order.ts
- client/webserver/site/src/js/register.ts
- client/webserver/site/src/js/registry.ts
Resolves https://github.com/decred/dcrdex/issues/1886
> ui: fix market view bugs

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/core/core.go
`ETH` `NewWallet` initializes a node client and database and when initializing the node client, a lock is placed on the wallet's `datadir`. As a result, trying to enable the wallet will return `datadir already used by another process` because `loadWallet` will eventually call `NewWallet` which will try to initialize the node client and place a lock on the already locked `datadir`. Closes #1883
> asset/eth: create node client on Connect

- client/asset/btc/btc.go
- client/asset/btc/electrum.go
- client/asset/btc/electrum/example/wallet/main.go
- client/asset/btc/electrum/jsonrpc.go
- client/asset/btc/electrum/wallet.go
- client/asset/btc/electrum/wallet_methods.go
- client/asset/btc/electrum_client.go
- client/asset/btc/electrum_client_test.go
- client/asset/btc/rpcclient.go
- client/core/core.go
- dex/networks/btc/config.go
- server/asset/btc/btc_test.go
Resolves https://github.com/decred/dcrdex/issues/1867
To use a non-default wallet, it is necessary to:
- Include the full path to the wallet file loaded in Electrum in all RPCs that pertain to a specific wallet. This string is passed in the RPCs without interpreting the path.  See https://github.com/spesmilo/electrum/issues/7391
- Use named/dict `params` because positional arguments do not work for the wallet argument.  See https://github.com/spesmilo/electrum/issues/6221
Tested with: (1) the `electrumlive` BTC wallet "test", (2) the example/wallet/main.go app for LTC, and (3) interactive BTC testing with dexc and the UI with both an empty wallet arg for the default and a path to the wallet file `~/.electrum/testnet/wallets/wallet_1`. Tested on [a 0.5 …
> client/asset/btc: provide Electrum wallet path in RPCs if specified

- client/webserver/site/src/js/forms.ts
This PR is build on top of #1841
This PR is based in this matrix chat: https://matrix.to/#/!SFRQQFIHUUNXARfvew:decred.org/$Yy4D-nIYqum6RkurYGH6RDPz3WnvbzRBh85xZjow06o?via=decred.org&via=matrix.org&via=planetdecred.org
Where @chappjc mentioned the `Wallet Settings` header appearing and not disappearing was a small bug, but later said he feels like it should always show, when availble. 
I think that's reasonable, so this PR removes hiding the wallet settings header. The wallet setting header starts as hided. It will always show, if available. 
New behavior:
> client: No hide header when having additional settings

- client/core/bookie.go
- client/core/core.go
- server/book/book.go
- server/book/book_test.go
- server/market/market.go
The market `'suspension'` route is a somewhat mixed purpose notification in that all connected clients receive a notification of scheduled future suspension, but only `'orderbook'` subscribers get the _sequenced_ suspension notification at the time the market actually clears the book.
As such, if you have orders on the book, but do *not* have an orderbook subscription (e.g. you closed the browser window and it unsubscribed after 30 seconds or so), you will not get the final suspension notification that performs the "auto-revokes" and sends the kinder `TopicOrderAutoRevoked` notes to the frontend.  Instead, your client thinks the orders are still booked **until you reconnect with the server after market resumption** and order status reconciles from booked to revoked.  This is a bug.
To …
> server/market: send revoke order notes on suspend with purge

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/interface.go
- client/core/core_test.go
- client/core/trade.go
Two new fields are added to `asset.WalletInfo`: `MaxSwapsInTx` and `MaxRedeemsInTx`. `Core` uses these fields to call `Swap` and `Redeem` in batches if needed. These fields are currently only populated by ETH and ETH token wallets. They check each of the versions of the contract, and the fields are populated so that at most 1/4 of the gas limit of a block can be filled up by a swap or redeem transaction.
Closes #1771
> core/eth: Handle block gas limit

- client/asset/btc/btc.go
- client/asset/dcr/dcr.go
- client/asset/dcr/simnet_test.go
- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/interface.go
- client/core/addbond.txt
- client/core/core_test.go
- client/core/locale_ar_test.go
- client/core/new.txt
- client/core/regwithbond.txt
- client/core/trade.go
- dex/networks/dcr/script.go
- dex/networks/dcr/script_test.go
- server/asset/dcr/dcr.go
- server/asset/dcr/dcr_test.go
Further breaking up https://github.com/decred/dcrdex/pull/1480 for feasible review, this piece deals with:
- Definition of the fidelity bond transaction
- Creation of the bond and refund txn (for client)
- Parsing of the bond txn (for server)
To make this transition smoother, the **client and server retain all the legacy registration fee machinery**, and the client's continues to use the legacy registration system.
This creates a time-locked fidelity bond, which is redeemable by the user who posted the bond after a certain time. This creates a opportunity cost to use DCRDEX instead of a simple monetary cost.  It also is a prerequisite for [mesh](https://github.com/decred/dcrdex/issues/1765).
The DEX considers a user's bond as active when the bond script's `lockTime` (when it can be …
> fidelity bonds foundation: define bond tx structure, create and parse

- server/market/market.go
- server/swap/swap.go
- server/swap/swap_test.go
I also pulled out problematic part of `TestMalformedSwap` test into separate `TestRetriesDuringSwap` since it doesn't seem to be related to "testing malformed" (and I've discovered quite a lot of things this way about this functionality).
Closes https://github.com/decred/dcrdex/issues/1730.
> server/swap/test: fix intermittent TestMalformedSwap failures

- client/core/core_test.go
- client/core/simnet_trade.go
How about relaxing testing conditions a little bit so that there is no chance for intermittent failure due to reasons it happens in the example from issue description ?
Closes https://github.com/decred/dcrdex/issues/1912.
> client/core: fix intermittent TestWalletSyncing failure

- client/cmd/simnet-trade-tests/main.go
- client/cmd/simnet-trade-tests/run
- client/core/simnet_trade.go
- dex/testing/zec/harness.sh
- server/matcher/match.go
Fix numerous balance calculating issues. Run most tests twice,
alternating the maker and taker between clients. Add all, except, and
runonce commands. Cause requests to fail using communications rather
than altering match data.
closes #1783 and fixes some other problems with them not running.
> client/tests: Fix simnet tests.

- client/webserver/locales/parse.go
- client/webserver/locales/parse_test.go
I've noticed this template-parsing issue, and it seems it's been introduced recently (since in Decrediton 1.7.5 I don't observe it),
**On master:**
**With the changes from this PR:**
> UI: template parsing doesn't work with dash

- client/comms/wsconn.go
- client/comms/wsconn_test.go
This avoids hangs on shutdown with comms requests that would be waiting to timeout.
Since the connection dropping does not abort requests (and should not since there is a reconnect loop), we must call the expire func when the wsConn is explicitly shutdown, otherwise users of `Request` and `RequestWithTimeout` may hang until the request timeout is reached, depending on the use pattern.
For example, with this pattern used throughout the client, it would hang at `<-errChan` until timeout even if the `conn` were explicitly shutdown after sending the request:
```go
errChan := make(chan error, 1)
err = conn.RequestWithTimeout(reqMsg, func(msg *msgjson.Message) {
errChan <- msg.UnmarshalResult(response)
}, timeout, func() {
errChan <- fmt.Errorf("timed out waiting for %q response", route)
})
// …
```
> client/comms: expire requests on connection shutdown

- client/asset/btc/btc.go
- client/asset/btc/rpcclient.go
- client/asset/zec/zec.go
Resolves https://github.com/decred/dcrdex/issues/1768
Requires https://github.com/decred/dcrdex/pull/1909.
This root cause is essentially a simple omission from the `asset.Balance` for ZEC.  However, testing also revealed that zcashd does not unlock locked outpoints when they are spent, like dogecoind.  As such, this PR also sets the `UnlockSpends` config flag, and adds a spent utxo check to the `(*rpcClient).listLockUnspent` method.
> client/asset/btc: get locked balance for ZEC

- client/websocket/websocket.go
- client/websocket/websocket_test.go
- dex/runner.go
I've encountered this `panic` once (`dexc` doesn't crash since there is a `recover()` in place, but it did show up in logs, and I had to refresh web page to get it to working state):
```
2022-10-19 12:07:10.545 [CRT] WEB[WS][[::1]:52108]: Uh-oh! Panic while handling message from [::1]:52108.
​
Message:
​
&msgjson.Message{Type:0x1, Route:"loadcandles", ID:0x2, Payload:json.RawMessage{0x7b, 0x22, 0x68, 0x6f, 0x73, 0x74, 0x22, 0x3a, 0x22, 0x64, 0x65, 0x78, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x73, 0x73, 0x67, 0x65, 0x6e, 0x2e, 0x69, 0x6f, 0x3a, 0x37, 0x32, 0x33, 0x32, 0x22, 0x2c, 0x22, 0x62, 0x61, 0x73, 0x65, 0x22, 0x3a, 0x34, 0x32, 0x2c, 0x22, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x22, 0x3a, 0x30, 0x2c, 0x22, 0x64, 0x75, 0x72, 0x22, 0x3a, 0x22, 0x35, 0x6d, 0x22, 0x7d}}
​
Panic:
​
runtime error: …
```
> client/ws: fix panic in ws communications

- client/webserver/site/src/js/forms.ts
This PR fixes an error when creating an external wallet.
If going to external wallet form the following error will be thrown: 
The reason is because the configOpt is not added into the input when the input html element `ConfigOptionInput` is created. This PR fixes it.
> client: missing configOpt at input

- client/core/core.go
...like is done in ReconfigureWallet
Resolves https://github.com/decred/dcrdex/issues/1763
> client/core: delay walletstate note until creation complete

- client/asset/dcr/dcr.go
- client/asset/dcr/rpcwallet.go
All accounts must be unlocked, including any unmixed account, which is used to supply keys to the refund path of the swap contract script. If using a mixed account configuration with individually-encrypted accounts, AND the unmixed account is not unlocked, preparing the backup refund tx in Swap will fail (good and early!).
> client/asset/dcr: Unlock must unlock unmixed account

- client/db/bolt/db.go
Would it be useful to have DB path logged on startup ? to be able to back it up somewhere of a separate device, nuke it, etc.
I couldn't easily find where `dexc` stores its data.
> client/db: log database path on startup

- client/core/core.go
- client/core/simnet_trade.go
- client/core/trade.go
- client/db/types.go
multi: Ensure redeemed matches are confirmed.
Remove conditional checks for revoked matches that allow some to skip
redemption confirms. All matches that are redeemed now must make it to
status order.MatchConfirmed to be considered inactive.
closes #1924
> multi: Ensure redeemed matches are confirmed.

- client/asset/dcr/spv.go
- client/asset/dcr/spv_test.go
Resolves #1816.
After headers are fetched, other processes occur before the wallet is considered
synced and balance is updated. Use `SpvSyncer.Synced()` to accurately report
sync completion.
Reporting sync completed only after block headers are fetched results in dexc
reporting an outdated balance, which will only be corrected when a block is mined
_after_ wallet synchronisation (including account discovery and blocks rescan)
fully completes. Thus, new blocks won't necessarily update the balance unless
the new block notification is reported after the sync actually completes.
> client/asset/dcr: determine sync status with SpvSyncer.Synced() method

- client/webserver/site/package-lock.json
Again...
```
loader-utils  2.0.0 - 2.0.3
Severity: high
loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) via url variable - https://github.com/advisories/GHSA-3rfm-jhwj-7488
loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS)  - https://github.com/advisories/GHSA-hhq3-ff78-jv3g
fix available via `npm audit fix`
node_modules/loader-utils
1 high severity vulnerability
To address all issues, run:
npm audit fix
```
> js: Update loader-utils.

- client/asset/btc/btc.go
- client/asset/dcr/dcr.go
- client/asset/interface.go
- client/asset/options.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/registry.ts
This PR closes: #1874.
I added a `ShowByDefault` config option into `OrderOption struct`, which defines value to show by default. 
I am showing the txsplit option by default and hiding the others, as chapp showed interest in keep showing it. 
How it looks right now: 
hiding:
showing:
> client: hide advanced pre order options if not showing by default

- client/webserver/live_test.go
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/wallets.ts
- This fixes an error on the markets page for an unsupported wallet.
- Also fixes panic when trying to create specific test wallets(`mona`,...).
- Minor refactoring of the live tests. 
Closes #1949
> webserver: fix live testing wallet issues

- server/asset/btc/btc.go
- server/asset/doge/doge.go
- server/asset/zec/zec.go
This resolves a couple minor bugs introduced in https://github.com/decred/dcrdex/pull/1597
The `feeConfs` arg that was previously used for `estimatefee` was neglected when the `FeeEstimator` config item was replaced with a more sophisticated `(*Backend).estimateFee` method.  This setting was important for DOGE and BCH where a value of 1 almost always returns an estimate of -1 (failure), resulting in one of the median fee estimates.  In the case it was the "hard" way that is extremely demanding in terms of RPCs to the node, making a remote dogecoind instance virtually infeasible.
A second change is reducing the max blocks in the hard median fee estimator from 50 to 16, which is plenty because if it doesn't find 101 txns in 16 blocks it should just go with the "no competition" rate.
> server/asset/doge: use feeConfs and reduce maxFeeBlocks

- client/core/core.go
- client/core/core_test.go
<s>Requires https://github.com/decred/dcrdex/pull/1866, this PR is the last two commits:</s>
**client/core: blind cancel of unknown orders reported on connect**
```
There are a variety of pathological circumstances in which the
client can be unaware of orders that the server claims are active
(in epoch or booked status on the server). These include using
an old or corrupt DB file that lacks current orders, errors saving
submitted orders, and such trades having been self-revoked such
as if the server were down past the taker's locktime. Each of these
scenarios has been encountered in the wild.
This change introduces a simple "blind cancel" mechanism for submitting
cancel orders for any of the orders reported by the server on connect
that are not presently "active" according to the client. …
```
> client/core: blind cancel of unknown orders reported on connect

- client/core/core.go
- client/core/core_test.go
- client/core/locale_ntfn.go
- client/core/trade.go
Related to https://github.com/decred/dcrdex/pull/1889, this fixes one such bug that can lead to retired/non-existent orders on the client that are still booked on the server.
```
client/core: do not revoke trade when the cancel is revoked
This fixes a bug where a revoke_order notification from the server that
refers to a cancel order ID would cause the client to revoke the
targeted trade order instead.
Most of the time a cancel order is declared stale and deleted after it
becomes 2 epochs old, a heuristic we use to infer when we've missed the
preimage request for the cancel order.  This was necessary since unlike
trade orders, we don't expect to get status of cancel orders.  However,
we neglected the possibility that we could miss the preimage request
but reconnect in time to receive the …
```
> client/core: do not revoke trade when the cancel is revoked

- dex/networks/btc/script_test.go
- dex/networks/dcr/script_test.go
- server/asset/btc/btc.go
- server/asset/btc/rpcclient.go
- server/dex/dex.go
This ensures `txindex` is enabled by fetching information for a `coinbase` transaction of a given block which is essential for dex activities as it could be fatal for `btc` clone markets if this is not enabled. Closes #1778 
Litecoin Core version v0.21.2.1 has `getindexinfo` rpc command. Tested with bitcoin cash, dogecoin, litecoin and should work for zcash(my zec refuses to sync).
PS: @JoeGruffins, I'd be glad if you can find time to test this with zcash.
> server: fail fast if txindex is not enabled for btc clones

- client/core/bot.go
- client/core/core.go
- client/core/exchangeratefetcher.go
This addresses a bug where a fiat source rate returns zero rates after some time (~19hrs). This source has been removed in https://github.com/decred/dcrdex/commit/0210b57f513676daa32f071a7e67a53de2060095 and a sanity check added in  https://github.com/decred/dcrdex/commit/f7e7006c8e7e144e0946801d63ab62e1bd8a1060. Closes #1968.
PS:  I'd appreciate any suggestions of good sources to replace with.
> client: check for zero fiat rates and handle fiat rates request limit

- client/cmd/mmbot/main.go
- client/core/account.go
- client/core/core.go
- client/core/core_test.go
- client/core/locale_ntfn.go
- client/core/notification.go
- client/core/simnet_trade.go
- client/core/trade.go
- client/core/types.go
- client/core/wallet.go
- client/rpcserver/handlers.go
- client/rpcserver/handlers_test.go
- client/rpcserver/rpcserver.go
- client/rpcserver/rpcserver_test.go
- client/rpcserver/types.go
- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/css/market.scss
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/settings.ts
- client/webserver/webserver.go
- client/webserver/webserver_test.go
- dex/msgjson/types.go
`client/core`: 
- Login is updated not return a `LoginResult`. It only returns an error if the password is incorrect. On the first login after startup or after a logout, the wallets are connected, active trades are resolved, and the dex connections are authed. On subsequent logins, only the password is checked.
- Two new functions, `GetNotifications` and `AuthDEXConnections` are added.
- `loadDBTrades` now adds all trades for which a `walletSet` is able to be generated to the `dexConnection`'s trades map. A field `readyToTick` is added to `trackedTrade`, and `tick` returns early for trades where it is set to false. `resumeTrades` will set `readyToTick` to true for all trades where both wallets can be unlocked. `resumeTrades` is also called whenever a wallet is unlocked or connected in …
> client/core: Refactor Login

- client/asset/bch/bch.go
- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/btc/electrum.go
- client/asset/btc/electrum_client.go
- client/asset/btc/electrum_test.go
- client/asset/btc/rpcclient.go
- client/asset/btc/spv_wrapper.go
- client/asset/btc/wallet.go
- client/asset/dcr/dcr.go
- client/asset/doge/doge.go
- client/asset/doge/regnet_test.go
- client/asset/zec/zec.go
- client/core/core.go
- client/core/core_test.go
- client/core/trade.go
This refactors the BTC `baseWallet` fee rate handling to abstract the internal/external estimate calls in a `feeRate` method.  The `estimateSmartFee` RPC-specific wallet method is now removed and no longer part of the `btc.Wallet` interface.
This replaces https://github.com/decred/dcrdex/pull/1888.  The commit is still authored by @vctt94, but also "co-authored" by myself and @buck54321.
Co-authored-by: Brian Stafford <buck54321@gmail.com>
Co-authored-by: Jonathan Chappelow <chappjc@gmail.com>
> client: refactor btc FeeEstimator and added DOGE external

- client/asset/bch/spv.go
- client/asset/btc/spv.go
- client/asset/btc/spv_wrapper.go
- client/asset/dcr/spv.go
- client/asset/ltc/spv.go
This fixes an issue where wallet recovery deletes the existing neutrino log file but logging initialization is a one-time operation. Closes #1944.
> asset: create btcwallet+neutrino log dir and file without initialization

- client/webserver/site/src/js/wallets.ts
This fixes an issue where the fiat value displayed was for `send value` when it should be for `send value + txfee` which is the `totalSend`. The issue is not really noticeable for other dcrdex versions with this code because only the `txfee` fiat value(really small for some assets) is left out of the fiat value display for `totalSend`. Closes #1982
> minor: display fiat value for actual total send on send verification form

- dex/meter/meterer.go
- server/swap/swap.go
closes #1984
please see https://go.dev/play/p/U9d_pvnMBu6
As called out in the docs https://pkg.go.dev/time#Timer.Stop It does not close the channel. If the timer has already fired, nothing happens. The example says "assuming the program has not received from t.C already"
So anyway, we are not reusing the timer, so I don't think we need to worry about it.
> meterer: Do not wait for stopped timer.

- client/db/bolt/db.go
```
client/db/bolt: more aggressive DB compaction
This makes the DB compaction smarter, considering all free/unused
bytes regardless of their sources. Previously it was only considering
FreePageN, which can be was only a small part of the unused space,
making compaction very unlikely for most DBs in practice.
This also creates a relative free space threshold (5%) in addition to
an absolute bytes free space threshold (256 KiB). Free space must
exceed *both* thresholds to trigger a compaction. This is to spare
long and large compactions happening too frequently for very large
DB files.
The logging that reports the percent space reclaimed is also fixed
since it was reporting 1-pct instead of pct.
Example of new checks and logs with a large testnet DB:
CORE[DB]: Total DB size 1057017856 …
```
> client/db/bolt: more aggressive DB compaction

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/btc/rpcclient.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/interface.go
- client/cmd/dexc/config.go
- client/cmd/dexc/main.go
- client/core/core.go
- client/db/bolt/db.go
- dex/testing/loadbot/mantle.go
These options are aimed at improving startup and shutdown speed of headless clients by avoiding unneeded work.
```
client/{core,db}: options for core startup/shutdown
This adds two new core.Config options aimed at improving startup
and shutdown depending on the user's use case:
- NoAutoWalletLock instructs Core to skip locking the wallet on
shutdown. This can be helpful if the user wants the wallet to remain
unlocked. e.g. They started with the wallet unlocked, or they intend
to start Core again and wish to avoid the time to unlock a locked
the wallet on startup.
- NoAutoDBBackup instructs the DB to skip the creation of a backup DB
file on shutdown. This is useful if the consumer is using the
BackupDB method, or simply creating manual backups of the DB file
after shutdown.
These options …
```
> client/{core,db}: headless options

- spec/README.mediawiki
This only updates the readme for the current spec. Some places will still need to change like registration but hopefully that is ok as incremental changes.
Unexpectedly, none of the links with spaces scrolled. I am pretty sure that these worked before, so perhaps browser handling changed at some point? I have tested on firefox and chrome and it seems that underscores do not work, they need to be hyphens. Please confirm this behavior. Here are the changes on my branch https://github.com/JoeGruffins/dcrdex/tree/updatespecadmin/spec
Part of #1641
> spec: Update README.

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/core/bot.go
- client/core/core.go
This fixes a bug in the asset backends' `estimateSwap` handling when trying a split transaction.
It was possible for the estimates to permit/allow a split even when it would consume more than without a split transaction. The symptom of this was that the "locked" amount estimates obtained when requesting a split could be higher than if not using a split, resulting in an integer underflow in the caller when comparing the two amounts.
Resolves https://github.com/decred/dcrdex/issues/1959
[client/asset: fix estimateSwap split rejection](https://github.com/decred/dcrdex/commit/dac81568edf388767266f0bb71de745f6c06115f)
```
The enough func in estimateSwap does not account for a split transaction
at the start, so it is possible that funding for trySplit would actually
choose more UTXOs. Actual …
```
> client: fix split option handling

- client/asset/btc/spv_wrapper.go
- client/asset/dcr/spv.go
Resolves #2006.
Sync target height becomes 0 (for btc) or the same as the wallet tip (for dcr) when the correct value cannot be inferred from connected peers when the connection to all peers is lost.
Fix: cache sync target height so the cached value is used when calculating sync progress even when there are no peers connected.
> client/asset/{btc,dcr}: maintain sync progress after losing peers

- client/asset/dcr/dcr.go
- client/asset/dcr/externaltx.go
- dex/networks/dcr/script.go
- dex/networks/dcr/script_test.go
Resolves https://github.com/decred/dcrdex/issues/2009
The first commit fixes a bug whereby "unknown" spend status causes the DCR backend to attempt to refund even if it was already spent in certain undetectable situations.  Normally not an issue since for taker the maker redemption search would have been running prior to locktime expiry that triggers the refund attempt.
The second commit adds the ability to recognize when a located spending transaction is a refund, in which case that transaction is returned without authoring a new one.
In draft because it may be necessary to skip the broadcast step if the refund transaction was locate in this manner.
> client/asset/dcr: refund method recognizes spends in refunds

- client/orderbook/orderbook.go
closes #2029
Tested on a 32bit arm OS.
> orderbook: Move atomic fields to top of struct.

- client/Dockerfile
Switch to non-root user before executing `dexc`.
This PR modifies the volume mount directory from `/root/.dexc` to `/dex/.dexc`; scripts and `docker-compose.yml` files that specify the mount will have to be updated.
> [docker] Run dexc as non-root user

- server/swap/swap.go
This resolves the deadlock observed in https://github.com/decred/dcrdex/actions/runs/3824469529/jobs/6506641057#step:5:1100
```
When deleting a match after receiving the maker's redeem ack (of the
taker's redeem), do not violate established lock ordering of
Swapper.matchMtx and matchTracker.mtx.  This deals with the matchMtx
prior to locking the matchTracker, avoiding a possible deadlock with
another goroutine locking these.
```
> server/swap: avoid deadlock with maker redeem ack

- client/asset/eth/eth.go
- server/asset/eth/eth.go
- server/asset/eth/eth_test.go
Post merge geth will report both the current and highest block as the same number. Check the header time even when we would have been synced before the merge.
closes #2017
> eth: Always check header time.

- client/webserver/locales/en-us.go
- client/webserver/site/src/css/main_dark.scss
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/state.ts
Resolves #1985
Allows the user to hide the warning message on the order verification form. This will hide the message and display instead an option to show the warning again. 
---
`Window.localStorage` is used to remember the user's choice.
> ui: enable order warning acknowledgement

- client/webserver/site/src/css/main.scss
- client/webserver/site/src/css/main_dark.scss
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/html/register.tmpl
- client/webserver/site/src/html/wallets.tmpl
Trying to improve checkbox UX a bit in this PR, namely:
- define common style for checkbox-type inputs so that it is consistent across different forms (if necessary, particular form can adjust/redefine it ofc)
- lower check-box brightness in dark-mode (it's way too bright/white compared to everything else, sticking out)
- highlight (currently just making font bold, maybe there is a better approach for this) **label** when hovering over ; this helps significantly with signalling to the user that he **can click on the text**, which is much easier than trying to pin the actual **box**; I think there is a room to improve checkboxes overall (redesign them somehow), can't suggest anything better at the moment though
Demo: 
https://user-images.githubusercontent.com/112318969/208713669-bc8f2b50-b4 …
> ui: uniform responsive checkbox

- client/asset/eth/eth.go
When reconfiguring, the wallet settings on the baseWallet type were not being updated. When updating the RPC providers list on an unconnected wallet, the new providers were not being stored, so on Connect, it would attempt to connect to the old providers list.
Closes #2046
> cient/eth: Update wallet config after reconfigure

- dex/networks/bch/params_test.go
- dex/networks/btc/test/compat.go
- dex/networks/doge/params_test.go
- dex/networks/ltc/params_test.go
- dex/networks/zec/params_test.go
- server/asset/btc/testing.go
Extracting this change from https://github.com/decred/dcrdex/pull/1993, so that the DGB PR can be a model.
The idea of this change is that `CompatibilityCheck` is testing the parameters defined in `dex/networks`, so it should be in `dex/networks`.  This also makes a special test package (`dex/networks/btc/test`) so that this code, which is not used in production, does not find it's way into the exported product code.
> server/asset: move CompatibilityCheck to dex/networks

- server/asset/eth/rpcclient.go
The server's rpcClient will only take into account pending transactions if it can use the rpc_getmethods method to check the available methods, and if the txpool namespace is available.
> server/eth: Do not use txpool when calculating balance if not supported

- client/core/core.go
- client/core/wallet.go
> asset: display asset symbol in failed connect message

- client/webserver/site/src/css/application.scss
- client/webserver/site/src/css/main.scss
- client/webserver/site/src/css/main_dark.scss
- client/webserver/site/src/css/market.scss
- client/webserver/site/src/css/market_dark.scss
I noticed after #2002 that the checkbox is hard to see in dark mode. 
Also, we didn't have consistent input borders site-wide. 
Now all inputs, selects, and checkboxes have a light border in both dark and light mode.
> ui: normalize input borders

- client/asset/btc/btc.go
- client/asset/btc/spv_test.go
- client/asset/dcr/dcr.go
- client/asset/eth/eth.go
- client/core/core_test.go
- client/core/trade.go
> client/assets: add feeRate sanity check for swaps and minor refactoring

- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/wallets.ts
closes #2040.
I am always showing the settings button for tokens now, even though they don't have configopts defined. This way it is possible to enable or disable and export them.
> client: fix missing settings button for erc20 tokens

- client/webserver/locales/parse_test.go
- client/webserver/middleware.go
- client/webserver/site/src/css/market.scss
- client/webserver/site/src/css/market_dark.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/html/settings.tmpl
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/mm.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/settings.ts
- client/webserver/site/src/js/state.ts
- client/webserver/site/src/js/wallets.ts
- client/webserver/webserver.go
This PR implements saving (between page switch/refresh or `dexc` restarts) the following UI preferences a user can set:
- hide/show left market dock on `/markets` page
- select chosen wallet on `/wallets` page
Relevant UI views affected:
> ui: store markets/wallets user preferences

- client/webserver/site/src/js/markets.ts
> ui: use superscript format for market header asset symbols

- client/rpcserver/types.go
closes #2084
An oversight. There should always be a config. We check for keys later.
> client/rpcserver: Always add a new wallet config.

- client/core/notification.go
The matchTracker.swapConfirms is an atomic, with the confirms() method as it's acccessor. newMatchNote was neglecting this.
> client/core: fix newMatchNote swapConfirms data race

- client/asset/driver.go
`withDriver` held the mutex for the entire duration of the provided function, AND it was write locking. This blocked other things such as `Assets()` and more importantly, `DecodeCoinID`. Deadlock. The mutex only protects the map, so release it after retrieving the requested driver, and only use a read lock.
> client/asset: eliminate excessive locking on driver maps

- client/asset/btc/spv_test.go
Maybe resolves https://github.com/decred/dcrdex/issues/1268.
Looks like a typo that needs fixing regardless of whether or not it resolves 1268 (but it probably does as far as I can tell).
> client/btc: fix racing test

- client/asset/eth/multirpc.go
> eth: don't cancel ws header subscription context

- server/asset/common.go
- server/asset/eth/eth.go
- server/asset/eth/eth_test.go
re: https://github.com/decred/dcrdex/pull/2104#discussion_r1096819950
We don't use reorg. No need for complex tip change handling.
> server/asset/eth: forget reorg handling

- client/asset/eth/multirpc.go
Found another race:
```
Read at 0x00c000e82270 by goroutine 3921:
decred.org/dcrdex/client/asset/eth.(*multiRPCClient).nonceProviderList()
/Users/norwnd/dcrdex/client/asset/eth/multirpc.go:850 +0x178
decred.org/dcrdex/client/asset/eth.(*multiRPCClient).withPreferred()
/Users/norwnd/dcrdex/client/asset/eth/multirpc.go:837 +0x4e
decred.org/dcrdex/client/asset/eth.(*multiRPCClient).CallContract()
/Users/norwnd/dcrdex/client/asset/eth/multirpc.go:1149 +0x132
github.com/ethereum/go-ethereum/accounts/abi/bind.(*BoundContract).Call()
/Users/norwnd/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.25/accounts/abi/bind/base.go:186 +0x62c
decred.org/dcrdex/dex/networks/eth/contracts/v0.(*ETHSwapCaller).Swap()
/Users/norwnd/dcrdex/dex/networks/eth/contracts/v0/contract.go:296 …
```
> client/eth: multiRPCClient.lastProvider race

- client/Dockerfile
This PR backports the docker optimizations from master.
> [0.5] Dockerfile optimizations

- client/asset/eth/eth.go
~~This is needed for #2054.~~ The tokens supported versions were not exposed because tokens without wallets don't expose `WalletInfo` (no `Driver`).
Changing tacts on this a bit. Instead, we'll just have the tokens share the parent asset's versioning, and the server will maintain with a single protocol version. 
Just a reminder that server protocol version != contract version. A server's version does map to a contract version, but it's not one-to-one. i.e. you cannot add a new contract version without incrementing the server version, but a server version could be incremented for other reasons too. I've fixed versioning ambiguity in a couple places in this effort, but there is much more work done in #2038. I could potentially pull that out into a separate PR.
> client/asset: clarify eth and token versioning

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/charts.ts
- client/webserver/site/src/js/markets.ts
`RateEncodingFactor * quoteFactor / baseFactor` gives the conventional rate, but
`RateEncodingFactor * baseFactor / quoteFactor` was being used.
Closes #2114
> app: Fix candle chart Y-Axis

- client/core/account.go
- client/core/account_test.go
- client/core/bond.go
- client/core/core.go
- client/core/core_test.go
Issue:
Updating a dex cert to an invalid causes `core` to run a continuous retry using the bad cert (until dex is restarted). The old connection was disconnected and replaced even though the new connection failed.
Fix:
This fix allows `core.UpdateCert` to specify that failed connection(while updating a dex's cert) should not replace the previous connection.
-- Modified `core.connectAccount` to accept an `addFailedConn bool` value which is used to control behaviour concerning saving a failed connection to the conns map. 
I should have opened an issue first but I think it was better to deal with it.
> core: reestablish old dex connection if new one is unsuccessful

- client/db/bolt/db.go
- client/db/bolt/db_test.go
- dex/order/match_test.go
- dex/order/test/helpers.go
- server/auth/cancel_test.go
- server/book/orderpq_test.go
- server/coinlock/coinlocker_test.go
- server/market/integ/booker_matcher_test.go
- server/market/market_test.go
- server/market/routers_test.go
- server/matcher/match_test.go
Early on we got in the habit of building tests on data with reproducible random sequences using the `math/rand` package's global `*math.Rand` instance, seeding it with some arbitrary hard coded numbers to get certain sequence.  That proved quite problematic for test maintenance, concurrency, and now the standard library rightly has deprecated the use of `rand.Seed` and they have made the default initialization actually random instead of with "1" as the seed.
> The [math/rand](https://go.dev/pkg/math/rand/) package now automatically seeds the global random number generator (used by top-level functions like Float64 and Int) with a random value, and the top-level [Seed](https://go.dev/pkg/math/rand/#Seed) function has been deprecated. Programs that need a reproducible sequence of random …
> tests: repo-wide bandaid for rand.Seed badness

- dex/testing/loadbot/go.mod
- dex/testing/loadbot/go.sum
- go.mod
- go.sum
This updates the dcrwallet import for a deadlock fix in https://github.com/decred/dcrwallet/commit/f9452d346121990cadcfb9b5759e4ee02e806d71 (see https://github.com/decred/dcrwallet/pull/2205)
Thanks, @norwnd
> dep: update dcrwallet import for deadlock fix

- .github/workflows/build.yml
- client/core/bot.go
- run_tests.sh
- server/db/driver/pg/internal/matches.go
- server/db/driver/pg/internal/orders.go
Rebased on https://github.com/decred/dcrdex/pull/2098, this switches CI to use Go 1.19 and Go 1.20, dropping 1.18.
https://github.com/decred/dcrdex/pull/2100/commits/8af52e32aed67c6d929bcce9f118d2bec88dea28
This does not however update the go.mod files.  Those still require at least 1.18, for now.
> ci: test with Go 1.20 and 1.19

- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/wallets.ts
When attempting to create a token wallet when the parent wallet has not yet been created, the configuration screen was blank. This is fixed.
Closes #2085
> app: Fix token wallet creation

- client/core/bond.go
- client/core/types.go
Observed another race:
```
Read at 0x00c0006a80a0 by goroutine 47:
decred.org/dcrdex/client/core.(*dexAccount).status()
/Users/norwnd/dcrdex/client/core/types.go:847 +0xed
decred.org/dcrdex/client/core.(*Core).rotateBonds()
/Users/norwnd/dcrdex/client/core/bond.go:168 +0x1e4
decred.org/dcrdex/client/core.(*Core).watchBonds()
/Users/norwnd/dcrdex/client/core/bond.go:44 +0xd6
decred.org/dcrdex/client/core.(*Core).Run.func3()
/Users/norwnd/dcrdex/client/core/core.go:1579 +0x9e
Previous write at 0x00c0006a80a0 by goroutine 1617:
decred.org/dcrdex/client/core.(*dexAccount).auth()
/Users/norwnd/dcrdex/client/core/types.go:878 +0x5e
decred.org/dcrdex/client/core.(*Core).authDEX()
/Users/norwnd/dcrdex/client/core/core.go:6000 +0x15e6 …
```
> client/core: dexAccount race

- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/markets.ts
The fee summary panel now shows the fees as a percentage of the order for token assets, if the fiat rate is available for both the token and the parent. Also, if the percentage is less than 0.05%, "< 0.1" is displayed.
Closes #2095
> app: Fee summary touch-ups

- client/core/core_test.go
This improves `TestRegister` to use a `time.Ticker(10 * time.Microsecond)` instead of `time.After(10 * time.Millisecond)` when waiting on notifications and to free timer resources when done with tests. Notice the change in `tick duration` reduced to `10 Microseconds`.  While I am unable to reproduce the rare error described by #2128 this an attempt to resolve #2128.
> client/core: improve `TestRegister`

- dex/testing/dcrdex/harness.sh
- server/asset/eth/eth.go
- server/asset/eth/rpcclient.go
- server/asset/eth/rpcclient_harness_test.go
Previously, the ETH backend would not start if any of the providers could not connect or was outdated. Now, if at least one of the providers is able to connect and the header is recent, the backend will start. After connecting, a goroutine will start that will periodically check the health of the RPC providers, sort the list putting the non-outdated ones first, outdated ones after, and the ones that fail to respond last. Requests will then attempt to use the rpc providers in this order.
Closes #2122
> server/eth: Monitor RPC provider health

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/markets.ts
This makes the order `status` text as well as any "active" light indicator expand the order details div, in addition to clicking the `expander`. This is just to make it a bit easier to get the order details to expand, without having the entire header element under user-order trigger expanding it, although that might be ok too.
To clarify, you can click the status text in addition to the expander icon to the order `detailsDiv` to expand down.
(click) =>
> ui: make order detailsDiv slightly easier to drop down

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
`TipChange` was being called for token wallets that were not yet connected. This caused core to call the token wallet to retrieve its balance, but because it was not yet connected, it would return an error.
Closes #2137.
> client/eth: Only call tipChange and peersChange for connected wallets

- client/comms/wsconn.go
- client/comms/wsconn_test.go
This seems to be a known issue on some versions of `MacOS` or `OS X` where an error: `x509: “invalid-cert-name” certificate is not standards compliant` is returned. Since we cannot check the error type using `errors.Is` or `errors.As`, this PR checks if the returned error contains the known error message `certificate is not standards compliant`.
Users could run varying versions of `macOS` and could be affected by this issue. This PR will ensure that a retry loop is not started because the cert is considered `Invalid`.
Issue: https://github.com/golang/go/issues/51991
For more context, I use `macOS` and was a bit flustered that `TestWsConn` kept failing, so I had to investigate.
> client/comms: check for non-standard compliant error

- server/auth/auth.go
> server/auth: use `misstep` parameter of `*AuthManager.Inaction(...)` instead of global `SwapSuccess` variable

- client/core/core.go
Additional space at the end was causing the port to not parse properly.
Closes #2146
> core: Trim URL before parsing

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/eth/multirpc.go
- client/asset/eth/multirpc_live_test.go
- client/asset/eth/nodeclient.go
- client/asset/eth/nodeclient_harness_test.go
When fetching a new or cached header with a provider, do a basic check on the header's time to determine if the header, and so the provider, are up to date.
closes #2064
> client/eth: Check provider header times.

- client/core/helpers.go
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/orderutil.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/wallets.ts
Resolves https://github.com/decred/dcrdex/issues/1945.
For the case described in the linked issue (and I haven't seen other cases) now  status is same (and correct one) for all navigated views:
[status-discrepancy.webm](https://user-images.githubusercontent.com/112318969/219619838-0382951b-f727-4ebb-837e-514555db75ca.webm)
> ui: fix order status discrepancy on different views

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
Revising the "best" swap estimates for dcr and btc as per the discussion on https://github.com/decred/dcrdex/pull/2139#discussion_r1110502885
Previously we considered the "best" swap fee estimate to be when there was a single transaction that batched several matches, but the true best is when there is a perfect match with another multi-lot order.
The UI and Go interface docs describe this as well.  This makes the estimates reflect this interpretation.
> client/asset/{btc,dcr}: best swap estimate is perfect match

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/locales.ts
Resolves https://github.com/decred/dcrdex/issues/2080.
This should address boths parts of https://github.com/decred/dcrdex/issues/2080:
- progress stuck at 100% for more than one would expect (while wallet is still undergoing some final stages of syncing; this also makes sync progress behavior  consistent with 99.9% shown on `/wallets` page)
current behavior seems to result from rounding 99.9% to 100% (currently on **master**), while `.toFixed(1)` will not round and just trim all the extra digits instead, which is probably what we want here too,
- `> 1 day remaining` message isn't very accurate
I've reimplemented some edge-case handling to address that.
> ui: wallet sync progress improvements (register page)

- client/db/bolt/db.go
The db.Notification serialization and thus ID changed in https://github.com/decred/dcrdex/commit/c994f032fe0e9a36e58a9a984dd924734c659e36#diff-592072666205a423f50bc3061a74c2cda51bfe4689d4044315ff285d29645bc3R832
The ID was used as the bucket key.
Therefore any notes prior to the upgrade will be stored in a bucket with a different key than it's new ID.  This isn't a big deal except that acknowledging such notes will fail for eternity.
In draft because I'm considering auto-acking such notes on load.
> client/db/bolt: ignore notes with bad IDs

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
Resolves https://github.com/decred/dcrdex/issues/2136 <s>https://github.com/decred/dcrdex/issues/2137</s>
Best/worst fee rate estimates from PreSwap (to PreOrder on frontend) are now considering the current effective (likely) fee rate, not the server's MaxFeeRate or the "recommended" max fee when authoring txns that would be more than double current base fee.
> client/asset/eth: use currentFeeRate for preSwap, not max

- client/asset/eth/eth.go
- client/asset/eth/multirpc.go
- client/asset/eth/multirpc_live_test.go
- client/cmd/dexcctl/simnet-setup.sh
- dex/testing/eth/create-node.sh
- dex/testing/eth/harness.sh
Check all providers that are not known to be good. Check them on
reconfigure as well. Also use WebSocket with full nodes rather than the
light node.
> client/eth: Remove non compliant providers.

- client/core/core.go
- client/db/bolt/db.go
After testing bonds PRs with my testnet dexc db, I went back to master or another PR, and that failed to load the Accounts because it didn't know v3 of `db.AccountInfo`.  However, i barely noticed this because it's not a fatal error.
This acts on a long standing comment to make this error fatal.  <s>I'm just using panic/recover as suggested by the comment because I didn't really want to add and `error` return to `initialize`, although that wouldn't be horrible now that I look again.</s> Now returning an error from `initialize`.
> client/core: return from Run if db.Accounts fail in initialize

- dex/testing/btc/base-harness.sh
- dex/testing/dcr/harness.sh
- dex/testing/eth/harness.sh
Just a thought. We don't have to auto-mine, and I haven't considered how this might affect others tests, but it seems simple enough and I think we'll want something reasonable for bond maintenance.
> testing: add miners to harnesses

- client/asset/eth/eth.go
- client/asset/eth/multirpc.go
- client/core/core.go
- server/asset/eth/eth.go
Resolves https://github.com/decred/dcrdex/issues/2158
```
This quiets down the logs from the RPC provider compatibility tests,
which was only supposed to be enable for testing and debugging.
This also removes a duplicate check for PendingNonceAt.
This also removes the redundant sublogger so that
CORE[eth][ETH] becomes just CORE[eth].  Same on server.
Finally, the changes the subloger used by CreateWallet not be
CORE[CREATE], and instead just show the asset symbol.
```
This also resolves the missing parent path for the compliant providers json file on initial wallet creation.
> client/asset/eth: less provider check spam

- client/asset/dcr/coin_selection.go
- client/asset/dcr/coin_selection_test.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/simnet_test.go
- client/asset/interface.go
- client/core/account.go
- client/core/bond.go
- client/core/core.go
- client/core/core_test.go
- client/core/types.go
- client/core/wallet.go
- client/webserver/live_test.go
- client/webserver/site/src/css/wallets.scss
- client/webserver/site/src/css/wallets_dark.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/wallets.ts
- dex/networks/dcr/script.go
<s>Requires https://github.com/decred/dcrdex/pull/2036. In draft until that's settled.</s>
This PR is the commits starting with `client/{asset,core}: RefundBond broadcasts too`.
Commit messages (but there are a ton of "fixup" commits already pushed that will be squashed before this is merged):
[client/{asset,core}: RefundBond broadcasts too](https://github.com/decred/dcrdex/commit/c759d01b4bb6e45a82c5f22bba779dd89d7b44b8) 
```
The asset.Bonder.RefundBond method now broadcasts, as it was supposed
to from the beginning. Only MakeBondTx required broadcasting in the
consumer.
```
[client/{asset,core,webserver}: BondLocked balance category](https://github.com/decred/dcrdex/commit/df1d6d4c06cba7a1b72dd056de7ed88225b2a963) 
```
This adds the client.WalletBalance.BondLocked field, which parallels …
```
> client: bond reserves

- .github/workflows/release-docker.yml
- client/Dockerfile
- client/Dockerfile.release
- SIlence apt terminal warning
- Use `docker/login-action` for docker hub login
> build: use docker/login-action and make apt-get non-interactive

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/eth/node.go
- client/asset/eth/nodeclient.go
- client/core/bookie.go
- dex/networks/eth/params.go
- dex/networks/eth/tokens.go
- server/asset/eth/eth.go
- server/asset/eth/eth_test.go
- server/asset/eth/rpcclient.go
- server/asset/eth/rpcclient_harness_test.go
<s>Rebased on https://github.com/decred/dcrdex/pull/2111</s>
Resolves https://github.com/decred/dcrdex/issues/2010
ETHSwap: https://etherscan.io/address/0x8c17e4968b6903e1601be82ca989c5b5e2c7b400#code
ERC20Swap: https://etherscan.io/address/0x1bbd020ddd6dc01f974aa74d2d727b2a6782f32d#code
All code verified by etherscan
> enable eth and usdc.eth on mainnet

- client/db/bolt/db.go
- client/db/bolt/upgrades.go
- dex/order/serialize.go
- dex/order/test/serialize_test.go
Option 2 of 2 that resolves https://github.com/decred/dcrdex/issues/2164
See other option at https://github.com/decred/dcrdex/pull/2165
I **have** confirmed that this PR works yet.
> client/db,dex/order: patch archived match status based on enc version

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/wallets.ts
A variety of notifications from the client backend cause the frontend to update an asset's "button" on the wallet's page.  In part, this involves setting `tmpl.img.src`, which unfortunately initiates a GET request for the resource, whether the path has changed or not.
For instance, my testnet bch wallet was spewing wallet state notes, causing repeated fetches of the bch.png icon each time:
If the browser isn't sharp about caching these resources, it hits the backend repeatedly:
```
2023/02/23 13:54:17 "GET http://127.0.0.2:5758/img/coins/bch.png HTTP/1.1" from 127.0.0.1:54706 - 200 4103B in 12.844756ms
2023/02/23 13:54:20 "GET http://127.0.0.2:5758/img/coins/bch.png HTTP/1.1" from 127.0.0.1:54706 - 200 4103B in 12.682972ms
2023/02/23 13:54:23 "GET http://127.0.0.2:5758/img/coins/bch.png …
```
> site: do not get icon repeatedly

- client/asset/dcr/coin_selection.go
The txFee was being incorrectly subtracted from the excess value when `subtract == true`. This does not need to be subtracted from the `excess`, as it is subtracted from the actual value being sent.
> client/dcr: Incorrect excess return from sendEnough

- client/webserver/site/src/css/market.scss
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/markets.ts
Cursor was set to pointer for the entire table, but only the headers are interactive. 
Sort direction showed oldest first. Changed to newest first.
> ui: fix sort direction and cursor on recent matches table

- client/asset/dcr/coin_selection.go
- client/asset/dcr/coin_selection_test.go
This updates the algorithm used to find the UTXOs with the least over fund. It does 1000 random selections of UTXOs, and picks the most optimal one.
Inspired by this:
https://github.com/bitcoin/bitcoin/blob/3015e0bca6bc2cb8beb747873fdf7b80e74d679f/src/wallet.cpp#L1129
> client/dcr: Improved UTXO selection algorithm

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/order.tmpl
- client/webserver/site/src/js/order.ts
This is part 1 for addressing https://github.com/decred/dcrdex/issues/2175, it resolves regression with `Funding Coins` being clickable previously https://github.com/decred/dcrdex/issues/2175#issuecomment-1446343544 but no longer on the current **master**.
Seems like regression originates here: https://github.com/buck54321/dcrdex/commit/b9aaef2c280e2cb4ca1c4dbca99ac7b1fa939aee
Tested `Acceleration Coins` links too, seem to be working for BTC on **testnet**.
> ui: funding/acceleration coins missing links regression

- client/core/core.go
The wallet balance was not being updated after funding an order, causing the available balance to be too high and locked balance to be too low.
> core: Update wallet balance after funding order

- client/core/core.go
- client/core/trade.go
> client/core: bad log msg formatting

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
Resolves https://github.com/decred/dcrdex/issues/2045
Turns out the timeouts there before shutdown were (wait for it)... DNS.  The only actual issue there was that shutting down when `eth.checkForNewBlocks` was timing out would involve a random chance of receiving from the canceled context instead of the ticker.
This change checks for a shutdown that may have occurred while `eth.checkForNewBlocks` timed out.  I've decided to keep the ticker because with health providers, it is desirable to keep a regular check interval in terms of wall time rather than relative to the previous check.  Tickers don't backup indefinitely, but they will buffer a single tick, so a single tick may be delayed when there is a timeout.
> client/asset/eth: break immediately on shutdown when timing out

- client/asset/btc/spv.go
There are now plenty of public full **Bitcoin** nodes supporting compact block filters.  This default peer was added when the node landscape was quite different.  In addition, it's generally overloaded and constantly at it's max incoming peer limit.  Further, with the peer manager you can always add it back manually, but you cannot remove it when it's a "Default" peer.
> client/asset/btc: remove mainnet cfilters btc spv node default

- dex/testing/dcrdex/harness.sh
- server/asset/eth/eth.go
- server/asset/eth/rpcclient.go
- server/asset/eth/rpcclient_harness_test.go
This change allows server operators to rank RPC entpoints by priority. The healthy connection with the highest priority will always be attempted first. If no priority is specified for an endpoint, 0 is assumed.
Closes #2161
> server/eth: RPC client priority

- run_tests.sh
Looks like this build step is no longer needed/relevant ? If it does serve some implicit purpose I'm not aware of, I'd like to document it with a comment here instead.
> remove unnecessary build step

- client/db/bolt/db.go
Pretty much a nit, but could help a not-very-technical user administering `dexc`, because currently when I have 1 instance running, starting another gives me this error:
```
error creating client core: database initialization error: timeout
```
it becomes this instead:
```
error creating client core: database initialization error: timeout, could happen when database is already being used by another process
```
> client/db clarify DB timeout error

- server/dex/dex.go
Server was logging config about reg fee instead of bonds.
> server: Log bond info instead of reg fee

- client/core/core.go
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/wallets.ts
> client/core,app: Fix rate/volume decimal precision

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/markets.ts
Similar to https://github.com/decred/dcrdex/pull/2163, but for the `updateWallet` method of the markets page.
> app: conditionally set logo img src (markets page)

- client/asset/dcr/spv.go
- client/asset/dcr/spv_test.go
This fixes `(*spvWallet).GetBlockHeader` so that it correctly considers the main chain status of the block when computing confirmations and retrieving `NextHash`.
The new function matches the behavior of dcrd and dcrwallet's getblockheader handlers.
> client/asset/dcr: spv block header confs is -1 for orphan

- client/asset/btc/btc.go
- client/asset/btc/rpcclient.go
- client/asset/btc/spv_test.go
- client/asset/btc/spv_wrapper.go
- client/asset/btc/wallet.go
This PR targeting BTC SPV wallet being able to spot reorgs, as per https://github.com/decred/dcrdex/pull/2219#pullrequestreview-1340616893 (functionally mirroring https://github.com/decred/dcrdex/pull/2219).
While it is possible to just fix the issue and move on I think some [code clean up is warranted here](https://github.com/decred/dcrdex/pull/2227).
> client/asset/btc: fix SPV reorg handling

- dex/testing/loadbot/go.mod
- dex/testing/loadbot/go.sum
- go.mod
- go.sum
`go: upgraded decred.org/dcrwallet/v2 v2.0.10 => v2.0.11`
Almost missed this update after https://github.com/decred/dcrwallet/pull/2210 was merged, but we should release with this patch.
> deps: update dcrwallet for data race fix in peering

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
This adds a 20% buffer to the send tx fee estimate in order to not return an error from the send function when the base fee rises between the time the estimate is done and the ETH is sent.
Closes #2186
> client/eth: Add send tx fee estimate buffer

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
Resolves #2243
Since tips are cached for 10 seconds, this adds a secondary method of recognizing a new state that requires confirmation checks on pending txs.
> client/eth: balance change trigger pending txs recheck

- client/core/core.go
I think we should not send notes for the first disconnect. follow up for #2028
EDIT: Changes in the PR are suggestions offered by @buck54321. This will allow resetting a connection's total anomaly count when the time since the `lastConnect` is > `wsAnomalyDuration`.
> nit: don't send connection anomaly notification for first disconnect

- server/asset/btc/btc.go
- server/asset/btc/btc_test.go
- server/asset/common.go
- server/asset/dcr/dcr.go
- server/asset/dcr/dcr_test.go
- server/asset/eth/eth.go
- server/market/orderrouter.go
- server/market/routers_test.go
- server/swap/swap_test.go
The trade address provided with an order is checked for validity, but it also must be checked that it is the proper type for inclusion in a swap contract.  This renames `server.asset.CheckAddress` to `CheckSwapAddress`, and updates it with the same type checks used client-side in `dex/networks/{dcr,btc}.MakeContract` as well as in `ExtractSwapDetails`.
> server/asset: trade address validation consistency

- client/asset/btc/btc.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/forms.ts
Resolves https://github.com/decred/dcrdex/issues/2192
When using a `<input type='date'>` element, it is tricky to get the time zone correct when using the `value`, `valueAsNumber`, and `valueAsDate` fields.  This is because the browser will always display the date as UTC, regardless of how you have set `valueAsDate`.  Also, when getting the date out with `new Date(input.value)`, where the value is `yyyy-mm-dd`, the `Date` parses as in UTC (12am UTC instead of local).
When the user is interacting with the input element, they are thinking in local time.  However, unless we offset the time that we set, it can show an incorrect date.  This change sets the `value` date string manually to the local date. We could also offset the `Date` that we assign to `valueAsDate` so that it will show a …
> app: fix wallet birthday is UTC date

- client/asset/eth/multirpc.go
I was fiddling with Arbitrum L2, Ethereum wallet does seem to work with it nicely (with minor adjustments it syncs with arbitrum Provider, and I was able to transfer some Arb ETH/USDC to/from it without any obvious issues!),
but I run into a nasty panic that crashes **dexc** when I'm adding arbitrum Provider (it could be Ethereum provider, the importaint thing here is to trigger "HTTP fallback"):
```
2023-03-24 12:30:38.873 [ERR] CORE[eth][RPC]: Connected to websocket, but headers subscription not supported. Attempting HTTP fallback
2023-03-24 12:30:39.330 [DBG] CORE[eth][RPC]: Connected with 1 of 1 RPC servers
2023-03-24 12:30:39.330 [TRC] CORE[eth][RPC]: handling header refreshes for "arbitrum-one.public.blastapi.io"
2023-03-24 12:30:39.330 [TRC] CORE[eth][RPC]: handling websocket …
```
> client/eth/rpc: fix HTTP provider panic

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/markets.ts
Resolves https://github.com/decred/dcrdex/issues/1139
If you load the markets page while there is a cancel order in the epoch, you see a zero-quantity market buy.
This change prevents cancels from being added to the order table.
> ui: do not add cancel orders to table as market order

- client/webserver/site/src/js/wallets.ts
When transaction fee is comparable to amount left in user wallet we might get into negative territory calculating max send value.
[send-negative-amt-ui.webm](https://user-images.githubusercontent.com/112318969/227706401-7bdb39db-46ef-4b50-b8df-9366643f31be.webm)
> ui: prevent negative amt on send form

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/markets.ts
This reverts commit 821e1768ca6a109700946e0c8ccc1710d58d358a.
The `BalanceWidgets` are reused, and we have to update the logo path, particularly when just changing between markets.
Whoops.  This goes back to always setting the log `src` attribute.  We could get fancy to only do it when called from `setWallet` (rather than every balance note as when called from `updateAsset` in response to balance or wallet state notes), but let's just make sure this works right for the release.
> Revert "app: conditionally set logo img src"

- client/asset/btc/btc.go
"legacy" balance needed to construct the `asset.Balance` with an initialized `Other` map too.  We missed this because BTC uses the new `getbalances`.
```
panic({0x18d7a20, 0x25835b0})
/home/jon/go120/src/runtime/panic.go:884 +0x213
decred.org/dcrdex/client/asset/btc.(*baseWallet).Balance(0xc0003ec680)
/home/jon/github/decred/dcrdex/client/asset/btc/btc.go:1504 +0x197
decred.org/dcrdex/client/core.(*Core).walletBalance(0xc0001e2000?, 0xc0012a2240)
/home/jon/github/decred/dcrdex/client/core/core.go:2054 +0x32
decred.org/dcrdex/client/core.(*Core).createWalletOrToken(0xc0001e2000, {0x25900d0, 0xc000134140}, {0xc000b4208a, 0x3, 0x3}, 0xc0019f0030)
/home/jon/github/decred/dcrdex/client/core/core.go:2497 +0x4d1
decred.org/dcrdex/client/core.(*Core).CreateWallet(0xc0001e2000, {0xc00130c020, 0x1, …
```
> client/asset/btc: init asset.Balance.Other in legacyBalance

- client/asset/eth/eth.go
- client/core/core.go
- client/webserver/site/src/js/forms.ts
I'm reaching into "unknown" area here a bit, hope this doesn't rub you in wrong way (don't want to step on someone's toes if it's already being worked on, still, I would like to figure out how it works for myself anyway).
Currently **Token** wallet displays its `Wallet Type` as empty. This is either unnecessary to see for the user, or it could be a bug (and this PR treats it this way),
before / after:
Also tested that ETH/USDC wallet creation isn't broken with this change, however affected code is a bit hairy and I might have missed something.
> ui: token wallet is missing type

- client/webserver/webserver.go
Minimal fix for release-v0.6.
Pertaining to https://github.com/decred/dcrdex/pull/2283, this just filters out IPv6 addresses from injection into the csp part of the http response header.
Even though all IPv4 except 127.0.0.1 _does not match_ (we must rely on `'self'` working correctly for these), they do not make the CSP entry invalid, so we are continuing to insert those so we do not create a change of behavior.
On master we may actually remove this `content-src` injection since the browser bug was fixed about a year ago.  On master, we should also update the backend log line that prints out the URL so that it doesn't include the wildcard address since that's no good for a browser address.
All this PR does is to avoid adding IPv6 addresses, since those actually make the CSP **invalid**. …
> [0.6] client/webserver: keep IPv6 out of csp header

- client/asset/eth/multirpc.go
- client/asset/eth/nodeclient.go
I think I observed this overflow recently on match card, consider additional protection when `uints` are used.
> client/asset/eth: avoid confirmations overflow

- client/webserver/site/src/js/markets.ts
`mkt.spot` might not be initialized when we are setting up left Market doc - we leave **Price**/**Change** values set at `-`. This is probably fine as long as these will be updated in the future, but they don't always update due to (looks like) a typo this PR fixes.
> ui: price/change header/row discrepancy

- docs/wiki/Ethereum.md
This adds a "Wallet Recovery" section to the Ethereum page.  I am mainly using this as a chance to sternly warn against using the wallet from multiple wallet programs simultaneously.  I am intentionally not showing screens or describing how to get the backup private key.
This also removes ArchiveNode from the RPC provider list since they have announced that [they are shutting down](https://defidude.medium.com/sunsetting-archivenode-io-c72a78fe3653).
> wiki: add eth recovery section and remove archivenode

- client/asset/eth/eth_test.go
- client/asset/eth/multirpc.go
closes #2271
This mostly uses the logic from `addrHost` in core but also works for files.
> client/eth: Fix domain.

- client/webserver/locales/en-us.go
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/locales.ts
- client/webserver/site/src/js/wallets.ts
Closes # 2241
UI changes:
> @norwnd (#2241): As a sidenote, I'm not even sure why this connect button is there in the first place , wouldn't it be better to try re-connect wallet automatically every 30s or something?
This part is not handled in this PR. @chappjc, what do you think?
IMO, using a reconnect loop for wallet connection when are not sure that we will ever connect seems to be undesirable. Wallet connection will be attempted in any part of the client code that requires a connected wallet, plus, like the note above, If a user is missing wallet files, we are going to try forever until they take action.
> site: Notify users when connecting wallets fail

- client/asset/eth/multirpc.go
- client/webserver/webserver.go
- client/webserver/webserver_test.go
- This fixes an issue where using the IPv6Unspecified address `[::]` for csp connect-src directive could cause issues resulting in some icons not loading properly.
- Add missing log arg.
Closes #1652 
@norwnd, please can you confirm that this PR fixes the issue on your end?
> Use zero IPv4 loopback address instead of IPv6 unspecified address for CSP connect-src directive

- server/swap/swap.go
- server/swap/swap_test.go
Resolves https://github.com/decred/dcrdex/issues/2228.
The reason for this occasional failure (best I can tell) is server responding with an `error` to client **before** server is ready (has released corresponding atomic var) to accept next request attempt.
The simple, robust way to resolve it would be to respond with `error` to clients only **after** server is ready to handle those follow-up requests (there are quite a bit of those in tests, we could potentially just retry there but it is messy and unnecessary imo).
> server: TestMalformedSwap fails occasionally

- client/asset/eth/multirpc.go
- client/asset/eth/multirpc_live_test.go
This adds `(*multiRPCClient).withAll`, which is used by `sendSignedTransaction` to broadcast a transaction to all providers, preferred first.
> client/asset/eth: broadcast to all providers

- client/core/account.go
- client/core/bond.go
- client/core/core.go
- client/core/core_test.go
This resolves:
>	TODO: split the above code into a dexConnection constructor, and the below into
>      a startDexConnection function so we don't have the anti-pattern of
>	returning a non-nil object with a non-nil error and requiring the caller
>	to check both!
> core: remove anti-pattern in `core.connectDEX`

- client/webserver/webserver.go
#2283 was supposed to use `addr` and not `s.addr` which is passed to the CSP.
> bug fix: use prepared webserver adress in csp

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/markets.ts
This diff uses the JS optional chaining feature to prevent errors caused by attempting to access a null field. If a user losses internet connection and regains it, some js errors will be logged when notes try to access the `dex` or `market` field on `MarketPage` before those fields are initialized. But the changes here are not limited to only note handlers since it is cleaner and less code to use optional chaining to prevent runtime errors.
> site: Check for uninitialized market in certain note handlers

- .github/workflows/release-docker.yml
- Trigger docker build workflow on release published (instead of `created` which does not trigger reliably when creating releases via the GH web interface)
- Allow the manual triggering of the build
> Github docker build workflow adjustments

- server/market/market.go
When an account-based asset is the quote asset in a market, and there is a booked buy order, the quantity to check must be in units of the quote asset (the account-based asset).
Test/repro: On the simnet harness fund your wallet with something like `0.39` ETH.  On the DCR-ETH market, book a **buy** order at 0.01 ETH/DCR for 1 lot, which should say "Total: 0.10 ETH".
Stop the server process and start again with `./run`.  It would unbook the order because it was comparing the base asset (10 DCR or 1000000000 atoms) with the eth balance of 0.039 ETH (390000000 gwei).
With this change, it will compare quote units (plus fees) against balance.
> server/market: startup balance checks must convert base to quote

- pkg.sh
For the Windows system tray build, this adds the missing build tags and ldflags, and it targets the "dexc-tray.exe" file name.
While here add back in the `-buildid=` hack that is needed for reproducible builds.
Also set `GOWORK=off`
> pkg: fix systray build

- client/orderbook/orderbook.go
- dex/msgjson/types.go
- server/market/bookrouter.go
Server orderbook is updated to cache the 100 most recent matches in memory, and they are returned whenever a client syncs the orderbook.
Closes #2296
> multi: Send recent matches in orderbook sync

- client/core/bond.go
- client/core/bookie.go
- client/core/core.go
- client/core/core_test.go
- client/core/types.go
- dex/msgjson/types.go
- dex/testing/dcrdex/harness.sh
- server/cmd/dcrdex/config.go
- server/cmd/dcrdex/main.go
- server/dex/dex.go
The first commit removes the server's startup requirement of having DCR reg fee info specified.  This was a hold-over from before we even had multi-asset reg fee support.  There is still the RegFees map (which may also be empty in a bonds-only config).
The second commit removes the warning about a server that does not support DCR for registration. This also removes the handling of ancient servers that even lacked the RegFees map (only had the dcr-specific fields).
> multi: allow no dcr reg fee config on server, remove dcr-specific fields

- dex/networks/ltc/tx.go
ltcsuite is adopting our MW tx deserialization code, and it [revealed](https://github.com/ltcsuite/ltcd/issues/17#issuecomment-1507856230) a small usability issue with the `decoder` API, which this fixes.
This also updates the `maxWitnessItemsPerInput` and `maxWitnessItemSize` to match the current values following the btcsuite backports in https://github.com/ltcsuite/ltcd/pull/25
> dex/networks/ltc: witness limits fixes and decoder simplifications

- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/markets.ts
Resolves https://github.com/decred/dcrdex/issues/2254.
Rate fits reasonably well with the longest `canceled/settling` status and max rate step we currently have = 6
> ui: display your orders rate in header

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/markets.ts
Given `<div data-tmpl="bal">48<img src="/img/coins/eth.png" class="micro-icon"></div>`, if we do `balTmpl.textContent = "48"` that nukes the child `img` class.  To only update the text and persist the `img` child node set before, we have to target only the text node via `balTmpl.firstChild`.
> site: persist fee asset icon on markets page

- server/asset/eth/rpcclient.go
This makes the `endpoint` type a `fmt.Stringer` so it can be used as expected in printf-like statements (`endpoint` used to just be a `string`).  Without this change, it prints like this:
```
[WRN] ASSET[eth][RPC]: Error checking required modules at {"wss://eth-mainnet.nodereal.io/ws/v1/asdf" 'ɘ'}: needed apis not present:  txpool.
```
> server/asset/eth: make endpoint a Stringer

- client/webserver/site/src/css/market_dark.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/markets.ts
This corrects the `side-indicator`'s sell color.  It was correct on the light theme.
This also prevents both `buy` and `sell` classes on the `sideLight` div.  Both issues can be seen:
`.side-indicator.sell` used the buy color.  And the `sideLight` div had both `buy sell` classes.
The second issue addressed in this PR is the "active" indicator light not being shown for orders with settling matches.
Both issues visible here:
> site: correct order buy/sell colors

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/btc/electrum.go
- client/asset/btc/livetest/livetest.go
- client/asset/dcr/dcr.go
- client/asset/eth/eth.go
- client/asset/interface.go
- client/asset/zec/zec.go
- client/core/core.go
- client/core/wallet.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/mm.ts
- client/webserver/site/src/js/registry.ts
This resolves an existing TODO:
>   TODO: Use an asset.Authenticator interface and WalletTraits to do this instead.
- Implements an `asset.Authenticator` for wallets that require auth.
- Added a `btc.ExchangeWalletAuthenticator` the implements the `asset.Authenticator` interface.
>  multi: implement asset.Authtenticator for assets that require authentication

- client/webserver/site/package.json
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/charts.ts
- client/webserver/site/src/js/doc.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/mm.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/wallets.ts
As a follow-up to https://github.com/decred/dcrdex/issues/2174 we still have some rates in order book (& depth/candle charts) with trailing zeros:
in this PR I'm basically truncating those leading 0s, which works because those rates are already complying with their respective rate steps, so it looks more like this:
> ui: consistent rate formatting

- client/core/bond.go
The time-to-bond-refund logging is really spammy on mainnet.  For roughly 4 weeks you see a countdown logged every 20 seconds.  This throttles that logging so it only happens once every 30 minutes, until the refund is just 15 minutes away.  The 15 minute threshold is partly for sim/testnet so we can see more feedback in testing, but also so a mainnet user sees the countdown as the time gets closer.
> client/core: don't spam bond refund countdown

- client/asset/interface.go
- client/asset/zec/zec.go
- client/core/core.go
- client/core/locale_ntfn.go
- client/core/notification.go
- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/webserver.go
- client/webserver/webserver_test.go
Just copied the `ShieldedWallet` interface from #2250.
> client/core: add core methods and webserver endpoints for shielded wallets

- client/asset/interface.go
- client/asset/zec/regnet_test.go
- client/asset/zec/shielded_rpc.go
- client/asset/zec/shielded_test.go
- client/asset/zec/zec.go
- run_tests.sh
Add methods for working with shielded pools. Only the client/asset parts are implemented. **client/core** and UI will follow in separate efforts. As such, this API may change.
> client/asset: add methods for ZCash shielded pools

- client/asset/btc/btc.go
> assets: ensure context cancellation take precedence over ticker during new block update

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/js/forms.ts
Closes #2328.
Zec wallet does not require a password and uses the `NoAuth` boolean field in its wallet def. But we seem to add that as criteria to display the single `Create` btn that is used only by seeded/token wallets that do not have required config opts.
The `walletDef.noauth` field is already properly handled by the last else statement in the block of code near code change.
> webserver/site: fix handling of NoAuth wallets

- client/asset/zec/zec.go
- dex/networks/zec/params.go
- server/asset/zec/zec.go
Counterpart of #2336 for release-v0.6 branch. We don't have a `zecWallet` type yet, so I'm not adding the `FeeRate` to the zec wallet yet, but setting the `FeeEstimator` is effectively the same thing.
> zec: implement FeeRate to short-circuit fee checks - release-v0.6

- client/asset/btc/btc.go
- client/asset/btc/rpcclient.go
- client/core/core.go
- client/core/core_test.go
- dex/networks/bch/params_test.go
- dex/networks/btc/test/compat.go
- dex/networks/dgb/params.go
- dex/networks/doge/params.go
- dex/networks/zec/params.go
- dex/networks/zec/params_test.go
A few issues related to BTC/clone RPC connection and reconfiguration popped out:
- Running dexc on simnet, you can create a wallet that connects to bitciond/clone on mainnet (or reverse)
- You cannot switch to the correct one because if errors trying to validate the previous deposit address from the other network
- "Clone" asset always return `restartRequired = true` when attempting to reconfigure because a condition for live-reconfigurability compares the new wallet type against `"bitcoindRPC"` when clones have strings like `"dogecoindRPC"`.
- Reconfiguring a disconnected wallet could fail in certain circumstances because the context could already be canceled, blocking some of the reconfigure checks that involve an RPC with the new client.
> client/asset/btc: RPC connect and reconfig fixes

- server/asset/btc/btc.go
https://github.com/decred/dcrdex/commit/12147ba908e9c17dcf3cce7e23231796afb0b428 but for BTC
1 second polling is too fast for remote nodes.
This variable affects all btc clone assets.
> server/asset/btc: compile time configurable poll interval

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
> client/btc: Use coin specific tx hashes.

- client/db/types.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/order.tmpl
- client/webserver/site/src/js/locales.ts
- client/webserver/site/src/js/order.ts
Resolves https://github.com/decred/dcrdex/issues/1947.
With changes in this PR (note, these screenshots were indeed made in November 2022, just waited for https://github.com/decred/dcrdex/pull/1978 to go in first; I didn't re-test it myself after rebase, but you'll probably be doing your own testing and I'm optimistic that it still works fine):
> ui: add expected refund time to match-card

- .github/workflows/build.yml
- client/webserver/site/package.json
As of 2023-04-18, Node.js 18 and 20 are now the "active/current" LTC releases.  v16 will be EOL on 2023-09-11.
As a reminder, Node.js has an "even number" LTC release convention, similar to Ubuntu.
https://nodejs.dev/en/about/releases/ (the image is updated but not the table).
> ci: node v18/v20 in actions

- client/cmd/dexc-desktop/main.go
I noticed dexc-desktop was missing firo.
> dexc-desktop: Register firo for dexc-desktop

- client/app/config.go
- client/cmd/dexc-desktop/main.go
- client/cmd/dexc/main.go
- client/webserver/api.go
- client/webserver/middleware.go
- client/webserver/webserver.go
**client/webserver: more judicious use of authMiddleware**
```
The authMiddleware calls (*Core).User and injects the struct into the
request.  This is primarily needed for html template execution in the
web page handlers.  It is not required for any of the other redirection
middleware or the api endpoints.  And it is definitely not required
for fileServer (img/css/js resources).
This change restricts the user of authMiddleware to the web page
sub-router.  Almost every page requires it, using the commonArgs
helper to prepare the data for template rendering.
This modifies the redirection middlewares (requireInit, requireLogin,
rejectUnauthed, requireDEXConnection, etc). to only use the Core
methods that are actually required, if any.
Finally, this modifies the two api handlers that required …
```
> client/webserver: more judicious use of authMiddleware

- client/cmd/dexc-desktop/main.go
- dex/networks/eth/tokens.go
This diff resolves two non-critical bugs:
- Registered assets were not filtered in the `dexc-desktop` pkg
- `getContractAddrFromFile` did not return early if no address was found.
> dexc-desktop: Filter registered assets for those available on the specified network

- client/asset/bch/bch.go
- client/asset/btc/btc.go
- client/asset/btc/electrum.go
> asset: Implement `asset.FeeRater` for SPV wallets and minor refactor

- client/core/core.go
- client/core/types.go
- client/webserver/http.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/html/order.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/order.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/wallets.ts
Noticed while looking over #2349 that we were passing the network via a data attribute for a few pages, requiring some custom page templates structs that are otherwise unneeded. It's cleaner to report it in the `core.User` instead.
> add network field to core.User

- client/asset/btc/electrum/wallet_methods.go
Some Electrum wallets do not have a Replace by Fee parameter for the `payto` RPC. Make sending optional.
Based on discussion [here](https://github.com/decred/dcrdex/issues/2359)
> electrum/wallet: Make sending RBF for payto RPC optional

- README.md
I created an Arch User Repository (AUR) package for the dcrdex client here: https://aur.archlinux.org/packages/dcrdex ([PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dcrdex))
If you run Arch or a derivative, you can install that with one of the AUR helpers like `yay` or `pamac`.
This PR calls out our current push for packaging as described in https://proposals.decred.org/record/ae7c4fe, and it starts a list of the OS packages.
> docs: Arch Linux package and OS packaging README update

- dex/networks/dgb/params.go
- dex/networks/doge/params.go
Regtest net ids are the same for Digibyte & Doge. They use the old btc one unchanged
> dex/networks: dgb & doge have duplicate netid

- client/asset/btc/btc.go
- client/asset/dcr/dcr.go
- client/asset/interface.go
- client/asset/zec/shielded_test.go
- client/asset/zec/zec.go
- client/mm/price_oracle_test.go
- client/webserver/site/src/css/main.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/locales.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/wallets.ts
Closes #2177
UI changes:
Edit: IMO, reducing the tooltip width and adding border-radius makes the tooltip look slick.
> multi: Add wallet balance tooltip and all known wallet balances to translation map

- client/asset/bch/bch.go
- client/asset/btc/btc.go
- client/asset/btc/electrum.go
Backport of https://github.com/decred/dcrdex/pull/2356 to v0.6.2
This is so the native SPV wallets are `FeeRaters`, providing a live estimate from any enabled external source.
> [0.6.2] asset: Implement asset.FeeRater for SPV wallets and minor refactor

- run_tests.sh
My workspace has a .golangci.json file (not .golangci.yml) that golangci-lint seems to prefer.  I use this to configure my IDE, where I use more strict linters, which I can ignore.  When I ran run_tests.sh, it used the default linters instead of the ones in the new .golangci.yml file.  This fixes the issue by having run_tests.sh do `golangci-lint -c ./.golangci.yml run`.
Here's my .golangci.json file for reference.  I use this because I like the revive linter in my IDE, but we don't want it in CI.  Also I occasionally turn on the shadowing checks for go vet, but most of the time it makes too much noise about shadowed `err` variables.
```json
{
"linters-settings": {
"govet": {
"check-shadowing": false
},
"revive": {
"enableAllRules": true,
"rules": [
{
"name": "var-naming",
"disabled": …
```
> CI: specify golangci config file

- client/webserver/webserver.go
Absolutely minimal version of https://github.com/decred/dcrdex/pull/2350
This just stops calling `(*Core).User` in the file server.  The effect is that static asset retrieval is on the order of microseconds instead of milliseconds.
This version does not change any of the middleware used in either the web or api routers.
> [0.6.2] client/webserver: avoid authMiddleware for file server

- client/asset/btc/btc.go
- client/asset/dcr/dcr.go
- client/asset/interface.go
- client/core/bond.go
- client/core/core.go
- client/core/types.go
- client/core/wallet.go
- client/webserver/api.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/register.ts
- client/webserver/webserver.go
```
When used for computing the bond fee buffer, the "fee rate limit" makes
an extremely high fee rate buffer, which makes BTC bonds impractical.
This change:
- switches to using a dynamic fee rate with the configured fallback rate
for both ReserveBondFunds and BondsFeeBuffer, where the former is
used as the requirement for the frontend to proceed with registration
- uses the exported BondsFeeBuffer method when automatically creating
the "extra" split output in certain order funding edge cases instead
of a buffer based on the high limit.
- tweaks the bond tx input count to be slightly less conservative, going
from 12 -> 8 possible inputs
The motivation for these changes is that using the wallet's configured
fee rate limit creates extremely high fee buffers, whereas we have
defined the …
```
> btc: more sensible bond fee buffer

- client/webserver/locales/en-us.go
- client/webserver/site/src/css/forms.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/js/register.ts
- client/webserver/site/src/js/settings.ts
Based on feedback from the community and other users new to Decred, this tweaks some of the bond messaging during registration:
- "How will you post bond?" ==> "How will you create your bond?" on the form where you choose the bond asset
- Includes the `whatsabond` info text on the same form, just below the previous question/title
> site: bond asset choice wording tweaks

- .github/workflows/build.yml
- run_tests.sh
Copying https://github.com/decred/dcrd/pull/3145, this caches the go module build output folder and build cache.
> CI: use cache github action for Go mod and test

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/btc/coin_selection.go
- client/asset/btc/coin_selection_test.go
- client/asset/btc/livetest/livetest.go
- client/asset/btc/spv_test.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/simnet_test.go
- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/interface.go
- client/cmd/dexcctl/main.go
- client/core/core.go
- client/core/core_test.go
- client/core/types.go
- client/db/bolt/db.go
- client/db/types.go
- client/rpcserver/handlers.go
- client/rpcserver/rpcserver.go
- client/rpcserver/rpcserver_test.go
- client/rpcserver/types.go
This adds a `core.MultiTrade` function. It allows callers to fund multiple trades in one go. It is only implemented for BTC currently, but will be implemented for other assets later, after this is reviewed. In order to fund multiple orders in one go, the BTC wallet first attempts to fund each of the orders with the existing UTXOs. If this was not possible and splitting is not allowed, the orders that are able to be funded are returned. If splitting is allowed, a split transaction with one output per order will be created.
This also updates `FundOrder` to return the fees spent on any split transactions, and this is stored in the database.
> client/{core, btc}: MultiTrade

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/btc/electrum_client.go
- client/asset/btc/rpcclient.go
- client/asset/btc/spv_test.go
- client/asset/btc/spv_wrapper.go
- client/asset/btc/wallet.go
- client/asset/interface.go
- client/core/core_test.go
- client/core/trade.go
- client/db/types.go
Concerns about overshooting the gap policy have come up. This enables a file-backed recycled address cache for unused redemption and refund addresses.
> client/asset/btc: recycle unused redemption and refund addresses

- client/core/core_test.go
- client/core/trade.go
In certain cases, the redeem confirmation status was skipping the retries of the `'redeem'` request.  This was happening because `confirmRedemption` would advance the status to confirmed regardless of whether there was a stored `RedeemSig`, which indicates that the redeem request was accepted by the server.
This fixes the issue by <s>adding the `RedeemSig` check to `shouldConfirmRedemption`, which allows `resendPendingRequests` when they are needed.</s> only advancing to `MatchConfirmed` if both (a) match is confirmed, and (b) server has received and ack'd our `redeem` request, which is necessary to complete our role in the swap dance.
> client/core: ensure redeem is accepted before confirm/complete match

- docs/release-notes/release-notes-0.6.2.md
This checks in the release notes for [v0.6.2](https://github.com/decred/dcrdex/releases/tag/v0.6.2)
> docs: add release notes for v0.6.2

- client/cmd/dexcctl/simnet-setup.sh
- client/core/core.go
- client/rpcserver/handlers.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/css/market.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/markets.ts
If target bond tier is more than zero but bonds have not been sent yet, inform the user of the state rather than incorrect message that they must change their bond settings.
Also updating the simnet setup script to use bonds and attempting to fix a couple bugs.
closes #2408
> client/UI: Add pending bond message.

- client/core/core.go
- client/webserver/api.go
- client/webserver/http.go
- client/webserver/live_test.go
- client/webserver/locales/en-us.go
- client/webserver/middleware.go
- client/webserver/site/src/css/forms.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/init.tmpl
- client/webserver/site/src/html/register.tmpl
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/charts.ts
- client/webserver/site/src/js/init.ts
- client/webserver/site/src/js/locales.ts
- client/webserver/site/src/js/login.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/register.ts
- client/webserver/webserver.go
- client/webserver/webserver_test.go
This reworks app initialization to achieve a number of ux goals.
1) Adds chance for user to quickly configure native wallets and add
known servers (view-only), https://github.com/decred/dcrdex/pull/1986#discussion_r1061747565
2) Adds seed backup dialog
3) Makes the Wallets view the landing page
> ui: rework app initialization

- client/asset/btc/coin_selection.go
- client/asset/btc/coin_selection_test.go
Logic was incorrect. This is not critical as it only affects MultiTrade, which is not yet in use.
> client/btc: Fix bug in leastOverFundWithLimit

- client/core/core_test.go
- client/core/trade.go
- server/auth/auth.go
This backports two important bug fixes for the 0.6 release branch:
- https://github.com/decred/dcrdex/pull/2405 To prevent users being penalized for not reporting their redeems.
- https://github.com/decred/dcrdex/pull/2411 So positive tier users always have a positive order limit, big enough for at least a single lot.
> [0.6] backport two fixes for release branch

- client/cmd/dexc-desktop/app.go
- client/cmd/dexc-desktop/app_darwin.go
- client/cmd/dexc-desktop/config.go
- client/cmd/dexc-desktop/go.mod
- client/cmd/dexc-desktop/go.sum
- client/cmd/dexc-desktop/main.go
- client/cmd/dexc-desktop/pkg/pkg-darwin.sh
- client/cmd/dexc-desktop/syncserver.go
Builds on #2333.
I researched other options and [MacDrive](https://github.com/progrium/macdriver) seem to be a reasonable option. It allows using supported native Mac APIs, which covers our use case.
I was able to implement some "native" macOS app behaviour and features; keeping the app running without windows, creating new windows, and having a dock icon menu.
I'm putting this up so we can have discussions around it and clarify what feature is missing (menu items etc)
EDIT: If we want to keep the New Window menu as @martonp mentioned here https://github.com/decred/dcrdex/pull/2333#issuecomment-1562681245, we'd have to allow more than one window on macOS.
> dexc-desktop: Use macdrive for Darwin

- client/webserver/site/package-lock.json
GitHub's dependabot is reporting the following security issues:
https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
https://github.com/advisories/GHSA-j8xg-fqg3-53r7
Indeed, `npm audit` confirms:
```
semver  <=5.7.1 || 6.0.0 - 6.3.0 || 7.0.0 - 7.5.1
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix`
node_modules/@typescript-eslint/eslint-plugin/node_modules/semver
node_modules/@typescript-eslint/typescript-estree/node_modules/semver …
```
> site: npm audit fix

- dex/testing/dgb/harness.sh
- dex/testing/doge/harness.sh
- switch on mining for DGB
- add mining for DOGE
set/export NOMINER="1" to disable
DGB documented to have issues after mining ~100 blocks. Selectively disable as needed.
> doge: enable background mining in harness

- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/markets.ts
> site: Fix order marker bug

- dex/testing/dcr/harness.sh
DCR watch mining is still on by default but now can be disabled by setting NOMINER to a non-empty string value.
> dex/testing: DCR watch mining can be disabled with NOMINER

- client/webserver/site/src/css/main_dark.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/init.tmpl
- client/webserver/site/src/html/settings.tmpl
- client/webserver/site/src/js/init.ts
- client/webserver/site/src/js/settings.ts
Format app seed in chunks of 8. Change seed input to a `<textarea>`. Remove input whitespace.
> ui: improve app seed display

- client/asset/dcr/dcr.go
- client/asset/dcr/rpcwallet.go
- client/asset/dcr/spv.go
- client/cmd/dexcctl/main.go
- client/core/core.go
- client/rpcserver/handlers.go
- client/rpcserver/handlers_test.go
- client/rpcserver/rpcserver.go
- client/rpcserver/rpcserver_test.go
- client/rpcserver/types.go
- client/rpcserver/types_test.go
- dex/msgjson/types.go
part of #2264
~depends on #2290~
Adds a rpc consumer for ticket purchasing.
> client/dcr: Add rpc staking.

- client/webserver/http.go
- client/webserver/locales/parse_test.go
- client/webserver/middleware.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/register.tmpl
- client/webserver/site/src/html/settings.tmpl
- client/webserver/site/src/js/app.ts
- client/webserver/webserver.go
We use almost none of the `*core.User` data that was embedded in the `webserver.CommonArguments`. In continuation of #2350, I've completely removed the `User` and made adjustments to template data where necessary.
> remove core.User from auth middleware user info

- client/webserver/live_test.go
- client/webserver/webserver.go
These are just some changes I think the webserver live test can use. I think it needs more improvement and could work on them little by little.
- Set "initErrors" to false to allow for error-free account creation.
- Initiate and use math/rand.Rand instead of deprecated math/rand.Seed.
- Set the Rate and MatchID feild for user order match.
- Use caser.Title instead of deprecated string.Title.
> webserver: fix live-test

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/eth/eth.go
- client/asset/interface.go
- client/core/core.go
- client/core/core_test.go
- client/core/types.go
- client/mm/mm.go
- client/mm/mm_basic.go
- client/mm/mm_basic_test.go
- client/mm/mm_test.go
- client/mm/price_oracle.go
- client/mm/sample-config.json
- client/mm/wrapped_core.go
This updates the basic market maker strategy to place multiple orders at various distances from the basis price instead of just one. It uses the new MultiTrade function to do this.
The basis price calculation is also updated to use fiat rates as a fallback if there are no trades on the dex or an oracle rate.
Something still missing from this is adjusting the rates based on how many previous buys/sells have been matched. There
needs to be a skew setting that places orders from the side with more previous matches farther from the basis price.
> client/mm: Update Basic Market Maker 

- client/asset/btc/btc.go
- client/asset/dcr/dcr.go
- client/asset/eth/eth.go
- client/asset/interface.go
- client/core/core.go
- client/core/core_test.go
- client/core/types.go
- client/mm/mm.go
- client/mm/mm_basic.go
- client/mm/mm_test.go
- client/mm/wrapped_core.go
The possibility of refunds was previously ignored in the market making balance handling code.
- `core.SingleLotFees` now returns refund fees in addition to swap and redeem. This is needed because ETH reserves refund fees when funding a swap, so the market maker `MaxSell`/`MaxBuy` implementations need to know about this.
- `asset.SingleLotSwapFees` is now `asset.SingleLotSwapRefundFees`
- `core.FeeBreakdown` now includes Refund fees.
- `PendingRefund` is removed from the `botBalance` struct. Matches are assumed to eventually be redeemed
until we actually see a refund.
- Revoked matches where a swap has not been sent are handled.
The Refund field of `core.FeeBreakdown` is not yet populated. This will be implemented in a future diff.
> client/multi: Consider refunds in market making

- client/asset/dash/dash.go
[Dash v19.2.0](https://github.com/dashpay/dash/releases/tag/v19.2.0)
Dash Core 19.2.0 is a **mandatory** minor version that does include breaking changes. You can find detailed release notes at <https://github.com/dashpay/dash/blob/v19.2.0/doc/release-notes.md>.
When upgrading from a version < 19.2, a migration process will occur. Although expected to complete quite quickly, this migration process can take up to thirty minutes to complete on some systems.
This release is **mandatory** for all nodes. Versions < 19.2 are expected to fork off from the rest of the network on July 6th.
> client/asset/dash: Update minNetworkVersion to v19.2.0.

- client/core/bond.go
If client has good standing with the server, it will not preemptively create a bond before its only bond expires. Always restore weak bonds if they are the last bonds to avoid going to zero. Reserve enough coin to restore live bonds rather than tracking the delta.
closes #2459
> client/bond.go: Avoid dropping tier.

- client/core/core.go
- client/core/types.go
- client/db/bolt/db.go
- client/db/types.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/css/market.scss
- client/webserver/site/src/css/market_dark.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/orders.ts
- client/webserver/site/src/js/orderutil.ts
- client/webserver/site/src/js/registry.ts
- dex/testing/dcr/harness.sh
- dex/testing/firo/test/electrumx_network_test.go
Allow sweeping of fully-executed orders from active orders list on markets view. Shows a broom icon in the button menu to sweep a single order, and near the header to sweep all retired orders.
Show (a copy of) the button menu on hover, allowing the user to perform actions without expanding the active order entry.
> ui: improve active order interactions

- client/core/helpers.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/orders.ts
- client/webserver/site/src/js/orderutil.ts
The rate display for market orders on the `orders`, `order` and 'market'(on the "user-order card") page, including the `Actual Rate` field when exporting a market order, will use the average order rate instead of just zero or `market`. Closes #1969.
> multi: use average rate for market order rate display

- server/asset/eth/eth.go
- server/asset/eth/eth_test.go
- server/asset/eth/rpcclient.go
- server/asset/eth/rpcclient_harness_test.go
We weren't using header subscriptions with WebSocket provider connections, so were polling every second by default. 
1) Add WebSocket header subscriptions to minimize requests.
1) Automatically increase the poll interval for HTTP connections if the IP is not a loopback address. Previously, the poll interval could be modified by setting the `blockPollIntervalStr` with `ldflags` at compile-time, but this is a little more user friendly, I think, and captures the intent just the same.
> server/eth: websocket header subscriptions and less frequent http polling

- dex/testing/firo/test/electrumx_network_test.go
Came out of the squash merge, apparently.
> dex/testing/firo: remove duplicate build tag

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/btc/electrum.go
- client/asset/btc/electrum_test.go
- client/asset/btc/livetest/livetest.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/simnet_test.go
- client/asset/dcr/spv_test.go
- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/interface.go
- client/asset/zec/shielded_test.go
- client/core/core.go
- client/core/core_test.go
- client/core/notification.go
Gives wallets a way to issue asynchronous notifications. Replaces the `TipChange` function. These notifications are sent to the front end, but are not used yet. This will help solve some issues that were raised in #2482, but it's also just a better pattern than the tip change function and should enable more up-to-date information on the front end.
> client/{asset,core}: wallet notifications

- client/asset/interface.go
- client/core/core.go
- client/core/wallet.go
- client/rpcserver/handlers.go
- client/rpcserver/rpcserver.go
- client/rpcserver/rpcserver_test.go
- client/rpcserver/types.go
- dex/msgjson/types.go
This adds a `WalletHistorian` interface which exposes a `TxHistory`
function. This will allow wallets to display the history of their
transactions. Also adds a method to the RPC server to retrieve the
wallet history.
> client/asset: Add WalletHistorian interface and RPC method 

- client/core/bookie.go
- client/core/core_test.go
- client/core/types.go
- client/mm/mm_basic.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/markets.ts
Updates the basic market maker to rebalance when the order book receives an `EpochMatchSummary` notification from the server instead of when an `EpochNotification` arrives. When the `EpochNotification` arrives, the OrderBook has not yet been updated with the matches of the previous epoch.
> client/{core,mm}: Rebalance on EpochMatchSummary instead of new epoch

- client/comms/wsconn.go
- client/core/core.go
We were assuming that if no certificate was provided, that the connection was not encrypted, and then erroring (except in the case of .onion). But it could also be that the domain has a certificate provided by a certificate authority, in which case we can resolve it. So we'll just assume that every host is using an encrypted connection.
> client/core: assume TLS

- client/asset/eth/multirpc.go
- client/core/core.go
- client/core/core_test.go
- client/core/exchangeratefetcher.go
- dex/bip-id.go
- Run rate fetcher all the time, regardless of whether we have sources. If we don't have sources, its a no-op every 12 minutes which is not worth the complication involved with starting and stopping the fetch loop.
- Use individual timeouts for requests, not a single timeout for all requests to complete.
- Adds some documentation around request limits and our request rates.
> client/core: rate fetcher tweaks

- server/cmd/dcrdex/config.go
- server/cmd/dcrdex/main.go
- server/comms/server.go
For setups where the server is running behind e.g. nginx that handles encryption.
> server/comms: allow the server to run without encryption

- client/cmd/testbinance/main.go
- client/comms/wsconn.go
- client/core/core_test.go
- client/core/trade.go
- client/mm/config.go
- client/mm/libxc/binance.go
- client/mm/libxc/binance_live_test.go
- client/mm/libxc/binance_test.go
- client/mm/libxc/interface.go
- client/mm/mm.go
- client/mm/mm_simple_arb.go
- client/mm/mm_simple_arb_test.go
- client/mm/mm_test.go
- client/mm/sample-config.json
- client/orderbook/orderbook.go
- client/orderbook/orderbook_test.go
- client/rpcserver/handlers.go
- dex/bip-id.go
- dex/calc/convert.go
This implements the simple arbitrage strategy which only places orders
when there is an arbitrage opportunity.
- A `libxc` package is added which contains a `CEX` interface used to
interact with a centralized exchange's API. It is implemented for
Binance.
- The new strategy is implemented in `mm_simple_arb.go` and can be run by
creating a `BotConfig` with a non-nil `ArbCfg`.
- A testbinance command line tool is added which starts a webserver that
responds to the requests that the Binance testnet does not support.
- A `VWAP` function is added to the client orderbook.
- `client/comms/WSConn` is updated with a `SendRaw` function which sends
arbitrary byte slices over the websocket connection.
> client/{mm, core}: Simple Arbitrage

- client/app/config.go
- client/cmd/dexc-desktop/.gitignore
- client/cmd/dexc-desktop/syncserver.go
- client/comms/wsconn_test.go
- client/core/account_test.go
- client/db/bolt/db_test.go
- client/db/interface.go
- client/db/types.go
This diff includes minor cleanup:
1. Fixes some typos
2. Ignores the darwin installer dir
3. Variable naming fix.
> Minor cleanup

- client/core/trade.go
I had to do this in order for the **simnet-trade-tests** `makerghost` test to pass, e.g. `./run dcrbtrc -t makerghost`.
When we, for the purposes of testing, intentionally block the maker from sending their `redeem` \o the server, the maker is stuck in the status `MakerSwapCast`. The server will eventually revoke the match, and the maker seems to be stuck in `MakerSwapCast` indefinitely, never satisfying the test, but more importantly blocking the order from being retired.
In practice, this would be like the maker losing contact with the server before redeeming and not establishing contact again until after the server revokes the match. So unless I'm missing something, this scenario is possible, could be caused by user intervention, and we're just not handling it.
closes …
> client/core: allow maker match status MatchConfirmed when redeem can't be reported

- .github/workflows/build.yml
- client/Dockerfile
- client/cmd/dexc-desktop/go.mod
- dex/testing/loadbot/go.mod
- docs/wiki/Server-Installation.md
- go.mod
- run_tests.sh
- Bump go.mod versions from 1.18 to 1.19
- Bump CI build.yml versions to 1.20 and 1.21
- Bump CI action versions
- Update Go and Node Dockfile images to 1.21.0 and 20.6.1 respectively.
I don't know when we should update our required Go versions but with the recent release of Go 1.21 I think it's time to bump to at least 1.19.
To verify the docker images:
$ docker pull golang:1.21.0-alpine3.18 for Go
$ docker pull node:current-alpine3.18 for Node
> go.mod/workflow/Dockerfile: version update

- client/cmd/dexc-desktop/pkg/pkg-debian.sh
* Fix build erroring out when `build/` directory does not exist
* Create debian control directory with correct permissions
> dexc-desktop: Fix Debian build issues

- client/webserver/live_test.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/wallets.ts
This PR adds the ability to enter an arbitrary VSP URL.  
Closes #2498
> ui: Custom VSP URL in VSP selection dialog

- README.md
- docs/wiki/Client-Installation-and-Configuration.md
- docs/wiki/Ethereum.md
- docs/wiki/Getting Started With Fuzzing.md
- docs/wiki/Testnet-Testing.md
> fix: typos

- dex/testing/walletpair/README.md
- dex/testing/walletpair/walletpair.sh
This is a tmux script for a 2-wallet pair that developers can use to perform manual testing on mainnet and testnet. The script aims to solve a number of problems.
1) Testing by self-trading with a single wallet has historically failed to detect some bugs.
2) Keeping your personal mainnet wallet on a release branch is advisable, so we don't want to use our primary wallet for testing.
3) For testing on mainnet, we want to use a testing server that has ultra-low lot limits and bond size, and we only want to run the nodes/markets that we're interested in testing. It wouldn't be a server suitable for public use.
> dex/testing: add script for two-wallet testing

- client/webserver/site/src/html/dexsettings.tmpl
Added the missing closer button to the Update bond dialog.
> ui: Closer button to Update bond dialog

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/eth/txdb.go
- client/asset/eth/txdb_test.go
- client/asset/interface.go
This diff updates the ETH wallet to support the `asset.WalletHistorian` interface. Since ETH RPC nodes do not support querying the transactions an account has made, the transactions are stored locally in a database. Initially they are stored with a block number of 0 and the max possible fees, but when the transaction is confirmed, these values are updated.
The pending transaction tracking used for more accurate balance reporting is updated to use the same data as required for tracking pending transactions for the wallet history. Also, the database used for monitoring pending redemption transactions and resubmitting them is upgraded to be used for both that functionality and the new tx history functionality.
> client/asset/eth: Transaction History

- client/asset/dcr/dcr.go
This pulls the critical fix out of #2444. I will convert that PR to an issue to track the dcrwallet bug.
> client/dcr: force cfilters scan for unconfirmed spv txs

- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/site/src/js/doc.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/template.go
> ui: fix unsupported asset bugs on markets view

- client/asset/dcr/dcr.go
- client/asset/dcr/spv.go
- client/asset/interface.go
- client/core/core.go
Decred SPV wallet send a notification when mempool txs are seen. Doesn't work for btc/neutrino, unfortunately.
> client/dcr: emit notification when mempool txs are seen

- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/forms.ts
Fix a bug that prevented proceeding to the post-bond form on the add server form page. Closes #2561
https://github.com/decred/dcrdex/tree/124120056da7651dc371304e0e800e0534e7676e fixed a js error log caused by navigating backwards usingng the default swipe-to-navigate feature on Macos.
> ui: Fix bug on add server form page

- client/asset/dcr/spv.go
- client/orderbook/orderbook.go
- dex/candles/candles.go
- dex/generics/generics.go
- dex/networks/zec/block.go
- dex/utils/generics.go
- server/apidata/apidata.go
- server/apidata/apidata_test.go
- server/db/driver/pg/candles_online_test.go
- server/db/driver/pg/epochs.go
- server/db/driver/pg/internal/epochs.go
- server/db/driver/pg/markets.go
- server/db/driver/pg/tables.go
- server/db/interface.go
- server/dex/dex.go
> apidata: store completed candles in db

- client/cmd/dexc-desktop/app.go
- client/webserver/site/src/html/order.tmpl
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/order.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/wallets.ts
This PR fixes the handling/behavior of links that are to open in a new window (`target="_blank"`).  When the UI runs within a Webview window, clicks on those links are passed through to the default URL handler of the OS, instead of being handled inside the WV.
Closes #2453
> ui: External link handling in dexc-desktop

- client/webserver/site/src/css/market.scss
- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/locales.ts
- client/webserver/site/src/js/markets.ts
This PR modifies the behavior of the order submit button so that it prevents the user from submitting the order if it would fail due to  the below conditions:
* quantity is 0
* buy or sell quantity is more than available balance 
Closes #2527
> ui: Order submit button state management

- dex/testing/firo/test/electrumx_network_test.go
> dex/testing: rationalize imports

- client/webserver/site/package-lock.json
running `npm audit fix`
Fixes one critical vulnerability:
```
@babel/traverse  <7.23.2
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
fix available via `npm audit fix`
node_modules/@babel/traverse
```
> site: Update deps.

- client/webserver/site/src/js/markets.ts
Reverted the change introduced in #2534 causing maxSell/maxBuy estimates being requested with zero rate.
> ui: handleBalanceNote bug fix

- client/webserver/site/src/html/bodybuilder.tmpl
Sign out is usually at the bottom of profile menus.
> ui: Move sign out menu item to bottom of hamburger menu

- client/webserver/site/src/html/markets.tmpl
- client/webserver/site/src/js/locales.ts
- client/webserver/site/src/js/markets.ts
Closes https://github.com/decred/dcrdex/issues/2574
This MR fixes a [bug](https://github.com/decred/dcrdex/pull/2548/files#diff-1e4f8de7bbcd6448186a65982ea5e8fe3d7b64b982ed09520ff884829db5221aL1100-R1100) that was introduced in  https://github.com/decred/dcrdex/pull/2548.
Improved the "noWallet" message in https://github.com/decred/dcrdex/pull/2577/commits/70b3ae2827d182ca92895237769e76c48b19e66a  as suggested by @martonp.
> site: Fix js check for base and quote wallet availability

- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/order.ts
Bug from #2541. Was redirecting _blank links regardless of whether we were on WebKit.
Also added simnet entries for all assets in CoinExplorers. They are the same as mainnet, and will go to nowhere, but at least they'll be links.
> ui: only redirect _blank links for dexc-desktop

- client/mm/config.go
- client/mm/libxc/binance.go
- client/mm/mm.go
- client/mm/mm_arb_market_maker.go
- client/mm/mm_arb_market_maker_test.go
- client/mm/mm_basic.go
- client/mm/sample-config.json
This adds a market making strategy that is kind of a combination between the basic market maker and the simple arbitrage strategies. Based on a CEX order book, it places orders on the DEX order book, and when there is a match on the DEX, the opposite order on the CEX is immediately executed for a profit.
```
// ArbMarketMakerConfig is the configuration for a market maker that places
// orders on both sides of the DEX order book, at rates where there are
// profitable counter trades on a CEX order book. Whenever a DEX order is
// filled, the opposite trade will immediately be made on the CEX.
//
// Each placement in BuyPlacements and SellPlacements represents an order
// that will be made on the DEX order book. The first placement will be
// placed at a rate closest to the CEX mid-gap, and …
```
> client/mm: Arb Market Maker

- client/webserver/middleware.go
- client/webserver/site/src/css/main.scss
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/settings.tmpl
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/settings.ts
- client/webserver/site/src/js/state.ts
- client/webserver/webserver.go
Store the `darkMode` preference in `localStorage` instead of a cookie - Webview on Linux doesn't persist the cookie jar.
Fixes #2603
> ui: Fix darkMode flag persistence

- client/core/core.go
Bug can cause orders not to proceed if they were booked through a server reconnect.
> [0.6] core: fix version check on server reconnect

- client/core/core.go
Bug can cause orders not to proceed if they were booked through a server reconnect.
Closes #2619
> core: fix version check on server reconnect

- client/webserver/site/src/js/app.ts
Do not hide the markets menu item when a DEX connection is not configured.  Clicking the item in that case will redirect to /register.
> ui: Markets menu item visibility

- client/cmd/dexc-desktop/go.mod
- client/cmd/dexc-desktop/go.sum
- client/mm/libxc/binance.go
- client/mm/libxc/binance_live_test.go
- client/mm/libxc/binance_test.go
- client/mm/libxc/binance_types.go
- client/mm/libxc/orderbook.go
- client/mm/libxc/orderbook_test.go
- go.mod
- go.sum
Previously the Binance library was subscribing to a market data stream from Binance that sent the 20 orders closest to the mid-gap in every update. Now, it fetches a snapshot of 1000 orders, this is stored in memory, and is updated based on a stream that sends diffs instead. Other minor cleanup is done in the Binance library as well.
> client/mm/libxc: Binance orderbook diff updates

- client/webserver/site/src/js/locales.ts
1. Remove duplicate `ID_API_ERROR` translation key.
2. Update `ID_API_ERROR`  translation to support `msg` arg.
> client: Fix `ID_API_ERROR` translation

- client/core/bookie.go
To reproduce, just call the `core.Book` method for any market.
I already discarded the original log, but this is from Cryptopower:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1058897]
goroutine 3038 [running]:
decred.org/dcrdex/client/core.(*bookie).translateBookSide(0x0, {0xc009ffa160, 0x3, 0x7?})
/home/joe/go/pkg/mod/github.com/ukane-philemon/dcrdex@v0.0.0-20240104133235-beacdac7d43d/client/core/bookie.go:589 +0x77
decred.org/dcrdex/client/core.(*Core).Book(0xc0037fe000, {0xc0051de020?, 0x1?}, 0x0?, 0x0?)
/home/joe/go/pkg/mod/github.com/ukane-philemon/dcrdex@v0.0.0-20240104133235-beacdac7d43d/client/core/bookie.go:577 +0x891
github.com/crypto-power/cryptopower/ui/page/dcrdex.(*DEXMarketPage).se …
```
> core: Fix nil bookie panic in `core.Book(...)`

- dex/networks/polygon/params.go
[Circle now issues USDC on Polygon on a native contract](https://www.circle.com/blog/native-usdc-now-available-on-polygon-pos) instead of using a bridge. They are recommending that everyone switch to the native token. Coinbase already only supports withdraws of the native token.
Devs: If you have bridged USDC in your mainnet walletpair or getgas/deploy wallets, you'll need to be on a commit before this one, and send it to yourself.  I know of a couple of methods.
1. Send it to coinbase, which still accepts deposits of both tokens, and then withdraw, which will be the native token. 
2. You could also send it to e.g. MetaMask and use Uniswap to convert from USDC.e to USDC, then send it back.
Closes #2559
> polygon: switch to native usdc on polygon

- client/core/core.go
- client/core/core_test.go
- client/core/trade.go
This PR handles an edge case that causes a match init request to be sent before connecting to the server : See: https://github.com/decred/dcrdex/issues/2617#issuecomment-1858697056
Closes: #2617
> core: Ensure login in `core.resendPendingRequests`

- client/asset/btc/btc.go
- client/asset/dcr/dcr.go
- client/asset/zec/zec.go
> client/{btc,dcr,zec}: Use binary search for maxOrder loop

- dex/testing/walletpair/walletpair.sh
This adds a simnet option to the wallet pair which runs both dex clients on simnet and puts the appdata in a separate folder. Also, both of the dex clients now run an rpc server, and dexcctl scripts for each client are added to the harness-ctl folder.
> dex/testing: Update walletpair

- client/asset/dash/dash.go
Dash upgraded to a hard fork version.https://github.com/dashpay/dash/blob/v20.0.0/doc/release-notes.md
I have tested
- basic regtest harness: works
- client/asset/dash_test.go: works
> client: update Dash minimum version to 200000 v20.0.0 breaking changes

- client/core/bond.go
- client/core/core.go
- client/core/locale_ntfn.go
- client/core/notification.go
- client/core/trade.go
- client/webserver/api.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/coinexplorers.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/notifications.ts
- client/webserver/site/src/js/order.ts
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/state.ts
- client/webserver/site/src/js/wallets.ts
- client/webserver/webserver.go
Modified the rendering of notification and pokes:
* implemented `formatDetails` related TODO items in `bonds.go`
* bond related transaction hashes are displayed shortened and are clickable (linking to coin explorers)
* order hashes link to order details view
There are a few additional things I think would improve legibility but I wanted to solicit comments on first:
* the below 2 notifications include technical detail that may not be useful and could perhaps be trimmed:
(As this is not a fatal error that requires user action maybe it could be rephrased to be less scary)
(This may well occur relatively frequently.  Maybe rephrase to something along the lines of
> ***Trade limit exceeded*** 
> Order quantity on <order#> exceeds trade limit. [Increase trade limit](#)
* Order # links lead to …
> multi: Clickable tx and order links in notes/pokes

- client/core/bond.go
- client/core/types.go
- client/webserver/site/src/js/dexsettings.ts
- client/webserver/site/src/js/registry.ts
This PR adds a core method that exposes expired bonds for all connected dex servers.
> core: Add `ExpiredBonds` field to `ExchangeAuth`

- dex/testing/eth/README.md
- dex/testing/eth/create-node.sh
- dex/testing/eth/harness.sh
I recently updated geth to `1.13.4-stable` and the harness did not work. It seems some config variables were removed, and that the light nodes also do not work, unless I am missing something. This removes the config vars and disables the light nodes for now.
> harness: Disable geth light nodes.

- client/app/config.go
- dex/testing/walletpair/README.md
- dex/testing/walletpair/walletpair.sh
Follow up to #2639
- Get TLS key/cert in order for rpc server
- Parse simnet status from command line arguments
> walletpair: fix rpc server cert. parse simnet from args

- client/core/core.go
This PR adds a method `ActiveOrders` that returns the user's active orders across all dex servers.
> core: add `ActiveOrders` method to `Core`

- client/webserver/site/src/js/wallets.ts
This adds `title` attributes to the elements containing identifiers that are shortened, so that they can be quickly viewed in full without copying to the clipboard.
> ui: Show full tx ID/bond ID/address in hover popups

- client/core/bond.go
In `makeAndPostBond`, `exchangeAuth -> bondStateOfDEX` was being called (for logging) before `monitorBondConfs`, resulting in a warning.
```
[WRN] CORE: Found a pending bond that is not waiting for confirmations. Re-posting: ...
```
> core: fix unmonitored bond warning

- client/core/core.go
This PR resolves a deadlock when `c.connectWalletResumeTrades` defers a `RUnlock`, and another goroutine (`c.handleWalletNotification` or `c.peerChange`) tries to hold a write lock (blocks as expected) and code path in `updateBondReserves` tries to hold another `RLock` (this will block waiting for the write lock in `c.handleWalletNotification` or `c.peerChange`, which in turn is waiting for the deferred `RUnlock`).
> core: Fix deadlock in `c.connectWalletResumeTrades`

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/btc/spv_test.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/interface.go
- client/core/bond.go
- client/core/core.go
- client/core/core_test.go
- client/core/locale_ntfn.go
- client/core/notification.go
- client/core/wallet.go
When the server tells us of an unknown v0 bond attempt to find and recreate it so that it can be refunded later. Useful when restoring from seed.
closes #2371
> multi: Add FindBond to Bonder.

- client/webserver/site/src/js/doc.ts
- dex/testing/dcrdex/genmarkets.sh
- dex/testing/loadbot/loadbot.go
- dex/testing/loadbot/mantle.go
- dex/testing/loadbot/sidestacker.go
The doge loadbot does not run on master for one because the amount of dcr needed for registration is not sent to the dcr wallet. The lot size makes one lot trades impossible due to it being dust. And for some reason the default feerate for doge is not used so setting explicitly. I would think it should use the client default so can look into why it does not if needed.
Loadbot works on the default dcr_doge after these changes.
> loadbot: Adjust doge values.

- dex/msgjson/types.go
- server/dex/dex.go
This PR adds a `/healthy` endpoint to the API, to be consumed by a status page monitoring the health of the platform.  The status returns `false` if `storage.LastErr()` is non-nil, or the BTC asset backend reports the chain being out of sync (via `Synced()`).
The necessity of the latter is debatable but it feels like that, BTC being one of the main assets, it indicates that the DEX as a service does not function as intended when that chain is not synced.
Also, `storage.fatalErr` is not being reset after a (transient) DB error.
Thoughts, suggestions?
> server: Health API endpoint

- client/asset/bch/bch.go
- client/asset/btc/btc.go
- client/asset/dash/dash.go
- client/asset/dcr/dcr.go
- client/asset/dgb/dgb.go
- client/asset/doge/doge.go
- client/asset/driver.go
- client/asset/firo/firo.go
- client/asset/ltc/ltc.go
- client/asset/zcl/zcl.go
- client/asset/zec/zec.go
- client/core/core.go
- client/core/types.go
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/registry.ts
- dex/calc/parcels.go
- dex/msgjson/types.go
- dex/networks/zec/script.go
- server/asset/zec/zec.go
- server/dex/dex.go
- server/market/market.go
- server/market/market_test.go
Built on #2669. [This is the diff you're looking for.](https://github.com/buck54321/dcrdex/compare/a3e3a32...buck54321:dcrdex:minmarketrate)
> multi: enforce a minimum market rate that avoids dust redemption outputs

- client/asset/eth/multirpc_test_util.go
- client/asset/polygon/chaincfg.go
- client/asset/polygon/multirpc_live_test.go
- client/asset/polygon/polygon.go
- dex/networks/polygon/genesis_config.go
- dex/networks/polygon/params.go
- server/asset/polygon/polygon.go
Switch to Polygon Amoy testnet. 
https://polygon.technology/blog/introducing-the-amoy-testnet-for-polygon-pos
New contracts launched and contract data synced with polygonscan. Gas estimates verified.
Devs: Don't forget to update your **`~/dextest/credentials.json`**
Devs and testers: Please hit the MATIC faucet ([good one at Alchemy](https://www.alchemy.com/faucets/polygon-amoy)) and [Circle's testnet USDC faucet](https://faucet.circle.com/)
> polygon: switch to amoy

- .gitignore
- client/webserver/site/src/css/utilities.scss
- client/webserver/site/src/html/dexsettings.tmpl
- server/admin/api.go
- server/admin/server.go
- server/admin/server_test.go
- server/auth/auth.go
- server/cmd/dcrdex/config.go
- server/cmd/dcrdex/main.go
- server/cmd/dexadm/dexadm_harness.conf
- server/cmd/dexadm/index.html
- server/cmd/dexadm/main.go
- server/cmd/dexadm/script.js
- server/dex/dex.go
Adds a rudimentary GUI for interacting with the server admin API. Test against the simnet harness by running `./dexadm --harness` in **server/cmd/dexadm**.
> admin: add gui

- dex/fiatrates/fiatrates.go
- dex/fiatrates/oracle.go
- dex/fiatrates/sources.go
- dex/fiatrates/types.go
- tatanka/client/client.go
- tatanka/client_messages.go
- tatanka/cmd/demo/main.go
- tatanka/cmd/tatanka/main.go
- tatanka/mj/types.go
- tatanka/tatanka.go
Closes #2727 
The new code in `fiatrate` pkg would eventually replace the existing providers we use elsewhere. That will be the focus of another effort.
> fiatrates: Implement a fiat rate oracle for tatanka

- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/register.ts
The registration flow didn't take into account the case where an exchange had not yet been added to user.Exchanges. It assumed the exchange would already be view only.
Closes #2749
> app: Fix registration flow forms

- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/wallets.ts
Bond related rows were being displayed for non-bond transactions, age of txs was not being updated, and copy buttons didn't match the color transitions of the text they were copying.
> app: Tx History UI Fixes

- client/asset/ltc/spv.go
- client/cmd/dexc-desktop/go.mod
- client/cmd/dexc-desktop/go.sum
- dex/logging.go
- dex/testing/loadbot/go.mod
- dex/testing/loadbot/go.sum
- go.mod
- go.sum
Temporary `replace` pointing to combined dcrlabs/ltcwallet#6, dcrlabs/ltcwallet#7, dcrlabs/ltcwallet#8, which collectively fix a number of bugs and enabled better logging.
I'm keeping an eye on the testnet seeds to see which are stable, so those may change in the next couple of days.
> ltc: better ltcwallet logging

- client/cmd/bisonw-desktop/app.go
- client/cmd/bisonw-desktop/app_darwin.go
- client/cmd/bisonw-desktop/gen.go
- client/cmd/bisonw-desktop/go.mod
- client/cmd/bisonw-desktop/go.sum
- client/cmd/bisonw-desktop/icon_darwin.go
- client/cmd/bisonw-desktop/main.go
- client/cmd/bisonw-desktop/pkg/pkg-darwin.sh
Closes #2674.
The first time we send a notification, the user has to `Allow` the app to continue sending notifications, but if they deny the app, they can allow notification later in their app settings.
Tested on Ventura 13.6.6.
Notification Settings
> dexc-desktop: Implement native notifications for MacOS

- client/mm/exchange_adaptor.go
- client/mm/exchange_adaptor_test.go
- client/mm/mm.go
- client/mm/mm_arb_market_maker.go
- client/mm/mm_arb_market_maker_test.go
- client/mm/mm_basic.go
- client/mm/mm_basic_test.go
- client/mm/mm_simple_arb.go
- client/mm/mm_simple_arb_test.go
- client/mm/mm_test.go
- dex/asset.go
- Update architecture such that bots embed `unifiedExchangeAdaptor`, which reduces duplication and enables sharing of utilities and more concise access to immutable properties.
- Move pause handling to `unifiedExchangeAdaptor`
- Add log formatting utilities
- More trace logging
- Normalizes some naming
> mm: light refactoring. more logging

- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
Updates swap redemption/refunds and bond redemptions to be sent to external addresses.
> client/btc: Swap / Bond redemptions to external address

- client/asset/btc/btc.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/native_wallet.go
- client/asset/dcr/rpcwallet.go
- client/asset/dcr/spv.go
- client/asset/dcr/spv_test.go
- client/asset/dcr/wallet.go
- client/asset/interface.go
This diff updates the DCR wallet to identify any unknown transaction and add it to the transaction history. Redeems, refunds, and bond refund transactions are updated to use an external address instead of an internal one. Otherwise, the RPC wallet's listsinceblock command would not return them.
Closes #2744
> client/dcr: Identify unknown txs

- client/asset/btc/btc.go
This PR fixes a bug where a write operation might be attempted even when `txHistoryDB` might be nil resulting in a panic.
> client/asset/btc: check for nil `txHistoryDB` before write operation

- client/asset/bch/bch.go
- client/asset/bch/spv.go
- client/asset/btc/btc.go
- client/asset/btc/spv.go
- client/asset/btc/spv_wrapper.go
- client/asset/dcr/config.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/native_wallet.go
- client/asset/dcr/spv.go
- client/asset/dcr/spv_test.go
- client/asset/driver.go
- client/asset/interface.go
- client/asset/ltc/ltc.go
- client/asset/ltc/spv.go
- client/core/core.go
- client/core/wallet.go
Makes Decred SPV wallet an `asset.Rescanner`
> dcr: enable rescans for spv wallets

- client/asset/bch/bch.go
- client/asset/btc/btc.go
- client/asset/driver.go
- client/cmd/bwctl/main.go
- client/core/core.go
- client/rpcserver/handlers.go
- client/rpcserver/rpcserver.go
- client/rpcserver/rpcserver_test.go
- client/rpcserver/types.go
- dex/testing/bch/harness.sh
[bchd](https://github.com/gcash/bchd) was the only node implementation that served filters, it's been [busted for some time](https://github.com/gcash/bchd/issues/531), and [efforts to upgrade are stalled](https://github.com/gcash/bchd/pull/528). Similarly, [efforts at gitlab.com/bitcoin-cash-node](https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node/-/issues/261) have been stalled for years.
The fact that the spv wallet hasn't worked for so long and nobody has sought support leads me to believe that nobody is using this wallet. That said, we need to provide a way for those users to move funds should they appear, so I've added an rpcserver endpoint to generate a transaction that spends all funds to another address. The transaction will need to be pasted into e.g. …
> bch: disable Bitcoin Cash SPV wallet

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/eth/multirpc.go
- client/asset/eth/node.go
- client/core/core.go
- client/core/core_test.go
- client/webserver/api.go
- client/webserver/webserver.go
- Fixes an issue where a test case in `TestDeleteArchivedRecords` deals with the same file when it should have been two different files.
- Remove unused `lots` argument passed to `core.createTradeRequest`
- Ignore other unused variables
- Fix error check in `*multiRPCClient.withAll(...)`
> multi: Bug fixes and remove/ignore unused param

- client/asset/dash/dash.go
- client/asset/firo/firo.go
- dex/testing/dash/harness.sh
Firo: 0.14.13.3 - latest
Dash: 20.1.1    - latest
Note: This is a further bump of Firo from 0.14.13.2 -> 0.14.13.3 released today (Jun 19 2024)
and marked as mandatory.
For dash project this was not considered
a breaking change but it broke our harness
due to an RPC parameter change in 20.1.0.
> client,testing: update minimum Firo & Dash version

- client/asset/eth/eth.go
Fixes typos, ignore unused params and light test refactoring in the `eth` pkg.
> asset/eth: Ignore unused parameters and refactor

- client/mm/mm_basic.go
- client/mm/mm_simple_arb.go
The bot loops were using the exchange adaptor's context instead of the one in the parameters.
> mm: Use proper context in bot loop

- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/native_wallet.go
- client/asset/dcr/rpcwallet.go
- client/asset/dcr/spv.go
- client/asset/dcr/spv_mixing.go
- client/asset/dcr/wallet.go
- client/asset/interface.go
- client/core/core.go
- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/site/src/css/wallets.scss
- client/webserver/site/src/html/wallets.tmpl
- client/webserver/site/src/js/registry.ts
- client/webserver/site/src/js/wallets.ts
- client/webserver/webserver.go
- client/webserver/webserver_test.go
The `CSPPServer` and `Cert` configurations are no longer necessary when setting the mixing configuration.
To activate a the Peer-to-peer of a boolean true that is required.
> Remove Deprecated CPP Funds Mixer Configuration

- client/asset/btc/btc.go
- client/asset/btc/simnet_test.go
- client/asset/dcr/dcr.go
- client/asset/dcr/simnet_test.go
This PR ensures that a caller is able to call WalletTransaction and get a result with `Confirmed == true` if and only if the effects of the transaction can be seen in the available balance. This is important for market makers to be able to accurately track balances.
> client/dcr,btc: Ensure balance and wallet transaction results synced

- dex/dexnet/http.go
- dex/logging.go
- dex/txfee/feefetcher.go
- dex/txfee/feefetcher_test.go
- server/asset/btc/btc.go
- server/asset/btc/btc_test.go
- server/asset/btc/feefetchers_test.go
Replaces #2638, which was never merged to the release branch
Steps on #2769. Does not replace that work, but offers some patterns that I think are useful and should be adapted to Tatanka.
Enables external fee rate estimation for Bitcoin. `estimatesmartfee` is not always the best estimate and requires priming. We retain `estimatesmartfee` as a backup. 
- Sources have rank / priority
- Sources have customizable refresh times
- Registered APIs for Tatum and Blockdaemon are available via a new configuration file format option
- A composite score is calculated based on the the valid scores from the best available priority group, with the weight of the individual score in the composite falling off over time after a period of full validity
> server/btc: use external fee rates

- client/webserver/site/src/js/mm.ts
The conversion factor for the base asset was being used in stead of the conversion factor for the base fee asset.
> app: Incorrect allocated amount displayed for base swap fees

- client/asset/bch/bch.go
- client/asset/btc/btc.go
- client/asset/ltc/ltc.go
- client/asset/zec/zec.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/html/mmsettings.tmpl
- client/webserver/site/src/js/mmsettings.ts
The multi split option was not available on BTC clones. Also, the multi split buffer option was available on base assets, but it should only be available for quote assets.
> mm: Fix multi split option related bugs

- client/mm/price_oracle.go
- client/mm/price_oracle_test.go
The symbols used to look up token rates included the network, causing errors. This diff updates this so that only the token symbol is used.
Closes #2831
> mm: Oracle token errors

- client/core/core_test.go
- client/core/wallet.go
Two wallet connections running in parallel was causing a panic.
There were parallel calls to `xcWallet.Connect` happening in `core.refundExpiredBonds` and `core.connectWallets`. The second connect was timing out, causing the panic in #2793.
Resolves: #2793
> core: Make wallet connection synchronous

- client/asset/dcr/native_wallet.go
- client/asset/dcr/spv_mixing.go
Closes https://github.com/decred/dcrdex/issues/2845.
Also resolves @JoeGruffins concerns here https://github.com/decred/dcrdex/issues/2856#issuecomment-2208171213
> asset/dcr: Skip starting mixer during initial sync

- client/webserver/locales/en-us.go
- client/webserver/site/src/html/wallets.tmpl
Closes #2802 
EDIT: I think it might be better to separate user added peers from discovered peers cuz having the Remove col empty doesn't look great, wdy think @buck54321?
> webserver: Fix manage peer view

- docs/wiki/Client-Installation-and-Configuration.md
Update Client Installation and Configuration to provide links to Dash v20.1.1, Firo v0.14.13.3 and Electrum-Firo v4.1.5.5
> docs: update client install doc for Dash and Firo

- client/webserver/site/src/js/mmsettings.ts
The total allocation displayed did not properly reflect the order reserves.
> mmui: Fix allocation display bug

- client/mm/libxc/binance.go
- client/mm/mm.go
`https://api.binance.com/api/v3/exchangeInfo` currently weighs ~6 MB, preventing the MM bot from being configured:
```
[ERR] WEB: error loading Binance with updated config: error connecting to CEX: failed to connect to CEX: connect failure: error getting markets: error getting markets from Binance: error decoding request: unexpected EOF
```
This PR increases the size limit to 16 MiB and fixes a couple of incorrectly wrapped errors.
> Increase file size limit for Binance market info requests

- client/Dockerfile
- client/Dockerfile.release
PR #2521 broke the build as it changed nodebuilder to the alpine variant, this fixes the git install.
Changed config directory to reflect https://github.com/decred/dcrdex/blob/master/client/app/config.go#L39
> Dockerfile nodebuilder fix

- client/mm/mm.go
- client/webserver/site/src/html/mm.tmpl
- client/webserver/site/src/js/mm.ts
When starting a bot, existing orders on the books will be cancelled. A message regarding this is displayed on the allocation screen.
> mm: Cancel existing orders when starting bot

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/eth/txdb_test.go
The recipient field was being populated with the "to" field of the eth transaction (which may be a contract address) instead of the recipient of a send transaction as in other assets.
> client/eth: Tx history recipient bug

- client/webserver/site/src/js/mm.ts
The number of booked orders was not being updated on the UI page, and the profit/loss was not being limited to 2 decimals.
> mm: Minor UI fixes

- client/mm/exchange_adaptor.go
- client/mm/mm_arb_market_maker.go
- client/mm/mm_basic.go
- client/mm/mm_simple_arb.go
Book feeds were not being closed, leading to warning logs.
> mm: Close book feeds

- client/cmd/bisonw-desktop/go.mod
- client/cmd/bisonw-desktop/go.sum
- dex/testing/loadbot/go.mod
- dex/testing/loadbot/go.sum
- go.mod
- go.sum
Updates btcwallet and ltcwallet deps to get the fix for the shutdown bug resolved [here for btcwallet](https://github.com/btcsuite/btcwallet/pull/944) and [here for ltcwallet](https://github.com/dcrlabs/ltcwallet/pull/9).
> btc/ltc: update wallet deps

- client/core/core.go
- client/core/wallet.go
RPC wallet password changes were not being stored correctly in the `LiveReconfigurer` short path, i.e. no other wallet settings were being changed.
> core: store wallet pw changes on LiveReconfigurer no-restart path

- client/webserver/site/package-lock.json
- client/webserver/site/src/js/doc.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/opts.ts
- client/webserver/site/src/js/order.ts
- client/webserver/site/src/js/wallets.ts
This was a patch we did on the `release-v0.6` branch (#2596) that somehow never made it into master. This is to address a bug in Electron that adds a non-existent language code into `navigator.languages`.
> ui: filter out injected non-existent language

- client/cmd/bisonw-desktop/go.mod
- client/cmd/bisonw-desktop/go.sum
- client/core/core.go
- client/webserver/site/src/css/main.scss
- client/webserver/webserver.go
- dex/testing/loadbot/go.mod
- dex/testing/loadbot/go.sum
- go.mod
- go.sum
- werbserver: remove unused fields for mm config path
- ltc: update ltcwallet to tame the warnings when a peer was rejected for not supporting compact filters
- ui: CSS fix to follow up #2927 where small logo size wasn't always being set correctly
- core: fix some fallout from #2895 where a transient unsynced state at peer change wasn't properly followed up on, resulting incorrect sync status % displayed at the UI
> multi: assorted fixes

- client/asset/btc/btc.go
- client/asset/btc/coinmanager.go
- client/asset/zec/regnet_test.go
- client/asset/zec/shielded_rpc.go
- client/asset/zec/transparent_rpc.go
- client/asset/zec/zec.go
- client/asset/zec/zec_test.go
- client/cmd/testbinance/main.go
- client/cmd/testbinance/wallets.go
- client/mm/exchange_adaptor.go
- client/mm/libxc/binance_live_test.go
- dex/testing/dcrdex/genmarkets.sh
- Refactor zcash multi-split. It wasn't working well or considering shielded funds
- Fix Zcash withdraw address sent to cex. The unified address wasn't being parsed to a transparent.
- Add ZEC-BTC market on the testbinance server
- 0-conf transparent outputs are now immature for the purposes of split-order funding and e.g. simple sends. This is because orchard outputs require 1 conf, and we use z_sendmany which is ambigious as to where it will get funds from. Calling z_sendmany with 0 sometimes seems to throw errors, even if there is enough transparent funding.
I'll have a ZEC-USDT market up on the mainnet testing server in the morning. There's is a matching market on binance.us that bots can arb against. We can't arb zec on binance global until we implement the new exchange addresses.
> zec: fix zcash multisplit

- client/comms/wsconn.go
- client/core/core.go
Only servers behind an .onion address will be using cleartext.
> core: Fix connecting via Tor

- client/core/bond.go
- client/mm/mm_basic.go
- client/mm/mm_basic_test.go
- client/mm/mm_test.go
- client/mm/price_oracle.go
I noticed while making dcr-btc with the basic market maker that we only had one oracle, the volume was super low, and the rate had drifted an uncomfortable amount without any indication that something was wrong. But since volume was not zero, we used the oracle average anyway. This PR adds a number of improvements and failsafes that prevent oracle-derived rates from being used unless certain reasonable conditions are met.
1. Sum of oracles' 24-hr. volume must be > $100,000 USD, or else we use the fiat-derived basis price.
2. If we have a valid oracle price (enough volume), and a valid fiat-derived price, we'll do a sanity check for mismatch and error if the mismatch between the rates is > 5%.
3. Stop trying to look up binance.com markets on binance.us when binance.com is 451.
> mm: add volume minimums and sanity checks for oracle rates

- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/charts.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/mm.ts
- client/webserver/site/src/js/mmarchives.ts
- client/webserver/site/src/js/mmlogs.ts
- client/webserver/site/src/js/mmutil.ts
Closes #2962
Closes #2956
Closes #2955
Closes #2954
Also prevents trying to update mm panel on /markets for `runevent` notifications if it's not the market we're looking at.
> ui: fix a number of minor ui issues

- client/app/config.go
- client/core/core.go
This is useful enough for testing and working around bugs to add permanently, I think.
> core: enable limiting connections to one server

- dex/testing/walletpair/walletpair.sh
This allows starting walletpair with only one wallet by specifying the CLI flags `-1` or `-2`.
> walletpair: allow starting walletpair with just one wallet

- client/asset/importall/importall.go
- client/cmd/bisonw-desktop/main.go
- client/core/core.go
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/orders.ts
- client/webserver/site/src/js/registry.ts
- server/asset/importall/importall.go
Also switches to using **importall** package in **bisonw-desktop**.
Does not delete the **client/asset/zcl** or **server/asset/zcl** or testing packages yet. We can do that any time, but it might be worth discussing a way to handle low-cap assets that enables them to be switched on by the user somehow, so I'll leave the code for now.
I highly doubt anybody is using bw as a Zclassic wallet, but it doesn't matter if they are, since the only option for wallet type is the external RPC wallet.
> get rid of dead asset zcl

- client/webserver/site/src/js/mmutil.ts
> mm,ui: don't double account for bot-locked balance

- client/asset/interface.go
I guess you can hit this if you shut down and restart immediately. Not a showstopper.
> core: don't give a NaN for sync progress if we start at target height

- client/cmd/bisonw-desktop/pkg/pkg-darwin.sh
The `MACOSX_DEPLOYMENT_TARGET` env var is required to compile backwards compatible cgo builds with on Mac.
The `-tray` thing was just copypasta.
> bisonw-desktop: fix filename flavor and enforce darwin cgo minver

- client/webserver/site/src/js/markets.ts
Only show one section at a time in the bond waiting UI on the markets page.
Closes #2978
> app: Fix bond waiting UI

- dex/testing/walletpair/walletpair.sh
tmux was doing something weird with the argument expansion. This fixed it for me.
> walletpair: fix tmux arg expansion

- client/asset/dcr/spv.go
There is an unsafe subtraction when checking the number of confirmations on a DCR transaction.
May close #2999. I was unable to reproduce, but this code is definitely suspect.
> client/dcr: Fix negative swap confs

- client/cmd/testbinance/main.go
- client/mm/libxc/binance.go
- client/mm/libxc/bntypes/types.go
Untested. Attempting to solve a problem with stuck books.
> binance: Retry keep alive.

- client/webserver/site/src/js/wallets.ts
When displaying token transactions on the wallet page for the parent asset, the unit info for the parent asset was being used, causing incorrect amounts.
Closes #2994
> app: Fix amounts displayed for token transactions in tx history

- client/asset/dcr/dcr.go
closes #2971
`handleTipChange` must wait until the go functions are finished, so the tipMtx is held for writes for both of them. syncTxHistory calls SyncStatus which also conditionally holds the tipMtx for reads, randomly causing deadlock. I think running syncTxHistory as a goroutine and not waiting is the simplest answer.
> dcr: Remove tx history wait.

- client/comms/wsconn.go
- client/core/core_test.go
- client/mm/libxc/binance.go
Just the URL update part of the changes discussed and aborted in #2958. I think this was actually the crux of the problem we were seeing, but we also fixed some other stuff in that PR too.
> binance: update book stream url

- .github/workflows/build.yml
`ubuntu-latest` was [bumped](https://github.com/actions/runner-images/pull/10687) from v22 to v24.
> testing: use ubuntu 22 for github actions

- client/asset/btc/rpcclient.go
The `ChangePosition` field is unused and sometimes negative apparently, causing an error when estimating send fees.
> btc: remove unused field from fundrawtransaction result struct

- client/app/config.go
- client/core/core.go
- client/db/bolt/db.go
- client/db/bolt/db_test.go
This is a refactor of #2975 meant as a stop-gap for the release branch. I will close #2975 in favor of a more comprehensive archiving solution to be worked out later.
> [1.0]client/db: enable archive pruning

- client/asset/btc/btc.go
Conservative mode is known to massively overestimate transaction fees, and while economical mode still has issues and still overestimates, its not nearly as extreme.
I'm new on this repo so not totally aware of the ramifications of this, but opening this PR for awareness/discussion. My understanding is that the server mandates fee rates for swap txns, so this change should only affect clients when calculating their redeem transactions (which are not as sensitive to timely mining)
References:
https://github.com/bitcoin/bitcoin/pull/30275
https://delvingbitcoin.org/t/bitcoind-policy-estimator-modes-analysis/964
> btc: estimatesmartfee in economical mode.

- client/webserver/site/src/js/dexsettings.ts
This PR fixes an issue where a dex server's new status is unknown until the user refreshes the page to trigger fetching user info, usually after a server has been disabled or enabled.
Closes #3030 
I believe the message is sufficient, suggestions are welcomed.
> webserver/site: refetch user info after updating a DEX server

- client/asset/dcr/dcr.go
- client/core/core.go
My linter picked up the incorrect error check in core, and I also found that `dcr.handleTipChange` always accepts an err arg that was checked, but all of the current sites provide a nil error, hence the need for this PR to fix these error checks.
> multi: fix error checks in core and dcr wallet

- client/asset/zec/zec.go
Zcash has far lower block times that Bitcoin (75 seconds), so our tx history scanning needs to go farther back. 100 blocks is probably excessive, but that's the reorg limit of zcashd, so we'll roll with it for now and implement some more careful reorg recognition logic in the future.
> zec: increase tx history query buffer

- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/rpcwallet.go
- client/asset/dcr/simnet_test.go
- client/asset/dcr/spv.go
- client/asset/dcr/spv_test.go
- client/asset/dcr/wallet.go
GetRawTransaction will error if txindex is not specified on the node, and until now GetTransaction has been good enough for client.
Until 12a90a7fbd we were only using `GetRawTransaction` for mempool redemptions, which it will not error for https://github.com/decred/dcrd/blob/7735cbb4e11b61636e88ad07e9ad8c1a30dd4047/internal/rpcserver/rpcserver.go#L2899
closes #2947
> client/dcr: Remove GetRawTransaction.

- client/asset/btc/btc.go
Even with the fix from #3028, `estimatesmartfee` is still terrible. At this point, I'm done with it, and I'm disabling it for Bitcoin and making external fee rates the default.
Our fee rate logic for btc and btc clones has always been a shit show, and it still is. This change makes the reasoning even harder. A complete rework is far overdue, but this isn't that. This just needs to get into the patch so that bots are not overpaying redeem fees by >= 3x.
> btc: disable estimatesmartfee for bitcoin

- client/webserver/site/src/js/mmutil.ts
In a situation when an Arb bot was running and a Basic MM bot is being started, the UI would attempt to allocate a negative amount. This is fixed.
> mmui: Fix Basic MM allocation bug

- client/mm/exchange_adaptor.go
- client/mm/exchange_adaptor_test.go
- client/mm/libxc/orderbook.go
- client/mm/mm_simple_arb.go
- client/mm/mm_test.go
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/markets.ts
- client/webserver/site/src/js/mm.ts
- client/webserver/site/src/js/mmutil.ts
- client/webserver/site/src/js/registry.ts
Some code clean up and fixes.
- Removed unused code related to the simple arb
- Simple arb bot was not reporting if the CEX orderbook was not synced
- Fixes a divide by 0 panic happening in libxc.orderbook.vwap
> mm: Epoch reports follow up

- client/db/bolt/db.go
Running these functions on a resource contrained machine and a large database was incredibly slow due to overuse of the `newestBuckets` func. Every key was accessed and sorted every time a batch of orders/matches was processed.
Rather than repeatedly performing this work, the full set of keys is now accessed only once. The resulting code runs ~200x faster.
There is a slight change in behaviour because database transactions are now committed with a **maximum** of 1000 deletions rather than **exactly** 1000. This is not an issue because the exact size of each transaction doesn't matter, the important point is to limit the maximum size of each transaction to prevent excess memory consumption.
This performance gain removes the need to log the progress of each individual batch, so now only a …
> bolt: Improve delete inactive orders/matches perf.

- client/asset/dcr/dcr.go
> dcr: Add mix split tx identification.

- client/mm/exchange_adaptor.go
Fixes a possible deadlock due to a nested RLock.
Closes #3062
> mm: Fix deposit balance check deadlock

- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/markets.ts
Fixes a bug related to closing popups on the market page.
> app: Fix market page form close

- client/asset/btc/spv_wrapper.go
[Fixes #3055](https://github.com/decred/dcrdex/issues/3055)
changed:
assetdb-backup/btc/regtest/2024-11-03T16:59:15
to:
assetdb-backup/btc/regtest/2024-11-03T17_24_29
`:` invalid for Windows filepath
> asset/btc: fix format time for assetdb-backup/btc filepath

- client/asset/eth/txdb.go
- dex/lexi/datum.go
- dex/lexi/db_test.go
- dex/lexi/dbid.go
- dex/lexi/index.go
- dex/lexi/keyprefix.go
- dex/lexi/lexi.go
- dex/lexi/log.go
- dex/lexi/table.go
Add the Lexi DB package, which wraps badger DB to provide a simplified API, to capture the sometimes tedious mechanics that we've repeated in various places, and to add utilities for indexing data for quick retrieval of filtered data.
This change is just the addition of the package. I will demonstrate it's use in tatanka separately. 
I'll add some more testing, but feel free to review as is.
See [this diff](https://github.com/buck54321/dcrdex/compare/c8b41cd...buck54321:dcrdex:eth-lexi) for an example of how it would replace the tx DB for Ethereum.
> lexi: add new database package

- client/asset/interface.go
- client/core/core.go
- client/mm/exchange_adaptor.go
- client/mm/mm.go
- client/mm/utils.go
- client/webserver/site/src/js/mmutil.ts
When the wallet is not able to fund all the orders requested, it resulted in a panic in the mm code, because a nil MultiTradeResult was returned. This also fixes the UI to properly display unknown errors in the epoch report.
> mm/core: Fix multi trade funding error

- client/mm/libxc/binance.go
- dex/dexnet/http.go
- dex/dexnet/http_live_test.go
- dex/dexnet/http_test.go
Parse binance error response bodies for error code and message. Log query strings and request bodies when an error is encountered.
Replaces #2912
> binance: parse error responses

- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/externaltx.go
- client/asset/dcr/native_wallet.go
- client/asset/dcr/spv_test.go
closes #3086
`*NativeWallet.mixFunds()` is called in `*ExchangeWallet.handleTipChange` as `dcr.cycleMixer` where `dcr.tipMtx` is held. This is similar to the deadlock in #3066 .
> dcr: Make tip an atomic.

- dex/lexi/lexi.go
- dex/lexi/table.go
When looking up a key that did not exist in the db, it would attempt to generate a new one, and a nil error would be returned instead of ErrKeyNotFound.
> lexi: Avoid generating key when reading

- .dockerignore
- client/Dockerfile
- client/Dockerfile.release
- client/entrypoint.sh
Obtain container IP address and set `--webaddr`, in order to allow `http` access to port `5758`.
> Fix webtls in Docker

- dex/testing/dcr/README.md
- dex/testing/dcr/create-vspd.sh
Use the downloaded vspd and vspadmin binaries.
closes #3083
> testing/harness/dcr: Update vspd to client/v4.0.1.

- .gitignore
- internal/libsecp256k1/README.md
- internal/libsecp256k1/build.sh
- internal/libsecp256k1/libsecp256k1.go
- internal/libsecp256k1/libsecp256k1_test.go
- run_tests.sh
Add a c library that has some primitive cryptographic functions needed for working with adaptor signatures.
part of #2754
> internal: Add libsecp256k1 c library.

- .gitignore
- internal/cmd/xmrswap/README.md
- internal/cmd/xmrswap/example-config.json
- internal/cmd/xmrswap/main.go
> xmrswap: Work on testnet.

- client/mm/libxc/binance.go
- client/mm/mm.go
Return the actual error message from Binance so it prints properly on the UI.
> libxc/binance: Better error message

- client/mm/libxc/binance.go
- client/mm/libxc/binance_test.go
Since the conversion from MATIC -> POL (#2957), the symbol conversion for polygon and polygon tokens was not working properly. This is fixed.
> libxc/binance: Fix polygon symbol conversion

- client/mm/exchange_adaptor.go
- client/mm/exchange_adaptor_test.go
- client/mm/mm.go
The balance handling was incorrectly handling situations where multiple matches in the same order shared a swap or redemption transaction. For example if there were three matches which redeemed 1 DCR each using the same transaction, the balance handling would think that 9 DCR was redeemed instead of 3.
> mm: Fix balance handling for shared txs across matches

- client/mm/config.go
- client/mm/exchange_adaptor.go
- client/mm/exchange_adaptor_test.go
The market making code did not account for the multi split buffer when determining the orders to place. This caused the btc and dcr wallets to error when the bot had insufficient funds.
Closes #3130
> mm: Account for mult split buffer when making MultiTrade

- client/asset/eth/eth.go
- client/asset/interface.go
I've noticed UI breaks in the following scenario:
- Ethereum/Polygon transaction gets stuck 
- user action is requested in UI suggesting to bump transaction fee
- I didn't do anything about this user action (eventually clicked "keep waiting") but transaction got mined on its own
- and then UI broke with the following error in console:
looking through the relevant code it seems we are **requesting** action while we should **resolve** action instead, which is what I've done in this PR
> client: eth, fix user action resolution handling

- client/comms/wsconn.go
All of the surrounding code suggests that we want to continue on error with initial connect unless reconnect is off. We are also already logging the error. So, do not return error for some connect failures.
closes #3180
> wsconn: Ignore some connect errors.

- client/asset/btc/btc.go
- client/asset/btc/spv_wrapper.go
use a more straightforward return value
> refactor: use a more straightforward return value

- tatanka/client/trade/README.md
- tatanka/client/trade/compat.go
- tatanka/client/trade/compat_test.go
- tatanka/client/trade/match.go
- tatanka/client/trade/match_test.go
- tatanka/tanka/swaps.go
This should give us some direction for how trading will work.
> tatanka/trade: add order compatibility and matching functions

- client/cmd/bisonw-desktop/go.mod
- client/cmd/bisonw-desktop/go.sum
- dex/testing/loadbot/go.mod
- dex/testing/loadbot/go.sum
- go.mod
- go.sum
This modifies the main module to require the latest secp256k1/v4@v4.4.0 release which includes the necessary `xmrswap` updates instead of a development version and tidies all modules in the repository to ensure they are hoisted forward accordingly.
> multi: Update secp256k1 to 4.4.0.

- client/core/core.go
Swap fees are dictated by the server so the local wallets suggestion does not need to be considered when estimating fees in SingleLotFees.
This changes leaves the code matching its comment, and also matching how fees are calculated/estimated in other places (e.g. PreOrder)
> core: Don't use wallet for swap fee estimate.

- client/cmd/assetseed/main.go
closes #3108
It doesn't seem the seed works with bitcoin core, is there anything we can do to make the output more useful? I tried using it with "sethdseed" but it says it is invalid.
> assetseed: Update to work with mnemonic.

- client/asset/firo/firo.go
Firo Electrum is a dex "external" wallet. While testing dex `basic-MM` for a set of Simnet harnesses and electrum firo wallets on DCR-FIRO it was noticed that Firo placements were not able to be funded. This was the tested on `bison.exchange` **mainnet** and the same was observed.
```sh
2025-02-26 09:06:15.137 [DBG] CORE[firo]: Attempting to fund a multi-order for firo, maxFeeRate = 20
2025-02-26 09:06:15.152 [INF] CORE: FundMultiOrder only funded 0 orders out of 3 (options = map[])
```
> mm,client,firo: Fix Electrum Firo mm issues.

- dex/lexi/db_test.go
- dex/lexi/index.go
- dex/lexi/lexi.go
- dex/lexi/table.go
- tatanka/client/mesh/mesh.go
- tatanka/db/bonds.go
- tatanka/db/db.go
- tatanka/db/reputation.go
This adds a new type `lexi.KV` to be used for key and value arguments to lexi. `KV` is just defined as an `interface{}`, but must be one of a handful of types parseable by `parseKV`. This extends and replaces the `IndexBucket` that was used for iteration prefixes. 
This approach is sloppier, and relies on the caller to ensure their arguments are of an appropriate type, but negates the necessity of `lexi.B` for conversion of `[]byte` everywhere, and really just makes using lexi easier to use, which I'm all for. A argument-type mistake reaching production would be a panic-worthy event anyway, imho.
> lexi: add KV argument type

- client/asset/eth/multirpc_test_util.go
- client/asset/zec/regnet_test.go
- client/tor/tor_live_test.go
- dex/lexi/db_test.go
- server/noderelay/noderelay_test.go
`TempDir()` is a method introduced in Go 1.15 for `testing.T`. It automatically creates a temporary directory and cleans it up after the test is complete, eliminating the hassle of manually handling errors and cleanup.  More detail about TempDir  https://pkg.go.dev/testing#B.TempDir
> refactor: use t.TempDir() instead of os.MkdirTemp

- client/webserver/site/src/js/charts.ts
I'm not certain why this was ever commented out, but this was a nice feature.
> ui: show line for rate input value on depth chart

- client/asset/eth/eth.go
- client/asset/eth/txdb.go
- client/asset/eth/txdb_legacy.go
- client/asset/eth/txdb_legacy_test.go
- client/asset/eth/txdb_test.go
- dex/lexi/db_test.go
- dex/lexi/index.go
- dex/lexi/table.go
```
lexi: Add unique index support
- Implements unique index creation for tables
- Prevents insertion of duplicate entries on unique indexes
- Supports replacement of existing conflicting entries when `Set`
is called with `WithReplace`
```
```
eth: Migrate transaction DB to Lexi
- No functional changes, but this is needed for various upcoming features
- On `Connect`, if a legacy DB is found, all the entries are inserted into
a new Lexi DB, and the legacy DB is deleted.
```
This is required for both bridging and gasless redeems.
> eth: Migrate transaction DB to Lexi 

- client/core/core.go
- client/core/notification.go
- client/mm/config.go
- client/mm/exchange_adaptor.go
- client/mm/exchange_adaptor_test.go
- client/mm/mm.go
- client/mm/mm_arb_market_maker.go
- client/mm/mm_arb_market_maker_test.go
- client/mm/mm_basic.go
- client/mm/mm_basic_test.go
- client/mm/mm_simple_arb.go
- client/mm/mm_simple_arb_test.go
- client/rpcserver/handlers.go
- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/webserver.go
- dex/utils/generics.go
This diff updates the market maker to listen for updates to the server config. If the lot size of a market that a bot is currently trading on is updated, the number of placements that the bot makes is updated so that the bot places as many lots as possible without exceeding the amount that was placed before the lot size update.
Additionally, the lot size is now saved with the `BotConfig`. An additional `overrideLotSizeChange` parameter is added to `StartBot`, which if false, will return an error if the lot size has changed since the bot was configured. This will allow the UI to prompt the user to either update their configuration, or continue with the old one even though the lot size has changed.
> mm: Handle market params update

- client/asset/bch/spv.go
- client/asset/btc/btc.go
- client/asset/btc/btc_test.go
- client/asset/btc/coin_selection.go
- client/asset/btc/coinmanager.go
- client/asset/btc/electrum.go
- client/asset/btc/electrum_client.go
- client/asset/btc/electrum_client_test.go
- client/asset/btc/redemption_finder.go
- client/asset/btc/rpcclient.go
- client/asset/btc/spv.go
- client/asset/btc/spv_scan_filters.go
- client/asset/btc/spv_test.go
- client/asset/btc/spv_wrapper.go
- client/asset/btc/wallet.go
- client/asset/dcr/dcr.go
- client/asset/ltc/ltc.go
- client/asset/ltc/spv.go
This PR is an improved version of https://github.com/decred/dcrdex/pull/2636.
1. Add an `ExchangeWalletCustom`
2. Revert changes in https://github.com/decred/dcrdex/commit/d7a54886f062d0916f1f4da64c85f9470246b0bf
3.  [expose spv scanFilters method](https://github.com/decred/dcrdex/commit/b367a55c47b17f69e7f0806dbcc975323ec799e2)
4. Export `btc.Wallet` methods. This aligns with the existing pattern - `dcr.Wallet` methods are exported. Custom wallets would now implement the `btc.Wallet` interface directly. 
6. Expose dcr wallet options.
Each of these changes is in a separate commit to ease review. 
Other related commit:  https://github.com/decred/dcrdex/pull/1227/files#diff-cd95defa7320b76287f90152b40ee5ec5edec59ca9af2eb9579ecda539ece20a
> multi: Add ` ExchangeWalletCustom` to support external btc-clone wallets

- client/asset/eth/eth.go
- client/asset/interface.go
- client/mm/exchange_adaptor.go
- client/mm/exchange_adaptor_test.go
- client/mm/mm_basic.go
- dex/testing/loadbot/mantle.go
- dex/testing/loadbot/sidestacker.go
- dex/testing/loadbot/sniper.go
- dex/txfee/feefetcher.go
- dex/utils/generics.go
In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
> refactor: use the built-in max/min to simplify the code

- client/asset/dcr/spv.go
- client/asset/dcr/spv_mixing.go
> client/dcr: Create new syncer on Run error.

- tatanka/client/mesh/mesh.go
- tatanka/client/mesh/trade.go
- tatanka/client/orderbook/orderbook.go
- tatanka/client/orderbook/orderbook_test.go
- tatanka/tanka/swaps.go
This applies review from #3194
It was suggested the orders would be "push" oriented. So, a user will be listening for new users and send them their orders periodically along with separate order updates that are very small. The signature is no longer stored as we expect listeners to catch messages directly from other peers. The order id is now just the peerID and a nonce. This is simple and allows an order to be found by update easily. Update is now a separate method.
> tatanka: Update orderbook for push data.

- client/webserver/site/src/js/forms.ts
closes #2724
Another solution is to use this hack https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript/33928558#33928558
It's probably best for the user to run on localhost or with the --webtls flag if they want to use the clipboard from a remote location.
> client/site: Hide copy button on unsecure connection.

- client/asset/bch/spv.go
- client/asset/btc/btc.go
- client/asset/btc/electrum_client.go
- client/asset/btc/rpcclient.go
- client/asset/btc/spv_test.go
- client/asset/btc/spv_wrapper.go
- client/asset/btc/wallet.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dcr/rpcwallet.go
- client/asset/dcr/spv.go
- client/asset/dcr/spv_test.go
- client/asset/dcr/wallet.go
- client/asset/interface.go
- client/asset/ltc/spv.go
- client/asset/zec/transparent_rpc.go
- client/asset/zec/zec.go
- client/core/core.go
- client/core/core_test.go
- client/webserver/api.go
- client/webserver/live_test.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/js/forms.ts
- client/webserver/site/src/js/wallets.ts
- client/webserver/webserver.go
- client/webserver/webserver_test.go
Closes #2662
Alternative to #2685
Marks used addresses. Doesn't show tx info on the deposit form, but does show the used address indicator when the tx is seen.
> multi: check for used addresses

- .github/workflows/README.md
- .github/workflows/build-snap.yml
- .gitignore
- client/cmd/bisonw-desktop/README.md
- client/cmd/bisonw-desktop/pkg/common.sh
- client/cmd/bisonw-desktop/pkg/pkg-debian.sh
- client/cmd/bisonw-desktop/pkg/pkg-snap.sh
- client/cmd/bisonw-desktop/pkg/prepare-snap.sh
- client/cmd/bisonw-desktop/pkg/publish-snap.sh
- client/cmd/bisonw-desktop/snap/local/snapcraft.yaml.in
- client/cmd/bisonw-desktop/src/bisonw.svg
- client/cmd/bisonw-desktop/src/org.decred.dcrdex.desktop
- client/cmd/bisonw-desktop/src/org.decred.dcrdex.metainfo.xml
This PR adds configuration, build scripts and Github workflow to build the Snap package and publishing it in the [Snap Store](https://snapcraft.io/store).
The snap build uses the .deb package.  The PR also contains a few fixes/improvements in the deb build:
*   Icons: added SVG icon for hicolor and symbolic variations, fixed 128px PNG to match official version
*   icon install location changed to /usr/share/icons which is the XDG standard
*  binary installs in /usr/bin directly (this is standard practice, simplifies deb scripts)
*   added AppStream metainfo file (for GNOME/KDE/Ubuntu software centers and the snap)
> dexc-desktop: Snap package

- client/asset/dcr/spv.go
closes #3240
The wallet config was changed from Disabled to Enabled, so we pass true now instead of the default of false.
> dcr: Enable mixing for v5 wallet.

- client/asset/dcr/coin_selection_test.go
In the Go 1.21 standard library, a new function has been introduced that enhances code conciseness and readability. It can be find  [here](https://pkg.go.dev/slices@go1.21.1#Equal).
> refactor: use slices.Equal to simplify code

- client/asset/btc/btc.go
- client/asset/btc/electrum.go
The transaction db for firo electrum wallets was not being created because the firo electrum wallet does not supporting listing onchain history. This was a bug. The db should have been created, but only the syncing of historical transactions should have been disabled.
Closes #3247
> firo: Fix electrum wallet tx db panic

- client/asset/btc/electrum.go
- client/asset/btc/electrum_client.go
Fixed GetBlockHash to handle Firo's 120-byte block header. Previously, it deserialized a hex string and re-serialized it in Bitcoin's 80-byte format before double SHA-256 hashing, causing issues with Firo. Now, the hex string is converted to bytes and hashed.
> electrum: Fix GetBlockHash for Firo compatibility

- client/core/bookie.go
- client/mm/exchange_adaptor.go
- client/mm/mm_arb_market_maker.go
- client/mm/mm_basic.go
- client/mm/mm_simple_arb.go
closes #3097 
For core were were handling this correctly:
https://github.com/decred/dcrdex/blob/8ecd2ea3bfad93a97a4602ec064c978bda9d1878/client/websocket/websocket.go#L260-L264
However in mm we were not checking if the feed is closed. It can be closed when the market is shut down or when the cert is updated? Unsure if that is handled correctly, but it could possibly panic.
It could also potentiality close on send if the channel is blocking, but I think this is a mistake. The close is there in case the caller did not call Close but the docs say that the caller MUST call close, so I don't think we need to check. The problem will be that the channel is blocking with a 256 buffer, so we need to see that error log and do something about it if it happens.
> multi: Check book feed isn't closed.

- client/asset/btc/electrum.go
- client/core/wallet.go
- client/db/bolt/db.go
There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
> refactor: use slices.Contains to simplify code

- client/asset/firo/block_deserialize.go
- client/asset/firo/firo.go
- client/asset/firo/regnet_test.go
- client/asset/firo/tx_deserialize.go
- dex/networks/firo/params.go
- docs/wiki/Home.md
Fix: #3252
De-serialize:
- header: for either regtest, mainnet or testnet
- minimally: all Firo transaction types to reach the start of the next transaction in a block stream.
- fully: Normal transparent transactions
Return de-serialized header and any Normal transparent
transactions as wire.MsgTx's
> client: Deserialize Firo blocks from wire bytes

- dex/ws/wslink.go
- tatanka/client/conn/conn.go
- tatanka/client/conn/conn_live_test.go
- tatanka/client/mesh/mesh.go
- tatanka/client_messages.go
- tatanka/cmd/tatanka/main.go
- tatanka/mj/types.go
- tatanka/tatanka.go
- tatanka/tatanka_test.go
- tatanka/tcp/client/client.go
- tatanka/tcp/server.go
Starts some groundwork on making the client connection to the mesh more robust.
- Adds an http request to the tatanka node that allows clients to fetch its whitelist.
- Client connection maintains two connections to the mesh, one primary and one secondary.
- The primary connection is used for sending messages and subscribing to topics. The secondary connection is maintained for quick failover.
- Updates the client connect request to include a set of initial subscriptions.
- Adds a UpdateSubscriptions request to update all the subscriptions of a client in a single request. This is useful when upgrading the secondary connection to the primary connection.
- The `conn.MessageHandlers` tatanka request and peer request handlers are updated to include a respond function to avoid having to look …
> tatanka: Improve client connection maintenance

- client/cmd/bisonw-desktop/app.go
- client/cmd/bisonw-desktop/app_darwin.go
- client/cmd/bisonw-desktop/go.mod
- client/cmd/bisonw-desktop/go.sum
- client/cmd/bisonw-desktop/main.go
- client/webserver/site/src/js/notifications.ts
- client/webserver/site/src/js/registry.ts
This PR upgrades the existing `macdrive` to `darwinkit` with some refactoring.
`Darwinkit` is the new implementation of MacOS libraries in Go and it removed/updated a lot of the existing methods in the previous go library.
Also, there have been changes in how certain types behave, e.g webview (It refuses to load until is is put into a window, this particular behavior causes a white screen until the page is fully loaded)
Before now, this is what I did:
1. Load the webview.
2. The webview delegete method: `WebViewDidFinishNavigation` is triggered by webview when it has finished loading the URL and then we create the window and put the webview inside of it to avoid the white screen.
But now we have to create the webview, put it inside the window and let it load.
Other changes:
1. Open …
> multi: Update macdrive -> Darwinkit

- client/asset/btc/btc.go
- client/asset/dash/dash.go
- client/asset/dcr/dcr.go
- client/asset/dcr/dcr_test.go
- client/asset/dgb/dgb.go
- client/asset/doge/doge.go
- client/asset/eth/eth.go
- client/asset/firo/firo.go
- client/asset/interface.go
- client/asset/polygon/polygon.go
- client/asset/zcl/zcl.go
- client/asset/zec/zec.go
- client/core/core.go
- client/rpcserver/handlers.go
- client/webserver/live_test.go
Existing wallets aren't having default settings set when loading. The settings are only saved when creating or re configuring. This checks every load that the wallet has all defaults.
> client: Always set default config values.

- client/mm/config.go
- client/mm/exchange_adaptor.go
- client/mm/exchange_adaptor_test.go
- client/mm/mm.go
- client/mm/mm_arb_market_maker.go
- client/mm/mm_arb_market_maker_test.go
- client/mm/mm_simple_arb.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/html/mmsettings.tmpl
- client/webserver/site/src/js/mm.ts
- client/webserver/site/src/js/mmsettings.ts
- client/webserver/site/src/js/registry.ts
```
This diff updates the market maker to attempt to reallocate available funds
to bots before doing a deposit or a withdrawal. For example, if a deposit
is required, and the user has additional available funds on the CEX that are
not allocated to any bots, funds will be allocated to the bot on the CEX
and unallocated from the bot on the wallet to simulate a deposit. Bots may
be configured to only attempt these "internal transfers", to attempt both
internal and external transfers, or to do no rebalancing at all.
```
> mm: Internal transfers

- client/core/account.go
- client/core/core.go
- client/core/locale_ntfn.go
- client/core/notification.go
- client/webserver/site/src/js/markets.ts
When a DEX account is disabled or enabled, it could cause stale data/state to be displayed on the market page/other pages since there's no feedback on the action carried out.
This PR adds a notification for account status toggles. Once the FE receives this notification, user data is retrieved, and the market page is refreshed to reflect the current state.
This is an extension of the fix introduced in https://github.com/decred/dcrdex/pull/3037.
> multi: send notifications for change in DEX account status

- tatanka/client/conn/conn.go
- tatanka/client/mesh/mesh.go
- tatanka/client/mesh/trade.go
- tatanka/client/orderbook/orderbook.go
- tatanka/client/orderbook/orderbook_test.go
- tatanka/client/trade/compat.go
- tatanka/client/trade/match.go
- tatanka/client/trade/match_test.go
- tatanka/client_messages.go
- tatanka/mj/types.go
- tatanka/tanka/swaps.go
> tatanka: Use orderbook.

- client/webserver/api.go
- client/webserver/site/src/html/bodybuilder.tmpl
- client/webserver/site/src/html/settings.tmpl
- client/webserver/site/src/js/app.ts
- client/webserver/site/src/js/settings.ts
- client/webserver/site/webpack/common.js
- client/webserver/template.go
- client/webserver/types.go
- client/webserver/webserver.go
- client/webserver/webserver_test.go
This PR introduces a new API endpoint to ensure a consistent reporting of the Bison Wallet build ID.
Closes https://github.com/decred/dcrdex/issues/3088
> multi: add `/buildinfo` endpoint and refactor

- client/app/config.go
- client/app/version.go
- client/cmd/bisonw-desktop/pkg/pkg-darwin.sh
- client/cmd/bisonw-desktop/pkg/pkg-debian.sh
- client/cmd/bisonw-desktop/pkg/windows-msi/BisonWallet.wxs
- client/cmd/bisonw-desktop/winres.json
- client/cmd/bisonw/winres.json
- client/cmd/bwctl/version.go
- client/webserver/webserver.go
- client/webserver/webserver_test.go
- docs/RELEASE-CHECKLIST.md
- pkg.sh
- server/cmd/dcrdex/version.go
According to the note for maintainers in client/app/version.go and similar files:
> // - Update the Version variable below on the master branch to the next
//   expected version while retaining a pre-release of 'pre'
This PR updates app versions to the next expected version of `1.0.4` with a `-pre` suffix.
Closes https://github.com/decred/dcrdex/issues/3288
> multi: bump app version(s)

- dex/logging.go
- dex/utils/generics.go
- server/asset/driver.go
Optimize code using a more modern writing style.
> refactor: use maps.Copy for cleaner map handling

- client/asset/eth/eth.go
- client/asset/eth/eth_test.go
- client/asset/interface.go
- client/core/trade.go
- dex/testing/eth/harness.sh
There was a problem reported with an init was sent twice. This was due to a nonce issue. This pr ignores that and attempts to prevent a second init being sent regardless. ~It currently doesn't work because I'm unsure how to get the txid of the swap and server wants that. I think @martonp said something about this being possible before, by examining the data from tx history, but unsure. Or we could just fail, which seems like a waste. Or change the server logic.~
> multi: Keep trying init with the same secret.

- internal/adaptorsigs/dleq.go
- internal/adaptorsigs/dleq_test.go
Resolves intermittent failures in the `VerifyDLEQ` function where it would incorrectly report that ed25519 points do not match.
The root cause of the bug was an improper conversion of point coordinates from `*big.Int` (used by `dcr/dcrec`) to the fixed-size little-endian byte arrays required by the `filippo.io/edwards25519` library.
The `(*big.Int).Bytes()` method returns a variable-length big-endian slice that omits leading zeros. The previous code reversed this variable-length slice directly. This process is only correct by chance if the coordinate's value is large enough to occupy all 32 bytes. For smaller values, the resulting byte slice was not a valid 32-byte little-endian representation, causing the point comparison to fail.
This commit introduces a `bigIntToLittleEndian32` helper …
> internal/adaptorsigs: Correct endianness conversion for DLEQ verification

- client/mm/exchange_adaptor.go
Fixes a race causing a test failure in #3300
https://github.com/decred/dcrdex/actions/runs/15932258777/job/44943955714?pr=3300
> exchange_adaptor: Fix withdrawal amount race.

- client/mm/event_log.go
- client/mm/event_log_test.go
- client/mm/exchange_adaptor.go
- client/mm/exchange_adaptor_test.go
Updates the run end time along with each event update in order to avoid having a nil end time if the process is killed during a market making run.
Closes #3227
> mm: Update run end time after each event

- dex/lexi/db_test.go
- dex/lexi/index.go
- dex/lexi/lexi.go
Adds the ability to upgrade, add, and delete indexes in the lexi db. Instead of using the `Table.AddIndex` function to create indexes, the indexes are configured when creating a table using the `TableCfg` type below. This is needed in order to be able to upgrade the ETH transaction db to support user ops.
``` golang
// IndexCfg is the configuration for an index.
type IndexCfg struct {
// Version is the version of the index. If a different version is passed
// in since the last time the table was created, the index will be
// re-created. FBytes must be used if an index is being upgraded.
Version uint32 `json:"version"`
// Unique is whether the index is unique. If true, the index will not allow
// duplicate values. If you attempt to add an entry that would create a
// duplicate in the …
```
> lexi: Upgrade, add, and delete indexes

- client/webserver/api.go
Previously the entire certificate was being passed as a string, causing core to think it was the file path of the certificate.
Closes #3309
> client/webserver: Pass cert as []byte to RedeemPrepaidBond

- dex/lexi/db_test.go
- dex/lexi/index.go
- dex/lexi/keyprefix.go
- dex/lexi/lexi.go
- Gets rid of the upgrade function and exposes GetDBVersion and SetDBVersion instead.
- Adds a badger.Txn argument to DeleteIndex and ReIndex to be able to do an upgrade and change the DB version in the same transaction.
- Moves db version to the reserved prefixes.
> lexi: Simplify upgrade API

- client/asset/btc/btc.go
This logging already existed in the dcr package but it was absent in btc where it is arguably much more important (btc fees are a lot more variable and have much higher real world value).
> btc: Log SingleLotRedeemFees estimates.

- client/cmd/testbinance/main.go
- client/mm/exchange_adaptor.go
- client/mm/exchange_adaptor_test.go
- client/mm/libxc/binance.go
- client/mm/libxc/binance_test.go
- client/mm/libxc/cbtypes/types.go
- client/mm/libxc/coinbase.go
- client/mm/libxc/coinbase_live_test.go
- client/mm/libxc/coinbase_test.go
- client/mm/libxc/interface.go
- client/mm/mm_arb_market_maker.go
- client/mm/mm_arb_market_maker_test.go
- client/mm/mm_simple_arb.go
- client/mm/mm_test.go
- client/webserver/locales/en-us.go
- client/webserver/site/src/html/forms.tmpl
- client/webserver/site/src/html/mmsettings.tmpl
- client/webserver/site/src/js/mmsettings.ts
- client/webserver/site/src/js/mmutil.ts
- client/webserver/site/src/js/registry.ts
This PR updates multi-hop arbitrage strategy. It replaces the previous strategy of using market orders for both legs with a combination of limit IOC in the first leg, and either a market or limit GTC for the second leg.
- Adds a `quoteQty` parameter to `Trade` that is required for market buys and optional for limit buys.
- The `quoteQty` parameter is required for limit buys in order to be able to use as much of the first leg as possible
This calculation cannot be done from the calling code, as it is not aware of the lot size.
- Add Limit IOC order type for quick executions of the first leg.
- First leg now always a Limit IOC order for quick executions, avoiding market movements before the second leg can be executed.
- Second leg: Limit GTC or Market, based on config.
- Adds a …
> mm: Multi-hop arb improvements 

- dex/lexi/db_test.go
- dex/lexi/lexi.go
Since `DB.Upgrade` was added, `DB.SetDBVersion` does not require a txn parameter.
> lexi: Remove txn parameter from SetDBVersion

- dex/lexi/db_test.go
- server/asset/btc/rpcclient.go
Replace older sort functions with slices.Sort to simplify code
> refactor: use slices.Sort where appropriate

- client/asset/btc/btc.go
- client/asset/btc/rpcclient.go
- client/asset/btc/spv_peer_manager.go
fix inconsistent function name in comment
> chore: fix inconsistent function name in comment

- client/asset/btc/electrum_client.go
- client/asset/btc/wallet.go
- client/asset/dcr/spv.go
- client/rpcserver/handlers.go
- client/webserver/locales/parse_test.go
There is a [new function](https://pkg.go.dev/slices#Sort) added in the go1.21 standard library, which can make the code more concise and easy to read.
> refactor: replace sort.Slice with slices.Sort for natural ordering

- client/db/bolt/upgrades_test.go
- server/auth/auth.go
The new version of Go has been optimized, and variables do not need to be reassigned.
For more info: https://tip.golang.org/wiki/LoopvarExperiment#does-this-mean-i-dont-have-to-write-x--x-in-my-loops-anymore
> refactor: omit unnecessary reassignment
