server/book/go.mod, server/book/go.sum, server/book/orderpq.go, server/book/orderpq_test.go
This implements a binary heap-based priority queue of orders for efficient retrieval of the "best" orders from the order book, where best means closest to market price.
For the buy side (think left side of the depth chart), where the best order is the order with the highest price rate, a priority queue with a min-oriented heap will be used.
For the sell side, where the best order is the order with the lowest price rate, a pq with a min-oriented heap will be used.
This allows accessing the best element in constant time, and other operations (delete, insert, update) in log time, although insert and update is constant time on average.  Finding the worst (i.e. min in a max heap) is a linear time search of the leaf nodes, but that operation is not needed.
The implementation is relatively …
=> book: add OrderPQ, a min or max priority queue for orders

spec/README.mediawiki
When a limit order that crosses the spread gets matched with standing orders in the book, the price rate for each match is the price rate of the standing order, not the price rate of the taker from the queue.
=> spec: correct limit-limit match price rate

spec/README.mediawiki
- Use Blake-256 instead of SHA-256 as hash function. SHA-256 was chosen because it is more ubiquitous, however, this hash function is used only internally to the server and client software. It is not required to implement blake-256 to integrate and asset.
- Remove time in force from Market order serialization.
- Move "rate" and "time in force" to end of Limit order serialization.
- Note the Fisher-Yates seed is the first 8 bytes of the hash
- fix typos and spelling
These changes pertain to the work in https://github.com/decred/dcrdex/pull/15
=> spec: use blake-256, remove market time-in-force

spec/README.mediawiki
"Taker" was incorrectly used where "maker" was intended when describing failure to initiate the swap.
Fix spelling of quantity.
Change orderbook to order book except with variable names since two
words is used throughout.
=> spec: fix maker-taker wording in failure to init scenario

server/book/book.go, server/book/book_test.go, server/book/orderpq.go, server/book/orderpq_test.go, server/order/order.go
This modifies the `Book` and `OrderPQ` types to support copying out a slice of orders in sorted order.  While just book updates will normally be served to the client, it will also be necessary to provide the full order books when clients start up or reconnect.  Further, the HTTP API will need to provide full snapshots of the order book, which it may obtain (and refresh at some interval) via these new `Book` methods: `SellOrders`, `SellOrdersN`, `BuyOrders`, and `BuyOrdersN`.
This also makes the order book capacity configurable via the constructor, and dynamically settable via the new `Realloc` method.
=> book: export and copy functions

server/asset/bip-id.go, spec/README.mediawiki
Possible solution to issues raised at https://github.com/decred/dcrdex/pull/15#discussion_r320543344
Switches ASCII ticker symbol encoding to integer IDs. For standardization, the IDs are based on BIP-0044 coin type indices from https://github.com/satoshilabs/slips/blob/master/slip-0044.md.
=> spec: asset serialization IDs based on BIP-0044

server/asset/btc/btc.go, server/asset/btc/btc_test.go, server/asset/btc/live_test.go, server/asset/btc/testing.go, server/asset/btc/tx.go, server/asset/common.go, server/asset/dcr/dcr.go, server/asset/dcr/live_test.go, server/asset/dcr/tx.go, server/asset/ltc/live_test.go
The DEXTx interface did not have a fee rate method, but fees must be verified by the swap coordinator.
For the Bitcoin backend, this adds quite a bit of time to transaction fetching, since the `btcjson.TxRawResult` does not have an `AmountIn` field like Decred does, so the transaction for each vin's previous outpoint must be fetched as well.
=> assets: add fee rate method to DEXTx

spec/README.mediawiki
Schnorr signatures require the signed message to be 32 bytes.
=> spec: switch utxo signed message to blake256 hash

server/book/go.mod, server/book/go.sum, server/market/go.mod, server/market/go.sum, server/market/integ/booker_matcher_test.go, server/matcher/go.mod, server/matcher/go.sum, server/matcher/match_test.go, server/order/order.go, server/order/order_test.go
Regarding https://github.com/decred/dcrdex/pull/47#discussion_r334299792
An explicitly-defined `UnknownOrderType` `OrderType` is desirable, especially as the zero-value `OrderType`.
=> Add the UnknownOrderType OrderType as 0x0.

AUTHORS, README.md, testing/README.md, testing/harness.sh
This adds a base simnet harness mining past SVH with ticket buying wallets as well as a reorg script. The repository organization section of the readme has also been updated with the newly added
testing folder.
Work towards #31.
=> harness: add simnet harness.

spec/README.mediawiki
JSON-RPC is not ideal for bi-directional websocket communcation, and has features which make it undesireable in general for our needs, e.g. variable-type IDs. The version field included with every request is not needed once a websocket connection is established. There is also some unneeded overhead for notifications that can potentially be eliminated if we break from a strict adherence to JSON-RPC.
This proposed messaging protocol attempts to capture the strengths of JSON-RPC, but with a structure more suited to the needs of the DEX.
=> spec: change json-rpc to custom message protocol

server/comms/msgjson/msg_test.go, server/comms/msgjson/types.go, server/market/bookrouter.go, server/market/go.mod, server/market/go.sum, server/market/routers_test.go
The router handles client subscriptions to order book data, relaying information from the order book data source (likely a market manager) to subscribed clients.
Resolves #61
=> server: add an order book subscription router

spec/README.mediawiki
The client doesn't need to disconnect to create an authenticated connection, so let them stay connected and make them wait until swapconf confirmations on their registration fee to send the 'notifyfee' request.
=> spec: don't send notifyfee until swapconf confirmations

.github/workflows/go.yml, dex/order/order.go, server/asset/btc/btc_test.go, server/asset/dcr/dcr_test.go, server/book/book.go, server/coinlock/coinlocker.go, server/coinlock/coinlocker_test.go, server/db/driver/pg/internal/matches.go, server/db/driver/pg/internal/orders.go, server/db/driver/pg/markets.go, server/db/driver/pg/matches.go, server/db/driver/pg/orders.go, server/db/driver/pg/orders_online_test.go, server/db/driver/pg/system.go, server/db/driver/pg/system_online_test.go, server/db/interface.go, server/market/integ/booker_matcher_test.go, server/market/market.go, server/market/market_test.go, server/market/orderrouter.go, server/market/routers_test.go, server/matcher/match.go, server/matcher/match_test.go, server/swap/swap.go, server/swap/swap_test.go
This implements two pieces of the `MarketTunnel` `interface`:
=> market: implement MarketTunnel

server/swap/swap.go
Resolves issue raised in https://github.com/decred/dcrdex/pull/96#issuecomment-564635387.
=> swap: account for timer inaccuracy in chainWaiter loop

spec/accounts.mediawiki, spec/admin.mediawiki, spec/comm.mediawiki, spec/fundamentals.mediawiki, spec/orders.mediawiki
This is the corresponding spec update for PR https://github.com/decred/dcrdex/pull/96
=> spec: millisecond order time stamps and epoch duration

server/book/book.go, server/book/orderpq.go, server/book/orderpq_test.go, server/market/market.go, server/market/market_test.go
This adds `(*Market).Cancelable(order.OrderID)`.
Add `epochOrders` field to `Market`.  This is somewhat inefficient since
the `currentEpoch` in `runEpochs` has the same map. However, with the
current design, there is also `nextEpoch` to consider, so `epochOrders` is
updated in `processOrder` and `processEpoch`. In the future, the `Epoch` type
can provide a `HaveOrder` method, while `Market` will have to keep the
epochs as fields with a mutex guarding them, but it's not worth it now.
book: change pq book map to key to `OrderID` (why was it ever a `string`?).
Add `(*OrderPQ).HaveOrder`.
Add `(*Book).HaveOrder`.
=> market: implement MarketTunnel.Cancelable

server/auth/auth.go, server/market/market.go, server/market/market_test.go, server/market/orderrouter.go, server/market/routers_test.go
This addresses the same mistake that was fixed in swap in https://github.com/decred/dcrdex/pull/106.
=> multi: Now().Round -> Now().Truncate

dex/order/match_test.go, dex/order/order.go, dex/order/order_test.go, dex/order/test/helpers.go, server/book/book_test.go, server/coinlock/coinlocker.go, server/db/driver/pg/matches.go, server/db/driver/pg/orders.go, server/db/driver/pg/orders_online_test.go, server/db/driver/pg/testhelpers_test.go, server/db/interface.go, server/db/testhelpers_test.go, server/market/integ/booker_matcher_test.go, server/market/market.go, server/market/market_test.go, server/market/orderrouter.go, server/market/routers_test.go, server/matcher/match.go, server/matcher/match_test.go, server/swap/swap.go, server/swap/swap_test.go
A change to the order structs to embed a type called `Trade` with common field for limit and market orders. This cleans up `Order` interface so there is now only one method that accesses non-prefix data.
=> order: add Trade struct

client/comms/wsconn.go, client/comms/wsconn_test.go, client/core/core.go, client/core/core_test.go, client/core/types.go, client/db/bolt/db.go, client/db/bolt/db_test.go, dex/msgjson/types.go
This incorporates the db and comms package functionality into client core application. This PR should hopefully add some clarity to the client structure and enable concurrent work. @dnldd can add in order book handling. @JoeGruffins can implement an RPC server that uses the core. I'll start into authentication via web interface.
All the core does right now is list the available markets, but I think future work can be done independently in the following rough categories.
1. Order book subscription management
2. Registration and authentication
3. Order management
4. Data access
Eventually reconnect handling and match auditing too.
=> client/core: put the core together

spec/README.mediawiki, spec/accounts.mediawiki, spec/admin.mediawiki, spec/api.mediawiki, spec/atomic.mediawiki, spec/comm.mediawiki, spec/community.mediawiki, spec/fundamentals.mediawiki, spec/orders.mediawiki
Added select subsection links beneath their section link on the landing page. Also repositions the table of contents for each section below the section header. Since we paginated, we are able to upgrade the section headers 1 level. This enables one move level of table of contents navigation, though it's not used yet.
Moves the message-rate, timestamp, and coin ID subsections to a new encoding subsection on the comms page. 
[Quick Link](https://github.com/buck54321/dcrdex/blob/specheaders/spec/README.mediawiki)
=> spec: upgrades headers. add subsection links to readme

dex/asset.go, server/asset/btc/btc.go, server/asset/btc/live_test.go, server/asset/btc/utxo.go, server/asset/common.go, server/asset/dcr/cache.go, server/asset/dcr/dcr.go, server/asset/dcr/dcr_test.go, server/asset/dcr/live_test.go, server/asset/dcr/tx.go, server/asset/dcr/utxo.go, server/asset/ltc/live_test.go, server/asset/ltc/ltc.go, server/auth/auth.go, server/market/market_test.go, server/swap/swap.go, server/swap/swap_test.go
Change `asset.DEXAsset` to `asset.Backend`. Also renames `dcr.DCRBackend` to `dcr.Backend`.
=> server/asset: fix asset backend stutters

server/db/interface.go, server/market/market.go, server/market/market_test.go, server/market/routers_test.go
`(*Market).processOrder` must respond to the submitter of new orders
only after updating `epochOrders` so that `Cancelable` will reflect that
the order is now in the epoch queue.
`SubmitOrderAsync` may not use order ID for logging when orders fail
validation because the `ServerTime` is not yet set.
Also, when testing order submission, set the time in the current epoch.
=> market: update epochOrders map before responding to order router

client/core/core.go, client/core/core_test.go, client/core/types.go, dex/msgjson/msg_test.go, dex/msgjson/types.go, server/comms/server.go, server/market/market_test.go, server/market/orderrouter.go, server/market/routers_test.go
This changes the `msgjson.ConfigResult` to include market variables, as proposed in https://github.com/decred/dcrdex/issues/126
Also:
- Rename `msgjson.{Limit,Market,Cancel}` to `msgjson.{Limit,Market,Cancel}Order`.
- Update `market` package tests.
-  `client/core`: Include new market variables from `msgjson.ConfigResults` in `core.Market`.  Unmarshal and unpack into `core.Market`.
-  `comms`: rename `rpcRoute` type and export to `MsgHandler`.  The `comms.Route` function is exported so it make senses that the type of each input argument should be exported too, if for no other reason than published documentation.
I intend to implement the `config` route (of the new `comms.MsgHandler` type) in the `dex` package in a follow-up PR if these changes work.
=> msgjson+: modify ConfigResult with Market config

server/book/book.go, server/book/orderpq.go, server/market/epoch.go, server/market/market.go, server/market/market_test.go
Duplicate order IDs in `processOrder` cannot really exist unless the
server time stamp is equal along with all the other serializable data.
This can still be checked as it is possible for this to happen, but it is
not the only check needed.
A proper duplicate order check may be done via the commitment;
this will be in another set of changes.
In the present changes, we now enforce that multiple cancel orders
targeting the same order cannot be added to the epoch queue. If not,
`ErrDuplicateCancelOrder`.
Add `EpochQueue.CancelTargets` to facilitate this check.
Further, verify that the target order is on the books or in the epoch
queue, and that the account of the `CancelOrder` is the same as the
account of the target order.  If not, `ErrInvalidCancelOrder`.
Add `(*Market).CancelableBy` to …
=> market, book: rework duplicate order detection for cancels

client/webserver/webserver.go, client/webserver/webserver_test.go
I'm unable to reproduce #149, but I'm figuring that the delay is longer than 1 ms at https://github.com/buck54321/dcrdex/blob/9318bad2f6338b0ff4984c4b1e8eea2e6ad4fdd8/client/webserver/webserver.go#L238 occasionally.
=> webserver: fix test synchronization

client/rpcserver/rpcserver_test.go
Updates **rpcserver**'s `TestClientMap` and `newTServer` as per #160.
=> rpcserver: fix TestClientMap sync

spec/atomic.mediawiki, spec/orders.mediawiki
These are the spec updates extracted from PR #145 .
`orderbook`'s `Order` obj include `com` in `epoch_order` only
Refer to the preimage as a 32-byte sequence instead of number.
fix `Order` object table and reorder fields
remove `match_data` route, other fixes
=> spec: various orderbook tweaks

client/order/epochqueue.go, client/order/epochqueue_test.go, dex/msgjson/types.go, dex/order/order.go
This adds an epoch queue to the client with match proof validation. This comprises of generating the seed from the first 64-bits of sorted and concatenated epoch order preimages and generating the commitment checksum from the sorted and concatenated epoch order commitments.
This will be rebased and updated to use the types defined in #145 when that's ready.
=> multi: add client epoch queue.

client/rpcserver/rpcserver.go, client/rpcserver/rpcserver_test.go
Use ports different from other tests. Retrieve ports with sync/atomic.
Try three times for an open port.
Tests are passing 10/10 for me now.  I think I was using the same ports as another test. Changing the ports. To be extra safe be cautious of concurrency issues when retrieving ports, in case tests are run in parallel, and try three times for an open port, incrementing by 3.
=> client/rpcserver: Fix port race

client/webserver/webserver.go, client/webserver/webserver_test.go
Creating listeners in New causes those resources to be locked up until
Run is called. Prevent this by creating listeners in Run.
=> client/webserver: Create listeners in Run

client/asset/dcr/config.go, client/asset/dcr/dcr.go
This changes the `DCRConfig.RPCCert` field config tag to `"rpccert"` since that is the dcrwallet setting for it's RPC certificate, whereas `"cafile"` refers to dcrd's cert.
This also changes the call to `rpcclient.Client.Connect` in `(*ExchangeWallet).Connect` so it does not retry on failure.  This is necessary to see many config errors.  Auto-reconnect is unrelated.
=> client/asset/dcr: RPC cert is rpccert, not cafile

server/auth/auth.go
interestingly, auth.Send is a valid value even when `auth` is `nil`, presumably because it's still a function just with a nil receiver.  The problem was that the receiver was still nil.
This caused the following panic (line numbers apply to commit [ce0a64179425a18ed844d27f1576432ac7551314](https://github.com/decred/dcrdex/tree/ce0a64179425a18ed844d27f1576432ac7551314/server)):
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x85254b]
goroutine 68 [running]:
sync.(*RWMutex).RLock(...)
/home/jon/go113/src/sync/rwmutex.go:48
decred.org/dcrdex/server/auth.(*AuthManager).user(0x0, 0xc1ed571e829157f5, 0x56adcacbb60063c0, 0x6e332c39b14d8edc, 0x1d8c77b52a58074c, 0x0) …
```
=> server/auth: AuthManager's coinWaiter had a bad AuthManager

client/core/core.go
In a short lived client test app I noticed that DB writes would be missing on the next run.  This seems to be if the the `Core` shutdown does not also wait for bbolt DB shutdown while their are pending/in-progress writes.  The db's `Run` method waits for context cancellation and then closes the bbolt DB. Using this instead of `ctx.Done` in `Core.Run`.
=> client.Core needs to wait for DB to close

dex/testing/dcr/harness.sh
Bug snuck in with #191. Decred test harness wallet and node now share a certificate.
=> client/asset/dcr: add rpccert entry to harness wallet config

client/core/core.go, client/core/core_test.go, client/order/epochqueue.go, client/order/epochqueue_test.go, client/order/orderbook.go
This adds the `epoch_order` notification handler to the client core.
=> core: handle epoch order messages.

client/comms/wsconn.go, client/comms/wsconn_test.go, client/core/core.go
`wsConn` reconnect tweaks and logging.
supervise all goroutines, using an internal context and cancellation function.
Remove unused `wsConn.sendCh` field.
Allow `(*wsConn).MessageSource` to return the channel repeatedly, and
document this.  Also close this channel when `wsConn` shuts down to signal
to the consumer that the conn is dead (if they didn't kill it).
Only queue reconnection in keepAlive, not `connect` or `Connect`. Previously the number of reconnects queued would grow exponentially because `connect()` was queueing reconnect on `Dial` failure.
=> client/comms: refactoring

client/comms/wsconn_test.go, client/rpcserver/rpcserver_test.go, client/rpcserver/websocket.go, client/webserver/webserver_test.go, client/webserver/websocket.go, dex/ws/wslink.go, server/auth/auth.go, server/comms/comms_test.go, server/comms/server.go, server/market/market.go
This adds `WriteControl` and `SetReadDeadline` to the `ws.Connection` interface.
Use `WriteControl` in `(*WSLink).outHandler` to send a ping.
Fix some some typos, and add extra logging.
Set initial read deadline in `(*WSLink).Start`, let pong handler set subsequent deadlines.
dex/ws: Use "peer" terminology instead of "client".  Rename `ErrClientDisconnected` -> `ErrPeerDisconnected`.  Alternatively, we could clarify that `WSLink` is only intended for use by a server, and `client/comms.wsConn` is for client connections to the server.
=> dex/ws: Add WriteControl and SetReadDeadline to Connection interface

client/db/bolt/db.go, client/db/test/dbtest.go, client/db/test/types_test.go, client/db/types.go
This adds `AccountBackup` type for backup and restore functionality for user accounts.
`RandomWallet` has also been updated to use the current time for balance update times to fix an issue with `TestWallets`.
Resolves #179.
=> client/db: add account backup and restore. 

client/core/core.go, client/order/epochqueue_test.go, client/order/orderbook.go, client/order/orderbook_test.go, server/swap/swap.go
This adds the `match_proof` notification handler to the client core.
=> multi: handle match proof messages.

server/asset/dcr/dcr.go
It was previously possible to connect to a node on a network that did not match with the one specified to NewBackend.
Cherry-picked from https://github.com/decred/dcrdex/pull/193
=> server/asset/dcr: verify network of connected node

server/cmd/dcrdex/log.go
This configures the package-wide logger for `decred.org/dcrdex/dex/ws` in the `dcrdex` app.  It has been neglected.
Cherry-picked from https://github.com/decred/dcrdex/pull/193
=> dcrdex: enable logging for dex/ws package

server/db/driver/pg/internal/matches.go, server/db/driver/pg/matches.go, server/db/driver/pg/matches_online_test.go, server/db/interface.go, server/market/market_test.go, server/swap/swap.go, server/swap/swap_test.go
Resolves https://github.com/decred/dcrdex/issues/216, implements the secret-related spec changes described in https://github.com/decred/dcrdex/pull/209
db: `SaveRedeemA` also stores the swap secret
The secret is also stored in the matches table.
Although the secret is used by both redeem txns, and both are validated,
`SaveRedeemA` stores the secret.  Thus, `SwapData` now includes a
`RedeemASecret` field for the secret since A revealed the secret even if
the server heard about the secret from B's `'redeem'` request first.
pg: refactor swap data storage functions to use the new
`(*Archiver).updateMatchStmt` method which is generalized for any SQL
statement with any number of arguments, expecting to update a single
row of the matches table for a market.
swap: update for SaveRedeemA with the …
=> db,swap: store the swap secret in the matches table

client/core/core.go, client/core/core_test.go, client/core/types.go, client/core/wallet.go, client/webserver/api.go, client/webserver/webserver_test.go
Resolves #235
Moves `xcWallet` from *types.go* to *wallet.go*.
=> core: fix wallet creation sequence

client/core/core.go, client/core/core_test.go, client/core/notification.go, client/core/trade.go, client/core/types.go, client/db/bolt/db.go, client/db/bolt/db_test.go, client/db/interface.go, client/db/test/dbtest.go, client/db/types.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/site/src/css/application.scss, client/webserver/site/src/css/main.scss, client/webserver/site/src/css/main_dark.scss, client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/js/app.js, client/webserver/site/src/js/charts.js, client/webserver/webserver.go, client/webserver/webserver_test.go, client/webserver/websocket.go
Adds a client notification system. **core** defines the interface, but the methods are implemented by the `db.Notification` type. **core** then defines concrete types that may or may not carry auxiliary information beyond the persistent db data.
Notifications above a certain "severity" are stored in the database. `(*Core).Login` now returns a list of the 10 most recent notifications for the browser to cache.
The browser uses `Window.localStorage` to store the most recent notifications and prevent extraneous requests when multiple tabs are used. As a demonstration of the usage of notifications in the browser, the current order table on the markets page is now updated live.
Closes #218
=> core/webserver: client notification system

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go
The utxo length check in the `Fund` loop was in the wrong spot.
=> client/asset: fix zero-utxo bug

server/asset/btc/btc.go, server/asset/btc/live_test.go, server/asset/common.go, server/asset/dcr/cache.go, server/asset/dcr/dcr.go, server/asset/dcr/dcr_test.go, server/asset/dcr/live_test.go, server/market/market_test.go, server/market/routers_test.go, server/swap/swap.go, server/swap/swap_test.go
At least resolves (only partially) #115, because connection errors are now communicated.
Adds **server/asset** `BlockUpdate` type that conveys errors and reorgs.
=> server/asset: switch to polling for dcr backend block notifications

client/rpcserver/handlers.go, client/rpcserver/handlers_test.go, client/rpcserver/rpcserver.go, client/rpcserver/rpcserver_test.go, client/rpcserver/types.go, client/rpcserver/types_test.go, client/rpcserver/websocket.go, dex/msgjson/types.go
Add init, newwallet, openwallet, and wallets routes.
~Change command arguments to a slice of strings.~ <- Implemented in another pr.
=> client/rpcserver: Add wallet routes

client/webserver/live_test.go, client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/js/app.js, client/webserver/site/src/js/basepage.js, client/webserver/site/src/js/doc.js, client/webserver/site/src/js/forms.js, client/webserver/site/src/js/http.js, client/webserver/site/src/js/login.js, client/webserver/site/src/js/notifications.js, client/webserver/site/src/js/register.js, client/webserver/site/src/js/settings.js, client/webserver/site/src/js/state.js, client/webserver/site/src/js/wallets.js
Creates a series of page classes that inherit from a `BasePage` class. Each page is moved to its own module. Common functions and constants are also organized into new or existing modules. 
This PR does not move or fully refactor the handling for the markets page. I'd like to follow up with that in a separate PR that focuses on /markets.
No substantive changes, but a couple of bug fixes and a bit more documentation.
=> webserver: reorganize and refactor javascript

client/db/test/dbtest.go
DB only stores severity >= `Success`, so `RandomNotification` should stick to that range.
=> client/db: don't use low severity level for randomized db tests

dex/btc/script.go, dex/btc/script_test.go, dex/dcr/script.go, dex/dcr/script_test.go, server/asset/btc/btc.go, server/asset/btc/testing.go, server/asset/btc/utxo.go, server/asset/common.go, server/asset/dcr/config.go, server/asset/dcr/dcr.go, server/asset/dcr/dcr_test.go, server/asset/dcr/live_test.go, server/asset/dcr/utxo.go, server/market/orderrouter.go
This addresses an issue where coins (UTXOs) with non-standard pkScripts
or redeem scripts for P2SH could be accepted as valid funding coins.
**dex/{btc,dcr}**: `ExtractScriptAddrs` indicates non-std scripts
`SpendInfo` includes a `NonStandardScript bool` field.  This allows the
`InputInfo` function to convey this state to the caller.
**server/asse**t: `FundingCoin` errors for non-std script coins
`{dcr,btc}.(*Backend).FundingCoin` now returns a "non-standard script"
error if the coin's pkScript or redeem script are non-standard.
The `{dcr,btc}.UTXO` type now has a `nonStandardScript bool` field.
`{dcr,btc}.(*Backend).utxo` sets `UTXO.nonStandardScript`.
`{dcr,btc}.(*UTXO).Auth` returns an error if the script is non-standard or
the number of required keys is zero. …
=> dex/dcr: detect non-standard scripts, like swap contracts

dex/encrypt/encrypt.go, server/admin/prompt.go, server/cmd/dcrdex/config.go, server/cmd/dcrdex/key.go, server/cmd/dcrdex/key_test.go, server/cmd/dcrdex/log.go, server/cmd/dcrdex/main.go
Replace the unencrypted "dexprivkey" file with an encrypted "sigkey"
file. The sigkey file is a binary encoding of the signing key and the
encryption parameters, created using encode.BuildyBytes and
encode.Crypter:
encode.BuildyBytes{0}.AddData(keyParams).AddData(encKey)
server/admin: Add PasswordHashPrompt, and modify PasswordPrompt
to retrieve the raw password string, not the hash of it.
Starting dcrdex with no existing "sigkey" file creates a new private key,
encrypts it, and stores the encrypted key along with the encryption
parameters:
```
Signing key password: {no echo}
2020-04-13 17:14:43.764 [INF] MAIN: Creating new DEX signing key file at /home/jon/.dcrdex/sigkey...
```
Subsequent startups load and decrypt the key file:
```
Signing key password: {no echo}
2020-04-13 17:14:26.060 …
```
=> dcrdex: use encrypt.Crypter for the signing key storage

server/auth/auth.go, server/auth/auth_test.go, server/cmd/dcrdex/config.go, server/cmd/dcrdex/main.go, server/dex/dex.go
Probably temporary, but it helps a lot in testing.
=> auth,dex,dcrdex: anarchy setting

client/cmd/dexc/main.go, client/cmd/dexc/ui/config.go, client/cmd/dexc/ui/config_test.go, client/cmd/dexc/ui/widgets.go
Replaced notui and web flags with tui and noweb flags. The default action for starting the dex is to no longer start the terminal ui while now starting the web server. You can still start the terminal ui with the --tui flag. You can prevent starting the web server with the --noweb flag.
=> dexc: make notui and web defaults

client/core/core.go, client/core/core_test.go
This adds the revoke_match message handler to the client core.
=> core: handle revoke match messages.

client/comms/wsconn.go, client/comms/wsconn_test.go, client/core/core.go, client/core/core_test.go, client/core/types.go, client/db/test/dbtest.go, client/db/types.go, client/rpcserver/handlers.go, client/rpcserver/handlers_test.go, client/rpcserver/rpcserver.go, client/rpcserver/rpcserver_test.go, client/rpcserver/types.go, client/rpcserver/types_test.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/site/src/css/main.scss, client/webserver/site/src/html/register.tmpl, client/webserver/site/src/js/register.js, client/webserver/webserver.go, client/webserver/webserver_test.go
Alternative to #252. Drops the *certs.json* file altogether in favor of a file upload. Saves the entire file to db. 
Standardizes to name `URL` or `url` in some places where it was previously `DEX` or `dex`.
Built on #251, so the diff you want is 
https://github.com/buck54321/dcrdex/compare/js...buck54321:certupload
UI: 
Registration form now allows opening of a file dialog to select a file. The contents of the file are sent in the preregister API call.
=> core: save entire TLS certificate

dex/testing/dcr/harness.sh
This fixes the DCR simnet chain getting stuck due to lack of voters.
=> dex/testing/dcr: make dcr harness' alpha wallet unlock and buy tickets

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/walletclient.go, client/asset/dcr/dcr.go, client/core/core.go, client/core/core_test.go, client/core/trade.go, client/db/bolt/db.go, client/db/interface.go, client/db/types.go
Reload and prepare active orders and orders with active matches, and the matches, from the database when the user signs in. Resolve the matches reported in the server's 'connect' response with the local state. Only issue errors when discrepancies are found for now, but more sophisticated handling will be needed.
Unlock wallets needed for active orders when the user signs in.
=> core: reload active orders and matches

server/auth/auth.go
Missed this `CloseAccount` call when `--anarchy` was introduced.
=> auth: do not close accounts on connect with --anarchy

server/admin/prompt.go, server/cmd/dcrdex/config.go, server/cmd/dcrdex/main.go
When the prompt for admin signing password is password, hitting `ctrl+c` does not cause the dcrdex app to exit, unless user presses enter, in effect entering an empty password. This behaviour may not be quickly obvious to users who may struggle with exiting the app from the password prompt step.
Also, propose `signingkeypass` config option to aid running dcrdex without the interactive prompt asking for signing key password. Similar to dcrwallet's `pass` option for setting wallet private passphrase in config:
https://github.com/decred/dcrwallet/blob/f5b98d7c5d089fe5e0ba47bb44bc55aaad3500e8/sample-dcrwallet.conf#L13-L19
A bit of a security concern, I wouldn't mind taking it out if it is considered too unsafe.
=> server/admin: cancel password prompt on interrupt request

server/market/orderrouter.go, server/market/routers_test.go
Incoming limit orders would not have their time-in-force set appropriately.  All of them were treated as standing.  When immediate limit orders were send from the client, this would result in an order ID mismatch on the client:
```
[ERR] CORE: Abandoning order. preimage: 70d70f6cee502f84e65c92770a47ba8ada88cd8dc28012543df0d94a75f61e3c, server time: 1588100600868: failed ID match. order abandoned
[ERR] WEB: error placing order: failed ID match. order abandoned
```
followed shortly after by a preimage request that the client could not answer (and a penalty)
```
[ERR] CORE: no active order found for preimage request for 3f233df511afb4230f0337e940cf86deb6c1a65d7f69e963392ec784db0b3d23
```
=> market: fix (*OrderRouter).handleLimit ignoring force

server/db/driver/pg/internal/orders.go, server/db/driver/pg/orders.go, server/db/driver/pg/orders_online_test.go, server/db/interface.go, server/market/market.go, server/market/market_test.go
pg: load book orders from DB
Add `BookOrders` to `db.OrderArchiver`.
Simplify `(*Archiver).ActiveOrderCoins` by removing the order type query
constraint since cancel orders already live in a separate table.
pg/internal: Add `SelectOrdersByStatus` query. Remove type constraint from
`SelectOrderCoinIDs` query since cancel orders are in separate table.
market: In `NewMarket` use `OrderArchiver.BookOrders` to get the book orders, followed by `book.Insert` to populate the book.
=> pg,market: load book orders from DB on Market construction

client/cmd/dexcctl/httpclient.go, client/comms/wsconn.go, server/comms/comms_test.go
The `ServerName` field should be set in the tls configuration for websocket clients.
=> client/comms: add servername to tls config

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/regnet_test.go, client/asset/dcr/config.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/simnet_test.go, client/asset/driver.go, client/asset/interface.go, client/cmd/dexc/go.sum, client/cmd/dexcctl/go.sum, client/core/core.go, client/core/core_test.go, client/core/wallet.go, client/webserver/live_test.go, dex/btc/config.go, dex/config/config.go, dex/config/config_test.go, go.mod, go.sum, server/asset/btc/btc.go, server/asset/btc/btc_test.go, server/cmd/dcrdex/go.sum
Resolves step 1 of https://github.com/decred/dcrdex/issues/292#issuecomment-619540709.
add config.Options() function to read key-value options from a config file or []byte data.
add config.Parse() function to populate a struct pointer with options parsed from a config file or []byte data.
config.Options() is called from `client/core.loadWallet` to read wallet connection settings from a config file path. Usage should ultimately move to `core.CreateWallet` so that the settings would be saved to db along with other wallet info.
config.Parse() is used by `client/asset/dcr` to read wallet connection settings into a DCRConfig object; and by `dex/btc` to read wallet connection (client) or backend connection (server) settings into a btc.Config object.
=> multi: implement generic parsing for ini configs

client/core/core.go, client/core/core_test.go, client/db/bolt/db.go, client/db/bolt/db_test.go, client/db/interface.go
Resolves #318 by checking if the app-wide encryption key is already set whenever `core.Initialize` is called.
The app-wide encryption key is derived and stored if it doesn't already exist, otherwise an error is returned.
=> client/core: prevent init of already initialized app

client/core/trade.go, server/db/driver/pg/internal/matches.go, server/db/driver/pg/matches.go, server/db/driver/pg/matches_online_test.go, server/swap/swap.go
When storing a match where the taker is a cancel order, store with
status `MatchComplete`, and without the maker swap address. The match
will also be flagged as inactive since there is no associated swap
negotiation.  `ActiveMatches` can now never return such a match with
a taker cancel order.
`InsertMatch` now identifies cancel orders for this handling by the taker's
order.  If the `order.Match.Taker` has a `nil` `*Trade`, the match is inserted
with the handling described above.
Internally, this allows both maker and taker addresses to remain `NULL` in
the matches table.  Scan code is modified to use `sql.NullString`.
This pertains to issue https://github.com/decred/dcrdex/issues/317#issuecomment-621967218, and resolves the "Missing matches" notification for cancel orders matches …
=> pg: cancel order matches are inactive

client/core/core.go, client/core/core_test.go, client/core/trade.go, client/core/types.go, client/db/bolt/db.go, client/db/bolt/db_test.go, client/db/interface.go
Adds a `DB` method `UpdateOrderStatus`. Updates the order status for both orders in `(*Core).negotiate`.
=> core: fix cancel order and match status updating

client/asset/btc/regnet_test.go, client/asset/dcr/simnet_test.go, client/core/core.go, client/db/test/dbtest.go, client/db/types.go, dex/btc/config.go, dex/config/config.go, dex/config/config_test.go
Resolves part 2 of #292.
I did not implement encryption of wallet settings before saving because it would make it impossible to load the wallet on dexc start; unless we chose to defer wallets loading AND unlocking to `core.Login`.
=> client/core: move cfg parsing to CreateWallet and save parsed cfg to db

client/core/core.go, client/core/notification.go
This PR primarily adds a new notification when the number of confirmation increases for the registration fee payment. 
Full list of changes:
- Reuses the same code for registration fee payment verification both during `Register` and `reFee` (re-check of the fee in case the verification wasn't completed correctly).
- By reusing the same code, the notification on success is now sent in both cases. Which wasn't happening for `reFee`.
- Adds notification when the confirmation amount increases but has not met the min requirement yet.
- Moves `confTrigger` as an internal function of `c.verifyRegistrationFee` since it is no longer being used anywhere else.
**Edit:**
Added 2 new fields to the `FeePaymentNote` notification: `ConfirmationsRequired` and `ConfirmationsReceived` so the client/frontend …
=> client/core: Add more registration notifications 

client/cmd/dexcctl/dexcctl_test.go, client/cmd/dexcctl/main.go, client/core/core.go, client/core/core_test.go, client/core/types.go, client/rpcserver/handlers.go, client/rpcserver/types.go, client/rpcserver/types_test.go, client/webserver/api.go, client/webserver/site/src/html/forms.tmpl, client/webserver/site/src/html/register.tmpl, client/webserver/site/src/js/forms.js, client/webserver/site/src/js/wallets.js, client/webserver/types.go, client/webserver/webserver_test.go
Part 3 of #292 
Both webserver and dexcctl now read the config text from the config file path (if provided) and sends the config text to the server rather than the config file path, in line with the reasoning that either user-facing apps could be run on a machine different from the dexc backend such that file paths valid on the local machine may be invalid on the server machine.
Also, modifies dexcctl `newwallet` args parsing to allow no arguments for config text, as is done on the web frontend, which causes the client core to use the default config path.
=> client/webserver,dexcctl: replace new wallet config file path with cfg text

client/asset/btc/btc.go, client/asset/dcr/dcr.go
This is a common enough setup hiccup that I think some logging here is warranted to show what wallet RPC server settings (host:port for dcr and btc, and cert for dcr) were parsed from the config file (although that is not always going to be the case - see step 4 on issue https://github.com/decred/dcrdex/issues/292#issuecomment-619540709).
On CreateWallet, you get the new "Setting up new..." log lines:
```
[INF] CORE[dcr]: Setting up new DCR wallet at 127.0.0.1:19567 with TLS certificate "/home/jon/dextest/dcr/alpha/rpc.cert".
[INF] CORE: Created dcr wallet. Account "default" balance available = 4647815451734 / locked = 0, Deposit address = SsfWraUBDUtU2dKAhBAYcb8HVTEupAnj9ta
...
[INF] CORE[btc]: Setting up new btc wallet at localhost:20556/wallet/gamma.
[INF] CORE: Created btc wallet. …
```
=> client/asset: log new wallet config while setting up

.github/workflows/build.yml, run_tests.sh
This updates actions/checkout to v2 to avoid [the checkout/v1 bug](https://github.com/actions/checkout/issues/23) when master changes.
This also updates golangci-lint to 1.26, which [adds a `github-actions` output format](https://github.com/golangci/golangci-lint/pull/1017).  This option is enabled in run_tests.sh along with the new [asciicheck](https://github.com/tdakkota/asciicheck) linter.
=> github,lint: use v2 of checkout and setup-go actions

dex/testing/ltc/README.md, dex/testing/ltc/harness.sh
Almost an exact copy of the btc harness. The only difference is that the
ltc node shuts down after encrypting a wallet and must be restarted.
Using litecoin v0.17.1
=> testing: Add ltc harness.

client/core/bookie.go, client/webserver/live_test.go, client/webserver/site/src/js/charts.js, client/webserver/site/src/js/markets.js
Shows epoch limit orders as a phantom layer on top of the order book. Differentiating is important here, because the epoch orders may or may not have processed by the time a placed order matches, so the epoch layer is not as likely to be matchable.
Updates to the [test app server](https://github.com/decred/dcrdex/wiki/Test-App-Server) to more realistically handle epochs.
=> app/charts: show epoch limit orders on depth chart

dex/order/order.go, server/market/market.go
Resolves https://github.com/decred/dcrdex/issues/356.
Both `id` and `uid` caching are not thread safe, and the UID is easily
forgotten.  This removes the uid cache field, and modifies the `UID`
methods to always call `OrderID`'s `String` method.
The order ID field still gets computed and cached on first call to `ID()`.
market: stamp the order a little earlier, fixing a possible `Warnf` panic
Regardless of `order.Order` implementation, the server time stamp is
required for order ID computation by definition of the order ID.
However, it is unfortunate that the implementations' ID caching is not
thread safe, requiring the first consumer to request the ID so it gets
written to the `Order`'s (`Prefix` actually) cache before passing the order
to other goroutines that may cause a concurrent …
=> dex/order: eliminate uid string cache in Prefix

server/market/market.go, server/market/market_test.go, server/market/routers_test.go
Use the `TAuth` and `TArchivist` stubs to help synchronize tests without sleeps.
=> market: eliminate sleeps in tests, cleanup

client/core/core.go, client/core/core_test.go, dex/msgjson/types.go, server/admin/api.go, server/admin/server.go, server/admin/server_test.go, server/admin/types.go, server/auth/auth.go, server/auth/auth_test.go, server/book/book.go, server/book/book_test.go, server/coinlock/coinlocker.go, server/coinlock/coinlocker_test.go, server/comms/comms_test.go, server/comms/link.go, server/comms/server.go, server/db/driver/pg/internal/orders.go, server/db/driver/pg/orders.go, server/db/driver/pg/orders_online_test.go, server/db/driver/pg/system_online_test.go, server/db/interface.go, server/dex/dex.go, server/market/bookrouter.go, server/market/epump.go, server/market/epump_test.go, server/market/market.go, server/market/market_test.go, server/market/orderrouter.go, server/market/routers_test.go
This deals with trade suspension on a per-market basis, and makes Market shutdown more courteous.  This does not deal with `Market` resume, or clean `Swapper` shutdown or resume, which is going to be a significant task in itself.
Notable areas of work:
- market: Graceful suspend (the `epochPump` and `(*Market).Run` work), with optional book purge and coin unlock (the book and coinlock work).
- db: Book purge from persistent storage (mass booked -> revoked status, plus pseudo-cancels recording the actions)
- msgjson, market: Add the `TradeSuspension` message, and send it to clients from `server/dex.DEX` to subscribed clients via `comms/Server` on `Market` suspend command.
- admin: market info and suspend routes
- market: refactor book router's update signals from market
Technically, a …
=> market,dex: trade suspension

client/webserver/api.go
The client should only send the cookie with first-party requests.
Cross-site requests should not include the auth cookie.
https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00#section-4.1.1
=> webserver: strict SameSite auth cookie attribute

client/webserver/webserver.go
Adds security headers
- [x frame options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options)
- [xss protection](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection)
- [x content type options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options)
- [referrer policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)
- [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)
- [feature policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy)
=> Add security headers middleware

client/core/bookie.go, client/core/core.go, client/core/core_test.go, client/core/trade.go, client/core/types.go, client/order/bookside.go, client/order/orderbook.go, client/order/orderbook_test.go, client/webserver/live_test.go, client/webserver/site/src/js/markets.js, client/webserver/site/src/js/orderbook.js, dex/msgjson/types.go, server/admin/server_test.go, server/market/bookrouter.go, server/market/market.go, server/market/routers_test.go, server/matcher/match.go, server/matcher/match_test.go
Introduces a new order book update type, `update_remaining`, which updates the quantity of a booked order. Modifies the `(*Matcher).Match` method to prevent duplicates. Client updates the `OrderBook` and sends a `BookUpdate` notification to websocket subscribers. 
Spec update to follow.
=> multi: book feed: update remaining quantity of partially filled book order

spec/orders.mediawiki
Enable updating the remaining quantity of booked orders via order book feed notifications. Adds a new notification type, `update_remaining`.
Work done in #366.
=> spec: describe update_remaining order book notification

README.md, server/cmd/dcrdex/config.go
Resolves #152. Don't forget to `CREATE DATABASE dcrdex_simnet OWNER dcrdex;` and `CREATE DATABASE dcrdex_testnet OWNER dcrdex;`
=> dcrdex: enable networked PostgreSQL db names and use by default

client/webserver/webserver.go
This fixes (*WebServer).Run being unable to return if there is a websocket handler goroutine waiting on the webserver mutex.
=> client/webserver: resolve shutdown deadlock

client/core/bookie.go, client/core/core.go, client/core/core_test.go, client/core/notification.go, client/core/trade.go, client/core/types.go, client/webserver/live_test.go, client/webserver/site/src/html/markets.tmpl, client/webserver/site/src/js/markets.js
New columns include order type, percent settled, and order status. Additionally, the age column is refreshed every second. Corrects a number of related deficiencies with epoch handling and status updates.
Resolves #297
=> app: show more details in user orders table

client/core/core.go, client/core/core_test.go, client/core/types.go, client/rpcserver/handlers.go, client/rpcserver/handlers_test.go, client/webserver/live_test.go, client/webserver/site/src/html/markets.tmpl, client/webserver/site/src/js/markets.js
This allows core methods to be called with a variety of different
patterns. Because net/url.Parse and net.SplitHostPort are not built for
our specific needs, a new function addrHost is added. This function will
parse dex addresses in a predictable manner that always produces a
host:port pair or just a host. Using the method on an already parsed
host will produce the same host.
closes #374
=> multi: Remove scheme from connection map.

client/comms/wsconn.go, client/comms/wsconn_test.go, client/core/core.go, client/webserver/api.go, client/webserver/webserver_test.go
Return **`certificate required`** or **`invalid certificate`** error message for cert-related connection issues.
Resolve #225.
_With no cert provided_
_With invalid cert provided_
=> client/comms: return descriptive error for ws conn cert issues

server/market/bookrouter.go, server/market/routers_test.go
`(*BookRouter).handleOrderBook` can run `sendBook` synchronously, not in a
new goroutine since the caller is in a goroutine for just that link, a
`(*Server).websocketHandler`, meaning `comms.Link.Send` called
by `handleOrderBook` doesn't block anything except for subsequent incoming
messages just for that client until this one is handled.
This makes it less likely for the ticks in `TestRouter` to be insufficient.  e.g. https://github.com/decred/dcrdex/runs/694271908#step:5:267
=> market: make handleOrderBook send book synchronously

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/regnet_test.go, client/asset/btc/walletclient.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/simnet_test.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/types.go, client/core/wallet.go, client/db/bolt/db.go, client/db/bolt/db_test.go, client/db/test/dbtest.go, client/db/types.go, client/rpcserver/handlers.go, client/rpcserver/rpcserver.go, client/rpcserver/rpcserver_test.go, client/webserver/live_test.go, client/webserver/site/src/html/wallets.tmpl, client/webserver/site/src/js/app.js, client/webserver/site/src/js/markets.js, client/webserver/site/src/js/wallets.js, client/webserver/webserver.go, client/webserver/webserver_test.go
This is a precursor to resolving #345. By allowing the simultaneous calculation of multiple categorized balances with different numbers of minimum confirmations, we can efficiently retrieve and display information more accurate to the specific DEX.
No UI updates, unless you count the RPC server help message.
Includes an update to **db**, so **nuke your dexc.db**.
=> multi: refactor balance reporting

client/core/core.go
Instead of capturing the err variable from `notifyFee`, the `Request`
handler should use it's own error.  It was a data race otherwise.
=> core: notifyFee's request handler was capturing err

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/core/core.go, client/core/core_test.go, client/core/notification.go, client/core/trade.go, client/core/types.go, client/core/wallet.go, client/db/interface.go, client/webserver/live_test.go, client/webserver/site/src/js/app.js, client/webserver/site/src/js/markets.js, client/webserver/site/src/js/wallets.js, dex/testing/btc/harness.sh
Update balances at the following times.
1. When registering
2. After withdrawal
3. After a trade is initiated and coins are locked
4. After any action on a match
A `Data`-severity notification is sent whenever an update occurs. Balances on the markets and wallets view are updated live. There is more to be done on the UI side, but I'd like to do it as part of a larger effort in a separate PR.
Changes to the simnet harness enable a second client to be run on the same machine, if done carefully. Will follow up with updates to the simnet testing wiki page.
Fixes some apparent bugs in the exchange wallets for the way unspent outputs are handled, to accommodate latency correctly, and to avoid a panic. I'm not sure how I went wrong there. Did the errors change? Might need more looking into, but …
=> multi: update balances when they change

server/market/market_test.go
This resolves a test timeout seen in https://github.com/decred/dcrdex/runs/715296974 for PR https://github.com/decred/dcrdex/pull/372, although it's still unclear why the market wasn't running.
The unguarded set of a channel was also technically a race but it couldn't ever be hit.  It wasn't necessary to nil it out, so don't.
=> market: Errorf->Fatalf, and eliminate not-a-race

server/auth/auth.go, server/comms/link.go, server/market/routers_test.go
For some reason I was following the pattern of draining a `Timer.C` channel if it had already fired when calling `Stop`, but this is not to be done for `Timer`s created with `AfterFunc` as per the [Go docs](https://golang.org/pkg/time/#Timer):
> When the `Timer` expires, the current time will be sent on `C`, unless the `Timer` was created by `AfterFunc`
Indeed, `time/sleep.go` makes it clear that the `C` channel is nil for timers created with `AfterFunc` and will block forever if you try to receive on it.
=> auth,comms: don't try to drain AfterFunc channels

client/core/core.go, client/core/notification.go, client/core/types.go, client/rpcserver/handlers.go, client/rpcserver/handlers_test.go, client/webserver/site/src/css/market.scss, client/webserver/site/src/html/markets.tmpl, client/webserver/site/src/js/app.js, client/webserver/site/src/js/doc.js, client/webserver/site/src/js/markets.js
This PR modifies the code so the order form is hidden while the registration payment has not been confirmed. Instead, a message is shown to communicate the status of the confirmation. See the previews for more info.
The full list of changes:
**Core changes:**
- Adds the dex URL to all `feepayment` notifications. This is particularly useful in this case to determine to either show or not the confirmation message in the current market.
- The registration update notification uses now the `regupdated` subject.
- Successful registration note uses now the `regcompleted` subject. So it server to multiple purposes in the frontend side. See 'Site changes' for more info. 
- Refresh the user after completed registration.
**Site changes:**
- ~Added an override handler in the app.js which enables the …
=> client/core: hide order form and display registration status message

client/webserver/site/package.json, client/webserver/site/src/html/settings.tmpl, client/webserver/site/src/js/app.js, client/webserver/site/src/js/settings.js, client/webserver/site/webpack/common.js
Hopefully enough for #429. As of right now, the shortened commit hash is just displayed in the settings view and printed to the top of the console. If we add a footer later, it can go there too.
You'll need to `npm install` the new dev dependency.
=> app: display the commit hash

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/cmd/dexc/main.go, client/cmd/dexc/ui/widgets.go, client/comms/wsconn.go, client/core/core_test.go, client/rpcserver/rpcserver.go, client/rpcserver/rpcserver_test.go, client/rpcserver/websocket.go, client/webserver/live_test.go, client/webserver/webserver.go, client/webserver/webserver_test.go, client/webserver/websocket.go, dex/runner.go, dex/ws/wslink.go, server/comms/comms_test.go, server/comms/server.go
Resolves #394
Eliminate sloppy `time.Sleep` sync patterns in tests. Improves `WSLink.Send` synchronization so that a graceful shutdown will wait for messages to finish sending.
=> server/comms: fix synchronization issues and drop sleeps in tests

client/core/core.go, client/core/core_test.go, client/core/types.go, client/rpcserver/handlers.go, client/rpcserver/handlers_test.go, client/rpcserver/rpcserver.go, client/rpcserver/rpcserver_test.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/webserver.go, client/webserver/webserver_test.go
In order to pass the fee's txid and number of needed confirmations
needed onto the callers of the register route, return a new
RegisterResult that holds that information.
closes #332
=> client: Return RegisterResult from Register.

server/account/account.go, server/admin/api.go, server/admin/server.go, server/admin/server_test.go, server/db/driver/pg/accounts.go, server/db/driver/pg/accounts_online_test.go, server/db/driver/pg/internal/accounts.go, server/db/interface.go, server/db/types.go, server/dex/dex.go, server/market/market_test.go
In order to view account data in the database, add an api enpoint to the
admin server that retrieves all accounts and returns a slice of
accounts. Byte arrays are encoded in hex for readability.
part of #329
=> admin: Add Accounts.

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/regnet_test.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/simnet_test.go, client/asset/interface.go, client/asset/ltc/regnet_test.go, client/core/core.go, client/core/core_test.go, client/core/trade.go, client/db/types.go
Resolves #302.
In addition to checking for matches that require a swap or redemption broadcast, also check for failed matches where the client has a pending/unspent swap output and perform auto-refund where possible.
The following match disruption scenarios, necessitating a refund, are considered:
- The client is the (Maker) and has broadcast their init swap but up till the locktime expiry on the client's/Maker's swap, the other party (the Taker) has not sent "notification" of their counterswap (or sent a counterswap that failed audit checks).
- The client is the Taker and has broadcast their counterswap but up till the locktime expiry on the client's/Taker's counterswap, the other party (the Maker) has not sent "notification" of their redeeming the counterswap (or sends an invalid …
=> app: auto-refund swaps when trade fails

client/core/core_test.go, client/core/trade.go, client/webserver/site/src/js/markets.js, dex/asset.go, dex/encode/encode.go, dex/order/match.go, server/asset/btc/utxo.go, server/asset/common.go, server/asset/dcr/utxo.go, server/market/routers_test.go, server/swap/swap.go, server/swap/swap_test.go
Locktime was not being set correctly. The server [intentionally sets](https://github.com/decred/dcrdex/blob/2ed220b0af975fe28b3fb33f9e2c0ec252e069a7/server/swap/swap.go#L1543) the `msgjson.Match.ServerTime` based on the match epoch so that locktime can be based off of a common point for both maker and taker. Plus, taker wasn't setting their locktime correctly when constructing the contract, which is now fixed.
=> core: fix locktime handling

client/core/core.go, client/webserver/site/src/js/markets.js
The field was changed to a reference in a later commit of #353, but that meant that it was recognized as waiting for confirmations on startup, since it would be zero. Pointer works better in this case.
Resolves #452
=> core: fix issue with regConfirms field of dexConnection

client/core/core.go, client/core/core_test.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/webserver.go, client/webserver/webserver_test.go
Fixes an embarrassing bug in `(*Core).Withdraw`. Whoops. 
@JoeGruffins, you'll want these changes for #422 
Also adds auto-connect and auto-unlock to `(*Core).Withdraw`.
=> core: fix withdraw

dex/marshal.go, server/admin/api.go, server/admin/server.go, server/admin/server_test.go, server/db/driver/pg/accounts.go, server/db/driver/pg/accounts_online_test.go, server/db/driver/pg/internal/accounts.go, server/db/interface.go, server/dex/dex.go, server/market/market_test.go
=> admin: Add account endpoint.

server/market/market.go
When the market suspend functions were added, the behavior of a CTRL+C shutdown was inadvertently changed to flush the books since the `persistBook` boolean added then was not set in the constructor (it was left as false).  This sets it to `true` in `NewMarket` so that unless a Suspend command is issued that explicitly sets it, a shutdown of the market due to context cancellation will not flush the book.
=> market: default to presist book (on ctrl+C quit)

server/asset/btc/btc.go, server/asset/common.go, server/asset/dcr/dcr.go, server/coinlock/coinlocker.go, server/coinlock/coinlocker_test.go, server/market/market.go, server/market/market_test.go, server/market/routers_test.go, server/swap/swap.go, server/swap/swap_test.go
Resolves https://github.com/decred/dcrdex/issues/363
The Market constructor loads all book orders from the DB and rebuilds the book. This PR checks each order's funding coins to be sure they are either unspent or involved in a dex monitored trade. As an optimization, if the filled amount is zero and the coins are spent, the monitored trade check is skipped and the order is not included in the rebuilt book.
This also will prevent any orders found in epoch status on startup from having their coins locked, as these orders are effectively dead.  Note that such dead epoch status orders were being created by a bug fixed in https://github.com/decred/dcrdex/pull/472, commit d4bcf4f810ca5c37df091ded2ab5907ee63d9a48.
=> market,swap,asset: verify funding of unfilled orders in NewMarket

client/cmd/dexc/main.go, client/rpcserver/rpcserver_test.go, client/webserver/webserver_test.go, server/cmd/dexcoin/go.sum
Resolves https://github.com/decred/dcrdex/issues/338.
Much of the work required for 338 was addressed with work done in https://github.com/decred/dcrdex/pull/435
This pull request consists of tests for the Connect methods added to rpc and web server.
=> dexc: webserver and rpcserve bind failures should shutdown dexc

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/core/core.go, server/asset/dcr/dcr.go
Tests show that `gettransaction` **may** return `tx not found error` for the fee tx if `gettransaction` is invoked immediately the tx is broadcasted.
This modifies the fee confirmations trigger to ignore such errors (assume network latency) and continue the check for required confirmations.
Also modifies asset methods that call `gettransaction` to return `asset.CoinNotFoundError` when the requested tx is not found.
=> core: ignore tx not found errors in fee confirmations trigger

dex/msgjson/types.go, spec/README.mediawiki, spec/accounts.mediawiki, spec/admin.mediawiki, spec/api.mediawiki, spec/comm.mediawiki, spec/fundamentals.mediawiki, spec/orders.mediawiki, spec/references.mediawiki
1. Describe new trade suspension messaging
2. Describe administrative API
3. Rewrite intro section. Combine "Abstract" and "Introduction". Shortened and more focused. 
4. Full table of contents in the spec readme
5. Various typos and drift corrections. 
View at https://github.com/buck54321/dcrdex/tree/spec-roundup/spec
Resolves #280
=> spec: update roundup

client/core/core.go, client/core/core_test.go, dex/msgjson/types.go, server/auth/auth.go, server/auth/auth_test.go
Resolves #273. The 'connect' response is now signed. The message is the `msgjson.Connect` serialization.
=> multi: sign connect response

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/asset/interface.go, client/core/core_test.go, client/core/trade.go
One potential cause for trade disruption as documented in #361 is when notifying the DEX after taking a required action results in an error such as when [sending `init` request after broadcasting swap tx](https://github.com/decred/dcrdex/blob/deaa965813825dd1505e948e1856abdd2bde11ba/client/core/trade.go#L618-L629) or when [sending `redeem` request after redeeming the counter-party swap](https://github.com/decred/dcrdex/blob/deaa965813825dd1505e948e1856abdd2bde11ba/client/core/trade.go#L698-L704).
Currently, the client does not update the match status to indicate that the required action has been executed and also does not re-attempt sending the request (unless dexc is restarted). 
Also, as mentioned in https://github.com/decred/dcrdex/issues/302#issuecomment-630744659, for `init` errors, …
=> core: properly handle client->server request errors during trade

client/asset/interface.go, dex/asset.go, dex/errors.go, dex/errors_test.go, server/asset/btc/btc.go, server/asset/btc/utxo.go, server/asset/common.go, server/asset/dcr/dcr.go, server/asset/dcr/utxo.go
Resolving https://github.com/decred/dcrdex/issues/483
Based on the `DetailedError` type https://github.com/decred/dcrdex/blob/ecbeacc290e78a1b0a199260c2effc0acd9dc0d6/server/db/driver/pg/errors.go#L14-L38
=> dex: general purpose go 1.13 error type

spec/admin.mediawiki, spec/fundamentals.mediawiki, spec/orders.mediawiki
Drops the minimum funding confirmations requirement. 
1. Confirmation requirements for funding outputs add no real security and some major programming and UX issues.
2. The user is required to lock up more funds than they are trading if their order doesn't match immediately, since transaction outputs can't be sized at trade time. Solutions such as pre-splitting transactions to lot-sized or multi-lot-sized outputs is possible, but would increase realized transaction fees, make small lot sizes infeasible even for low-tx-fee-rate assets, and still delays the users ability to trade after funding their exchange wallet.
3. The funding confirmation requirement also requires a lot of special handling of outputs, such as the change output monitoring for the client and special handling likely …
=> spec: remove funding confirmations requirement

client/rpcserver/websocket.go, client/webserver/websocket.go, dex/ws/wslink.go, server/comms/server.go
Based on https://github.com/decred/dcrdex/pull/484, the relevant diff for this PR is https://github.com/decred/dcrdex/pull/485/commits/5dd77ea6800d3fc48357d1628cb0d344c0309a21
Fixes superfluous header write in the event of upgrade errors.
ws: `NewConnection` only replies with error if not handshake error
Use `dex.NewError` to wrap handshake error on `gorilla/websocket.HandshakeError` with details from `upgrader.Upgrade`'s error.
client/{rpcserver,webserver},server/comms: do not `http.Error` on upgrade error
=> ws: Newconnection only replies with error if not handshake error

client/comms/wsconn_test.go, server/comms/comms_test.go
This extends test wait times to prevent timeouts on slow machines.
Resolves  #450
=> comms: extend test wait times.

dex/order/order.go, server/db/driver/pg/internal/orders.go, server/db/driver/pg/orders.go, server/db/driver/pg/orders_online_test.go, server/db/driver/pg/system_online_test.go, server/db/interface.go, server/market/market.go, server/market/market_test.go
Resolves issue https://github.com/decred/dcrdex/issues/451 in conjunction with PR https://github.com/decred/dcrdex/pull/462
dex/order: zero value `Commitment` `Value`/`Scan` to/from sql `NULL` `BYTEA`
server/db: `FlushBook` makes exempt cancels
`(*Archiver).FlushBook` now creates exempt cancel orders, which do not not
count in the user's cancellation ratio, to record the change of status of the
flushed orders from booked => revoked.
`OrderArchiver.RevokeOrderUncounted` revokes an order like `RevokeOrder`,
but the generated cancel is exempt.
server/db/driver/pg: two categories of server-generated cancel orders
Eliminate random `Commitment`s for revoke cancels, now `NULL`.
Server-generated cancel orders for revoked orders are now stored with
`NULL` in the commit column, which loads as the …
=> server/{db,market}: book purge does not affect cancellation ratio

client/db/test/dbtest.go, client/db/test/types_test.go, client/db/types.go
The race detector makes randBytes very very slow.  The test is typically ~40 seconds.
This adds a `-short` test option with fewer iterations, reducing the test time to about 4 seconds.
=> client/db/test: make -short tests, remove usless code

client/core/core.go, client/core/core_test.go, client/core/trade.go, client/webserver/site/src/js/markets.js, server/auth/auth.go, server/comms/link.go, server/dex/dex.go, server/market/bookrouter.go, server/market/market.go, server/market/market_test.go, server/market/routers_test.go, server/swap/swap.go, server/swap/swap_test.go
It was a mistake for `(*Swapper).checkInaction` to revoke orders in
persistent storage, as they would have still been on `Market`'s
in-memory book.
When a match fails, there is no good way to unbook the faulty order.
This creates a `Swapper.unbookHook` field (a function) set on construction-
time via `Config`.  In the dex manager, this unbook hook is a simple
dispatcher to the appropriate `Market`'s new `Unbook` method.
Add `(*Market).Unbook` to remove the order from the in-memory book,
and if it was removed, unlock the coins, change the order's status to
revoked in storage via `RevokeOrder`, record the cancel with the
`AuthManager` via `RecordCancel` for cancellation ratio tracking, and
finally send a signal to the book router of the `unbookAction`.
The `Unbook` method does not require …
=> dex,market,swap: unbookHook for swapper

dex/order/status.go, server/dex/dex.go
I spent some time studying orders today and found some places to nitpick. The missing `abort()` is actually probably needed though.
=> multi: Fix grammar.

dex/testing/dcr/create-wallet.sh
Resolving https://github.com/decred/dcrdex/issues/413.
The harness ran over night and is at block 4021 and counting.  Turns out it was because of the one block in a sdiff window where wallet refuses to make a purchase that makes `ticketbuyer.limit=5` inadequate over long enough.
=> testing/dcr: allow dcr harness to run forever

client/webserver/site/src/js/markets.js, client/webserver/site/src/js/ws.js
Resolves https://github.com/decred/dcrdex/issues/517
If you attempt to cancel more than one order on the browser interface, successive cancels trigger repeated `/api/cancel` POSTs.
For example, book two orders, cancel the first one successfully:
Then, try to cancel the second:
This action makes **two** immediate POSTs to `/api/cancel`, both invalid:
Note that one has an empty `pw` but the correct target `orderID`, while the other has the password, but the previously canceled `orderID` from the first sucessful cancel.
This does not happen if you refresh the page between cancels.
Apparently the `submitCancel` event listeners remained.  An anonymous handler function is a bit harder to unregister, but it can be done by calling `removeEventListener` at the end of the hander function, or with …
=> client/webserver/site: showCancel must not register multiple handlers

client/core/bookie.go, client/core/core.go, client/order/orderbook.go, server/market/bookrouter.go
Resolves https://github.com/decred/dcrdex/issues/446
server/market: fix book epoch order note for cancel orders
The epoch order note for a cancel order was not setting the order ID of
the cancel order itself, just the target ID.  Market ID and order time
stamp are also set now.
client/core: check market state in `Cancel`, improve messages
client/order: `ValidateMatchProof` short-circuits when order counts mismatch
When the number of preimages+misses in the match proof note does not
equal to the number of orders in the local epoch queue, skip the match
proof generation as it is guaranteed fail.
=> server/market,client/{core,order}: fix epoch order note for cancel orders

client/order/orderbook.go
This fixes a market suspend crash caused by the orderbook not initializing orders, buys, and sells in its constructor. This was done in preference of initializing on sync, which does not cover market suspensions for an unsynced market.
Resolves #500
=> core: fix market suspend crash.

dex/testing/dcrdex/harness.sh
I needed to set the password for the user to get things working for PostgreSQL12.2. Would get `db.Open: pq: password authentication failed for user "dcrdex"` if the user had no password set. This updates the harness to allow setting the pg password through dcrdex's config.
=> testing/dcrdex: allow setting --pgpass.

client/asset/btc/btc.go, client/asset/btc/livetest/livetest.go, client/asset/dcr/dcr.go, client/asset/dcr/simnet_test.go, client/core/core.go, client/core/trade.go, client/db/bolt/db.go, client/db/bolt/db_test.go, dex/encode/encode.go, dex/order/serialize.go, dex/order/test/helpers.go, server/auth/auth.go, server/auth/auth_test.go, server/db/driver/pg/matches.go, server/db/driver/pg/matches_online_test.go, server/db/interface.go, server/market/market_test.go
Resolves https://github.com/decred/dcrdex/issues/529
The `order.UserMatch` was not being serialized with the new `FeeRateSwap` field so it was being loaded from DB as 0 by default.
In addition, the `'connect'` response was not setting either base or quote fee rates, but it was also missing the recently added `MatchTime` that the client needs for lock time computation.
The server/db changes provide the data needed by `(*AuthManager).handleConnect` to provide this new match data to clients on connect.
In client/asset/{dcr,btc}, `(*ExchangeWallet).sendWithReturn` was assuming a certain change address format when computing the updated tx size.  This fixes that and refactors a bit so the functions mirror each other more closely, and to log more information about the generated transaction and …
=> dex/order,client/asset: fix UserMatch DB serialization, and change address assumption

client/db/bolt/upgrades.go
It has become clear that there are going to be multiple client DB scheme changes prior to release.  Writing upgrades for each of these will be a waste of time since the software is still pre-release.
This reverts the bolt db to version 0.
When we decide the DB scheme is stable and ready for release, the v1 upgrade that sets the version key can simple be uncommented.  The v0 test data does not need to be updated.
=> client/db/bolt: revert to db version 0

spec/README.mediawiki, spec/orders.mediawiki
If there is no match for an order, the client must currently infer that from the match proof. This PR adds a `nomatch` notification when the client's order does not match during the match cycle. The notification will be sent for market and limit orders (regardless of time-in-force). This is just one possible solution the issue raised in https://github.com/decred/dcrdex/pull/525#pullrequestreview-443328138.
=> spec: add nomatch notification

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/errors.go, client/core/trade.go, client/core/trade_simnet_test.go, dex/msgjson/types.go, server/market/integ/booker_matcher_test.go, server/market/market.go, server/matcher/match.go, server/matcher/match_test.go
Lock change coin in `ExchangeWallet.Swap`. Return unused coins when an order is canceled, or when a market is suspended with  `persist = false`.
=> client/asset, core: lock and return coins when needed

dex/ws/wslink.go, dex/ws/wslink_test.go
The added test provides come coverage for the `dex/ws` package and
exercises the `dex/ws.WSLink` type, especially the `outHandler` method.
One test causes the queue to bounce off zero while writing at the same
rate as `Send`ing/queueing. The following test queues more quickly than
the write rate, causing the queue to grow, reallocate, and drain on
disconnect.
`(*WSLink).outHandler` now remembers a write error and prevents further
write attempts of queued message as they will just fail, instead sending
an immediate error reply to the `Send`/`SendNow` caller.
`(*WSLink).outHandler` now writes a Close (1000) control message before
closing the underlying `net.Conn`, but only if there were no prior write
errors that would make the `WriteControl` fail.
`(*WSLink).outHandler` now limits the …
=> dex/ws: tests, Close control prior to disconnect, queue cap limit

client/core/bookie.go, client/core/types.go, client/rpcserver/handlers.go, client/rpcserver/handlers_test.go, client/rpcserver/rpcserver_test.go, client/rpcserver/types.go, client/rpcserver/types_test.go, client/webserver/live_test.go, dex/msgjson/types.go
Resolves https://github.com/decred/dcrdex/issues/466
=> client/rpcserver: Add orderbook route.

client/db/bolt/db.go
The returned byte slice from `bbolt.(*Bucket).Get` is not valid outside of
the transaction where it is used.  This change fixes several places
where the `[]byte` was used outside of the transaction without copying it,
resulting in mysteriously corrupted data, including `ChangeCoin`.
Add the `client/db/bolt.getCopy` function to load a value and make a copy.
If the loaded value is an empty slice, it returns nil.  Thus, to
identify a non-existent value, use `Bucket.Get` directly instead.
`getCopy` covers most of the cases where we want to get the value into a
slice that is safe to use outside of a transaction, and when we do not
wish to load an empty non-nil slice when nil was actually stored.
Notably, this fixes `decodeOrderBucket`, `DecodeMatchProof`, and
`makeWallet`>`DecodeWallet` …
=> client/db/bolt: fix data corruption from reused buffers

dex/marshal.go, dex/marshal_test.go
This changes `(*Bytes).UnmarshalJSON` to use `hex.Decode` instead of `hex.DecodeString`, which eliminates two copy-conversions (one `[]byte` => `string` and one `string` => `[]bytes`), and the hilarious over-allocation of the resulting slice by `hex.DecodeString`.
This also adds a check to ensure the first and last characters in the marshalled json are `"`.
If hex decoding fails, the `Bytes` is not changed, whereas before `hex.DecodeString` would return the partially decoded slice in the even of an error.
Adds test coverage for `(*Bytes).UnmarshalJSON`.
=> dex: improve and test (*Bytes).UnmarshalJSON

client/webserver/site/src/js/orderbook.js
Orders loaded on startup do not have an epoch property set. This changes
OrderBook's setEpoch method to keep orders where the epoch property is
undefined in addition to 0 or the new epochIndex.
Resolves https://github.com/decred/dcrdex/issues/568 and probably https://github.com/decred/dcrdex/issues/553 too
=> web: setEpoch should keep orders with no epoch property

client/webserver/live_test.go, client/webserver/site/src/css/main.scss, client/webserver/site/src/css/market.scss, client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/html/markets.tmpl, client/webserver/site/src/js/charts.js, client/webserver/site/src/js/doc.js, client/webserver/site/src/js/markets.js, server/asset/dcr/dcr_test.go
Fixes issues where overflow and div sizing were acting weird on resize. 
Creates and uses a stylish scrollbar class. Enables manual chart div click-drag resizing and remembers the user's preference across sessions. 
Also corrects a recent regression where certain order form elements were not being hidden for market orders.
Most of the loc are just html indentation changes. Best tested with the [test app server](https://github.com/decred/dcrdex/wiki/Test-App-Server).
resolves #550, #514, #296, #539
=> app: fix markets view layout issues

client/webserver/webserver.go, client/webserver/websocket.go, dex/ws/wslink.go
Add the client to the `WebServer`'s clients map only after it is connected
so that notify does not attempt to send to this client before the
`wsClient` is ready.
=> client/webserver: fix websocket Connect/Send data race

client/cmd/dexc/main.go, client/core/core.go
Fixes:
- Shutdown was not being aborted with any response.
- Data race in main on the `var clientCore *core.Core`
- Overriding the prompt with an other CTRL+C was not desirable.  This now has an unbuffered `os.Interrupt` signal channel so repeated ctrl+c has no effect (no repeated prompts and no prompt override) except for seeing `^C` on the prompt.
=> dexc,client/core: fix shutdown data race and abort failure

client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go
When selecting outputs for funding transactions, wallet outputs as returned by `listunspent` are filtered for only those with the account specified in the wallet configuration.
=> client/asset/dcr: filter dcr utxos by account

client/webserver/webserver.go, client/webserver/webserver_test.go, client/webserver/websocket.go
Make webserver connect and clients map update atomic so that any
connected client will be found in the map when accessed under lock,
and vice versa.
Bind the webserver to a random port in tests.
Remove dead code.
=> client/webserver: connect and update client map under lock

server/asset/dcr/dcr_test.go
This resolves a data race in the test with the `blockCache` field of the dcr backend.
This was previously fixed for the btc tests in https://github.com/decred/dcrdex/pull/109
=> server/asset/dcr: fix test data race on blockCache

client/webserver/live_test.go, client/webserver/site/src/js/charts.js
Zoom was constrained to +/- 50% of the mid-gap rate, but could accommodate double that width without major changes to other parts. 
Allowing more is possible, but there are tradeoffs for > 100%, as either a) the charts will need to be reconfigured to allow an off-center mid-gap, or b) the chart will expose a negative scale on the left. 
For now, I'm hoping this is an improvement and enough to resolve #553.
=> app: allow depth chart zoom up to +/- 100%

client/core/bookie.go, client/core/core.go, client/core/core_test.go, client/core/types.go, client/order/orderbook.go, client/rpcserver/rpcserver.go, client/rpcserver/rpcserver_test.go, client/rpcserver/websocket.go, client/webserver/live_test.go, client/webserver/webserver.go, client/webserver/webserver_test.go, client/webserver/websocket.go, server/market/bookrouter.go
This resolves a data race on the `bookie.feeds` map caused by the `handleReconnect` function making a shallow copy of the map.
This also refactors the `bookie`, `BookFeed`, and reconnect handling quite a bit. Main problems that are resolved:
1. `BookFeeds` were being copied to a new `bookie` in `handleReconnect`, but the `BookFeed.close` function was a method an the old `bookie` instance.  Now the `bookie` (and its `BookFeed`s) are not replaced, and instead a manual resubscribe is performed.
2. When reconnect resubscribed with the server, the feed receivers (e.g. web frontend) needed a fresh book since book/unbook/epoch messages are likely to have been missed.  This is resolved with a `FreshBookAction` notification type.
3. AfterFunc timer race between the bookie's close timer that called …
=> client/core: fix shallow map copy causing concurrent map write

dex/testing/btc/base-harness.sh, dex/testing/dcr/harness.sh
I've had the alpha/beta DCR simnet nodes ban each other.  This should prevent that from happening.
=> dex/testing: whitelist loopback peers in harness

server/asset/dcr/dcr.go, server/asset/dcr/dcr_test.go, server/dex/dex.go
Add `server/asset/dcr.(*Backend).ValidateXPub`.
In `server/dex.NewDEX`, validate the string provided in the `--regfeexpub`
config setting.  Also ensure `dcrBackend` exists.
The database would error on construction, but this catches the invalid xpub earlier.
=> server/{dex,asset/dcr}: validate regfeexpub earlier in startup

client/asset/dcr/config.go, client/comms/wsconn.go, client/comms/wsconn_test.go, client/core/bookie.go, client/core/core.go, client/core/core_test.go, client/core/trade.go, client/core/types.go, client/db/types.go, client/order/orderbook.go, dex/order/serialize.go, server/auth/auth.go, server/auth/registrar.go, server/swap/swap.go
Resolves https://github.com/decred/dcrdex/issues/554 and a few untracked issues
Main changes:
- Async incoming request/notification handling in client/core, no longer blocking
- Parallel client negotiation of trades with new matches (still sequential for a given trade)
- Configurable client request expiration
- Longer request timeouts for client's init and redeem requests, where the server
may wait up to broadcast timeout to respond.
- Longer timeout on client's coin waiters for `processAudit` and `notifyFee`
- Longer timeout on server's audit request
- Fix client outgoing messages not first being validated before writing to link
**client/core**
Incoming requests and notifications queue the call to the registered
handler function in a dedicated runner goroutine now to prevent
blocking …
=> client/core: async req/ntfn handling, parallel new match negotiation

client/webserver/live_test.go, client/webserver/site/src/js/markets.js
In the "Your Orders" table on the markets view, if a limit order has time-in-force = immediate, shows the type as `Limit (i)`.
=> app: indicate immediate time-in-force for user orders on markets view

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/trade.go, client/db/bolt/db.go, dex/order/match.go
client/core: filter and retire inactive trades
Update `(*trackedTrade).isActive` to exclude refunded matches, and some
revoked matches depending on match status and side.
For **revoked matches**:
- `NewlyMatched` requires no further action from either side
- `MakerSwapCast` requires no further action from the taker
- (`TakerSwapCast` requires action on both sides)
- `MakerRedeemed` requires no further action from the maker
TODO: Consider a new `dex/order.MatchRefunded` `MatchStatus`. For now we
check the `MatchProof.RefundCoin`.  Add a comment in `dex/order`'s
`MatchStatus` enum, and in `(*trackedTrade).refundMatches` where this status
would be set.
In the main trade ticker, clean out inactive trades from the
`dexConnection`'s `trackedTrades` map.
client/db/bolt: Make a note that we …
=> client: clean up inactive trades

spec/README.mediawiki, spec/comm.mediawiki, spec/community.mediawiki
part of #444 
It was discussed that the notification be tried on reconnect, and to add it to connect, but I thought just adding it to the connect response would be enough/better.
Also:
>message (e.g. state connected to complete swaps or risk further penalty or loss of reg fee!)
I think can be hard coded into the client, since it will be true for all bans
Can be viewed [here](https://github.com/decred/dcrdex/blob/a91ad6aaa874bca72df3bc1024483bedef102e0e/spec/community.mediawiki/#Penalties)
=> spec: Add penalize notifications.

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/livetest/livetest.go, client/asset/btc/livetest/regnet_test.go, client/asset/btc/walletclient.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/simnet_test.go, client/asset/interface.go, client/asset/ltc/ltc.go, client/asset/ltc/regnet_test.go, client/core/core.go, client/core/core_test.go, client/webserver/site/src/css/main.scss
Creates a "split transaction" to pre-size inputs, with some minimum reasonable consideration for negative net effects. The split transaction is sent during a call to `FundOrder` if the user has specified such in their wallet configuration's `txsplit` value.
Resolves https://github.com/decred/dcrdex/issues/340
=> client/asset/{btc,dcr}: enable split funding transactions

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go
Recent testing with the simnet trade harness uncovered this bug with balance reporting.
- Available balance should exclude locked balance.
- Restrict locked balance for dcr to the configured account, to match available balance reporting that uses configured account's available balance rather than the entire wallet's available balance.
dcr wallet's `listlockedunspent` was previously found to sometimes return spent outputs, which causes the calculated locked balance amount to be higher than it actually is (see #453). This has been fixed in https://github.com/decred/dcrwallet/pull/1753, ensuring that `listlockedunspent` only returns unspent outputs. Thus, the locked balance calculation in `dcr.lockedAtoms()` now fully relies on the results of the `listlockedunspent` cmd to determine locked …
=> client/asset: correct available and locked balance calculations

client/rpcserver/handlers.go, client/rpcserver/handlers_test.go, client/rpcserver/types.go, client/rpcserver/types_test.go, dex/order/order.go
rpcserver: Add myorders route.
While my orders were accessible through the exchanges endpoint, the data
was raw and unorganized. This adds some pre-computed, useful information
such as age of the order and amount settled. It also allows for
filtering by exchange and/or market.
rpcserver: Remove orders from exchanges endpoint.
Because orders can now be accessed through the myorders endpoint, they
can be removed from exchanges.
=> rpcserver: Add myorders route.

client/cmd/dexc/main.go, client/comms/wsconn.go, client/webserver/webserver.go, client/webserver/webserver_test.go
Have client/webserver.WebServer look for the "site" directory in the executable directory, then current working directory, then the repo-relative path.  Supplement the error message when site is not found with more information about where the program looked and where the user should put it.
=> client/webserver: prefer site in cwd, improve error

client/core/core.go, client/core/core_test.go, client/core/trade.go, client/db/bolt/db.go, client/webserver/site/src/html/markets.tmpl, client/webserver/site/src/html/wallets.tmpl, client/webserver/site/src/js/markets.js, dex/testing/dcrdex/harness.sh, server/market/integ/booker_matcher_test.go, server/matcher/match.go, server/matcher/match_test.go
- **server/matcher**: Add missed cancel orders to `nomatches`.
- **client/core**: Delete missed cancel from (*trackedTrade).cancel. Update DB status for cancel order.
- **app**: Re-show cancel button when a cancel misses. Other minor code improvements.
=> multi: handle unmatched cancel orders

dex/encode/encode.go, server/cmd/dcrdex/config.go, server/cmd/dcrdex/main.go, server/db/driver/pg/internal/meta.go, server/db/driver/pg/meta.go, server/db/driver/pg/meta_online_test.go, server/db/driver/pg/tables.go, server/db/interface.go, server/dex/dex.go, server/market/market_test.go, server/swap/swap.go, server/swap/swap_test.go
- Default behavior is auto-load based on most recent file in `DataDir`. 
- New flags to ignore previous state or to load from a specific file path.
- Implements a hash consistency check. Creates a single-row metadata table in the server database to store the swap state file hash. The `meta` table is also needed for #522.
=> server/swap: refactor swap state loading

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/walletclient.go, client/asset/dcr/dcr.go, client/core/core.go, client/core/core_test.go, client/core/trade.go
The client/asset order funding functions now keep a consistent view of
locked coins in both wallet and the funding coins map, preventing issues
with concurrent calls to e.g. FundOrder, FundingCoins, etc.
The btc backend now ensures funding coins are also tagged as "spendable"
in the listunspent result, ensuring the wallet has the keys to spend.
client/core: tweak logs and error messages
=> client/{asset,core}: make order funding thread-safe

client/asset/dcr/simnet_test.go, dex/testing/dcr/harness.sh, dex/testing/dcrdex/harness.sh
Update the mining and transfer addresses to account for the change to
dcrwallet master which always upgrades the cointype on simnet.
This also makes a valid seed for the "beta" wallet.
This also updates the dcrdex harness with a bew xpub from alpha's "server_fees" account.
=> dex/testing/dcr: update the addresses for simnet auto cointype upgrade

client/core/trade_simnet_test.go
- Reported by @JoeGruffins, the simnet trade tests suite was using account field in the wallet config map, which was changed to walletname in #533; prevented the btc wallets from being set up on the test clients.
- Trace level logging for test clients.
- Mine 1 block more than the required reg fee confirms to ensure fee tx gets required confirms.
- Improve tryUntil function to delay 250ms between calls to tryFn.
- Improve code that checks for specific notification in client notification channel.
=> client/core: fix btc wallet cfg in simnet tests, other improvements

dex/networks/btc/script.go, dex/networks/btc/script_test.go, dex/networks/dcr/script.go, dex/networks/dcr/script_test.go
We were neglecting to validate the secret size data push in the swap
contracts, which is important to prevent an attack whereby a swap is
initiated between coin with a longer maximum data push than
a different coin.  We were using the right contract format that included
the secret size for counter-party auditing, but we were not checking it.
Also, the contract was being built with the secret hash size instead of
the secret size itself, but it was the same so we didn't notice. 
`ExtractSwapDetails` now verifies that the secret size is as expected.
It also ensures the secret size is encoded with an `OP_DATA_1`.
`MakeContract` now uses `SecretKeySize` instead of `SecretHashSize`, but they
were the same value previously.
Note that the caller of `MakeContract` should ensure their secret hash …
=> dex/networks: validate secret size in contract

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/livetest/livetest.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/simnet_test.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/webserver/site/webpack/dev.js, dex/calc/fees.go, server/market/orderrouter.go
`RequiredOrderFunds` was calculating the maximum number of possible transactions (`maxSwaps` = # lots) internally based on the order quantity and the lot size. But for the quote asset, the maximum number of possible transactions is **not** based on the quote asset lot size, it's based on the rate-equivalent quantity of base asset and it's lot size. This was causing [@chappjc's over-allocation from here](https://github.com/decred/dcrdex/pull/562#issuecomment-668785417), because the BTC lot size was set relatively low. This could also go the other way, and under-allocate, potentially causing trouble. 
Rule of thumb: Lot size is only meaningful for the base asset.
I'm leaving this in draft for a minute while I look it through and think about testing.
=> multi: specify lots as a parameter to RequiredOrderFunds

server/swap/swap.go, spec/orders.mediawiki
The orders section of the spec seems to suggest that upon receiving an audit request, a client will respond with an ack (assuming the audit passes) **and** broadcast their txns right away.  However the next txn step requires the configured number of confirmations for whatever asset the audited contract is on.
=> spec: clarify audit and next step sequence

.github/workflows/build.yml, README.md, client/cmd/dexc/go.mod, client/cmd/dexcctl/go.mod, go.mod, server/cmd/dcrdex/go.mod, server/cmd/dexcoin/go.mod
This changes the Go requirement from 1.13/1.14 to 1.14/1.15.
Also some tweaks to the wording in README.md to reflect the client status better.
=> drop go 1.13, test go 1.15

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/asset/ltc/ltc.go, client/core/core.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/site/src/css/main.scss, client/webserver/site/src/css/typography.scss, client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/html/forms.tmpl, client/webserver/site/src/js/forms.js, client/webserver/site/src/js/register.js, client/webserver/site/src/js/wallets.js, client/webserver/webserver.go, client/webserver/webserver_test.go
Resolves #616. Browsers do not permit loading from the client computer without a file selection dialog. Load them from the dexc machine (likely the same machine) upon request from the browser instead.
=> app: attempt wallet config load from default path

client/asset/btc/btc.go, client/asset/btc/walletclient.go, client/asset/btc/wallettypes.go, client/asset/ltc/ltc.go, client/cmd/dexcctl/simnet-setup.sh, client/core/trade.go, dex/testing/dcrdex/harness.sh
Introduces a new **btc.ExchangeWallet** method, `legacyBalance` that uses the `getwalletinfo` RPC to get mature and immature balance. The use of `legacyBalance` is triggered by setting a new boolean field, `LegacyBalance` in the `BTCCloneCFG`.
A couple of bug fixes too.
=> client/asset/ltc: make Litecoin work again

client/webserver/site/src/css/main.scss, client/webserver/site/src/html/markets.tmpl, client/webserver/site/src/js/markets.js
The markets page was briefly displaying an unnatractive state while loading. Show only a small loading icon until initial market data is recieved.
Might resolve #583.
=> app: soft load markets page

client/core/core.go, client/core/trade.go, server/auth/auth.go
When there is a refunded or inactive revoked match for an order that is still active because it is either still booked or has other active matches, you get spammed a bit by `tick()` when the inactive matches pass through all the redeemable/swappable/refundable checks.  This skips them in the `tick()` loop.
=> client/core,server/auth: silence logging of inactive matches in tick

client/core/core.go, client/core/core_test.go, client/core/trade.go, client/core/types.go
The asset balances should update on tip change regardless of new trade
actions that may have occurred.
e.g. even with on trade activity:
```
[TRC] CORE: notify: |DATA| (epoch) - Index: 266382840
[TRC] CORE: processing tip change for dcr
[TRC] CORE: notify: |DATA| (balance) balance updated
[TRC] CORE: notify: |DATA| (epoch) - Index: 266382841
```
Resolves https://github.com/decred/dcrdex/issues/620
=> client/core: update asset balance on tip change

client/webserver/live_test.go, client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/js/charts.js, client/webserver/site/src/js/markets.js
1. Fixes a bug with order unbooking that was leaving orders in the sell table 
2. Depth chart now maintains a fixed zoom (#625)
3. Depth chart tick marks now align with increments of lot size and rate step
=> app: order book table and chart fixes

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/livetest/livetest.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/simnet_test.go, client/asset/interface.go, client/core/core_test.go, client/core/trade.go, client/core/types.go, client/db/bolt/db.go, client/db/bolt/db_test.go, client/db/interface.go, client/db/types.go, client/webserver/site/webpack/analyze.js, dex/order/match.go
Modifies the `client/asset.Wallet` interface to return realized fees for the `Swap` and `Redeem` methods. Tracks the fees in **core**. Fee data is persisted in client DB.
Unfortunately requires a client DB wipe.
=> client: track order fees

client/asset/btc/livetest/livetest.go, client/asset/dcr/simnet_test.go, client/core/core_test.go, client/core/trade.go, dex/asset.go, server/asset/btc/btc_test.go, server/asset/dcr/dcr_test.go, spec/atomic.mediawiki
The swap contract lock times are somewhat arbitrary, but they are meant to give the users plenty of time to pursue their refund if the swap does not go as planned.
For chains like BTC and DCR, where transaction finality plus potentially long delays for initial block inclusion, theoretically permit a taker lock time as short as 5 hrs (8 very slow back to back confirms) + 3 hrs (long delay for inclusion in a block).  However, going shorter is not advisable due to the human element (wake up after falling asleep during a swap to discover the counterparty has gone dark, necessitating a refund).
These changes would change the taker/maker contract lock times from 24/48 hrs to 12/24 hrs.
Would longer locktimes be desirable for long mempool backlogs?
=> multi: 8 hr taker / 20 hr maker lock times

server/market/orderrouter.go
related to https://github.com/decred/dcrdex/issues/626.  This is a temporary change because of @behindtext machines
=> increase clienttime deviation permitted to 10 min

spec/orders.mediawiki
Part of solution to #643. 
See changes [here](https://github.com/buck54321/dcrdex/blob/match-status/spec/orders.mediawiki/#match-negotiation), near the end of the match negotiation section.
=> spec: add match_status route

client/rpcserver/rpcserver.go, client/rpcserver/rpcserver_test.go
client/rpcserver: Use subtle.ConstantTimeCompare.
client/rpcserver: Require password to create.
=> client/rpcserver: Require password.

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/core/core.go, client/core/log.go, client/core/trade.go, client/websocket/websocket.go, dex/msgjson/msg_test.go, dex/msgjson/types.go, dex/ws/wslink.go, server/asset/btc/btc.go, server/asset/dcr/dcr.go, server/auth/auth.go, server/auth/auth_test.go, server/comms/link.go, server/comms/server.go, server/swap/swap.go
**server/auth**: `'connect'` response excludes match-related requests for revoked matches
The `'connect'` response includes a list of active matches. connect also triggers
sending pending requests and messages. This change excludes match-
related requests from being sent if the match in question is not included
in the list of active matches. Only pending `revoke_match` requests are
allowed in this case, purely as a courtesy to the client. Similarly, the connect
timeout for `revoke_match` requests is now 4 hours.
Test `RequestWhenConnected`/`SendWhenConnected`.
**dex/msgjson**: add `(*Message).ExtractMatchID`
**client/core**: missing matches are assumed revoked
Also improve logging on the most important client and server events.  INF level for a trade (both sides):
Maker, sell 20 DCR
> …
=> server/auth,multi: connect resp excludes revoked match requests

client/webserver/site/src/js/app.js, client/webserver/site/src/js/markets.js
Enables console logging of some useful debugging routes. The logging system can be used liberally whenever a need arises.
To enable logging, just type `enableLogger('notes', true)`, or `enableLogger('book', true)` in the browser's js console. Call `enableLogger` with `false` to disable.
=> app: add custom front end loggers

server/asset/btc/btc_test.go, server/asset/btc/utxo.go, server/asset/dcr/dcr_test.go, server/asset/dcr/utxo.go
Before, if there was no mainchain block at the specified height, a different error was returned, but if a block disappears from mainchain, it must be a reorg, and the constant `ErrReorgDetected` should have been returned instead.
=> server/asset/{dcr,btc}: treat all mainchain not founds as reorgs

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/livetest/livetest.go, client/asset/btc/wallettypes.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/simnet_test.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/trade.go, client/core/trade_simnet_test.go
Auto-trigger find redemption for Taker swaps that have gotten at least `swapConf` confirmations, has neither been redeemed by Maker or refunded to Taker.
The `FindRedemption` method is refactored to allow batching multiple contract coin ids in one call.
The dcr and btc implementations of the `FindRedemption` method are also modified to push find redemption requests to a goroutine dedicated to scanning blocks for potential contract spends.
There are 2 motivations for using a separate goroutine for processing find redemption requests:
- enable loading block txs once for multiple contracts (including multiple batches of contracts from different calls to `FindRedemption`)
- keeping the redemption search alive when a contract's spender is not found up till the current best block. When that …
=> app: auto-find redemption when Maker goes dark after Taker swap

client/core/core.go, client/core/core_test.go, client/core/trade.go
Each tracked trade needs to have it's matches checked as missing or not, but it was checked the other way around (each server match is checked against matches for the trades that are reported).
```
[DBG] CORE: Authenticated connection to 127.0.0.1:7232, 0 active matches
[TRC] CORE: Revoked match 9ad9a6e7feae2ffe8158ce9f182644c39d48a301cca9afc4855ce85b21c59575 (Taker) in status MakerSwapCast considered inactive.
[WRN] CORE: DEX 127.0.0.1:7232 did not report active match 9ad9a6e7feae2ffe8158ce9f182644c39d48a301cca9afc4855ce85b21c59575 on order 9a76f9da8c42f60a0c46d39588a027b08c3833fa4f88f7df8b482b36e5dbb2f1 - assuming revoked.
[ERR] CORE: notify: |ERROR| (order) Missing matches - 1 matches for order 9a76f9da were not reported by "127.0.0.1:7232" and are considered revoked - Order: …
```
=> client/core: missing matches were incomplete

dex/testing/btc/base-harness.sh, dex/testing/dcr/create-wallet.sh, dex/testing/dcr/harness.sh
Any shell commands executed inside a tmux window (e.g. via `send-keys`) are recorded in shell history.  This change prevents them from flooding the history file.
=> testing: do not save harness setup commands to shell history

client/webserver/site/src/js/app.js, client/webserver/site/src/js/markets.js, client/webserver/site/src/js/ws.js
Resolves https://github.com/decred/dcrdex/issues/583
Apparently when the browser (Firefox in this case) attempts `new window.WebSocket(uri)` enough times, it takes longer and longer to fail connecting and instead hangs for longer and longer.  This delayed connect timeout state seems to be browser-wide effecting all tabs and apparently persists across hard-refresh for some time.
To address this, we set a connect timeout to prevent these attempts from taking longer than 0.5 seconds.
There is a remaining issue of the app's `reconnected` reloading the page when websocket connects, which in turn disconnects and reconnects the just reconnected websocket.  Not ideal, but it does work.
=> client/webserver/site: websocket connect timeout

client/core/core.go
When an order is retired (eligible according to `(*trackedTrade).isActive`), all funding and change coins are unlocked.  This will be redundant with other unlock sites, and likely much of PR #648.
=> client/core: just unlock trade coins on retire

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/trade.go, dex/order/status.go, server/market/market.go
Coins are currently unlocked when
- a market order or limit order with tif immediate does not get matched
- an order is canceled (i.e. by user action)
- a market is suspended with persist=false
Other times to unlock coins (implemented in this PR):
- when new orders could not be submitted to the server, e.g. if sending the
request or validating the server's response fails.
- when all matches are either swapped or revoked for unbooked orders, i.e.
orders that will not receive future matches.
- after sending a swap, unlock the spent outputs to ensure accurate balance
reporting.
~Also revoke orders in UnbookOrder note handler to ensure that coins are
unlocked for server-revoked orders. If such orders remain at status Booked,
their coins will never be unlocked because the expectation would be …
=> client/core,asset: ensure coins are unlocked when no longer needed

client/webserver/site/src/js/markets.js
This allows you to click on the red thing as well as the lock icon:
=> client/webserver/site: allow clicking on expired balance ico to unlock

client/websocket/websocket.go
The payload for the browser's "book" route is a `marketResponse`, not a `BookUpdate` with an embedded `marketResponse` inside *its* payload.
=> client/websocket: FreshBookAction/"book" route payload fix

client/comms/wsconn.go, client/comms/wsconn_test.go, client/core/core.go, client/core/core_test.go, client/core/trade.go, dex/ws/wslink.go
Swap contracts are no longer permitted to be broadcast if the DEX connection is known to be down.  This can happen when a computer or client process comes out of suspend and immediately tries to take their action, particularly the taker trying to bcast their swap.  The net connection's read timeout must still put the link into a failed state quickly for this to work during a resume, but this connectivity check is also valuable with normal connectivity trouble, not just machine/process suspend.
Triggering of ticks with the tick timer is also modified to skip tick execution if a long delay since the previous timer fire is detected (computer resume) to allow time for DEX re-connection.  This together with the swap check described above prevents needlessly broadcasting a swap contract for a …
=> client/core: safe swap and comms tweaks

server/account/account.go, server/auth/auth.go, server/auth/auth_test.go, server/auth/cancel.go, server/auth/cancel_test.go, server/cmd/dcrdex/config.go, server/db/driver/pg/orders_online_test.go, server/dex/dex.go, server/market/market.go, server/swap/swap.go
server/auth: cancel ratio grace period
Implement the new user grace period by not enforcing until
total / (1+total) > threshold
This also begins enforcing the cancellation ratio as orders are canceled
and orders fully settled.  Previously it was just checked on connect.
The default latest orders window is now 100, up from 25.
The spec changes are in https://github.com/decred/dcrdex/pull/671
=> server: new user cancel ratio exception

client/cmd/dexc/go.mod, client/cmd/dexc/go.sum, client/cmd/dexc/main.go, client/cmd/dexc/ui/config.go, client/cmd/dexc/ui/log.go, client/cmd/dexc/ui/serverview.go, client/cmd/dexc/ui/widgets.go, client/cmd/dexcctl/go.sum, dex/logging.go, dex/testing/dcrdex/harness.sh, go.mod, go.sum, server/cmd/dcrdex/config.go, server/cmd/dcrdex/go.sum, server/cmd/dexcoin/go.sum
This adds a `--loglocal` switch to use the local time zone in log entries, with the default to log UTC time stamps.
Without `--loglocal`, it displays the following for a reference:
`2020-09-03 19:06:50.697 [INF] MAIN: Logging with UTC time stamps. Current local time is 14:06:50 CDT`
=> multi: add loglocal flag, default to utc

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/livetest/livetest.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/simnet_test.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/trade.go, client/rpcserver/handlers_test.go, client/webserver/live_test.go, client/webserver/webserver_test.go
Funding coins are no longer unlocked when ExchangeWallets shuts down,
so trying to retrieve funding coins from unspent outputs may fail, unless
the coins were manually unlocked.
Also fixed issues with redeem script being required, but unset for some coins
such as when parsing `listunspent` results in `dcr.parseUTXOs` and when
loading funding coins from `listlockunspent` results in `btc.FundingCoins`.
=> client/asset: retrieve funding coins from locked outpoints

client/core/core.go, client/core/core_test.go, client/core/notification.go, client/core/trade.go, client/core/types.go, client/core/wallet.go, client/db/types.go, client/rpcserver/rpcserver.go, client/rpcserver/rpcserver_test.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/site/src/js/markets.js, client/webserver/webserver.go, client/webserver/webserver_test.go
Resolves #672.
**Show contract-locked amounts.**
- Core: when retrieving and setting a wallet's balance, calculate and include
total amounts locked in unspent swap contracts, i.e. contracts sent by the client
that have not been refunded by the client or redeemed by the counter-party (with
the exception of maker contracts which are always considered spent if maker has
redeemed taker's contract, even if maker's contract has not redeemed by taker.
- Webserver/site: display locked balance as bal.locked + bal.contractlocked.
**Update balances when coins are unlocked.**
The following actions that lead to coin unlocking already cause wallet
balances to be updated:
- match revocation (revoke_match handler -> tracker.revokeMatch)
- inactive order retirement (core.listen -> bcastTimeout ticker) …
=> app: show contract-locked amounts and update balances when needed

spec/admin.mediawiki, spec/community.mediawiki, spec/fundamentals.mediawiki
Define a new-user bring up / grace period with respect to the enforcement of cancellation ratio.  Implementation in https://github.com/decred/dcrdex/pull/638
=> spec: define cancel ratio new user period

client/core/trade_simnet_test.go, dex/testing/dcr/harness.sh, dex/testing/dcrdex/harness.sh, server/cmd/dcrdex/config.go, server/db/driver/pg/orders.go, server/market/orderrouter.go, server/matcher/match.go, server/swap/swap.go, server/swap/swap_test.go
The contains a number if fixes to the server's inaction checks:
- Fix inaction asset ID checks skipping checks because of incorrect swapAsset.
- Set swapConfirmed time from the block time, not time.Now, which was causing inaction check to pass by fractions of a second.
- On startup, schedule an inaction check for each asset.
- Separate block based and "event"-based checks.  `NewlyMatched`->`MakerSwapCast` timing starts at the time the match requests are sent (**event-based**), `MakerSwapCast`->`TakerSwapCast` starts at the time the maker's swap reaches swapConf (**block-based**), `TakerSwapCast`->`MakerRedeemed` starts at the time the taker's swap reaches swapConf (**block-based**), and `MakerRedeemed`->`MatchComplete` starts at the time the maker broadcasts their redeem, notifies server, …
=> server/swap: inaction check fixes

dex/msgjson/types.go, server/auth/auth.go, server/auth/auth_test.go, server/db/driver/pg/internal/orders.go, server/db/driver/pg/orders.go, server/db/driver/pg/orders_online_test.go, server/db/interface.go, server/market/market_test.go
Similar in implementation to the match_status route, the order_status route
accepts a slice of `struct{Base,Quote,OrderID}` and returns the status and
fill amts for the requested **user-submitted** orders that are found in db.
Will put up a follow up with spec changes for the new `order_status` route
and the updated `connect` route.
=> server/{auth,db}: add order_status route

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/dcr/dcr.go, dex/networks/btc/script.go
Resolves https://github.com/decred/dcrdex/issues/690
Even when context is canceled or timed out, it is necessary to wait for
launched goroutines.
I think we might want to refactor some of this pretty soon.  Most likely the best pattern is to pass the
`Context` into the two find functions and not have them be goroutines at all.
=> client/asset/btc: FindRedemption has to wait for goroutines

client/core/core.go, client/core/trade.go, client/webserver/api.go, client/webserver/webserver.go, server/dex/dex.go, server/market/market.go, server/market/market_test.go, server/market/orderrouter.go, server/market/routers_test.go
Resolves https://github.com/decred/dcrdex/issues/675
dexc
```
2020-09-16 12:07:28.584 [DBG] CORE[dcr]: Change output size = 36, addr = Ssf5q5eQ68RG5uhXnvc82bKv4cyKSwJ5VDn
2020-09-16 12:07:28.586 [DBG] CORE[dcr]: 4 signature cycles to converge on fees for tx 8e653cbc34cc5000951fd35f89e1bb2cd5eb19817762216bee0ff77b0f9ff4d9: min rate = 11, actual fee rate = 11 (2772 for 251 bytes), change = true
2020-09-16 12:07:28.589 [INF] CORE[dcr]: Funding 2000000000 atom order with split output coin 8e653cbc34cc5000951fd35f89e1bb2cd5eb19817762216bee0ff77b0f9ff4d9:0 from original coins [a7a74691be2ec98b6e060eab92be6a653304be0c03cb7cf38c0915d1f7239099:1]
2020-09-16 12:07:28.589 [INF] CORE[dcr]: Sent split transaction 8e653cbc34cc5000951fd35f89e1bb2cd5eb19817762216bee0ff77b0f9ff4d9 to accommodate swap of …
```
=> server/market,client/core: order router waits for funding coins on asset net

client/webserver/live_test.go, client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/js/charts.js, client/webserver/site/src/js/orderbook.js
For the depth chart gap calculations, epoch orders are only considered if there are no booked orders on the side. This prevents some silly chart renders with illogical gaps based on epoch orders with matchable rates.
=> app: prevent epoch orders from pushing depth chart around

client/core/bookie.go, client/core/core_test.go, client/core/types.go, client/order/epochqueue.go, client/order/orderbook.go, client/rpcserver/handlers.go, client/rpcserver/rpcserver_test.go, client/webserver/live_test.go, client/webserver/site/src/js/app.js, client/webserver/site/src/js/markets.js, client/webserver/site/src/js/orderbook.js, client/webserver/site/src/js/ws.js, client/webserver/webserver_test.go, client/websocket/websocket.go, client/websocket/websocket_test.go
Moves responsibility for sending initial order book notification from **webserver** to **core**. Just populate the new order book feed with the initial `FreshBookAction` update as soon as it's created, under lock. This solves some bugs where the book is processed client side before `book_order` messages that came first, leading to double entries. This also precludes the fancy handling of the `webserver.marketResponse` that we were doing. That type is eliminated now, and the `MarketPage` handles the `BookUpdate` directly.
Include the epoch index in the **OrderBook**'s `epochQueue` orders. The fixes a `MarketPage` bug where epoch orders [were being added to the book](https://github.com/decred/dcrdex/blob/05e5254242d6f91ef7bb8ab49644f8bf45eb8b18/client/webserver/site/src/js/markets.js#L495-L4 …
=> core: fix some order book feed bugs

client/core/core.go, client/core/core_test.go, client/core/types.go
Included in and superseded by PR #705 
This adds a trade resumption handler to the client core as well as associated tests.
**Dependent on #269**
=> client/core: handle trade resumption messages. 

client/core/core.go, client/core/trade.go
Before returning `only one cancel order can be submitted per order per epoch` error message, first check if the existing cancel order is stale and delete the cancel order to allow submission of new cancel order.
=> client/core: delete stale cancel order on cancel re-attempt

client/core/core.go, client/webserver/live_test.go, client/webserver/site/src/css/main.scss, client/webserver/site/src/css/main_dark.scss, client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/js/app.js
Before, only one poke-severity notification was shown at a time, and would be simply replaced if another notification came immediately after. This change makes all poke notes persist for ~4 seconds before fading away. If more than one is visible, they stack vertically.
Bonus: DEX connection and disconnection notes are now only poke-level. This resolves #428. We really don't need to persist those. If there's a problem, we'll see an error.
=> app: show multiple poke notes

client/asset/dcr/dcr.go, client/asset/dcr/simnet_test.go
Issue with outputs spent in txs broadcast with sendrawtransaction being
temporarily returned by listunspent is [now fixed in dcrwallet](https://github.com/decred/dcrwallet/commit/f5bd1a27b888a1fc5df1efb5a83d2785a4a04fd3). Outputs
spent this way (such as in split transactions) are no longer cached in
the `splitFunds` map.
Min. required dcrwallet version bumped.
=> client/asset/dcr: retire splitFunds cache

server/db/driver/pg/internal/matches.go, server/db/driver/pg/matches_online_test.go
Every user was being credited for every other user's success when retrieving match outcomes from the DB.  This adds the account constraint that is required for successes.  Note that putting `AND (makerAccount = aid OR takerAccount = aid)` before all the status constraints results in a more optimized query plan according to `EXPLAIN ANALYZE`, esp. if we create indexes on these columns.
=> include omitted account constraint, needed for successes

client/core/core.go, client/core/trade.go, client/core/types.go, client/webserver/site/src/html/markets.tmpl, client/webserver/site/src/js/markets.js
The only thing we were using the cancel order for was its `targetID` to find the target order. Might as well just send the target order. This also solves the weird thing with the `cancelStatus` element. That element is gone now in favor of just using the order status column. One new notification was required.
=> core/app: don't send cancel order for OrderNote

client/core/core.go, client/core/core_test.go, client/core/status.go, client/core/trade.go, server/db/driver/pg/internal/matches.go, server/db/driver/pg/matches.go, server/db/driver/pg/matches_online_test.go, server/db/interface.go, server/swap/swap.go, server/swap/swap_test.go
NOTE: This PR is now targeting on the `status-integ`.
**server/db**
- Remove `aSigAckOfBRedeem` column from matches table.
- Storing the participant (taker) redeem coin sets `active = FALSE`.  Previously this was set when both redemption acks were received.
Now any match in the table with status `MatchComplete` will also be inactive.  Previously matches could be (and often were) `MatchComplete` but also active.  This was not great.
**server/swap**
- `processBlock` no longer checks the redeem txns for their confirmations.  We were checking against swapConf, but confirmations on the redeem txns never were important, only that both parties could author and bcast their redeem txns (the secret was shared and both parties used it to spend the respective contract outputs).
- `processBlock` just …
=> server/{db,swap},client/core: no maker redemption ack, no redeem confs

client/asset/btc/btc.go, client/asset/btc/livetest/livetest.go, client/cmd/dexc/go.sum, client/cmd/dexcctl/go.sum, dex/networks/btc/script.go, dex/networks/btc/script_test.go, server/asset/btc/tx.go, server/swap/swap.go
Server was already using vbytes for fee rate in the contract audit. This changes the client's btc backend to use vsize (not serialized tx size) in computing BTC txn fee rates, and updates the server's logging of the fee rate on the audited contract.
**dexc** on this PR
`[DBG] CORE[btc]: 2 signature cycles to converge on fees for tx 5ca1b392...: min rate = 6, actual fee rate = 6 (852 for 142 bytes), change = true`
`[INF] CORE: Broadcasted transaction with 1 swap contracts for order 62332bf.... Fee rate = 6. Receipts (btc): [5ca1b392:0]`
(note **852 for 142 bytes** and **actual fee rate = 6**)
**dcrdex**  on this PR
`[DBG] SWAP: Optimal fee rate for "btc": 6`
...
`[DBG] SWAP: processInit: valid contract {txid = 5ca1b392, vout = 0} (btc) received at 2020-10-08 18:33:06.319 +0000 UTC from …
=> client/asset/btc: use vbytes when computing fee rate

client/core/core.go, client/webserver/live_test.go, client/webserver/middleware.go, client/webserver/site/src/css/application.scss, client/webserver/site/src/css/main.scss, client/webserver/site/src/css/main_dark.scss, client/webserver/site/src/css/market.scss, client/webserver/site/src/css/market_dark.scss, client/webserver/site/src/css/settings.scss, client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/html/forms.tmpl, client/webserver/site/src/html/markets.tmpl, client/webserver/site/src/html/settings.tmpl, client/webserver/site/src/js/app.js, client/webserver/site/src/js/charts.js, client/webserver/site/src/js/doc.js, client/webserver/site/src/js/settings.js, client/webserver/site/src/js/state.js, client/webserver/webserver.go
The note bell gets a number instead of a dot. All notifications > POKE now show in the poke notes (renamed to popup notes). POKE-severity notification history is now available as through the bell dropdown as a "Recent Activity" feed, but is not persistent across sessions. 
Up to 100 notifications will be shown in the bell dropdown now (used to be 10).
The popup notifications can now be disabled on the settings page. Default is on.
Settings page is given a proper layout.
A handful of other CSS tweaks.
=> app: improved notifications UI

client/core/core.go, client/core/status.go, client/core/trade.go, client/core/trade_simnet_test.go
The coins sent with the retried `'redeem'` requests were empty. This fixes
the `finalizeRedeemAction` call to use the redeem coin.
This also removes a misplaced log in `resolveServerMissedTakerRedeem`.
It is not unexpected for the maker to be at `MatchComplete` with the
server at `MakerRedeemed` if the taker hasn't done their `'redeem'`.
In trade_simnet_test.go, set `Core`'s logger in `core.Config`.  Note that
these simnet tests are presently failing due to recent changes on master.
=> client/core: fix resendPendingRequest sending wrong redeem coin

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/livetest/livetest.go, client/asset/btc/livetest/regnet_test.go, client/asset/btc/walletclient.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/ltc/ltc.go, dex/networks/btc/script.go, dex/networks/btc/script_test.go, server/asset/btc/btc.go, server/asset/btc/btc_test.go, server/asset/btc/testing.go, server/asset/btc/utxo.go, server/asset/ltc/ltc.go, server/market/orderrouter.go
Using segwit contracts saves us something like 30% in transaction fees. This will give us a little bit of wiggle room on Bitcoin markets where on-chain fees are outrageous.
Segwit is implemented as an option for the wallet backends and server's asset backends. Bitcoin is configured to use segwit by defualt. Litecoin will too, and I've tested it, but I'm leaving it in non-segwit just to demonstrate the option. It's important to offer the option, because even though some bitcoin forks won't have segwit, our clone backend might still be useful.
=> assets: implement segwit btc swap contracts

client/asset/btc/btc.go, client/asset/dcr/config.go, client/asset/dcr/dcr.go, client/asset/ltc/ltc.go, dex/networks/btc/config.go, server/asset/btc/btc_test.go, server/asset/dcr/dcr_test.go, server/swap/swap_test.go
Given the recently reduced importance of the redeem transactions being mined promptly, this introduces a new client exchange wallet option to set the confirmation target for the redeem transaction.
The contract transaction may already be created with segwit inputs to lower fees (and accounting for this is corrected in https://github.com/decred/dcrdex/pull/729), but the redeem transactions will need [p2wsh contract prevouts](https://github.com/decred/dcrdex/issues/733) as their inputs to get the segwit discounts as well.  However, quickly mining the redeem txns is not nearly important as with the swap contract txns.  Thus, the user should have the ability to use lower fee rates for the redeem txns.
The default for BTC is 2 blocks; default for DCR is 1 block.
This also sneaks in a test data …
=> client/asset: redeem confirmation target blocks

server/book/book.go, server/book/orderpq.go, server/market/market.go, server/market/orderrouter.go, server/market/routers_test.go
Addressing https://github.com/decred/dcrdex/issues/615
When a user submits a new order, all of that user's unfilled book orders have their funding coins checked.  If any of them are spent, those orders are unbooked.  The newly submitted order is processed normally after that.  The idea behind checking on order placement is to prevent a user from moving the same bunch of coins around into new utxos to fund a large number of bogus (unfunded) orders.  Although a user could submit multiple orders with valid funding coins, then proceed to spend those coins, this user could affect similar disruption by simple not executing swaps on match, so continually checking funding coins for online users is not particularly useful.  PR #725 handles users going offline.
e.g.
```
[TRC] MKT: Checking 2 …
```
=> market: verify unspent status of unfilled orders

client/core/core.go, client/webserver/site/src/js/app.js, client/webserver/site/src/js/markets.js
1. Unlock the `dexAccount` when the user logs back in after logging out.
2. Don't try to connect to already connected wallets. It can cause an error and leave the wallet connected but with a `nil` `WaitGroup` (Resolves #751).
3. `refreshMarkets` and `refreshUser` after DEX reconnect. Fixes an issues where orders weren't showing in the "My Orders" table after reconnect.
4. UI: Update times for notifications and activity feed more often.
=> core/app: bug roundup

client/asset/interface.go, client/core/core.go, client/core/trade.go, client/core/types.go
Resolves #735.
Compute the following locked amounts for each DEX market (across all active orders):
- `BaseOrderLocked` and `QuoteOrderLocked` - total funds currently locked for swap, but not actually swapped yet.
- `BaseContractLocked` and `QuoteContractLocked` - total funds locked in unspent (i.e. unredeemed / unrefunded) swap contracts.
Also adds an `xcWallet.balance.OrderLocked` to store the total amount of funds locked for swaps in a wallet, for all DEX markets.
Noting that while the new `xcWallet.balance.OrderLocked` field reports the total amount locked by the DEX client for order funding purposes, the existing `xcWallet.balance.Locked` amount continues to report the **total amount locked in a wallet** i.e. funds locked by `Core` for order funding purposes AND funds locked outside …
=> client/core: split locked balances in categories

dex/runner.go, dex/ws/wslink.go, server/auth/auth.go, server/auth/auth_test.go, server/auth/registrar.go, server/comms/server.go
This tracks actively running fee coin waiters by account ID.  An account is only permitted to start one waiter at a time.
Also fixes two leaks: a ticker leak in `dex/ws.WsLink`, and a context leak in `dex.ConnectionMaster`.  BTW, the `RWMutex` locking in the `ConnectionMaster` methods seems unnecessary if `Disconnect` and `Wait` are never called before `Connect`.
=> server/auth: prevent multiple fee coin waiters for one account

server/admin/prompt.go
Unfortunately this is required to build dexcctl on Windows too since it uses server/admin for a PromptPassword function.
=> server/admin: allow compilation on Windows

client/webserver/site/src/js/ws.js
This pull request addresses https://github.com/decred/dcrdex/issues/583
In firefox executing a request when the websocket is not open would result in a blocking infinite loop. The initial request from the user would be put into the queue due to the websocket being closed. Then that queued request was executed in the onopen event. Then that request would be queued again and the cycle continued infinitely. 
It seems that firefox is blocked from fulfilling the request due to the loop, where chrome does actually fulfill the request which discards the looping action and the browser renders the page requested.
=> client: markets page randomly spins

client/asset/dcr/dcr.go, client/core/core.go, dex/calc/convert.go, dex/msgjson/types.go, server/auth/auth.go, server/auth/auth_test.go, server/auth/latest.go, server/auth/latest_test.go, server/book/book.go, server/db/driver/pg/internal/matches.go, server/db/driver/pg/internal/orders.go, server/db/driver/pg/matches.go, server/db/driver/pg/orders.go, server/db/interface.go, server/market/market.go, server/market/market_test.go, server/market/orderrouter.go, server/market/routers_test.go, server/matcher/match_test.go, server/swap/swap.go, server/swap/swap_test.go
This implements a concept for limiting user order quantities.
- Users are limited in the amount they can have in active swaps ("settling"). The limit is computed based on the user's match history.
- Only orders that are considered "likely taker" are subject to this limit.  Likely taker includes: market order, limit with TiF immediate, limit with TiF standing and a rate that is within the spread.
- Separate to the taker order limit, there is an constant limit for booked order quantity in lots, to which all submitted standing limit orders are subject to.  To be conservative, an order may be considered "likely taker" AND be subjected to this book limit at the same time.
- Match outcome history now includes value of the match (swapped, stuck long, stuck short, and spoofed).  The match outcome …
=> server/{auth,db,market,swap}: user order quantity limits

client/cmd/dexc/main.go, client/cmd/dexc/ui/config.go, client/cmd/dexc/version/version.go, server/cmd/dcrdex/config.go
This is all reused code, so fairly trivial.
dexc has a version package because config is still in the ui package, while dcrdex does not.  This will all likely change.
```
$    go build
$    ./dexc -V
dexc version 0.1.0-pre+dev (Go version go1.15.3 linux/amd64)
$    go build -ldflags "-X decred.org/dcrdex/client/cmd/dexc/version.appPreRelease=release -X decred.org/dcrdex/client/cmd/dexc/version.appBuild="
$    ./dexc -V
dexc version 0.1.0-release (Go version go1.15.3 linux/amd64)
$    go build -ldflags "-X decred.org/dcrdex/client/cmd/dexc/version.appPreRelease= -X decred.org/dcrdex/client/cmd/dexc/version.appBuild=$(git rev-parse --short HEAD)"
$    ./dexc -V
dexc version 0.1.0+05350967 (Go version go1.15.3 linux/amd64)
```
```
$    ./dcrdex -V
dcrdex version 0.1.0-pre+dev (Go …
```
=> set 0.1 in dexc and dcrdex versions

client/webserver/webserver.go
Because Windows can't seem to figure it out?
=> webserver: set content-type explicitly for js and css files

client/core/core.go, client/core/trade.go, client/webserver/webserver.go
Startup now prints a couple helpful new messages:
```
2020-10-22 19:19:54.820 [INF] WEB: Web server listening on 127.0.0.1:6758
****  OPEN IN YOUR BROWSER TO TRADE  --->  http://127.0.0.1:6758  ****
2020-10-22 19:19:55.118 [DBG] CORE: notify: |POKE| (conn) DEX connected - DEX at 127.0.0.1:7232 has connected
2020-10-22 19:19:55.120 [DBG] CORE: Broadcast timeout = 1m0s, ticking every 20s
2020-10-22 19:19:55.120 [INF] CORE: Connected to DEX server at 127.0.0.1:7232 and listening for messages.
2020-10-22 19:19:55.120 [DBG] CORE: connectDEX for 127.0.0.1:7232 completed, checking account...
2020-10-22 19:19:55.120 [DBG] CORE: dex connection to 127.0.0.1:7232 ready
2020-10-22 19:19:55.120 [INF] CORE: Successfully connected to 1 out of 1 DEX servers
2020-10-22 19:19:55.120 [INF] CORE: Loaded 1 …
```
=> client: startup improvements and minor fixes

client/cmd/dexc/ui/config.go, client/core/core.go, client/core/core_test.go, client/core/status.go, client/core/trade.go, client/core/trade_simnet_test.go, client/core/types.go
**dexc**
- Set default log level to debug.
**core**
- Allow retries of failed swaps until the broadcast timeout has expired
- Allow retries of redemptions frequently until the broadcast timeout, and less frequently afterwards until resolution.
- Do not group swaps or redemptions for retries.
- Retries on failed swaps and redeems are metered so that they don't run every tick, but reconfiguring a wallet clears the tick meterer.
=> core: don't fail match on misses and redeem errors

client/asset/btc/btc.go, client/asset/ltc/ltc.go, client/webserver/site/src/css/market.scss, client/webserver/site/src/css/market_dark.scss, client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/html/markets.tmpl, client/webserver/site/src/html/order.tmpl, client/webserver/site/src/js/app.js, client/webserver/site/src/js/charts.js, client/webserver/site/src/js/markets.js
1. Fix bug with depth chart unbinding its resize handler
2. Links to transaction outputs open in new tab
3. Harmonize "pre-split" and "pre-size" at the UI level
4. Use more familiar "immediate or cancel" for "match for one epoch only". Add a tooltip with more explanation
5. Change order submission button text and color to indicate buy/sell
6. Improves the setNotes -> prependNoteElement loop to skip intermediate saves
7. Add a warning in order the order confirmation dialog about keeping the client and blockchains daemons running during settlement.
=> ui: bugs and usability fixes

server/book/book.go
The book's Clear function used when purging the book during a suspend operation works by allocating new priority queues.  This fixes the heap orientation of the sell side, and reduced the default order book capacity to a more sensible level.
=> server/book: Clear uses correct heap orientation

client/core/core.go, client/core/core_test.go, client/core/status.go, client/core/trade.go, server/swap/swap.go
Fixes some issues with match status resolution, the worst of which could result in client deadlock. 
1. chappjc's `extras` loop bug fix from #802 
2. bug with locking the `matchStatusConflict` in a loop, because we were creating a `matchStatusConflict` for every match instead of one per order. That is resolved, and the offending locking pattern has been remedied.
=> core: match status resolution fixes

client/core/core.go, client/core/core_test.go, client/core/trade.go
Resolves https://github.com/decred/dcrdex/issues/780
This delays a trade's tick that is usually launched by the redemption (and audit) requests to allow for multiple redemptions to be batched more effectively. Specifically, the handlers now process the message and update the trade and match fields so that when tick happens after a delay, there can be multiple redeems provided to `redeemMatches` instead of one at a time several times.
=> client/core: batch trade ticks for audit and redemption reqs

server/auth/auth.go, server/dex/dex.go, server/market/market.go
**server/dex**
This reorders the subsystem stack so that DEX manager shutdown is ordered properly now.  Namely:
- <s>comms server shuts down after the subsystems that use it (all but assets)</s> comms didn't move because we want it _started_ after the subsystems that use it are up for the sake of _incoming_ message handling, even though stopping it before those dependent subsystems stop can result in dropped _outgoing_ messages
- book router shuts down after the markets that use it
**server/market**
When a market is stopped by context cancellation (not a market suspend admin command), it does not wait for the current epoch to close, so any orders in that truncated epoch were just being dropped without changing their status from epoch to executed (how a no-match/fail is normally handled …
=> server/{dex,market}: cleaner shutdown

client/core/notification.go
The current capacity of 16 is too small.
=> client: bump notification channel capacity to 1024

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/comms/wsconn.go
See https://golang.org/pkg/sync/atomic/#pkg-note-BUG. Have seen a panic in the wild.
=> align 64-bit fields for atomic

client/webserver/site/src/html/order.tmpl, client/webserver/site/src/js/orderutil.js, client/webserver/types.go
1.Cancel matches are not considered for the "settled" calculation on /orders or /order. Also fixes a misleading part of the filled display that should have excluded cancellations.
2.The match card for a cancellation no longer shows trade-specific details.
=> ui: fix settled calculations and displayed values

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/livetest/livetest.go, client/asset/btc/walletclient.go, client/asset/btc/wallettypes.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/simnet_test.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/trade.go, client/core/wallet.go
This PR introduces wallet password caching and some additional logic to ensure wallets are unlocked when needed. Another important change is that the `asset.Wallet` interface now has a `Locked() bool` method that needs to be implemented. Already done for **dcr** and **btc** obviously.
=> core: avoid wallet locked errors

server/book/book.go, server/book/book_test.go, server/book/orderpq.go, server/book/orderpq_test.go
This hides the notion of capacity from `Book` consumers by creating a book with modestly-sized buy/sell priority queues instead of the mammoth defaults of before, and the underlying `OrderPQ`s automatically reallocate into a larger queue when `Insert`s push the queue to capacity.
The queue increases by the larger of `minCapIncrement` (4096) or 1/8th of the current utilization (note that utilization is the same as capacity when realloc is triggered by `Insert`->`Push`).
The queue will also automatically reallocate to a *smaller* capacity when `Extract*`/`Remove*`/`Pop` reduces the utilization of the queue to a point where the ideal capacity is significantly below the current capacity, specifically `savings > deallocThresh && savings > pq.capacity/3` where `deallocThresh = 10 * …
=> server/book: automatic book reallocation

client/core/core.go, client/core/core_test.go, client/core/notification.go, client/core/trade.go, client/core/types.go, client/webserver/live_test.go, client/webserver/site/src/css/main.scss, client/webserver/site/src/css/market.scss, client/webserver/site/src/css/order.scss, client/webserver/site/src/css/orders.scss, client/webserver/site/src/html/order.tmpl, client/webserver/site/src/js/app.js, client/webserver/site/src/js/order.js, client/webserver/site/src/js/orderutil.js, client/webserver/types.go
Add confirmation count to match cards on the order details page, for matches in `MakerSwapCast` or `TakerSwapCast`. It's a bigger job than it sounds like, because 1) we weren't tracking confirmation count on our own swaps yet, and 2) I didn't think we should add the count unless it updated live, so the count, match status, and various coin ID links will update live now. 
There are just a few more pieces needed to make the whole page update live. Will save the rest for another PR.
=> core,ui: add confirmation for currently waiting swap

client/core/core.go, client/core/core_test.go, client/core/errors.go, client/core/types.go, client/rpcserver/rpcserver.go, client/rpcserver/rpcserver_test.go, client/rpcserver/types.go, client/rpcserver/types_test.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/webserver.go, client/webserver/webserver_test.go
Previously, caller had to load the file themselves. This allows a either the file name or the file contents. `Core` will load the file if a file name (`string`) is provided. `[]byte` will be assumed to be the certificate file contents and used unmodified.
This was originally part of #717.
=> core: allow filename for tls cert

client/core/bookie.go, client/core/core.go, client/core/notification.go, client/core/trade.go, client/webserver/site/src/js/app.js
Broken off from #717. Includes `MatchNote` changes that aren't yet used, and a correction for the details of an `OrderNote`.
=> core: constant subjects for notifications

client/core/core.go, client/core/core_test.go, client/core/notification.go, client/core/status.go, client/core/trade.go
This prevents contract auditing from blocking all incoming messages (and pretty much any other activities for the trade in question).
Instead of expiring the coin waiter after broadcast timeout, it just goes until it finds the contract or the match is revoked.
The trackedTrade locking is also changed a great deal in match status resolution, no longer locking a trackedTrade unless and until needed.
=> processAudit runs txn search async, redo match res. locking

client/core/bookie.go, client/core/core.go, client/orderbook/bookside.go, client/orderbook/bookside_test.go, client/orderbook/epochqueue.go, client/orderbook/epochqueue_test.go, client/orderbook/orderbook.go, client/orderbook/orderbook_test.go, client/orderbook/rateindex.go, client/orderbook/rateindex_test.go
match_proof notifications are not in sequence with other book messages and should not be used to indicate a transition from one epoch to another.
Since match_proof lags epoch close by up to preimage request timeout and some additional latency, the `OrderBook` needs to track several epochs for the purposes of evaluating these lagging match proofs.
Resolves https://github.com/decred/dcrdex/issues/824 and https://github.com/decred/dcrdex/issues/628
=> client/core: epoch tracking right

dex/order/match.go, dex/order/order.go, server/admin/api.go, server/admin/server.go, server/admin/server_test.go, server/db/driver/pg/internal/matches.go, server/db/driver/pg/internal/orders.go, server/db/driver/pg/matches.go, server/db/driver/pg/matches_online_test.go, server/db/driver/pg/orders.go, server/db/driver/pg/orders_online_test.go, server/db/driver/pg/testhelpers_test.go, server/db/interface.go, server/dex/dex.go, server/market/bookrouter.go, server/market/market.go, server/market/market_test.go, spec/admin.mediawiki
closes #727 
Adds admin functions to retrieve market data. Separated into getting the orderbook, epoch orders, and matches for a specific market. Matches can also show inactive matches if a token is included.
While some of this data could be taken from memory in other places, I think trusting the database as the ultimate source of truth is reasonable.
=> admin: Add trade info getter functions.

client/cmd/dexcctl/config.go
Look for the dexcctl.conf file in ~/.dexcctl (or appdata(dexc, false)) instead of ~/.dexc.
dexcctl will also look for rpc.cert in .dexcctl if not specified on the command line, but if it is not found there, it will check in ~/.dexc.
=> .dexcctl folder

client/core/bookie.go, client/core/core.go, client/orderbook/bookside.go, client/orderbook/bookside_test.go, client/orderbook/epochqueue.go, client/orderbook/epochqueue_test.go, client/orderbook/orderbook.go, client/orderbook/orderbook_test.go, client/orderbook/rateindex.go, client/orderbook/rateindex_test.go
Backport of https://github.com/decred/dcrdex/pull/834 for 0.1.3
match_proof notifications are not in sequence with other book messages
and should not be used to indicate a transition from one epoch to
another. Since match_proof lags epoch close by up to preimage request
timeout and some additional latency, the OrderBook needs to track
several epochs for the purposes of evaluating these lagging match
proofs.
unexport some internal orderbook types and functions
=> [0.1.3 backport] client/core: epoch tracking right

client/Dockerfile
* Include `dexcctl` in image
* Locked down base image release
=> Added dexcctl to client docker image

client/core/core.go, client/core/core_test.go
closes https://github.com/decred/dcrdex/issues/552
Using an index number as the key in blockWaiters allows duplicate waiters to exist in blockWaiters. Duplicate waiters will cause duplicate notifications to be sent to the server.
If we use AssetID as the key to blockWaiters we will no longer send duplicate notifications as only one waiter will exist per registration.
I think this may cause issues if the user registers more than one dex, but I believe that was a problem prior to using AssetID as the key to blockWaiters.
=> client/core: duplicate fee payment notifications sent to server

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/types.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/site/src/css/market.scss, client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/html/markets.tmpl, client/webserver/site/src/js/app.js, client/webserver/site/src/js/forms.js, client/webserver/site/src/js/login.js, client/webserver/site/src/js/markets.js, client/webserver/site/src/js/order.js, client/webserver/site/src/js/orders.js, client/webserver/site/src/js/register.js, client/webserver/site/src/js/settings.js, client/webserver/site/src/js/wallets.js, client/webserver/webserver.go, client/webserver/webserver_test.go, dex/calc/fees.go
Get maximum order estimations for a given market and side based on the wallet balance and, in the case of buy orders, the rate in the rate input field. The data is sourced directly from the wallet, because the limits change based on available funding coins.
The data is shown in the UI as a small message above the rate field. When you click on the label, the quantity fields are pre-populated with the max order.
=> client/multi: add max order estimation

client/webserver/types.go, client/webserver/types_test.go
This fixes the incorrect year that is displayed for a matches "Time" in the order's page.
=> client/webserver: fix match's TimeString for order details page

client/asset/dcr/dcr.go
This mirrors the divide-by-zero check used with btc when computing "sync status"
https://github.com/decred/dcrdex/commit/726d8ee566a1fa16c0fd2704547f941ba3b3cb81#diff-1b07e494f4bdd99b2a617ac110fbadc081e5b6ae1abf23f64032bbee5ebebef1R579-R582
This prevents a JSON encoding error with a NaN value (`WEB: JSON encode error: json: unsupported value: NaN`).
=> client/asset/dcr: totalToSync divide by zero check

client/asset/dcr/dcr.go, client/comms/wsconn.go, client/core/trade_simnet_test.go, client/core/types.go, client/core/wallet.go, dex/testing/btc/base-harness.sh, dex/testing/dcr/harness.sh
This gets the trade_simnet_test working again.
Since the BTC gamma and delta simnet wallets are no longer encrypted (requires no pass), the previous trick used by `TestNoMaker` to prevent a swap txn stopped working for this BTC wallet.  Instead, this now sets `xcWallet.encPW` and `xcWallet.pw` to force `locallyUnlocked` to block swap actions.
`TestMakerGhostingAfterTakerRedeem` was not working before, and apparently it was because `swapErr` was not `nil`ed to allow resuming the swap process after the maker disconnects from the DEX server.  This is fixed now.
There is also a lot of cleanup to trade_simnet_test.go.
The lot size of the dcrdex simnet harness was increased recently, so the tests are updated with appropriate order quantities, and the asset harnesses modified to fund the …
=> client/core: get trade_simnet_test working again

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/dcr/dcr.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/errors.go
The first commit, https://github.com/decred/dcrdex/pull/893/commits/3910136e938918698764bf219bd1d8b6c07b6e04, prevents hanging on shutdown with a disconnected wallet.  Shutdown would hang because the subsystem context was not canceled by `PromptShutdown` until *after* wallets were locked. This modifies both dcr and btc `(*ExchangeWallet).Lock` methods to check node disconnected status, and modifies the dcr method with a 5 second timeout since it has context-enabled RPC methods unlike btc.  This commit also adds a basic dcr `OnClientConnected` notification handler to log when the client (re)connects.
The second commit, https://github.com/decred/dcrdex/pull/893/commits/905b1be23e460150b2b838fb0effa7c1124883f3, consistently uses the `(*Core).connectWallet` method instead of calling …
=> prevent wallet Lock from blocking shutdown

client/core/trade_simnet_test.go, client/websocket/websocket.go, client/websocket/websocket_test.go, dex/ip.go, dex/ip_test.go, dex/ws/wslink.go, dex/ws/wslink_test.go, server/comms/comms_test.go, server/comms/link.go, server/comms/server.go
This fixes some log statements in dex/ws that were showing the illegible ip key.
NOTE: I'm still considering changing `dex.IPKey` to a full `net.IPv6len` array and using a CIDR mask in `NewIPKey` instead of a partial copy so that the `IPKey` can be converted to an IP string, right now it is an irreversible conversion from a `net.IP` to a `dex.IPKey` (can no longer distinguish ipv4 from ipv6).  Making this change would allow passing only the `IPKey` (or a `net.IP`) to the `WSLink` constructor, and the address string could be extracted on construction instead of passed as another input.
=> fix logs showing ipkey instead of address string

client/cmd/dexc/config.go, client/core/core.go, client/core/core_test.go, server/cmd/dcrdex/config.go, server/cmd/dcrdex/config_test.go
This is based on PR #882, so the commit of interest is https://github.com/decred/dcrdex/commit/bfb407e2ccd4005c3dccaf783a1b6ddfb5148cfa.
The issue is that `host + ":" port` is not always correct for IPv6 because the host needs brackets around it when joined with a port.  This updates all the listen address parsing and construction code to work properly with IPv6.
For dcrdex with `--rpclisten=[::1]:17232`:
**before**
`NewServer failed: address ::1:17232: too many colons in address`
**after**
`[INF] COMM: RPC server listening on [::1]:17232`
A similar fix is applied to client.
=> allow apps to listen on IPv6 addresses

client/asset/dcr/dcr.go
The Confirm Registration dialog error was showing the address it was trying to send to even though that address is of no use at best, and resulted in users manually sending funds there (e.g. dcrctl sendtoaddress) when that would not complete the registration.
This PR simply removes the "to address %s" part of the error message to avoid this pitfall.
=> client/asset/dcr: do not include fee address in sendRegFee

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/dcr/dcr.go
The changes the client's BTC backend so that the FundOrder implementation will favor confirmed utxos.
=> client/asset/btc: favor confirmed utxos in FundOrder

client/asset/btc/btc.go, client/asset/btc/walletclient.go, client/asset/btc/wallettypes.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/webserver/site/src/html/wallets.tmpl
This fixes #879 by validating deposit address for each wallet after successful connection.
I wiped a running wallet dir and created fresh one as #879 describes and the client
validated the deposit address and generated new one.
=> client: Validate known deposit address after wallet connection

client/asset/dcr/dcr.go, client/core/core.go, client/core/wallet.go
This resolves issues with the internal wallet lock state that could occur when starting dexc with both an unlocked wallet and active orders or swaps.
It also refactors much of the wallet balance code including updating balance on ReconfigureWallet.
These changes are in 2nd and third commits: https://github.com/decred/dcrdex/compare/d695d6e...de38eb6. The [first commit](https://github.com/decred/dcrdex/pull/910/commits/d695d6e61fc509d71c84e81f69eca009fc5bad07) is a follow up on the deposit address validation changes.
=> client/core: locked wallet means missing password or locked backend

client/asset/btc/btc.go, client/asset/btc/walletclient.go, client/asset/btc/wallettypes.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/wallet.go, client/webserver/site/src/html/wallets.tmpl
This is a backport of commit https://github.com/decred/dcrdex/commit/59802fa038bf7fae4ee4a024114e77d5e2bbb16b from PR #902 and the related first commit of https://github.com/decred/dcrdex/pull/910.  The locallyUnlocked fixes in https://github.com/decred/dcrdex/pull/910 will be in another 0.1.4 PR.
=> [0.1.4] backport deposit address validation

server/market/orderrouter.go
This adds order id to returned error message when the target is not known.
Closes #810
=> server: Add order id to cancel route error message

client/core/core.go, client/core/wallet.go
This is a backport to 0.1.4 of the wallet lock commits in https://github.com/decred/dcrdex/pull/910 that resolve issues with the internal wallet lock state that could occur when starting dexc with both an unlocked wallet and active orders or swaps.
This is the last planned change for 0.1.4.
=> [0.1.4] backport wallet lock state fix

client/core/types.go, client/rpcserver/handlers.go, client/rpcserver/handlers_test.go, client/rpcserver/types.go
This adds new `[]match` to the `myOrder` struct returned by the rpcserver's `myorders` route.
Closes #728
=> rpcserver: add matches slice to myorders route reply

client/rpcserver/handlers.go
This restores a description line which was deleted in #909 unintentionally.
=> rpcserver: restore helpmsg unintened field description deletion

client/core/core.go, client/core/core_test.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/site/src/html/wallets.tmpl, client/webserver/site/src/js/wallets.js, client/webserver/webserver.go, client/webserver/webserver_test.go
This adds the possibility to update wallet's settings/name & password simultaneously.
With this users which used an unencrypted wallet could switch to a different encrypted wallet.
Closes #855
=> client: Update wallet's settings & password simultaneously

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/dcr/config.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/ltc/ltc.go, client/core/core.go, client/core/wallet.go, dex/networks/btc/config.go
This diff adds new fee rate threshold wallet setting which will be checked against server `maxFeeRate` when placing and order.
if `maxFeeRate` is greater than the threshold, client throws an error.
Part of #858
=> client: Fee rate limit setting

client/webserver/live_test.go, client/webserver/site/src/js/app.js, client/webserver/site/src/js/register.js, client/webserver/webserver.go
re: https://github.com/decred/dcrdex/pull/753#discussion_r507247831
Moves the **/user** and **/defaultwalletcfg** endpoints behind the user auth middleware.
=> app: require auth for user and defaultwalletcfg API endpoints

client/asset/dcr/config.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/simnet_test.go
Backport of https://github.com/decred/dcrdex/pull/923 to address an otherwise unresolvable data race on the package-level chainParams var.
Co-authored-by: chappjc <chappjc@protonmail.com>
=> [0.1.4] move client/asset/dcr package-level chainParams to field

.gitignore, client/core/core.go
Simplified backport of https://github.com/decred/dcrdex/pull/921 to release-0.1 branch for 0.1.4
=> [0.1.4] client/core: avoid potential wallet reconfigure deadlock

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/asset/interface.go, client/core/core.go
This prevents a deadlock on wallet reconfigure that would happen if the client asset backend's tip change handler (a Core method) attempted to acquire the Core.walletMtx because it was already locked in ReconfigureWallet.  The deadlock was on `oldWallet.Disconnect` inside `ReconfigureWallet` because it would be waiting for the block monitor goroutine to return that was likely to itself be waiting on `Core`'s `walletMtx` (e.g. monitorBlocks>checkForNewBlocks>tipChange).
I hit the deadlock in testing release-0.1 today.
The `tipChange` goroutine that tried to re-lock `walletMtx` inside `refreshUser` via `updateBalances`:
```
goroutine 15952 [semacquire, 5 minutes]:
sync.runtime_SemacquireMutex(0xc0002b1ef4, 0x0, 0x0)
/home/jon/go115/src/runtime/sema.go:71 +0x47 …
```
=> client/core: avoid potential wallet reconfigure deadlock

client/core/trade_simnet_test.go, dex/testing/dcr/create-wallet.sh, dex/testing/dcr/harness.sh, dex/testing/dcrdex/README.md, dex/testing/dcrdex/harness.sh
Modify dcrdex harness to receive custom epoch duration value from env variable rather than cli arg to retain support for relaying all cli args to dcrdex.
Update dcrdex harness readme to mention the supported `PG_PASS` and `EPOCH` env variables and the behaviour of passing cli args verbatim to dcrdex.
=> dex/testing: harness improvements

client/cmd/dexc/sample-dexc.conf, client/cmd/dexcctl/sample-dexcctl.conf, server/cmd/dcrdex/config.go, server/cmd/dcrdex/sample-dcrdex.conf
=> sample config files

client/asset/btc/btc.go, client/asset/dcr/dcr.go
Currently, when a contract redemption search is canceled, active
searches are allowed to complete before the FindRedemption method
returns with an error.
This is a refactor to enable stopping active searches when the
associated context is canceled.
Resolves #782
=> client/asset: improve find redemption cancellation

go.mod, go.sum
For reference: https://github.com/go-chi/chi/blob/master/CHANGELOG.md#v150-2020-11-12---now-with-gomod-support
In a nutshell, go-chi maintainers decided to convert the v4+incompatible module to a v1 module do avoid the /vX part of the import that it would necessitate if they made it a compatible v4 module.
=> update go-chi to latest with compatible module

client/core/core.go
Backport of https://github.com/decred/dcrdex/pull/947 to the `release-0.1` branch.
=> [0.1] client/core: don't panic on reconfigure of disconnected wallet

client/core/core.go
A regression was introduced in https://github.com/decred/dcrdex/pull/925 where attempting to reconfigure a never-connected wallet would panic.  This can be reproduced as follows:
- configure a dexc and shutdown
- stop one of the wallets (e.g. dcrwallet)
- start dexc and login (`initialize()` creates the `xcWallet`s and leaves in the wallets map any that failed to connect on login)
- go to /wallets page and attempt to reconfigure the down wallet -> panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4d9574]
goroutine 962 [running]:
sync.(*WaitGroup).state(...)
/home/jon/go115/src/sync/waitgroup.go:33
sync.(*WaitGroup).Wait(0x0)
/home/jon/go115/src/sync/waitgroup.go:104 +0x34 …
```
=> client/core: don't panic on reconfigure of disconnected wallet

client/core/account.go, client/core/bookie.go, client/core/core.go, client/core/core_test.go, client/core/notification.go, client/core/trade.go, client/core/trade_simnet_test.go, client/core/types.go, dex/testing/loadbot/go.sum
Resolves #379
I experimented with some different schemes for updating the cached `*User` struct and then creating copies on calls to `(*Core).User`, but ultimately decided that we don't really need to cache a `*User` at all, and the cleanest solution is to just get rid of it.
- remove `user` and `userMtx` fields from `Core`. `(*Core).User` now generates a new `*core.User` on demand.
- remove the `marketMap` field from `Core`. Anything that used the `core.Market` from the `marketMap` now uses the `msgjson.Market` from `cfg` instead.
- `dexConnections` and `xcWallets` methods to relieve some lock contention
- `*OrderLocked` and `*ContractLocked` fields changed to methods (breaking change)
=> core: remove cached User struct

client/core/core.go, server/auth/auth.go, server/auth/registrar.go
**server**
`handleConnect` now logs the auth event:
> [INF] AUTH: Created new user account 54154d3ef759845e34ee3c681842371046304b9bd05494297409223a213c629f from 127.0.0.1 with fee address SsbeD1czwoAwqxV8fiq1sbhT7JsypYN5LPK
> ...
> [INF] AUTH: New user registered: acct 54154d3ef759845e34ee3c681842371046304b9bd05494297409223a213c629f from 127.0.0.1 paid 100000000 to SsbeD1czwoAwqxV8fiq1sbhT7JsypYN5LPK
> ...
> [INF] AUTH: Authenticated account 54154d3ef759845e34ee3c681842371046304b9bd05494297409223a213c629f from 127.0.0.1 with 0 active orders, 0 active matches
**client**
`authDEX` already logged, but now it includes the acct ID.
> [DBG] CORE: Authenticated connection to 127.0.0.1:17273, acct 54154d3ef759845e34ee3c681842371046304b9bd05494297409223a213c629f, 0 active orders, 0 active matches, …
=> acct ID and address logging on auth and register

client/core/core.go, client/core/trade.go
This fixes a bug where resuming trades with required audit info can fail too readily.
I'm considered using `tickGovernor` instead of `swapErr` while searching in the background for the counterparty contract and audit info, but this turned out cleaner, and it's possible for wallet reconfigure to clear the `tickGovernor` unexpectedly.
This also avoids a bug where an order could be retired without saving the match revoked status to DB, making the order potentially load forever if there was a subsequent error such as funding coins not found.  This was caused by the self-revoke in `resumeTrades` not actually being stored to DB, just memory.
=> client/core: resumeTrades auditInfo search must retry

client/db/bolt/db.go, client/db/bolt/upgrades.go, client/db/bolt/upgrades_test.go
This creates a special backup of the dexc.db file prior to upgrade to a new version.
For example, if upgrading from version 1 to 2, it first writes a "dexc.db.v1.bak" file
in the backup subdirectory.
This is valuable for the following reasons:
1. Users have accidentally run on `master`, which is not advised since users should be on a release branch, and after the upgrade there is no way to go back
2. If the upgrade malfunctions in some fatal way, it would be great to have a pristine backup at the previous version.
=> client/db/bolt: backup before upgrade

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/walletclient.go, server/asset/btc/btc.go
This uses decred's `rpcclient/v6` for BTC wallet that all RPC calls are sent through `RawRequest`.
Closes #841
=> use decred's rpcclient for BTC

client/cmd/dexc/main.go, client/core/core.go, client/core/core_test.go, client/core/wallet.go, dex/runner.go, dex/testing/loadbot/mantle.go
Previously we gave `(*Core).PromptShutdown` the expanded responsibility of not just checking and prompting if a shutdown was OK but also locking the wallets.  This was not the right place to do that for several reasons:
1. `PromptShutdown` is just a check and prompt function, not a "partial shutdown" function.  Shutdown via context cancellation is the correct approach.
2. `Core` consumers could and were not using `PromptShutdown`, and instead just cancelling `Core`'s context thus leaving the wallets unlocked after shutdown, thus leading to the now-fixed "wallet not unlocked" bug (https://github.com/decred/dcrdex/pull/915) that was requiring such consumers to also restart their wallets when restarting.
3. Locking the wallets and the dex accounts before shutting down `(*Core).Run` goroutine …
=> client: don't lock in PromptShutdown, do it on Core shutdown

client/core/bookie.go
If the config request started by refreshServerConfig on reconnect times
out, it should not disconnect the current connection.  The wsConn's
reconnect / keepAlive loop will deal with it.
Some matrix discussion: https://matrix.to/#/!SFRQQFIHUUNXARfvew:decred.org/$i36zRmdeCzI_VV7zStk7ksQJ3oD1x3NFtzl3wXiA0QY?via=decred.org&via=matrix.org&via=planetdecred.org
=> client/core: do not disconnect on config timeout

go.mod, go.sum
This is PR #982 for the release-0.1 branch.  It is required to prevent silent memory corruption. https://github.com/golang/crypto/commit/86c0c3e7f9624c5d1a4ff79e1605de2d53284af5
=> [0.1.5] bump x/crypto for blake2 .s stack corruption fixes

client/cmd/dexcctl/simnet-setup.sh, dex/testing/btc/base-harness.sh, dex/testing/btc/harness.sh, dex/testing/dcr/create-wallet.sh, dex/testing/dcr/harness.sh, dex/testing/dcrdex/harness.sh, dex/testing/loadbot/run, dex/testing/ltc/harness.sh, run_tests.sh
This makes all the scripts specify bash in their shebang - using `#!/usr/bin/env bash`.
I still needed to change the scripts to use `nolog` option instead of `history` to make run on macOS.
Closes #951.
=> scripts: force bash with shebang.

client/core/core.go, client/core/core_test.go, client/core/trade.go
Backport of https://github.com/decred/dcrdex/pull/967 for 0.1.5
This addresses the issue of orders that lose their funding coins one way
or another (e.g. spend outside of dexc) can never be loaded. Prior to
this PR, that meant two things:
- On login, the user will be forever spammed by an "Order coin error"
/ "Source coins retrieval error".
- Matches for such orders can never be
recovered, even if they do not require funding coins. This made
recovery a manual task if there were matches in progress or requiring
refund, etc.
Unfunded orders that require funding (epoch/booked or with matches
needing to send swap txns) are explicitly blocked from negotiating new
matches, and any offending matches that require funding coins are
blocked with swapErr. However, notably, the trackedTrade is added …
=> [0.1.5] client/{core,cmd/dexc}: load unfunded orders for recovery

client/core/core_test.go, client/core/trade.go, go.sum
A minimal version of https://github.com/decred/dcrdex/pull/911.
This changes `Core` so that swap and redeem data is recorded in the DB immediately after the swap or redeem is broadcast, rather than after the `'init'` or `'redeem'` requests completes (or times out), which can take minutes.  When `Core` was killed ungracefully in this state, there is no recovery for certain matches.
The requests are still synchronous so users may experience long delays and perceived hangs when trying to quit (may have to wait a ~90 sec or so for a response timeout), but if they do a hard kill of the process, at least the DB will be consistent with the transactions they have broadcasted.
=> [0.1.5] client/core: store swap/redeem immediately after bcast

README.md
We need to specify that the 1.6 versions of dcrd and dcrwallet should be used.
This also makes Go 1.15 and Node.js 14 the minimum versions.
I was also considering bumping "At least 2 GB of available system memory" to 4 GB, but left it.  I feel like 2 GB for dcrd, dcrwallet, bitcoind, and dexc is pretty slim.
=> README: update requirements

dex/testing/dcr/harness.sh
Without it the mine-alpha script will fail
=> Fix missing arg on simnet mine-alpha script

client/websocket/websocket.go, dex/testing/eth/README.md, dex/testing/eth/create-node.sh, dex/testing/eth/harness.sh, spec/atomic.mediawiki
This adds a basic ethereum private network testing harness.
This network relies on proof of authority. More about this can be found here https://eips.ethereum.org/EIPS/eip-225
It creates two nodes, either of which can add new blocks to the network. Each node starts with funds that can be sent to addresses that we later create in tests.
The harness does not start an rpc client. I think it is best that we use ipc (Inter-process communication) as this seems to be the most secure. Other options are an http or ws server, but neither is permissioned. They can be restricted to the local network, but at that point it doesn't seem much different than using ipc.
closes #940
=> testing: Add Ethereum simnet harness.

client/core/core.go, client/core/core_test.go, client/core/trade.go
This is part 2 of a `resumeTrades` issue resolution following https://github.com/decred/dcrdex/pull/965
This addresses the issue of orders that lose their funding coins one way or another (e.g. spend outside of dexc) can never be loaded.  Prior to this PR, that meant two things:
1. On login, the user will be forever spammed by an "Order coin error" /
"Source coins retrieval error".
2. Matches for such orders can never be recovered, even if they do not
require funding coins. This made recovery a manual task if there were
matches in progress or requiring refund, etc.
Unfunded orders that require funding (epoch/booked or with matches needing to send swap txns) are explicitly blocked from negotiating new matches, and any offending matches that require funding coins are blocked with `swapErr`. …
=> client/{core,cmd/dexc}: load unfunded orders for recovery

client/webserver/api.go, client/webserver/live_test.go, client/webserver/webserver.go, client/webserver/webserver_test.go
Since the `/user` route is behind the auth cookie now, web API users have no way to know whether the client is already initialized. 
We already had the exported `Core` method, we just needed to expose it.
=> webserver: add isinitialized web api endpoint

client/webserver/site/src/css/market.scss
This is a small follow up and one last bit regarding #955 - I've discussed it with @buck54321 and haven't documented the it on the PR.
Before this switching to sort by a different column caused column width change, see video below:
https://user-images.githubusercontent.com/10324528/109538967-61a2b380-7ac9-11eb-9d05-f26752975ecc.mov
This fixes that jump by using the `visibility` css property instead of `display` which keeps the elements in the DOM tree while they are hidden.
=> Fix sorted column width jump on sort columns switch.

client/core/core.go, client/core/core_test.go, client/core/status.go, client/core/trade.go, client/core/trade_simnet_test.go, client/core/types.go, client/db/bolt/db.go, client/db/bolt/db_test.go, client/db/test/dbtest.go, client/db/types.go, dex/order/match.go
Remove following duplicate fields:
- ~`matchTracker.id`~ => `matchTracker.Match.MatchID` (from `order.UserMatch` embedded via `db.MetaMatch`)
- ~`db.MetaMatch.MetaData.Status`~ => `db.MetaMatch.Status` (from embedded `order.UserMatch`); this change also reflects in ~`matchTracker.MetaData.Status`~ => `matchTracker.Status`, `matchTracker` embeds `db.MetaMatch`.
Having duplicate fields in different paths of the same object means both fields have to be simultaneously updated otherwise an error could result. Primary motivation for this is making it tougher to shoot ourselves in the foot in this regard.
The issue with the duplicate id fields came to the fore when I needed to use both `matchTracker.id` and `db.MetaMatch.Match.MatchID` fields in a recent modification to the core_tests …
=> client/{core,db}: refactor db.MetaMatch struct, remove duplicate fields

client/comms/wsconn.go, client/core/account.go, client/core/bookie.go, client/core/core.go, client/core/core_test.go, client/core/trade.go, client/webserver/site/src/html/markets.tmpl, client/webserver/site/src/js/app.js, client/webserver/site/src/js/charts.js, client/webserver/site/src/js/markets.js
closes #943
Right now I am appending the exchange host on `Core.conns[host]` in case of connection failure, instead of only appending it on succcess. This way it is possible to give a feedback in the client that the exchange is not connected.
~~Right now it stills a work in progress, because there is a loader which I am not being able to remove.~~
This is how it looks if a dex server connection fails:
=> Show exchange disconnected if connection fails

client/core/account.go, client/core/account_test.go, client/core/bookie.go, client/core/core.go, client/core/core_test.go, client/core/errors.go, client/db/bolt/db.go, client/db/bolt/db_test.go, client/db/interface.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/site/src/css/settings.scss, client/webserver/site/src/html/forms.tmpl, client/webserver/site/src/html/settings.tmpl, client/webserver/site/src/js/markets.js, client/webserver/site/src/js/settings.js, client/webserver/types.go, client/webserver/webserver.go, client/webserver/webserver_test.go, client/websocket/websocket.go
This adds a new button to dexc's GUI to disable account manually, this is useful when a user wants to
re-register a suspended account which required deleting the dexc.db before this commit.
Closes #961.
=> dexc: disable account feature.

client/core/account_test.go, client/core/core.go, client/core/core_test.go, client/core/trade_simnet_test.go, client/core/types.go, client/core/wallet.go, client/db/bolt/db.go, client/db/bolt/db_test.go, client/db/interface.go, client/db/test/dbtest.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/site/src/html/forms.tmpl, client/webserver/site/src/html/settings.tmpl, client/webserver/site/src/js/register.js, client/webserver/site/src/js/settings.js, client/webserver/webserver.go, client/webserver/webserver_test.go
=> dexc: change application password feature.

client/comms/wsconn.go, client/rpcserver/rpcserver.go, dex/msgjson/msg_test.go, dex/msgjson/types.go, dex/ws/wslink.go, server/auth/auth.go, server/auth/registrar.go, server/market/bookrouter.go, server/market/orderrouter.go, server/swap/swap.go
A number of `json.Unmarshal` calls now properly handle a `Payload`
of the JSON `null` value, which depending on the caller's use of
`json.Unmarshal` can set a pointer of the type to `nil`.
The docs for `(*Message).Unmarshal` now call out the `null` `Payload`
handling explicitly. A `null` `Payload` is not an error however, since
the caller may be happy to accept (or even expect) a `null` `Payload`.
Further, for the caller to even allow their input to be set to `nil`, they must
call `Unmarshal` with sufficient indirection. For example,
```go
t := new(T) // *T
err := json.Unmarshal(msg.Payload, &t) // passed **T, can set t to nil
```
Only with the above approach can `json.Unmarshal` or `(*Message).Unmarshal`
set `t` to `nil`. Callers can either pass a `*T` instead and accept a
zero-value `T` …
=> multi: graceful support for json unmarshal of null

client/rpcserver/handlers.go, client/rpcserver/handlers_test.go, client/rpcserver/types.go, client/rpcserver/types_test.go
This follows up on https://github.com/decred/dcrdex/pull/821, which changed the cert argument to both `Register` and `GetFee` to be an `interface{}` (either `[]byte` or `string`).  However, the client/rpcserver's `parseGetFeeArgs` was keeping the cert as a `string` even though it was the cert *contents* not file name.
This can be tested with the dcrdex harness using `./dexcctl --simnet -p a getfee 127.0.0.1:17273 ~/dextest/dcrdex/rpc.cert`.  On master it spits out an error showing the full contents of the cert file saying file not found.
=> client/rpcserver: getfee expects cert bytes, not filename

client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/comms/wsconn.go, client/core/core.go, client/core/core_test.go, client/webserver/site/src/js/app.js, client/webserver/site/src/js/markets.js, dex/testing/dcr/harness.sh, go.mod, go.sum
This supports Decred account-based encryption/passwords.
The `(*ExchangeWallet).Lock/Unlock` methods use the new `accountunlocked` wallet RPC being added in https://github.com/decred/dcrwallet/pull/2020 to reliably determine how (un)locking should be performed.  This also uses `accountunlocked` in the `Locked` method. I briefly considered a flag to indicate account vs. wallet locking that get's figured out on walletreconfigure/creation/startup/etc, but this is far simpler, and it won't get confused if the user sets the account pass while the ExchangeWallet is running.
Also note that unlike `walletlock`, `lockaccount` throws an error if already locked, so we catch that too.
NOTE: to test, you must use dcrwallet built from github.com/chappjc/dcrwallet v1.6.3-0.20210324151833-873c564976fd
=> client/asset/dcr: support account-based locking

client/webserver/api.go, client/webserver/webserver.go
This allow multiple authenticated client http sessions by tracking multiple cookies in the WebServer. You can now login in different browsers without one login invalidating the other's auth cookie.
Logout ends all authenticated sessions however.  This is done because the logout route also performs `(*Core).Logout`, crippling other authenticated http sessions.  Also, if we just removed the auth token for the one session performing the logout, the backend would really have no way to keep the map clean and it could conceivable keep filling up if requests kept reauthing and not logging out.
=> client/webserver: allow multiple authorized sessions

client/core/core.go, client/core/core_test.go, dex/msgjson/types.go, server/market/market.go
This builds on https://github.com/decred/dcrdex/pull/1008 by including the `Commitment` in the `PreimageRequest`, which solves multiple issues with the current race between order submission response processing and incoming preimage requests.  Namely, we can record the commitment *before* submitting the order/cancel request, thus avoiding a race necessitating the `piSyncers` map hoop jumping.  More importantly however, we can reject outright preimage requests containing unrecognized commitments.  Without this, we had to blindly wait for an arbitrary timeout (was 1 min) to see if we got an order submission response back with the order ID of interest.
=> include order commitment in preimage request

client/asset/dcr/dcr.go, client/asset/interface.go, client/core/core.go
When an `asset.Wallet` is disconnected, it may not be possible to
reconnect it.  Document this with the `asset.Wallet` interface.
This is the case with Decred's rpcclient-powered `ExchangeWallet`
where calls to `rpcclient.(*Client).Connect` after having `Shutdown`
a previous connection will be met with the error:
`websocket client has already connected`
Always leave wallets connected in `setWalletPassword`. Callers like
`SetWalletPassword` have the `xcWallet` in the wallets map, so it should
stay live and usable.
In `ReconfigureWallet`, call `connectWallet` before `setWalletPassword`
anyway because the connection approach used by `setWalletPassword`
was too involved for the fresh `xcWallet` created by `ReconfigureWallet`
that is not yet in Core's wallets map.
=> client/{asset,core}: do not disconnect wallets in setWalletPassword

client/rpcserver/rpcserver.go, client/webserver/middleware.go, client/webserver/webserver.go, client/webserver/webserver_test.go, dex/testing/loadbot/go.sum, go.mod, go.sum, server/admin/api.go, server/admin/server.go, server/admin/server_test.go, server/comms/middleware.go, server/comms/server.go
This updates to chi/v5, which is the same as v1.5.4, just with proper
semantic import versioning (SIV). The project conceded the 1.5.x
approach did not work out since latest was previously v4.
See https://github.com/go-chi/chi/issues/561 for an epic discussion of this saga.
This also pulls in a chi data race fix in v1.5.2.
=> update chi for fixes to SIV snafu and a data race

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/interface.go, client/core/bookie.go, client/core/core.go, client/core/core_test.go, client/core/trade.go, client/orderbook/bookside.go, client/orderbook/orderbook.go, dex/msgjson/types.go, dex/order/match.go, server/dex/dex.go, server/dex/feemgr.go, server/market/bookrouter.go, server/market/market.go, server/market/market_test.go, server/market/orderrouter.go, server/market/routers_test.go, server/swap/swap.go
Add the most recent fee rate estimate to 1) The `orderbook` response, 2) the `epoch_report` notification, and 3) a custom `fee_rate` endpoint. There are two major reason for this.
1. SPV clients will have no way to estimate fees. They can use the suggested fee rate with some basic sanity checks.
2. This finally closes a small vulnerability regarding fee rates on zero-conf funding coins. Previously, we handled this only client side by ensuring a reasonably high fee rate. But since the server's latest fee rate is available at the client now, we can more justifiably reject low-fee zero-conf coin-funded orders. Right now, the filter is set to >= 90% of the most recently procured rate estimate.
Order estimates should also be more accurate now.
=> multi: fee rate estimate feed

client/core/bookie.go, client/core/core.go, client/orderbook/orderbook.go, dex/msgjson/types.go, server/market/bookrouter.go
Since there's no book or order updates with `epoch_report`, it should not increment `Seq`.  Having seq incremented in a message route that 0.1.x client's don't understand also breaks backward compatibility with 0.2 servers.
The book router messages that don't reflect book changes don't increment or include seq. For example, `MatchProof`, `TradeResumption`, and `TradeSuspension` when `Persist` is true.
This also updates the docs for `seq` in the `server/market.subscribers` struct to reflect the purpose of the [`Seq` value as per the spec](https://github.com/decred/dcrdex/blob/master/spec/orders.mediawiki/#order-book-subscriptions):
> The order book and all updates include a sequence ID, which increments by +1 whenever the DEX accepts, removes, or modifies an order. The client is …
=> multi: no Seq in msgjson.EpochReportNote

client/orderbook/epochqueue.go, client/orderbook/epochqueue_test.go, client/orderbook/orderbook_test.go, server/market/market_test.go, server/matcher/match_test.go, spec/fundamentals.mediawiki
client/orderbook: fix csum computation with missed preimages
The commitment checksum is computed from **all** orders in the epoch queue.
The shuffle seed is computed from the received preimages, but the csum
includes all the orders received in an epoch that were send to orderbook
subscribers in the `epoch_order` notes.
This fixes `(*EpochQueue).GenerateMatchProof` to use all epoch queue
commitments in csum computation, and it prints a message when
there are epoch queue orders that were not accounted for in either the
preimages or misses slices. An error is not thrown in this case since
one of the shuffle seed or commitment checksum will mismatch.
Now server and client compute the same csums when there are missed
preimages.  Their shuffle seeds already matched with misses.
Common test …
=> client/orderbook: fix csum computation with missed preimages

dex/testing/dcrdex/harness.sh, dex/testing/loadbot/loadbot.go
With https://github.com/decred/dcrdex/pull/1023, the "beta" DCR wallet was converted to an individually-encrypted account, but I did not update loadbot's unlocking command for beta.
This also changes the `walletpassphrase` duration argument for "alpha" to 0, which means indefinitely unlocked.
=> loadbot: beta uses unlockaccount, use 0 for indefinite dur

client/core/core.go, client/core/core_test.go
The `User` and `Exchanges` methods of `Core` include orders slices, which have
thus far included all orders including those that are inactive but about to
be retired on the next tick. Commit 461f3fc82c3c3de702e5f580d686612db5f36672 changes `marketTrades` to only return
**active** trades. Now `Logout`'s handling of active orders is consistent with the
orders slice returned by `User` or `Exchanges`, giving consumers such as
Decrediton or direct go consumers a better indication of when it is actually
safe to logout.
Commit 9fd6dbee5739ab6b14ff772c6f219dfd24bed791 also addresses some possibly missing cleanup actions on
`(*Core).Run` shutdown:  
The ticker has always retired inactive orders, which also returns any coins that
may still be locked in the wallets for such orders. This supplements …
=> client/core: inactive order handling

client/core/core.go, client/core/types.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/site/src/html/forms.tmpl, client/webserver/site/src/html/register.tmpl, client/webserver/site/src/js/register.js, client/webserver/site/src/js/settings.js, client/webserver/webserver.go, client/webserver/webserver_test.go
Resolves https://github.com/decred/dcrdex/issues/1041
The idea is the user should have all the information about the DEX markets and assets before they shell out to register, and lot size is arguably the most important (what if they wanted to trade less than lot size?).
I'm aware that if the DEX does not have DCR supported this will be lacking a value, but presently DEX servers must support it.  Also, this message will have to change to something more informative about all the markets at some point, as will the fee amount shown when multiple reg fee assets becomes supported.
=> client/{core,webserver}: getdexinfo instead of getfee

client/orderbook/bookside.go, client/orderbook/bookside_test.go, client/orderbook/orderbook.go, client/orderbook/orderbook_test.go, dex/testing/dcrdex/harness.sh
This fixes a copy operation not being performed on account of a go compiler
simplification.  See staticcheck SA4001 / https://play.golang.org/p/1X44V19HxFj
Instead of making multiple copies on each add/book, go back to storing
pointers, but now `bookSide` is responsible for modifying `Quantity`, and
making copies when returning an `Order` from it's methods.
This also resolves an issue with the `OrderBook.{buys,sells}` fields being
overwritten unsafely in the `Reset` method.  The resolution is a new
`(*bookSide).reset` method to clear the internal structures. This is also
less error prone as the initial `orderPreference` cannot be changed.
=> client/orderbook: fix copy Order operation in updateRemaining

client/core/core.go, client/db/bolt/db.go
When `ReconfigureWallet` is used to change the wallet's passphrase, there
are two DB updates, but the second one was using the original
`EncryptedPW`.  The resolution is to simply update the `EncryptedPW` field
of the client/db.Wallet instance passed to `db.UpdateWallet` in
`ReconfigureWallet` after updating the wallet balance. While two DB writes
is inefficient, this still uses the `(*Core).setWalletPassword` method as is
since it also checks the password and emits a notification.
This also revises `(*BoltDB).SetWalletPassword` so that it does not bother
to decode the current wallet's `db.Balance` since only the wallet encoding
bucket (`walletKey`) is updated, not the balance bucket (`balanceKey`).
A deep copy of the new encrypted PW is also done out of caution.
Resolves …
=> client: fix db store of enc pass in ReconfigureWallet

client/core/bookie.go, client/core/core.go, client/core/core_test.go, dex/msgjson/types.go, server/dex/dex.go, spec/README.mediawiki, spec/fundamentals.mediawiki
Add a version to the server that is communicated in the Config response.
Client checks and saves the version. The burden of conforming to an
API version is placed completely on the client.
depends on #1046 
closes #530
=> multi: Version server API.

client/core/notification.go
Resolves https://github.com/decred/dcrdex/issues/1043
The initial `matchTracker.counterConfirms` value when the `matchTracker` is created in `negotiate` or `dbTrackers` is -1 so that the first time confirmations is actually obtained it is logged even if it is zero.  This had the effect of showing -1 in `MatchNote`s.
This changes `newMatchNote` so that it only uses non-negative confirmation values.
=> match note should have non-negative counter confs

client/webserver/site/src/js/markets.js
=> app: abandon pre-order results if a new request is queued

client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/core/trade.go, client/core/trade_simnet_test.go
Transactions utilizing locktimes should watch the mediantime and not the
actual time to know when they can be finalized.
closes #897
=> dcr: Use median time in LocktimeExpired.

server/admin/api.go, server/admin/types.go, server/dex/feemgr.go, server/market/bookrouter.go, server/market/orderrouter.go
Both `BoookRouter` and `OrderRouter` use `FeeManager.LastRate` to obtain
fee rates, and these need to have the configured `MaxFeeRate` applied.
This could be done in the caller but the `FeeManager` embeds the `dex.Asset`
and thus should obey the known limits itself.
The rate from `FeeFetcher.FeeRate` is also now capped, but consumers scale
this and apply the limit after scaling anyway. `(*Market).processReadyEpoch`
already applied the `MaxFeeRate` after scale, but `(*Server).apiAsset` was
neglecting this cap and it is now applied.  e.g. the limit being applied at match-time
to a bad rate from a bad DCR `estimatesmartfee` result:
```
[DBG] SWAP: Optimal fee rate for "dcr": 630
[WRN] SWAP: Optimal fee rate 630 > max fee rate 10, using max fee rate.
```
The above check and limit was only …
=> server: ensure all fee rates are capped by config

server/admin/api.go, server/admin/server.go, server/admin/server_test.go, server/admin/types.go, server/db/driver/pg/internal/matches.go, server/db/driver/pg/matches.go, server/db/driver/pg/matches_online_test.go, server/db/interface.go, server/dex/dex.go, server/market/market.go, server/market/market_test.go
This modifies the admin endpoint at `/api/market/{marketID}/matches` to return decoded swap and redeem coin IDs and idiomatic json field names.
Before
```json
[
{
"ID": "513855f29eaf0783eac3290e5e0d545d9f04f588741f3c372c027715d38d895f",
"Taker": "d3e2b7bf0e5e6f55deed4991c75751a1f70bbd7ad88d5ed8a1ecb673b2ee2e92",
"TakerAcct": "b37eeb6e7be5824594d5fb69491766f12cad9ba37d04f49d4a97613954eaebd2",
"TakerAddr": "SssSuedGa2bkFHHXJ9hYBDVxDGLHoq3ytxt",
"TakerSell": false,
"Maker": "b5e5bc4ae87fd756a718531f57f1252b0720d454d98a68b048828192f23ff2eb",
"MakerAcct": "b37eeb6e7be5824594d5fb69491766f12cad9ba37d04f49d4a97613954eaebd2",
"MakerAddr": "bcrt1q2yfrdausj2dwsgjwg2wpmdrrevervjfq5v66ru",
"Epoch": {
"Idx": 107936073,
"Dur": 15000
},
"Quantity": 1000000000,
"Rate": 1000000,
"BaseRate": 10, …
```
=> server: MarketMatches includes swap/redeem coins

client/webserver/site/src/js/charts.js
This stops the wheel event propagation to prevent the page scroll bug when having long orders list.
Closes #1063.
=> chart: stop the wheel event propagation.

client/core/core.go, client/core/core_test.go, client/db/bolt/db.go, client/db/bolt/upgrades.go, client/db/bolt/upgrades_test.go, client/db/interface.go, client/db/test/types_test.go, client/db/types.go, dex/encode/encode.go, dex/order/serialize.go
This attempts to address high memory utilization (both VIRT and RES) during a db upgrade with the following changes:
- Eliminate the copy of two buffers from a `db.Get` because they are not used outside the db.Tx and thus do not need to be copies.
- Put each upgrade into a separate transaction.  This reduced memory use in my tests noticeably, but this means that if one upgrade in series of several version upgrades fails, it does not rollback to the starting version in the series, just the one version.
- A handful of preallocation optimizations, excluding cancel matches when loading an orders matches with `MatchesForOrder`, and not re-saving cancel matches in `reloadMatchProofs` since they will always lack both revoke bools and txdata fields that are added in these upgrades. …
=> client/db/bolt: omit copy of buffer and upgrade in separate db txns

server/comms/server.go, server/db/driver/pg/epochs.go, server/db/driver/pg/types.go, server/db/driver/pg/upgrades.go
`convertAssignRows` in the database/sql core library converts to and from a string even for integers, which is kinda crazy and really slow
=> pg: fastUint64 scanner with no string conversion

client/webserver/site/package-lock.json
I was prepping to tag v0.2.0 when npm informed me of a "vulnerability" in an unused package in the dev (not runtime) dependencies.  So here I am patching it just because dependabot will bother us about it.
=> fix an audit failure so we can call it a wrap

client/asset/bch/bch.go, client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go
If a user has active trades, they must be settled by a wallet that can
complete those trades. Disallow changing to a new wallet that cannot do
this.
closes #968
=> core: Check can trade with new wallet.

docs/release-notes/release-notes-0.2.0.md
- port fixes from https://github.com/decred/dcrdex/releases/tag/v0.2.0
- port fixes from https://github.com/decred/decred-binaries/pull/139
- incl. add commit 5771186 to proper location and remove from 2 wrong ones
=> docs: fix v0.2.0 release notes

dex/testing/eth/create-node.sh, dex/testing/eth/harness.sh
As mentioned [here](https://gist.github.com/chappjc/4feefe593f870cd008180c00f72f85ca) use snap nodes for the server as they greatly reduce the resources needed by the server after caught up. Also incorporate `datadir.ancient` which further helps with the cost of running an eth full node by saving some data on cheaper hdd's. Afaik other data must still be stored on an ssd due to the large number of reads and writes. Requires geth 1.10+
=> geth/harness: Use snap mode for server nodes.

client/db/bolt/upgrades.go
Using an old database on master, I was getting:
```
./dexc
2021-05-07 05:11:03.456 [INF] DEXC: dexc version 0.2.0-pre+dev (Go version go1.16)
2021-05-07 05:11:03.456 [INF] DEXC: Logging with UTC time stamps. Current local time is 14:11:03 JST
2021-05-07 05:11:03.459 [INF] CORE[DB]: Upgrading database from version 0 to 3
2021-05-07 05:11:03.459 [DBG] CORE[DB]: Upgrading to version 1...
error creating client core: database initialization error: error upgrading DB: error fetching database version: database version not found
```
Although `getVersionTx` returns version 0 for no bucket, `fetchDBVersion` would error. I can't see the purpose is having both of these, so removing one.
This probably means that our gzipped test database has a version with value 0.
=> bolt/upgrades: Remove redundant fetchDBVersion.

client/webserver/site/src/js/orderutil.js, client/webserver/types.go
This PR updates the status string for executed orders with 0% filled to "expired" (mentioned in #945), and for orders that are partially booked and partially currently settling to "booked/settling".
Closes #1084.
=> frontend: order status for unfilled non-standing orders

client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/simnet_test.go, client/cmd/dexc/main.go, dex/networks/dcr/script.go, dex/networks/dcr/script_test.go, dex/testing/dcr/harness.sh, dex/testing/loadbot/go.sum, dex/testing/loadbot/loadbot.go, server/asset/dcr/dcr.go, server/asset/dcr/dcr_test.go, server/asset/dcr/live_test.go, server/asset/dcr/tx.go, server/asset/dcr/utxo.go
`gettxout` version is the transaction version, not script, and there is no `GetTxOutResult.ScriptPubKey.Version` in dcrd 1.6.  So, for audit with dcrd 1.6 we have no choice but to pull blocks to get the raw transaction if the transaction is confirmed.  If it is still unconfirmed we can use `getrawtransaction`.
harness beta node now does not enable txindex
=> [0.2] assets: use script versions meticulously

server/swap/swap.go
before:
```
SWAP: Redemption error encountered for match 8a58cd9be1cb23a5885cd06afcfa2df0c5fb34145a084e0fb088b047e0d371ea, actor {Y'ޘ;+d %!s(uint32=0) %!s(bool=false) %!s(*order.LimitOrder=&{{[252 237 21 214 89 39 252 243 195 2 239 143 169 170 222 152 147 162 56 3 186 130 207 8 59 223 193 43 246 152 233 100] 42 0 1 {473000000 63757930048 <nil>} {476000000 63757930048 <nil>} [131 8 126 176 251 203 61 158 115 232 135 97 159 221 107 163 64 255 219 141 30 182 242 142 168 12 132 70 181 54 116 91] 0xc0007cc860} {[[39 79 163 17 80 111 97 30 209 94 54 23 166 43 240 213 117 45 206 34 89 252 250 197 84 72 72 204 127 67 72 224 0 0 0 3]] true 1000000000 bcrt1q5f7hx9ryq4gn52qjm89w4z29c5urnpkm2sugup {{0 0} 0 0 0 0} 1000000000} 25000 1}) %!s(*swap.swapStatus=&{42 0 {{0 0} 0 0 0 0} {820000000 …
```
=> swap: Implement Stringer for stepActor.

client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, dex/networks/dcr/script.go, dex/networks/dcr/script_test.go, dex/testing/dcr/harness.sh, dex/testing/loadbot/go.sum, server/asset/dcr/dcr.go, server/asset/dcr/dcr_test.go, server/asset/dcr/live_test.go, server/asset/dcr/tx.go, server/asset/dcr/utxo.go
On dcrd 1.7/master, use the new `GetTxOutResult.ScriptPubKey.Version` field.
Elsewhere, get output script version from either `TxRawResult.Vout[i].Version`
or the `wire.TxOut.Version`.
harness beta node now does **not** enable `txindex`
=> assets: use script versions meticulously

client/asset/dcr/dcr.go, client/core/errors.go, client/webserver/api.go, client/webserver/site/src/html/register.tmpl, client/webserver/site/src/js/constants.js, client/webserver/site/src/js/register.js, client/webserver/types.go, client/webserver/webserver_test.go
=> Add form when failing to register with low balance

client/core/core.go, client/core/core_test.go, server/market/market.go, server/market/market_test.go
This PR builds upon https://github.com/decred/dcrdex/pull/1077 to provide basic protection against malicious server behavior described in https://github.com/decred/dcrdex/issues/1020.
=> Client must allow only one preimage request per order

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/asset/interface.go, client/core/core.go, client/webserver/site/src/js/markets.js
Ignore prices below the rate step in markets.js.
Error on zero lots in MaxOrder.
Use an estimation for number of starting lots that includes a basic fee.
This lets estimations for very large orders start closer to the final
fee.
closes #1085
=> multi: Fix maxOrders panic.

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/interface.go, client/core/core_test.go, client/core/trade.go
Add signed refund txs to the Receipt when swapping and log so that the
user can salvage funds in the case that they lose access to the client
but still have the logs.
closes #1087
=> multi: Log swap refund txs.

client/webserver/http.go, client/webserver/site/src/css/orders.scss, client/webserver/site/src/html/orders.tmpl, client/webserver/site/src/js/orders.js, client/webserver/types.go, client/webserver/webserver.go, dex/encode/encode.go
This PR adds a button on the orders page that allows the user to download their orders in CSV format.
Closes #382
=> client/front-end: Export orders in csv file

client/webserver/site/src/html/wallets.tmpl
The create new wallet form was displaying much lower than the other boxes on the wallet screen. It wasn't so noticeable on firefox but very obvious in brave.
=> ui: fix position of new wallet form

client/asset/dcr/dcr.go
This makes dcr's `(*ExchangeWallet).Connect` shutdown the websocket RPC client if there are errors from any of the checks after establishing the connection that cause `Connect` to return a non-nil error.
e.g. the automatic wallet connection on login might error because of RPC version:
`[ERR] CORE: Unable to connect to dcr wallet (start and sync wallets BEFORE starting dex!): dcrd has an incompatible JSON-RPC version: got 6.2.0, expected 7.0.0`
Then the markets or wallets page will be unable to attempt a new connection because it is still connected:
`[ERR] WEB: balance error: 42 -> dcr wallet error: Decred Wallet connect error: websocket client has already connected`
=> client/asset/dcr: shutdown ws client on Connect error

client/core/bookie.go
`bookie` embedded the `orderbook.OrderBook` type by value, which when assigning to it as a field like `b.OrderBook = orderbook.OrderBook{}` would overwrite each original field rather than treating `OrderBook` as a distinct object that could be replaced entirely.
This changes `bookie` so that it embeds a `*orderbook.OrderBook` (pointer), which forces assignment to `b.OrderBook` to leave the fields of the existing `OrderBook` alone.
The race is between `(*bookie).reset` writing a new `OrderBook` into the `bookie`:
https://github.com/decred/dcrdex/blob/9b012f9242bea5e82431726cd27bbd7d2372294e/client/core/bookie.go#L84-L87
and `(*OrderBook).LogEpochReport`  writing to the `feeRates` fields:
https://github.com/decred/dcrdex/blob/9b012f9242bea5e82431726cd27bbd7d2372294e/client/orderbook/orderboo …
=> client/core: fix bookie.OrderBook race

client/asset/eth/eth.go, client/asset/eth/eth_test.go, dex/testing/eth/harness.sh, server/asset/eth/common.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go
=> client/asset/eth: Use gwei in Balance. 

client/webserver/site/src/js/markets.js
=> add price rate to browser title

client/asset/btc/btc.go, client/asset/btc/rpcclient.go, dex/testing/btc/base-harness.sh, server/asset/btc/btc.go, server/asset/btc/rpcclient.go, server/asset/dcr/dcr.go, server/asset/dcr/utxo.go
With both client and server btc asset backends using dcrd's rpcclient,
the error type from all methods including `RawRequest` would be
`dcrjson.RPCError` not `btcjson.RPCError`.
The numeric codes will still pertain the btcjson constants, even though
the `dcrjson.RPCError.Code` field is of type `dcrjson.RPCErrorCode`.
Thus, error matching first interprets the error as a `dcrjson.RPCError`,
and then compares the `int` representation of `Code` to the expected
`int` code form btcjson.
=> btc: with dcrd's rpcclient, errors are dcrjson.RPCError

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/asset/interface.go, client/cmd/dexc/version/version.go, client/core/core.go, client/core/trade.go, client/webserver/site/src/js/markets.js, server/cmd/dcrdex/version.go
This bumps the app versions to 0.2.1 and backports the following:
- client/asset/trade: incorrect asset symbol logged
- client/asset/dcr: shutdown ws client on Connect error
- max order size computations could easily cause hang while iterating on max lots given no initial fees and large number of lots
The `OrderBook` race fix is more nuanced so that is separate: https://github.com/decred/dcrdex/pull/1131
=> [0.2.1] backports

client/core/bookie.go
This is a backport of https://github.com/decred/dcrdex/pull/1124 to the `release-v0.2` branch.
I had not initially planned to backport on account of the race, however the fix avoids another more problematic bug:
```
fatal error: sync: unlock of unlocked mutex
goroutine 69 [running]:
runtime.throw(0xcbf405, 0x1e)
runtime/panic.go:1117 +0x72 fp=0xc004c13af0 sp=0xc004c13ac0 pc=0x437f72
sync.throw(0xcbf405, 0x1e)
runtime/panic.go:1103 +0x35 fp=0xc004c13b10 sp=0xc004c13af0 pc=0x46c7f5
sync.(*Mutex).unlockSlow(0xc00057607c, 0xc0ffffffff)
sync/mutex.go:196 +0xd8 fp=0xc004c13b38 sp=0xc004c13b10 pc=0x48a138
sync.(*Mutex).Unlock(0xc00057607c)
sync/mutex.go:190 +0x48 fp=0xc004c13b58 sp=0xc004c13b38 pc=0x48a048
decred.org/dcrdex/client/orderbook.(*OrderBook).ValidateMatchProof.func1(0x0, 0xee6d60, …
```
=> [0.2.1] client/core: fix bookie.OrderBook race

dex/testing/eth/README.md, dex/testing/eth/create-node.sh, dex/testing/eth/harness.sh, go.mod, go.sum
Immediatly stopping the miner after starting to mine was causing
transactions to not be included in blocks. Change to start once and
stop a fraction of a second before N blocks should be mined.
Update internal geth to slightly after 1.10.5 and set harness to start
at the london fork.
=> harness/eth: Fix mining script.

client/asset/eth/eth.go, client/asset/eth/node.go, dex/testing/eth/create-node.sh
Use dex's logger in order to more easily manage log messages from the
internal geth node.
=> client/asset/eth: Use dex.Logger in internal node.

client/webserver/site/src/html/markets.tmpl, client/webserver/site/src/js/markets.js
This PR closes #1097.
It also adds a `Not enough funds` message when not having balance for the purchase.
=> Fix maxOrder when not enough balance

client/webserver/site/src/css/market.scss, client/webserver/site/src/html/markets.tmpl, client/webserver/site/src/js/markets.js
Closes #1045.
> As a general rule, any error encountered when submitting a form should be displayed on the form itself, not the notification bell. 
We will need to skip notification in checkResponse function and just return false if there is an error, and then display `res.msg` in related form's error section for all other forms.
=> ui: Display order errors on the form.

client/asset/btc/btc.go, client/asset/btc/walletclient.go, dex/testing/btc/base-harness.sh
This is a backport of the *client* portion of https://github.com/decred/dcrdex/pull/1128 for `release-v0.2`
With the client btc asset backend using dcrd's rpcclient,
the error type from all methods including `RawRequest` would be
`dcrjson.RPCError` not `btcjson.RPCError`.
The numeric codes will still pertain the `btcjson` constants, even though
the `dcrjson.RPCError.Code` field is of type `dcrjson.RPCErrorCode`.
Thus, error matching first interprets the error as a `dcrjson.RPCError`,
and then compares the int representation of `Code` to the expected
int code form `btcjson`.
=> [0.2.1] btc: with dcrd's rpcclient, errors are dcrjson.RPCError

server/market/market.go
From:
`MKT: sending error to user cbd16ee56d4e7ccdbd484dea290251f1e423474d1ec8d21d8edfcd0a7db4bd1d, code: 45, msg: preimage hash 30356636616334376163636433333864333239636331366636643539663334303963633862666537366132373265316565633631326534396331313531343564 does not match order commitment 36613631393132326636356434656264326465313633656163366134663761303331626565613434626162646165353863666330386361386330626166663934`
To:
`MKT: sending error to user 41ac6276df3a138f71d61aaf81536ef5c54f085f5ce91853d6b74e76e3ac4d6a, code: 45, msg: preimage hash 05f6ac47accd338d329cc16f6d59f3409cc8bfe76a272e1eec612e49c115145d does not match order commitment 0146d824953597ae8c0f2dadb0a4520e2840c8f3eff6581be3f4e6d2a4422b5f`
The client also shows `2021-08-03 18:36:45.001 [ERR] CORE[wss://127.0.0.1:17273/ws]: No …
=> market: Fix preimage log.

dex/order/order.go, server/db/driver/pg/orders.go, server/db/interface.go, server/market/market.go, server/market/market_test.go, server/market/orderrouter.go, server/market/routers_test.go, server/swap/swap.go
This PR adds the ability for clients to submit cancel orders while a market is suspended.
The database entries after a cancel order during a market suspension will be identical to one that gets matched while the market is running, except the preimage will not be recorded. Also there will be no entry in the epochs table for the epoch in which this order was "matched". 
Closes #792
=> server: Allow cancel orders while market is suspended.

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, go.mod, go.sum
Also
- modify `TestFindRedemption` to test finding redeem txs in mempool
- fix re-org depth calculation in {dcr,btc}.checkNewBlocks.
=> client/asset/dcr: refactor findRedemptionsInBlockRange to use cfilters

client/cmd/dexcctl/main.go, client/rpcserver/handlers.go, client/rpcserver/handlers_test.go, client/rpcserver/rpcserver.go, client/rpcserver/rpcserver_test.go, client/rpcserver/types.go, client/rpcserver/types_test.go, dex/msgjson/types.go
appseed is able to return the app's seed as hex if supplied the correct
application password.
While here, fix error checking of type tests to not ignore expected
errors when no error happens.
Bump the rpcserver minor version to four because dexcctl was already at
three for some reason, and this adds a feature that is backwards
compatible because it is just a new endpoint.
closes #1147
=> rpc: Add appseed endpoint.

go.mod, go.sum, server/admin/api.go, server/asset/btc/btc.go, server/asset/common.go, server/asset/dcr/dcr.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go, server/dex/feemgr.go, server/market/market.go, server/market/market_test.go, server/market/routers_test.go, server/swap/swap_test.go
When using rpcclient with dcrd with a WebSocket connection and its auto-reconnect feature, RPCs will hang until the client reconnects or the `Context` provided to them is cancelled.  `asset.Backend` methods sometimes accept a `Context` from consumers, and sometimes we use a `Backend`'s built-in "RPC context" to cancel RPCs when the `Backend` subsystem stops.  Unfortunately, because subsystems that consume `Backends` (e.g. `Market`) are generally shutdown *before* the `Backend`s, their shutdown can hang on RPCs.  This suggests that we really do have to have every `Backend` method that performs an RPC accept a `Context`.  (Shutting down the `Backend`s first is not desirable.)  This also may suggest we should not use auto-reconnect.
I'm not prepared to take that leap to contextifying …
=> server: address RPC hangs with disconnected RPC server

dex/msgjson/types.go, server/dex/dex.go
To smooth the big coming 0.3 update, it would be very helpful to have the dex public key in the config response for 0.2.x servers so 0.3 clients are not forced to use the legacy account key path instead of HD key derivation.
See https://github.com/decred/dcrdex/pull/1015/files/07b2eddb074f4ae1230299a3d9bdf381f89fcbb7#r685272694 and https://github.com/decred/dcrdex/pull/1015/files/07b2eddb074f4ae1230299a3d9bdf381f89fcbb7#r681461826
Consider that we are jumping through hoops in code to deal with the possibility of legacy servers, but there is only one public server presently.  Just getting that server on 0.2.2 well in advance of 0.3 will make this a more pleasant experience.  Any private servers that might exist probably have close coordination with their clients.
=> [0.2.2] msgjson,server/dex: dexpubkey in config

dex/testing/dcr/README.md, dex/testing/dcr/create-wallet.sh, dex/testing/dcr/harness.sh
The dcr reorg script is modified to accept 2 optional arguments:
`./reorg (node depth), where
- `node` is the node that should undergo a reorg, either "alpha" or "beta" (default: alpha)
- `depth` is the number of blocks that should be purged from `node` (default: 2).
At the end of the reorg, both nodes will have `depth+1` new blocks.
During reorg, a clone of the alpha wallet is connected to the beta node after the beta node
is disconnected from the alpha node. This is done to enable mining multiple blocks on the
beta node.
The alpha wallet clone uses the same seed as the alpha wallet and is thus able to vote on
tickets purchased by the alpha wallet when the alpha node was connected to the beta node,
supplying enough votes to the beta node to validate previous blocks and allow the creation …
=> dex/testing/dcr: fix reorg script

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/rpcclient.go, client/asset/eth/rpcclient_harness_test.go, server/asset/eth/common.go, server/asset/eth/eth_test.go
Add TxIDFlag and SwapFlag in order to specify that a coin ID represents
either a txid or a swap. IsTxIDCoinID and IsSwapCoinID package methods
are included so that callers can easily discern if they have the right
type of coin ID for the operation they are performing.
related to #1021
=> eth: Add CoinID flags.

client/webserver/site/.stylelintrc, client/webserver/site/src/css/main.scss, client/webserver/site/src/css/market.scss, client/webserver/site/src/html/markets.tmpl
=> ui: restore vscroll to buy/sell orders tables

client/asset/bch/regnet_test.go, client/asset/btc/btc_test.go, client/asset/btc/livetest/regnet_test.go, client/asset/dcr/dcr_test.go, client/asset/dcr/simnet_test.go, client/asset/eth/eth_test.go, client/asset/eth/rpcclient_harness_test.go, client/asset/ltc/regnet_test.go, client/core/account_test.go, client/core/core_test.go, client/core/trade_simnet_test.go, client/rpcserver/rpcserver_test.go, client/webserver/live_test.go, client/webserver/webserver_test.go, client/websocket/websocket_test.go, server/asset/bch/live_test.go, server/asset/btc/btc_test.go, server/asset/btc/live_test.go, server/asset/dcr/dcr_test.go, server/asset/dcr/live_test.go, server/asset/eth/eth_test.go, server/asset/eth/rpcclient_harness_test.go, server/asset/ltc/live_test.go, server/db/driver/pg/accounts_online_test.go, server/db/driver/pg/matches_online_test.go, server/db/driver/pg/orders_online_test.go, server/db/driver/pg/orders_test.go, server/db/driver/pg/system_online_test.go, server/db/driver/pg/tables_online_test.go, server/db/driver/pg/upgrades_test.go
Begin transition from "// +build" lines to "//go:build".
See https://golang.org/design/draft-gobuild
=> go:build migration and gofmt fixes

dex/calc/fees.go, server/asset/eth/common.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go
Also implement InitTxSizeBase.
The size of a tx does not actually tell us how much a transaction paying
to a contract with extra data will cost to send. The evm will determine
how much gas will be used. The exact cost can probably be determined but
will take a lot of digging, and will change if the contract changes. For
now, use an approximation of used gas based off of tests.
Our current implementation also does not allow for batch transactions.
As such, return zero for InitTxSizeBase in order to ensure fee
calculations equate to what we expect, which is a one for one
initilizaion and gas fee.
Part of #1154
=> server/eth: Implement InitTxSize.

client/webserver/site/src/js/markets.js
There were multiple issues with the max order UI. There would be a console
error saying the the maxLoaded function was null. This would happen if there
were two concurrent requests where the one that started first finished last.
Also, if a cached value was input while a another value was being fetched,
the cached result would be overridden by the value being fetched from the
client causing a mismatch between the rate in the input box and the result
on the screen.
Closes #1169.
=> Fix max order UI.

server/db/candles.go, server/db/candles_test.go
`CandleCache` is designed to be used by clients, who may want access to the cached candles directly. Currently the only way to access the data is with `WireCandles`, which is not always efficient. Both dcrdata's `ExchangeBot` and dexc will benefit from having the candles exported.
=> client/db: export CandleCache candles

server/comms/comms_test.go
So, this is kinda a selfish pr, but I have been unable to run the server tests for a while because I have ipv6 disabled at the kernel level on my machine. This changes this test to use tcp4??? On master I cannot run tests with the failure:
```
--- FAIL: TestOnline (0.02s)
comms_test.go:673: server constructor error: Can't listen on :0: listen tcp6 :0: socket: address family not supported by protocol
```
=> comms/test: Use ipv4 in TestOnline.

client/core/core.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/site/src/js/forms.js, client/webserver/webserver.go, client/webserver/webserver_test.go
Primarily resolves #1172.
Also splits `core.register` into `core.registerHD` and `core.registerLegacy`. `core.PreRegister` now only attempts HD account registration to determine if an account exists and can be restored.
=> client/core: app seed optimisations

client/webserver/locales/parse.go, client/webserver/site/template-builder/main.go, client/webserver/template.go, client/webserver/webserver.go
When **`dexc`** is run with the `--reload-html` flag, re-translate templates on the fly. 
**You still can't update the maps in `locales.Locales`.** If you update one of those, you'll need to restart **`dexc`**.
=> webserver: retranslate template when --reload-html is used

client/core/localetest/main.go, dex/ip.go, dex/msgjson/types.go, server/comms/comms_test.go, server/comms/link.go, server/comms/middleware.go, server/comms/server.go
Several of the websocket routes are assigned both sustained and burst
rate limits of their own.
Despite challenges of DDoS, address spoofing, and large IPv6 subnets,
limiters are created by remote IP, with uniqueness determined by
`dex.IPKey`, which masks interface bits of IPv6 addresses, and provides
a method to retrieve the 48-bit prefix (public topology).
An IP's limiter is removed from memory a minute after last conn
is disconnected.  This is done to prevent churning connections
to reset limits.
`rpcMaxConnsPerIP` is the maximum number of active websocket connections
allowed per IP, loopback excluded.
This adds code to help devise possible prefix aggregation according to
some heuristic based on the number of different subnets in use from
the same prefix. Just logging of such …
=> server/comms: more fine grained websocket route limiter

client/webserver/locales/en-us.go, client/webserver/site/src/html/forms.tmpl, client/webserver/site/src/html/orders.tmpl, client/webserver/site/src/html/settings.tmpl, client/webserver/site/src/html/wallets.tmpl, client/webserver/site/src/js/app.js, client/webserver/site/src/js/doc.js, client/webserver/site/src/js/forms.js, client/webserver/site/src/js/locales.js, client/webserver/site/src/js/login.js, client/webserver/site/src/js/markets.js, client/webserver/site/src/js/order.js, client/webserver/site/src/js/orderutil.js, client/webserver/site/src/js/register.js, client/webserver/site/src/js/settings.js, client/webserver/site/src/js/wallets.js, client/webserver/site/src/localized_html/en-US/forms.tmpl, client/webserver/site/src/localized_html/en-US/wallets.tmpl, client/webserver/template.go
- Adds a couple of missed translations. I wanted to sneak this in before #1185.
- Refactors **locales.js**. I think the changes make the import and use of the module cleaner.
=> intl: add missing translations. refactor locales.js

client/core/core.go
Rather than search for addresses in contracts, use the deposit address
to determine if the new wallet is the same as the old one.
closes #1136
=> client/core: Check deposit addr in reconfigure.

client/asset/eth/rpcclient_harness_test.go, server/asset/eth/rpcclient_harness_test.go
os.Exit does not respect defer statements. Run tests in a separate
function for intended node teardown to happen.
was part of #1162
=> eth/testing: Ensure node shutdown happens.

client/core/core.go, client/core/core_test.go, client/core/errors.go, client/core/types.go, dex/msgjson/types.go, server/auth/auth.go
This is a prerequisite for multi-asset registration fee support.
Instead of using the `'register'` route to discover an existing account when restoring from an seed, use `'connect'` (`authDEX`).  Initially suggested https://github.com/decred/dcrdex/pull/1015#discussion_r666440449
This allows account discovery without having to request a registration address.  More importantly, when registration may be done with more than one asset, this avoids having to commit to a certain registration asset in order to discover an existing account.  This is because the `'register'` route will require an asset ID in a multi-asset registration scheme.
This eliminates the "in-process"/"incomplete" registration field and simplifies some logic in `Register`.
=> client/core: discover account via connect instead of register

client/cmd/dexcctl/simnet-setup.sh, server/db/driver/pg/internal/markets.go, server/db/driver/pg/pg.go, server/db/driver/pg/system_online_test.go, server/db/driver/pg/tables.go, server/db/driver/pg/tables_online_test.go
server/db: Update lot sizes when necessary.
No longer panic when lot size changes. If lot sizes changed, update them
in the db. Then, flush all persisted orders belonging to that market.
depends on #1202
closes #1174
=> server/db: Update lot sizes when necessary.

client/cmd/dexc/main.go
Resolves https://github.com/decred/dcrdex/issues/1176
The base branch to which this PR applies will need to be changed when we branch `release-0.3`.  I'm putting this up now so I do not forget.
=> [0.3] dexc: comment eth import for release

client/asset/eth/config.go, client/asset/eth/doc.go, client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/node.go, client/asset/eth/rpcclient.go, client/asset/eth/rpcclient_harness_test.go, client/cmd/dexc/gplimport.go, client/cmd/dexc/importlgpl.go, client/cmd/dexc/main.go, dex/networks/eth/abi.go, dex/networks/eth/abi_test.go, dex/networks/eth/doc.go, dex/networks/eth/txdata.go, dex/networks/eth/txdata_test.go, dex/testing/dcrdex/harness.sh, run_tests.sh, server/asset/eth/cache.go, server/asset/eth/common.go, server/asset/eth/config.go, server/asset/eth/doc.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go, server/asset/eth/rpcclient.go, server/asset/eth/rpcclient_harness_test.go, server/cmd/dcrdex/gplimport.go, server/cmd/dcrdex/importlgpl.go, server/cmd/dcrdex/main.go
In order to check data in a mempool transaction is formatted as we
expect and in order to read its arguments, add package methods that are
able to parse and validate Initiate and Redeem transaction data.
Some of this code is taken directly from the go-ethereum repository
where it is unexported there. abi.go and abi_test.go should be updated
if they change over there.
=> networks/eth: Add methods to decode tx data.

client/asset/btc/btc.go
I zeroed the `resultChan` capacity in [one of the last commits](https://github.com/decred/dcrdex/pull/1089/commits/fc1b11cc98cf76f193609f4ad8628902a34b3a8d) to #1098, and it looks like we were able to [miss a result ](https://github.com/buck54321/dcrdex/runs/3738084200?check_suite_focus=true).
=> revert dropped capacity for the redemption result chan

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/rpcclient.go, client/asset/eth/rpcclient_harness_test.go, server/asset/eth/common.go
This diff completes the MaxOrder function for ETH and also adds
functions that calculate the gas needed for initializing and
redeeming a swap on ETH. The gas calculation is function is used
in MaxOrder, but in case of a calculation failure, the hardcoded
gas value that is returned from the server is used.
Part of #1154
=> eth/client: Implement MaxOrder

client/asset/eth/eth.go, client/asset/eth/eth_test.go, server/asset/eth/common.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go
=> client/eth: FundOrder, ReturnCoins, FundingCoins

client/asset/eth/rpcclient.go, server/asset/eth/coiner.go, server/asset/eth/coiner_test.go, server/asset/eth/common.go, server/asset/eth/config.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go, server/asset/eth/rpcclient.go, server/asset/eth/rpcclient_harness_test.go
The eth contract requires the initial transaction used to initiate a
swap to extrapolate swap data. Confirm data upon Confirmations being
called.
Part of #1154
=> server/eth: Add Contract method. 

client/asset/bch/bch.go, client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/asset/driver.go, client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/node.go, client/asset/eth/rpcclient.go, client/asset/eth/rpcclient_harness_test.go, client/asset/interface.go, client/asset/ltc/ltc.go, client/core/core.go, client/core/core_test.go, client/core/types.go, client/webserver/live_test.go, dex/keygen/keygen.go, dex/keygen/keygen_test.go, dex/networks/eth/txdata_test.go, dex/testing/eth/harness.sh, run_tests.sh
`asset.Driver` is now updated with a `Create` function, which is used to initialize a seeded wallet, and `(Driver).Setup` has been renamed to `(Driver).Open`. The seed for seeded wallets is derived from the app seed using `blake256(appSeed|asssetID)`. The private key for the eth wallet is derived from this seed using the following BIP32 derivation path: `m/44'/60'/0'/0/0`.
=> eth/client/core: Derive account from app seed

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/rpcclient.go, client/asset/btc/spv.go, client/asset/btc/spv_test.go, client/asset/btc/wallet.go, client/core/bookie.go, go.mod, go.sum
This solves a couple of issues with bitcoin SPV syncing. 
1. Neutrino stores the block header before requesting filter headers and looking for wallet scripts, so the `balanceUpdate` requested by `Core` can come before the wallet has seen new funds. This was obvious during testnet syncing when outputs from even 1000s of blocks ago were not seen (block headers are stored in batches during initial sync) until an additional block was mined after sync.
2. Block notifications were being sent from `ExchangeWallet` before the `xcWallet` was added to the `wallets` map in `*Core`, resulting in error messages saying `non-existent 0 wallet should exist`.
This solution gives wallet notifications precedence by queuing polled new tips temporarily to allow the wallet notifications to come through. This …
=> btc spv: give wallet precedence for block notifications

client/asset/dcr/dcr.go
The legacy wallet Type of `""` must be recognized as an RPC wallet type.
=> client/asset/dcr: NewWallet must recognize the legacy type

client/core/bookie.go
This is a second crack at avoiding a data race with the spot price map. Initially "fixed" in https://github.com/decred/dcrdex/pull/1240.
The notification consumers process the spot price map
asynchronously, so we have to make a copy of the map
that we intend to store in dc.spots.
<details>
```
==================
Write at 0x00c0152baa20 by goroutine 52:
runtime.mapassign_faststr()
/home/jon/go117/src/runtime/map_faststr.go:202 +0x0
decred.org/dcrdex/client/core.handlePriceUpdateNote()
/home/jon/github/decred/dcrdex/client/core/bookie.go:967 +0x33d
decred.org/dcrdex/client/core.(*Core).listen.func1()
/home/jon/github/decred/dcrdex/client/core/core.go:5513 +0x16f
decred.org/dcrdex/client/core.(*Core).listen.func2()
/home/jon/github/decred/dcrdex/client/core/core.go:5527 …
```
=> client/core: make copy of spot price map

client/asset/btc/spv.go, client/core/harness_norace.go, client/core/harness_race.go, client/core/trade.go, client/core/trade_simnet_test.go
Work toward fixing https://github.com/decred/dcrdex/issues/1246, just the trade tests though, not the order status or pending requests tests.
Allow spv wallet to sync before funding it.  Wait a bit after funding it for it to filter the new blocks and update balance.
Add a sleepFactor that multiplies various test sleeps when the race detector is enabled.
Add a sleep in places before mining blocks, where it follows an SPV wallet doing a broadcast.  The send transaction commands return from wallet before the txn actually reaches miners.  Always was a race we were winning until SPV.
=> trade_simnet_test fixes

client/core/bookie.go, client/core/core.go
Temporary DEX connections should not subscribe to the price feed.
This launches the `subPriceFeed` goroutine only when the listen goroutine
is started with a persistent dex connection.
=> client/core: only subscribe to price feed for persistent conns

client/core/account.go, client/core/core.go
In testing https://github.com/decred/dcrdex/pull/1141 with manual account disable I hit some races with the `c.conns` maps.
The one in `(*Core).exchangeMap()` is a little surprising since that method is used all the time.
=> client/core: fix conns data races

client/asset/btc/spv.go
Use the known block `Hash` instead of using the `btcutil.(*Block).Hash` method.  That method mutates a field of the `Block` to cache the hash, unfortunately it is not thread-safe, and it is in use concurrent with other goroutines inside neutrino including `VerifyBasicBlockFilter`.
https://github.com/btcsuite/btcutil/blob/9cdf59f60c5150188dc0fadac6e9383522fddb74/block.go#L93-L106
<details>
<summary>race 1</summary>
```
==================
Read at 0x00c000d7f618 by goroutine 53:
github.com/btcsuite/btcutil.(*Block).Hash()
/home/jon/go/pkg/mod/github.com/btcsuite/btcutil@v1.0.3-0.20210527170813-e2ba6805a890/block.go:98 +0x52
decred.org/dcrdex/client/asset/btc.(*spvWallet).filterScanFromHeight()
/home/jon/github/decred/dcrdex/client/asset/btc/spv.go:1430 +0xf98 …
```
=> client/asset/btc: use known block hash

dex/testing/btc/base-harness.sh
This sets the bitcoind debug levels selectively.  I was getting spammed with libevent junk.
=> dex/testing: set btc harness debug levels per-subsystem

client/asset/btc/btc.go, client/asset/dcr/dcr.go
Both bitcoin and decred do not need the sequence to be set to one less
than max in order to redeem, only to refund. Remove the unneeded
assignments and move the doc. Point decred's doc at decred material.
=> client/asset: Use max sequence only for refunds.

client/core/types.go, client/webserver/types.go
Resolves https://github.com/decred/dcrdex/issues/922
Supplement `core.Match` with an `Active` field, set via `db.MatchIsActive`.
Update `(*orderReader).hasLiveMatches` to consult the `Active` field instead of just comparing `Status < MakerRedeemed`.
Update `(*matchReader).StatusString` with text for revoked matches.
When revoked and also active show "Revoked - Refund PENDING".
When revoked and not active, show if it was refunded, (auto)redeemed, or simply complete when no txns are needed.
**Revoked and waiting to refund**
**Revoked with nothing to do (inactive)**
**Revoked and auto-redeemed**
=> client/{core,webserver}: show match revoked status

client/asset/btc/btc.go, client/asset/dcr/dcr.go
Broadcasting the counterparty swap transaction in `AuditContract` is not required to pass the audit, yet for SPV wallets it can be quite slow.  It can even timeout if there is p2p trouble.
As such, just broadcast in a goroutine so the `AuditInfo` return can be recorded as soon as possible.
=> client/asset/{btc,dcr}: broadcast async

client/asset/btc/btc_test.go, client/asset/btc/spv_test.go
Protect `getBestBlockHashErr` with the `blockchainMtx` since it's accessed asynchronously from the block monitor loop via `getBlockHeader` -> `BestBlock`.
=> client/asset/btc: fix test race

client/asset/bch/bch.go, client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/livetest/livetest.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/simnet_test.go, client/asset/eth/eth.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/trade.go
The `Time` argument for `AuditContract` is not used now that the method does not search for the contract on the network, that now being the job of `SwapConfirmations`.
This replaces the `Time` arg with a `rebroadcast bool`, so that the consumer may decide if a rebroadcast should be attempted.
This also logs the audited counterparty contract script since that is essential if manually redeeming the counterparty contract is required.
=> client/asset: remove time from AuditContract args

server/asset/eth/common.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go
server/eth: Implement ValidateContract.
Require the the Contract field of msgjson.Init be filled with the txdata
used to create the swap. Validate that txdata to be of the correct
format sending the expected types of arguments.
work towards #1154 depends on #1235
=> server/eth: Implement ValidateContract.

client/core/core.go, client/core/status.go, client/core/trade.go, client/core/trade_simnet_test.go
When taker, it is possible to miss a revoke and have the initiation swap
happen automatically on start up. Add checkServerRevoke to the match
tracker in order to force false for isSwappable until at least one
order status message has been received for the order.
closes #1246
This change plus setting `-timeout=20` solves the simnet test issues for me.
=> client: Wait for server revoke status of init.

dex/msgjson/types.go, server/comms/server.go
Add the newish price feed, spots, and candles to the `routeLimiter`.
The "info" limiter includes the spots and candles routes.
A new shared limiter for subscription routes is created for the `order_book` and the new `price_feed` routes.
Add the connect route with its own rates. Burst is still 100. Clients should self limit during account discover, as we do.
=> server/comms: add new routes to limiter

client/asset/bch/bch.go, client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/asset/eth/eth.go, client/asset/interface.go, client/core/core_test.go
The code calling `RefundAddress` was previously removed, but the function was never removed from the wallets.
=> client: Remove RefundAddress

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/rpcclient.go, client/asset/eth/rpcclient_harness_test.go
The string address can have different formattings, so parse the input string into a `common.Address` and compare that to the account address.  For example, it can be formatted with mixed case and with or without "0x", among other things.
Also use direct array comparison for address equality instead of `bytes.Equal`.
Also address some missing error checks.
=> eth: compare parsed address in OwnsAddress

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/rpcclient_harness_test.go, server/asset/eth/common.go
Prior to this, `FundOrder` did not lock funds to use for the gas fees in the case of a refund.
=> eth/client: Lock funds for possible refund

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/rpcclient.go, client/asset/eth/rpcclient_harness_test.go, dex/networks/eth/txdata.go, dex/networks/eth/txdata_test.go
This PR updates the `Balance` method of the ETH client wallet by taking into account the effects of pending transactions. Pending incoming funds need to be represented by the `Immature` field in the `asset.Balance` struct, and pending outgoing funds must be subtracted from the `Available` field. When retrieving the pending balance from the eth client, the effects of incoming and outgoing funds in pending transactions are aggregated, so the pending transactions are all checked for their effects individually.
Part of #1154
=> eth/client: Pending balance

server/asset/common.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go, server/asset/eth/rpcclient.go, server/market/orderrouter.go, server/market/routers_test.go, server/swap/swap.go
The interfaces are going to need to diverge when it comes to tracking funding ability. This PR is a first thrust at a reasonable interface scheme so that we can begin work in `Swapper`, `Market`, and `CoinLocker`.
=> server,eth: add method for account balance retrieval

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/rpcclient.go, client/asset/eth/rpcclient_harness_test.go, server/asset/eth/common.go
This diff implements the Swap function in the eth client wallet. In addition, the eth client wallet no longer does gas estimations using the eth client and uses hardcoded values instead. Gas estimations do not vary unless the eth client is updated, and these changed will be caught by the harness tests, so it is safe to just use the hardcoded values.
Part of #1154
=> eth/client: Swap

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/nodeclient.go, client/asset/eth/nodeclient_harness_test.go
Implement `RegFeeConfirmations`. Add `transactionConfirmations` method
to `nodeClient`. Check local tx pool first, since non-zero confs will
always request from peers, and the tx we're looking for is ours.
=> client/asset/eth: RegFeeConfirmations

dex/testing/eth/create-node.sh, dex/testing/eth/harness.sh
The reorg script can cause reorgs like other chains, but has a precision
of two blocks for now, as it is so far not possible to mine only one
block at a time.
=> eth/harness: Add reorg script.

server/asset/eth/eth.go, server/asset/eth/eth_test.go
Older notions of coin ID have evolved. Except in the case of a funding coin, ETH coin ID will simply be the tx hash bytes.
=> server/asset/eth: update server coin ID parsing

client/asset/btc/btc_test.go, dex/asset.go, dex/bip-id.go, dex/calc/fees.go, dex/msgjson/types.go, dex/order/order.go, server/asset/common.go, server/asset/eth/coiner_test.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go, server/asset/eth/rpcclient.go, server/asset/eth/rpcclient_harness_test.go, server/book/accounts.go, server/book/accounts_test.go, server/book/book.go, server/book/book_test.go, server/book/orderpq.go, server/book/orderpq_test.go, server/dex/dex.go, server/market/balancer.go, server/market/balancer_test.go, server/market/integ/booker_matcher_test.go, server/market/market.go, server/market/market_test.go, server/market/orderrouter.go, server/market/routers_test.go, server/swap/swap.go, server/swap/swap_test.go
Adds funding validation for account-based assets i.e. eth.
**dex**: Add `RedeemSize` field to `Asset`.
**msgjson**: Add `RedeemSig` field to `Trade`. `RedeemSig` should be
populated when the redemption is to an account-based asset.
This PR also indirectly proposes a protocol for specifying
the funding account. The account address should be utf-8 encoded
and passed as the coin ID of the only coin, along with the pubkey
and signature. The data signed will be the serialized `msgjson.Limit` or
`msgjson.Market`, with server stamp set to 0. Same signature input
for the `RedeemSig`.
**dex/order*: The `Trade` type has methods for accessing the account address.
**server/asset**: `AccountBalancer` gets a `ValidateSignature` method.
**general scheme**: Orders and matches involving account-based …
=> server/{swap,market}: add funding checks for account-based assets

dex/networks/eth/cointypes.go, server/asset/eth/coiner.go, server/asset/eth/coiner_test.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go
TxCoinID contained an Index field which is now removed, and in many places the code assumed that a contract is a SwapCoinID when in fact it should be just a secret hash.
=> eth: Update TxCoinID and Contract

client/asset/eth/contractor.go, client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/nodeclient.go, client/asset/eth/nodeclient_harness_test.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go
The client apparently doesn't maintain a pending state, so the
way I had calculated balance client-side didn't work. Go back
to @martonp's initial implementation which parses redeem
and refund data from transactions.
Remove the `Pending` field from `Balance`. It wasn't used.
=> client/asset/eth: fix client balance calcs

client/asset/eth/contractor.go, client/asset/eth/contractor_test.go
These were ripped out with the changes in #1301 because `ExchangeWallet` no longer deals with the abigen types. Now re-implemented through contractor tests.
=> client/asset/eth: re-implement translation tests for abigen types

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/nodeclient.go, client/asset/eth/nodeclient_harness_test.go, client/asset/interface.go, client/core/trade.go, dex/networks/eth/txdata_test.go
=> eth/client: Redeem

client/asset/eth/eth.go, client/asset/eth/eth_test.go
Pull the swap data from the contract and compare the lock time against the best header's timestamp.
=> client/asset/eth: implement LocktimeExpired

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/interface.go, client/core/trade.go, client/webserver/live_test.go, dex/networks/eth/params.go, run_tests.sh, server/asset/eth/coiner.go, server/asset/eth/coiner_test.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go
The `msgjson.Init.Contract` and `server/asset.Contract.RedeemScript` fields
contain an encoding of the ETH contract version concatenated with the
swap's secret hash that is the unique key for the swap.
This updates server/asset/eth's `ValidateContract` and `Contract` methods
to decode and check this data.
This also adds the `dexeth.EncodeContractData` and `DecodeContractData` functions.
=> dex/networks,server/eth: decode swap data message blob

client/asset/eth/config.go, client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/node.go, client/asset/eth/nodeclient_harness_test.go
`Exists` works by trying to load the keystore and checking for > 1
wallets. Remove unused `"appdir"` setting from custom config. We already
have `CreateWalletParams.DataDir`.
=> client/eth: implement Exists

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/nodeclient.go, client/asset/eth/nodeclient_harness_test.go
=> eth/client: AuditContract

client/asset/eth/contractor.go, client/asset/eth/eth.go, client/asset/eth/eth_test.go, dex/networks/eth/abi.go, dex/networks/eth/abi_test.go, dex/networks/eth/params.go, dex/networks/eth/txdata.go, dex/networks/eth/txdata_test.go, server/asset/eth/coiner.go
The functions used to parse and pack call data for the eth swap contract only supported version 0. This diff makes those functions version agnostic.
=> eth: Versionize tx data handling

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/btc/livetest/livetest.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/simnet_test.go, client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/interface.go, client/core/core_test.go, client/core/trade.go, client/core/trade_simnet_test.go, client/db/bolt/upgrades.go, client/db/types.go
Add an argument for contract data. Rename `MatchProof.Script` field
to `ContractData`, for consistency. Implement redemption request queue,
analogous to btc and dcr.
=> client/asset/eth: implement FindRedemption

.github/workflows/build.yml, server/db/driver/pg/epochs.go
The golangci-lint install script at goreleaser.com is deprecated. Docs now advise to install from a github link:
> golangci/golangci-lint err this script is deprecated, please do not
> use it anymore. check goreleaser/godownloader#207
This update caught a previously undetected missing `rows.Err` check in `LoadEpochStats`.
=> CI: fix deprecated golangci-lint install url, bump to 1.43

server/asset/btc/btc.go, server/asset/common.go, server/asset/dcr/utxo.go, server/swap/swap.go
The server's audit of the taker's contract must also verify that the contract hash used in their contract script matches the secret hash from the maker's contract.  This check is already performed client-side, this just updates the server's auditing to do it as well.
This was included in a recent v0.2 backport PR: https://github.com/decred/dcrdex/pull/1338
=> server: validate taker's contract hash in audit

server/asset/btc/btc.go, server/asset/common.go, server/asset/dcr/utxo.go, server/swap/swap.go
This is https://github.com/decred/dcrdex/pull/1351 for the `release-v0.4` branch.
The server's audit of the taker's contract must also verify that the contract hash used in their contract script matches the secret hash from the maker's contract.  This check is already performed client-side, this just updates the server's auditing to do it as well.
=> [release-v0.4] server: validate taker's contract hash in audit

dex/keygen/keygen.go, dex/keygen/keygen_test.go, go.mod, go.sum
<s>Requires https://github.com/decred/dcrd/pull/2845</s>
Updates the `github.com/decred/dcrd/hdkeychain/v3` require to v3.1.0.
**WARNING:** Keys derived from the app seed are likely to be different with the updated strict BIP32 HD key derivation.  This includes
- DEX accounts
- Any keys derived by `Wallet`s such as in `client/asset/eth` where it prepares a private key for the BIP44 path m/44'/60'/0'/0/0
As such, you should not rely on any of these accounts or keys being recoverable.
This updates the `GenDeepChild` helper, which is used in both client/core to setup DEX account keys from the app seed, and in client/asset/eth to derive the account private key from the wallet seed.
This is especially in the eth key derivation, where the intent is to follow BIP44 with the path …
=> dex/keygen: use ChildBIP32Std  for extended key derivation

dex/keygen/keygen.go, dex/keygen/keygen_test.go, go.mod, go.sum
This is https://github.com/decred/dcrdex/pull/1341 for the `release-v0.4` branch.
Requires https://github.com/decred/dcrdex/pull/1349, which updates the go.mods first.
Updates the `github.com/decred/dcrd/hdkeychain/v3` require to v3.1.0.
**WARNING:** Keys derived from the app seed are likely to be different with the updated strict BIP32 HD key derivation.  This includes
- DEX accounts
- Any keys derived by `Wallet`s such as in `client/asset/eth` where it prepares a private key for the BIP44 path m/44'/60'/0'/0/0
As such, you should not rely on any of these accounts or keys being recoverable.
This updates the `GenDeepChild` helper, which is used in both client/core to setup DEX account keys from the app seed, and in client/asset/eth to derive the account private key from the wallet seed. …
=> [release-v0.4] dex/keygen: use ChildBIP32Std for extended key derivation

client/asset/eth/fundingcoin.go, client/asset/eth/fundingcoin_test.go
The nonce in `FundingCoinID` is no longer needed because we only use the address in communication with the server, and the client wallet no longer uses a map to keep track of unique coin ids.
=> client/asset/eth: Remove nonce from funding coin id

client/asset/btc/rpcclient.go, client/asset/btc/wallettypes.go
Bitcoin Core v22 creates Descriptor wallets instead of Legacy wallets by default if the DB backend in the build is sqlite instead of bdb.  v0.21 still used Legacy wallets by default as descriptor wallets were experimental in v0.21.
This is a problem because descriptor wallets do not support the `dumpprivkey` RPC, which we need for several reasons, but most importantly for signing the redemption tx input with the private key for the address referenced by the contract script.
https://bitcoincore.org/en/releases/0.21.0/#experimental-descriptor-wallets
"New export RPCs for Descriptor Wallets have not yet been added"
This change adds a `getwalletinfo` check in `(*rpcClient).connect` to ensure that the `Descriptors bool` is false.
This should be cherry-picked to `release-v0.4` for RC2.
=> client/asset/btc: disallow descriptor wallets

client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/js/doc.js, client/webserver/site/src/js/markets.js, client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl, client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl, client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl
The legends on both the depth and candlestick charts were using incorrect units.  On the depth chart, it was applying the conversion factor a second time.  On the candlestick chart, an incorrect struct access was used to get the `unitinfo`, so no conversion was applied.
This should be cherry-picked to `release-v0.4` for RC2.
Depth legend before:
Depth legend after:
Candlestick legend before:
Candlestick legend after:
=> client/webserver/site: Use correct volume.

dex/ws/wslink.go, server/comms/link.go
**Must** be included in v0.4.
This increases the server's authorized read limit by a factor of 4. We have observed the previous limit of 65 KiB is inadequate when there are a large number of orders in a single epoch, and with more funding coins than normal.  This can be extremely disruptive.
This also doubles the unauthorized/default read limit, which is still quite small at 8192 bytes.
=> server/comms,dex/ws: increase websocket read limits

client/asset/eth/eth.go, client/asset/eth/eth_test.go
Return txid bytes for printing.
Reduce amount to withdraw by the max possible fee if value cannot
otherwise be sent.
part of #1154
=> client/eth: Fix withdraw TODOs.

client/cmd/dexcctl/config.go, client/cmd/dexcctl/main.go, client/cmd/dexcctl/version.go, pkg.sh
Just copying the version stuff from dexc to resolve https://github.com/decred/dcrdex/issues/1378
I'm aware there are new approaches. i.e. https://github.com/decred/dcrd/pull/2651 Please tell me if you want both dexc and dexcctl done that way @jrick .  I really don't have a preference.
=> dexcctl: prerelease and metadata build info

dex/msgjson/types.go
The backport in https://github.com/decred/dcrdex/pull/1155 was bad. 
:cry:
=> [release-v0.2] correct the dex pubkey tag in the config response

client/asset/btc/btc.go, client/asset/dcr/dcr.go
In the UTXO selection methods for DCR and BTC, initially only UTXOs with >0 confs are tried, and if there are insufficient funds, it
attempts it again with unconfirmed utxos included (minus "untrusted" for BTC). However, on the second run, both methods neglect to reset the `redeemScripts` slices.  This fixes the issue.
=> client/asset/{btc,dcr}: reset redeemScripts when changing min confs

server/asset/eth/eth.go, server/asset/eth/eth_test.go
Update server's eth backend to get swap contract addresses from the same place as the client.
=> server/eth: Use contract addresses in dex/eth

client/asset/eth/nodeclient.go, client/asset/eth/nodeclient_harness_test.go, dex/testing/eth/harness.sh
Use the base gas fee for the block before a tx was mined to caculate
exact gas used and test using that expected amount.
closes #1342
=> client/eth: Fix test gas calculations.

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/nodeclient.go, client/asset/eth/nodeclient_harness_test.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/status.go, client/core/trade.go, client/db/bolt/db.go, client/db/types.go
```   
client/asset:
Add AccounterRedeemer interface with methods for locking and unlocking
funds for redemption. ReserveN is used to reserve funds for an order.
Only the amount reserved is returned. All accounting from there is
handled by Core, who will return funds proportionally according to
match quantities and order size. The amount reserved is persisted in
the OrderMetaData so that accounting can be picked up exactly as it was on restarts.
This pattern was chosen over trying to figure out how much to lock
on restart with calculations based on order info because you would need
to consider changes in asset configuration and therefore persist more
data and ... it gets messy.
client/core:
Add RedeemSig to orders redeeming to and AccountRedeemer.
Track and return reserved redemption …
```
=> core,eth: handle redemption funding

client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/js/markets.js, client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl, client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl, client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl
As seen in the depth screen shots in https://github.com/decred/dcrdex/pull/1368, the price in the depth chart legend was showing as zero.  This is because the conversion factor was being applied to the `rate` field when it was already applied (`msgrate` contains the atomic "message rate").
=> app: correct price in depth chart legend

client/asset/eth/contractor.go, client/asset/eth/eth_test.go, dex/networks/eth/common.go, dex/networks/eth/params.go, dex/networks/eth/txdata.go, dex/networks/eth/txdata_test.go, server/asset/eth/coiner.go, server/asset/eth/coiner_test.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go, server/asset/eth/rpcclient.go
```
Separate swapCoin from redeemCoin. Switch (*rpcclient).swap method to
return a *dexeth.SwapState.
```
=> server/asset/eth: refactor coins

client/asset/btc/spv.go
Because of (a) what appears to be a neutrino bug, with a fix proposed in https://github.com/lightninglabs/neutrino/pull/240, and (b) that neutrino `wallet.PublishTransaction` is blocking while `inv` requests go to peers and `getdata` responses come back, this PR attempts to avoid an unnecessary delay with BTC SPV when broadcasting transactions.
In all my observations, `PublishTransaction` uses the **entire** `neutrino.Config.BroadcastTimeout`, which is nearly an intolerable delay for many operations.
With neutrino as the wallet's chain service, its `chainClient.SendRawTransaction` call is blocking for up to `neutrino.Config.BroadcastTimeout` while peers either respond to the `inv` request with a `getdata`, or time out. However, in virtually all cases, we just need to know that btcwallet …
=> client/asset/btc: work around PublishTransaction delays

client/asset/eth/node.go, dex/networks/eth/params.go
dex/networks/eth: add LoadGenesisFile helper
client/asset/eth: use dexeth.LoadGenesisFile in startNode
I started this in experimenting with getting the `params.ChainConfig` for server-side use with a modified `FeeRate` estimate that uses separate tip and base fee rates rather than the [legacy transaction fee estimation method `suggestGasPrice`](https://github.com/ethereum/go-ethereum/blob/bc6bf1e1937829b5d5b0d431a9333d47c3e08082/internal/ethapi/api.go#L63-L64).  Draft: https://github.com/decred/dcrdex/commit/64a72b48fe3b05fcf8d5f4a7d9296496092967ac Although in that draft, I think the server would be just as well off using the base fee from the current best header rather than bothering to check with `consensus/misc.CalcBaseFee` using the `ChainConfig`, especially since just need an …
=> eth: LoadGenesisFile helper

client/webserver/locales/en-us.go, client/webserver/site/src/html/forms.tmpl, client/webserver/site/src/js/forms.js, client/webserver/site/src/js/register.js, client/webserver/site/src/js/settings.js, client/webserver/site/src/localized_html/en-US/forms.tmpl, client/webserver/site/src/localized_html/pt-BR/forms.tmpl, client/webserver/site/src/localized_html/zh-CN/forms.tmpl
- ui: Add a line on the wallet wait form that displays
tells the user to send enough funds to cover tx fee in
addition to the registration fee
- ui: Fix a bugs where balance updates for different assets
were displayed on the wallet wait form, and one where
if wallet was already synced when page loaded, but fee
not yet paid, the confirm registration page would not load
This contains the same bug fixes as #1401, but adds a generic instruction to send enough to cover tx fees instead of trying to estimate how much they will be.
=> ui: Fix wallet wait form issues

client/asset/btc/spv.go, client/asset/dcr/dcr.go, client/asset/dcr/externaltx.go
When using dcrwallet in SPV mode and trading with another party (not yourself), there are certain errors and warnings logged that are not of cause for concern.
Consider the following logs of a Buy DCR order where the counterparty is another wallet and thus the dcr ExchangeWallet takes a different path to getting confirmations and spend status of their swap transaction:
> 2022-01-11 15:11:15.432 [DBG] CORE[dcr]: Contract output c4aeefdaa9dae7ab66e909d7107480287d638501bca8550fc1d53f1107f055bd:0 NOT yet found, will attempt finding it with block filters.
> 2022-01-11 15:11:15.432 [DBG] CORE[dcr]: Searching for tx c4aeefdaa9dae7ab66e909d7107480287d638501bca8550fc1d53f1107f055bd in blocks between block 852084 (000000004e22a09d0970a087ac07865d1ddd3f696940585e1039b6dc5a823dc7) to the block just …
=> client/asset/dcr: suppress harmless coin-not-found errors with SPV

client/core/core.go, client/core/core_test.go, client/core/errors.go
This complements the frontend work in https://github.com/decred/dcrdex/pull/1401
Other consumers should be able to rely on `(*Core).Register` to ensure balance is sufficient before initiating a `'register'` request.
```
$  ./dexcctl -p abc --simnet wallets
[
{
"symbol": "dcr",
"assetID": 42,
"version": 0,
"type": "dcrwalletRPC",
"open": true,
"running": true,
"balance": {
"available": 0,
...
$  ./dexcctl -p abc --simnet register 127.0.0.1:17273 100000000 42 ~/dextest/dcrdex/rpc.cert
insufficient balance for fee 100000000, have 0, but need fee amount plus network fees
```
=> client/core: check balance before register

client/core/core.go, client/core/core_test.go
This contains a bare minimum resolution to https://github.com/decred/dcrdex/issues/1406 for the `release-v0.4` branch (for `master`, https://github.com/decred/dcrdex/pull/1413).  The "already connected" error will still be received on subsequent connect attempts, only resolvable by a `ReconfigureWallet` or dexc restart, but this will at least put the initial error, which went unseen previously except for ERR logging, in the notification menu.
=> [release-v0.4] client/core: notify of wallet connect errors in Login

client/asset/btc/spv.go, client/asset/dcr/dcr.go, client/asset/dcr/externaltx.go
Cherry-pick of https://github.com/decred/dcrdex/pull/1403 for `release-v0.4`
Do not return asset.CoinNotFoundError from SwapConfirmations with an
SPV wallet since this is normal for mempool transactions in SPV.
For a non-SPV wallet, if the swap appears spent but it cannot be
located in a block with a cfilters scan, this will return
asset.CoinNotFoundError. For SPV wallets, it is not an error if the
transaction cannot be located SPV wallets cannot see non-wallet
transactions until they are mined.
Fix a few logs where arguments were orderd strangely.
Also silence a warning that happens each time a transaction is
found in a block while looking for a spending transaction immediately
afterward.
=> [release-v0.4] client/asset/dcr: coin not found not an error for spv

client/core/core.go, client/webserver/live_test.go, client/webserver/site/src/js/app.js, client/webserver/site/src/js/forms.js, client/webserver/site/src/js/markets.js
```
We were expecting a SupportedAsset in some places where it wasn't guaranteed.
Update Application.unitInfo method to accept optional xc [core.Exchange] argument
from which to look for UnitInfo. Pass the arg in relevant contexts.
Use MarketsPage.market.{baseCfg,quoteCfg} [dex.Asset] instead of
{base,quote} [core.SupportedAsset] in book-related code. Fix omission in
(*Core).convertAssetInfo.
```
Resolves #1428
=> client/{core,ui}: Fix unit info and asset config usage on markets page

client/core/core.go, client/webserver/site/src/js/app.js, client/webserver/site/src/js/forms.js, client/webserver/site/src/js/markets.js
0.4 port of #1431
```
We were expecting a SupportedAsset in some places where it wasn't guaranteed.
Update Application.unitInfo method to accept optional xc [core.Exchange] argument
from which to look for UnitInfo. Pass the arg in relevant contexts.
Use MarketsPage.market.{baseCfg,quoteCfg} [dex.Asset] instead of
{base,quote} [core.SupportedAsset] in book-related code.
```
=> [0.4]client/{core,ui}: Fix unit info and asset id / symbol usage on markets page

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/interface.go, client/cmd/dexc/importlgpl.go, client/core/core.go, client/core/trade.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go
depends on #1314 
This is what it would look like to encode the coin as a string. However, this changes the order ID, I believe, as the funding coins are all serialized and become part of the id
https://github.com/decred/dcrdex/blob/986c765be89df6e45cae5ef538675b2700c7f7a9/dex/order/order.go#L536-L541
I think maybe another field for `msgjson.Trade` might be best and leave the coins alone? Like `FundingAddress`.
=> eth: Funding coin encoding.

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/asset/eth/eth.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/types.go, client/core/wallet.go, client/webserver/locales/en-us.go, client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/html/wallets.tmpl, client/webserver/site/src/js/wallets.js, client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl, client/webserver/site/src/localized_html/en-US/wallets.tmpl, client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl, client/webserver/site/src/localized_html/pt-BR/wallets.tmpl, client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl, client/webserver/site/src/localized_html/zh-CN/wallets.tmpl
Required for https://github.com/decred/dcrdex/pull/1374 and a future solution to the Send vs. Withdraw (or Sweep) issue in https://github.com/decred/dcrdex/pull/1355#discussion_r775917934
This PR adds a `client/core.WalletTrait` type that is a bitset communicating various optional functionality of a `client/asset.Wallet` in an `xcWallet` (via a new `core.WalletState` field).
As an initial application of the traits, this hides the ETH wallet's "New deposit address" button.
=> client/asset,webserver: wallet traits and hide eth new address button

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/nodeclient.go, client/asset/interface.go, client/cmd/dexc/config.go, client/cmd/dexc/log.go, client/core/trade.go, dex/logging.go, server/asset/eth/coiner.go, server/asset/eth/eth.go, server/asset/eth/eth_test.go, server/swap/swap.go
With these changes I was able to successfully swap.
A few of the current problems are pointed out.
=> eth: Fix init and redeem.

client/asset/btc/btc.go, client/asset/btc/spv.go, client/core/core.go, client/core/errors.go, client/core/wallet.go, client/rpcserver/handlers.go, client/rpcserver/rpcserver.go, client/rpcserver/rpcserver_test.go, client/rpcserver/types.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/js/wallets.js, client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl, client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl, client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl, client/webserver/webserver.go, client/webserver/webserver_test.go, dex/msgjson/types.go
Requires https://github.com/decred/dcrdex/pull/1383 (the **first commit** in this PR).
Three other commits added in this work:
**`client/asset/btc: add (*spvWallet).rescanWallet`**
Based on btcwallet's current approach for forcing a rescan, this drops all transactions in the wallet db and restarts the wallet.
**`rescanwallet` RPC** 
Trigger wallet recsan from dexcctl.
**client/webserver: rescanwallet http api and button handler**
Add a `(*WebServer).apiRescanWallet` for calling core's rescan wallet method.  Use the `WalletTrait`s that are now in `core.WalletState`.
**IMPORTANT NOTE:**  When you click "Rescan" it is an async process, so the sync status icon will appear and start updating percent.  Due to the issue we have remaining with the wallet birthday and the chain server syncing, it …
=> client: Add RescanWallet for BTC SPV, with RPC and HTTP API handlers.

server/swap/swap.go
There is an error log that happens when maker has a booked limit order that matches with a taker (partial) who fails to redeem:
```
2022-01-24 06:41:52.704 [TRC] SWAP: checkInactionEventBased: match 966b3aa51c4a9dcdb61adc89a13f0976cc3414da343e442ee78bd18c15fa7338 (MakerRedeemed)
2022-01-24 06:41:52.714 [DBG] SWAP: failMatch: swap 966b3aa51c4a9dcdb61adc89a13f0976cc3414da343e442ee78bd18c15fa7338 failing (maker fault = false) at MakerRedeemed
2022-01-24 06:41:52.824 [ERR] MKT: Finished swap 966b3aa51c4a9dcdb61adc89a13f0976cc3414da343e442ee78bd18c15fa7338 (qty 10000000000) for order 12b8a24fff2f7a98b3bb3d132261a21af781f7b0f24e9a4f8a13a4308de11d40 larger than current settling (0) amount.
2022-01-24 06:41:52.975 [DBG] AUTH: Registering outcome "no redeem as taker" (badness 1) for user …
```
=> server: Do not fail redeemed makers.

dex/networks/eth/params.go
ETHSwapV0 is on the Goerli Testnet.
=> dex/networks/eth: ETHSwapV0 testnet address

server/asset/btc/btc_test.go
Closes https://github.com/decred/dcrdex/issues/1408.
I can reproduce this panic by making `blockPollDelay` shorter in these unit-tests (see screenshot below). So extending this interval might help with encountering this `panic`.
From what I understand, the issue happens because these tests rely on timing (go-routine managing `time.Ticker` is not synchronised with the one running this test), and so `btc.blockCache` might not have the necessary block by the time `atHeight` gets called.
I've also checked tests for other assets, they shouldn't suffer from the same issue (DCR tests [explicitly sync block-cache](https://github.com/LasTshaMAN/dcrdex/blob/master/server/asset/dcr/dcr_test.go#L1245-L1269) and other coins don't have similar tests).
=> server/asset/btc: fix panic in BTC TestReorg

client/webserver/site/src/js/charts.js, dex/testing/dcrdex/harness.sh
testing/dcrdex: Reduce dcr/eth rate step. 
charts: Make sure regions are defined in render.
There was an apparent race between the resized method and render. If
render would happen first some elements that are initiated in resized
were not yet available, causing a js error and hang. Set those fields in
the constructor to avoid errors.
closes #1450,  closes #1357
I think this solves it.
I have not seen an error with the candle graph, so those changes may not be necessary. I think we se it with the normal graph because that is what we open the page to.
Also reduce the rate step in the simnet harness so the rates show.
=> charts: Make sure regions are defined in render.

client/webserver/site/src/js/markets.js
Doc's formatCoinValue will stick a comma in the value that we save to an
int field, causing it not to save at all, preventing four or more digit
coin values from being traded with my language settings. Prevent this by
using a simpler conversion that does not insert localized punctuation.
closes #1442
=> web/markets: Remove comma from field int value.

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/asset/eth/eth.go, client/asset/eth/eth_test.go, server/asset/eth/eth.go
The driver's DecodeCoinID function was attempting to parse the eth
coin's recovery address instead of the byte encoded address string.
Closes #1459.
=> client/asset/eth: Fix decode coin id

client/asset/eth/eth.go, client/asset/interface.go, client/core/trade.go
Further work on https://github.com/decred/dcrdex/issues/1311
This supplements the `swapRecipt` `String` method with the contract address, which in addition to the secret hash makes performing a manual refund more straightforward.
This also omits the raw refund transaction logging in `(*Core).swapMatchGroup` when the `Receipt.SignedRefund` provides no such data, as is the case with ETH.  The swap `Receipt`'s `Stringer` is still used here to log the secret hash and contract address for ETH `swapReceipts`.
=> eth: supplement eth swap receipt

client/core/core.go
This uses `(*xcWallet).setBalance` instead of directly assigning the balance. Even though the `xcWallet` is not in the `Core.wallets` map yet, this is necessary since `walletCheckAndNotify` is already running periodically in the sync status monitor goroutine, which calls `(*xcWallet).state` thus accessing the balance field.
Noticed in https://github.com/decred/dcrdex/pull/1439#issuecomment-1026199819
=> client/core: fix data race in ReconfigureWallet

client/core/core.go, client/core/core_test.go, client/core/wallet.go
For various reasons, some unknown, it is apparently quite common for wallet lock to hang either client shutdown or just logout.
This is particularly problematic because it leaves the user no choice but to hard kill the process, which may have undesirable consequences.   Even when it is just slow to lock, most users decide it's hung forever much sooner.  I'm estimating this threshold at around 5-10 seconds.
This PR wraps the `wallet.Lock` calls with a timeout contraption.  The individual implementations could also be modified with say a `context.Context` or a `time.Duration` argument, but in cases where the backend is not context enabled it ends up like this anyway, just with the backend worrying about this and the caller (core) being ultimately at the mercy of the backends actually doing …
=> client/core: allow wallet Lock to timeout

client/asset/dcr/dcr.go, client/asset/dcr/rpcwallet.go, client/core/core.go, dex/runner.go
Another alternative to https://github.com/decred/dcrdex/pull/1471, and the polar opposite approach to https://github.com/decred/dcrdex/pull/1413.  Unlike those, this just addresses the real issue, which is that dcrd's `rpcclient.Client` becomes unusable after `Shutdown`.  I had drafted this commit almost a month ago, but rejected it because I disliked the extra mutex, but given the state in an `xcWallet` or an `asset.Wallet` implementation like the `ExchangeWallet`s such as locked amounts, it's probably best just to solve it at the level of the `rpcWallet`.  If other assets have a similar constraint, they will have to adopt a similar solution.  e.g. BTC's wallet client does HTTP POST, and there's no issue there, but maybe eth would need special handling.
This allows the rpcclient to be …
=> client/asset/dcr: ensure rpcclient is fresh before Connect

client/cmd/dexc/version/version.go, client/cmd/dexcctl/version.go, pkg.sh, server/cmd/dcrdex/version.go
That'll be a patch release.  Immediately after this we should jump `master` to v0.5
The planned diff from v0.4.0 to v0.4.1: https://github.com/decred/dcrdex/compare/v0.4.0...d2c03e9ae35961c828624cd984cb5ef2de165c2a
=> bump v0.4.1

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/core/core.go
Pending outgoing funds were being previously incorrectly being added to the locked amount. This is no longer happening. Also, attempting to unlock more than is locked is no longer an error. The locked amount is just set to 0.
Closes #1460
=> client/asset/eth: Incorrect locked amount

docs/release-notes/release-notes-0.4.0.md
This updates the release notes from a v0.4 release candidate to the v0.4.0 tag.
This also includes some important language for upgrading Go consumers of `Core`.
When approved, I will create a GitHub "release" to go with the tag that was created on Jan 22.
=> docs: add dev Login note

client/asset/eth/eth.go, server/asset/eth/coiner.go
Save and return the value of a specific initiation rather than the
entire transaction value for validation later. This allows coins that
share a transaction to be matched separately.
closes #1469
=> eth/coiner: Save value of one initiation.

client/asset/eth/nodeclient.go
The v0 contract will reuse account nonces if the tx is not yet
confirmed. To avoid that get the next nonce from the light eth node pool
api while holding the nodeClient nonceSendMtx and set manually. Hold the
mutex until the tx has been sent or errors on sending.
closes  #1467
=> eth/nodeclient: Set contract nonces manually.

client/webserver/http.go, client/webserver/site/src/html/wallets.tmpl, client/webserver/site/src/js/wallets.js, client/webserver/site/src/localized_html/en-US/wallets.tmpl, client/webserver/site/src/localized_html/pl-PL/wallets.tmpl, client/webserver/site/src/localized_html/pt-BR/wallets.tmpl, client/webserver/site/src/localized_html/zh-CN/wallets.tmpl, client/webserver/webserver.go, go.mod, go.sum
=> webserver/ui: Generate QR codes for deposit address

client/asset/bch/bch.go, client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/externaltx.go, client/asset/dcr/simnet_test.go, client/asset/interface.go, client/core/bookie.go, client/core/core.go, client/core/core_test.go, client/core/trade.go, client/core/wallet.go
```
A FeeRater can generate fee suggestions when they are not validated by the
server, specifically for inputs to Withdraw, PayFee, Send, and
possibly Refund. This corresponds to places where
(*Core).feeSuggestionAny would be used.
```
=> client/{core,asset,btc,dcr}: Add FeeRater interface and WalletTraitFeeRater

client/webserver/site/src/js/markets.js
After clicking on the graph, no need to format the value from number to localized string because the rate input field has a number type.
Closes #1494
=> ui: Fix selecting prices over 1,000

client/asset/btc/btc.go, client/asset/dcr/dcr.go, client/asset/eth/eth.go, client/asset/interface.go, client/core/core.go, client/core/trade.go
This fix resolves a regression in 0.4 with the introduction of SPV wallets.
```
client/asset: Refund must indicate when spent
It is critical that asset.Wallet Refund signal to caller that it is
spent via asset.CoinNotFoundError so that it knows to begin looking
for the counterparty's redeem and move on to redeem as well.
This fixes dcr's refundTx so that it wraps asset.CoinNotFoundError
when lookupTxOutput indicates it is spent.
This also makes explicit the requirement for the asset.Wallet.Refund
method to return asset.CoinNotFoundError when spent.
client/core: allow more Refund errors to trigger redemption search
When locktime is expired, isRefundable will be true and thus block
the shouldBeginFindRedemption case in tick.  We handle this case
by having Refund errors signal when it is …
```
=> client: resolve failure to start redemption search

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/eth/eth.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/webserver/api.go, client/webserver/live_test.go, client/webserver/locales/en-us.go, client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/html/forms.tmpl, client/webserver/site/src/js/app.js, client/webserver/site/src/js/forms.js, client/webserver/site/src/js/register.js, client/webserver/site/src/js/settings.js, client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl, client/webserver/site/src/localized_html/en-US/forms.tmpl, client/webserver/site/src/localized_html/pl-PL/bodybuilder.tmpl, client/webserver/site/src/localized_html/pl-PL/forms.tmpl, client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl, client/webserver/site/src/localized_html/pt-BR/forms.tmpl, client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl, client/webserver/site/src/localized_html/zh-CN/forms.tmpl, client/webserver/types.go, client/webserver/webserver.go, client/webserver/webserver_test.go
- `client/core`: Add `EstimateRegistrationTxFee` function in core that determines the tx fee needed to register for the dex
- `client/asset`: Add `EstimateRegistrationTxFee` to wallet interface
- `client/webserver`: Add a new api endpoint `/regtxfee`
- `ui`: Each time the WalletWaitForm is loaded, this endpoint is called to retrieve an estimate
=> client/ui: Display registration tx fee estimate

client/websocket/websocket.go
This diff fixes panic described in #1496
Reproduction steps:
1. go to `/markets` page
2. shut down server
3. after client lost ws connection to the server, leave the `/markets` page. The first `unmarket` call from frontend will be served successfully and it will delete `cl.feed`.
4. go back to `/markets` page and leave it again. The `unmarket` request will fail because `cl.feed` is deleted earlier and `cl.feed.loop.Stop()` cause panic. 
Close #1496
=> Web: fix panic in `/markets`

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/trade.go, client/db/bolt/db.go, client/db/types.go
Previously, the funds needed for refunds were locked in `FundOrder` together with the funds needed for initiations, but they were unlocked when `Swap` was called with `LockChange = false`.  This diff applies the same logic we use to reserve funds for redemptions to refunds.
Prior to this PR, redemptions were being reserved using the server's max fee rate, but the redemption transaction was being submitted with the current fee rate estimate. This PR updates this to use the server's max fee rate when submitting the transaction as well. There is no reason to use a lower rate when submitting the transaction, as ETH uses dynamic transaction fees, and the entire fee will not be used anyways. The server's max fee rate is also used for refunds.
- `client/asset`: Rename `AssetRedeemer` interface …
=> client/core,eth: Lock funds for refund

client/webserver/site/src/html/bodybuilder.tmpl, client/webserver/site/src/js/markets.js, client/webserver/site/src/localized_html/en-US/bodybuilder.tmpl, client/webserver/site/src/localized_html/pl-PL/bodybuilder.tmpl, client/webserver/site/src/localized_html/pt-BR/bodybuilder.tmpl, client/webserver/site/src/localized_html/zh-CN/bodybuilder.tmpl
When swapping markets, this diff resets rate, lot and quantity input fields, and the total cost of trade text field.
Closes #1493
=> ui: Reset form when switching between markets

client/core/core.go, client/core/core_test.go, client/db/bolt/db.go, client/db/bolt/db_test.go, client/db/bolt/upgrades.go, client/db/interface.go, go.mod, go.sum
The latest revisions of bbolt expose DB compaction methods, which is necessary to reclaim any storage space from purged orders and matches from https://github.com/decred/dcrdex/pull/1475
https://github.com/etcd-io/bbolt/pull/248
This adds a compaction and custom backup file support to `client/db/boltdb.BoltDB`.
This also adds a `client/core.(*Core).BackupDB` method so Go consumers of `Core` may issue backup requests at any time.
```
2022-02-25 16:28:05.971 [INF] CORE[DB]: Backing up database...
2022-02-25 16:28:06.982 [INF] CORE[DB]: Compacting database...
2022-02-25 16:28:13.938 [INF] CORE[DB]: Compacted database from 1073156096 => 507797504 bytes (47.32% reduction)
```
=> client/db: compact DB on shutdown

client/core/core.go, client/core/trade.go
Resolves https://github.com/decred/dcrdex/issues/1489
```
When creating the swap transaction, see if a more current fee rate
should be used instead of the prescribed swap rate. This can be
particularly helpful for the taker because their swap may be a
long time after the match is made because the maker's swap must
be fully confirmed first.
If the current rate is swapRate < currentRate <= MaxFeeRate, then
use the current rate for the swap transaction.
```
We can also consider protocol changes where taker must get a new rate from server, and that will be enforced separately.
This current change is helpful even with that because it guards against server giving rates that are too low for whatever reason.
=> client/core: try a fresh fee rate for the init

dex/msgjson/types.go, server/asset/bch/bch.go, server/asset/btc/btc.go, server/asset/common.go, server/asset/dcr/dcr.go, server/asset/driver.go, server/asset/eth/eth.go, server/asset/ltc/ltc.go, server/auth/auth.go, server/cmd/dexcoin/main.go, server/db/driver/pg/upgrades.go, server/dex/dex.go, server/market/balancer.go, server/market/balancer_test.go, server/market/market.go, server/market/market_test.go, server/market/orderrouter.go, server/market/routers_test.go, server/swap/swap_test.go
```
Add RegisterToken method for token registration. The asset package
keeps a map of tokens as well as the token "fee families", e.g. all
tokens of a base chain asset.
DEXBalancer.CheckBalance reworked to account for fee-family assets.
```
=> server/{market,asset}: token registration and balance checks

client/core/core.go
Core will inject some data into the settings map, so make sure it always
exists even if not included in the create form.
Solves a bug introduced by 32721d830 that causes a panic for eth.
=> client/core: Always create a settings map.

client/asset/btc/spv.go, client/core/account.go, client/core/bookie.go, client/core/core.go, client/core/errors.go, client/core/errors_test.go, client/webserver/api.go, client/webserver/webserver_test.go
This difff makes errors more user-oriented.
1. It modifies `core.Error` type to support error wrapping and unwrapping.
2. It adds an `Unwarp()` method to `core.Error` type.
3. Adds an ` UnwrapErr(err error) error` function that unwraps until it finds a non-wrapped error.
4. Adds tests for `core.Error` type.
5. Modify error strings in `webserver_test.go`.
6. Adds `%w` directive to errors constructed with `core` `newError(...)`.
Moving forward it would be nice to wrap errors that might end up being shown to users via client, detailed errors messages are logged to the terminal while errors shown via client are unwrapped. 
**Update**: Errors created using `core` `newError(...)` should be wrapped using the `%w` directive when necessary.
Now:
Closes #1488.
=> client/core: Make errors user oriented

client/core/core.go, client/core/types.go, dex/msgjson/types.go, server/asset/btc/script.go, server/asset/dcr/script.go, server/auth/auth.go, server/auth/registrar.go
This is stage 1 of the signature message truncation fix plan outlined https://github.com/decred/dcrdex/pull/1526.
In these commits, both client and server begin recognizing signatures of both the truncated messages or the message hash.  Neither side begins signing the message hash.  After this has been deployed to servers, the next stage (https://github.com/decred/dcrdex/pull/1529) has the client begin creating signatures of the hashed messages.
=> start recognizing signatures of the hashed messages (sig fix stage 1)

client/core/core.go
This diff properly formats wallet sync status.
Closes #1514
=> fix inconsistent wallet sync status

dex/ws/wslink.go, dex/ws/wslink_test.go, server/auth/auth_test.go, server/comms/link.go, server/comms/server.go, server/market/bookrouter.go, server/market/routers_test.go
In order to avoid marshalling the same message multiple times when
sending to multiple clients, marshal once and send the raw bytes.
closes #1478
=> server/wslink: Add SendRaw.

client/webserver/site/src/html/forms.tmpl, client/webserver/site/src/localized_html/en-US/forms.tmpl, client/webserver/site/src/localized_html/pl-PL/forms.tmpl, client/webserver/site/src/localized_html/pt-BR/forms.tmpl, client/webserver/site/src/localized_html/zh-CN/forms.tmpl
This diff limits config file extensions supported to `.conf`, `.cnf`, `.cfg`, `.ini`. closes #182
=> webserver/site: limit config file extensions supported

client/asset/btc/btc.go, client/asset/btc/livetest/livetest.go
This fixes the client btc (and clone) "livetest" simnet tests, and makes the `asset.Wallet` API usable without a server or oracle providing the txData of the counterparty contract.  `Core` should still always provide txData, but in general this is a needless limitation that I have had to confront in several contexts recently.
```
When AuditContract was switched to a hard requirement of txData
(the raw tx bytes), it broke certain simnet tests where no server was
available to provide the data, and made the asset.Wallet API somewhat
incomplete with no way to retrieve this txData in either full node or
SPV mode because there is no method to do so.  This makes a redeem
cli tool or other use case with no server or txdata oracle extremely
cumbersome because the raw bytes are required as an input …
```
=> client/asset/btc: attempt audit with empty txdata

client/asset/btc/btc_test.go, client/asset/ltc/ltc.go, client/asset/ltc/regnet_test.go, dex/networks/bch/params.go, dex/networks/btc/clone.go, dex/networks/ltc/params.go, server/asset/ltc/ltc.go
Rebased on https://github.com/decred/dcrdex/pull/1553 so the "livetest" simnet test can actually succeed.
```
This switches the LTC code to using and requiring segwit features.
This bumps the asset version to 1.  Note that we do not have a good
method for supporting multiple asset versions simultaneously, but
we can punt on that since LTC has not been deployed on mainnet
anywhere to my knowledge.
```
The client has asset version checks and will simply refuse an order if the server and client asset version does not match.
See discussion about possible client support for multiple asset versions here: https://github.com/decred/dcrdex/pull/1054#discussion_r616266089
=> ltc: switch to segwit

server/db/driver/pg/internal/matches.go, server/db/driver/pg/matches.go, server/db/driver/pg/matches_online_test.go, server/db/interface.go, server/market/market_test.go, server/swap/swap.go, server/swap/swap_test.go
This PR contains three closely related updates to `Swapper` to improve the handling of matches around broadcast timeout and contract expiration.
**server/swap: wait for init/redeem for full wait expiration** https://github.com/decred/dcrdex/pull/1541/commits/bf2001c857cd4de4796256b939ece8151d50b6b8
```
In handleInit and handleRedeem, do not bother to limit the expiration
time of the processInit/processRedeem waiters by the broadcast timeout.
Both of the TryFuncs (processInit and processRedeem) will respond in
error if the match is revoked, so there is no need to tweak the waiter's
expire time.
This will prevent a client request timeout when the init or redeem is
submitted just before the Swapper revokes the match, when the waiter's
expire time could be set to the past despite the inaction …
```
=> server/swap: better contract expiry edge case handling

client/core/core_test.go, client/core/trade.go
Complementary to https://github.com/decred/dcrdex/pull/1541, this includes client-side checks.
In particular, `(*trackedTrade).counterPartyConfirms` checks if the contract is expired and returns an `expired bool`.  The callers (`isSwappable` and `isRedeemable`) consider the expired status in the same way they already consider spent status -- self-revoke and return false to the spendable/redeemable check.  Specifically, this happens _only_ in the `order.TakerSwapCast` && `order.Maker` condition of `isRedeemable`, and in the `order.MakerSwapCast` && `order.Taker` condition of `isSwappable`.
Note that in the first scenario above of the maker deciding if the taker's contract is redeemable, it is quite important not to redeem an expired contract.  This is true for either actor since the …
=> client/core: consider contract expiry before acting

client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/externaltx.go, client/asset/dcr/rpcwallet.go, client/asset/dcr/wallet.go, go.mod, go.sum, run_tests.sh
```
Use wire types for the Wallet interface rather than rpc types. This
is a necessary step towards a built-in wallet. Previous discussion in
1278.
```
=> client/asset/dcr: simplify dcr.Wallet interface

client/asset/eth/contractor.go, client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/eth/fundingcoin.go, client/asset/eth/fundingcoin_test.go, client/asset/eth/nodeclient.go, client/asset/eth/nodeclient_harness_test.go, client/asset/interface.go
Preparing for tokens. Peeled off of #1399.
```
Moves contractor from nodeClient to ExchangeWallet. The changes the
ethFetcher API quite a bit, but is overall a simplification. To accomplish
this, I moved the nonceSendMtx to from nodeClient to ExchangeWallet too.
Nonce generation and signing is moved into nodeClient.txOpts to dedupe.
Use block headers instead of full blocks for tip monitoring.
Simplify fundingCoin and eliminate fundingCoinID.
Simplify tests using more consts and simpler structs.
```
=> client/asset/eth: token prefactor

client/cmd/dexc/config.go, client/cmd/dexc/main.go, client/core/account.go, client/core/account_test.go, client/core/core.go, client/core/core_test.go, client/webserver/site/src/css/market.scss, client/webserver/site/src/css/orders.scss, client/webserver/site/src/html/wallets.tmpl, client/webserver/site/src/localized_html/en-US/wallets.tmpl, client/webserver/site/src/localized_html/pl-PL/wallets.tmpl, client/webserver/site/src/localized_html/pt-BR/wallets.tmpl, client/webserver/site/src/localized_html/zh-CN/wallets.tmpl, server/cmd/dcrdex/config.go, server/cmd/dcrdex/main.go, server/comms/middleware.go, server/comms/server.go
This introduces special handling for dex hosts with .onion host names.
Deployed to the dex-test.ssgen.io (**testnet**) server under the host name **dextesttaggpdj27s26wklczemovhqdzyvgokyumey33uemlw4imawqd.onion**.
No TLS is used with the dedicated .onion listener, and as such the client should not specify a TLS certificate.  The onion protocol provides end-to-end encryption and identification via the ed25512 key pair.  The hostname itself is all the certification that is needed AFAICT.
You can either make a new account or disable any existing dex-test.ssgen.io account and add the .onion host in its place.  If you had an account already, account discovery works as expected despite the changed host name (server is identified by it's signing key pair, not the TLS junk used for plain internet …
=> hidden service / .onion dex support

client/webserver/site/src/js/order.ts
Make eth coin ids link to etherscan on the orders page.
Closes #1559
=> app/order: Link ETH coin ids to Etherscan

client/asset/eth/eth.go, client/asset/eth/eth_test.go, client/asset/interface.go, client/core/core.go, client/core/core_test.go, client/core/trade.go
For account based coins, let core use the Reserve and Unlock methods to
handle redemption and refund reserves for assets that use them. This
solves a minor bug where redemption funds are not unlocked for a tracked
trade that is redeemed normally.
closes #1539
=> client: Let core handle redeem and refund locking.

client/asset/dcr/rpcwallet.go
=> client/dcr: Unlock wallet if acct not encrypted.

client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/asset/dcr/externaltx.go, client/asset/dcr/rpcwallet.go, client/asset/dcr/wallet.go
Resolves https://github.com/decred/dcrdex/issues/1587
```
The mainchain and valid returns from (*ExchangeWallet).blockHeader were
switched.  This flips them correctly.
This also changes the way a block is detected as side chain by checking
the Confirmations field of the getblockverbose result instead of
requesting the hash of the block at the same height and comparing
the hashes.  A side chain block will have -1 for Confirmations.
This also changes the way the next block is retrieved for stakeholder
approval checking.  Instead of requesting the hash of the block at the
next height, use the NextHash field returned by getblockverbose.
This saves an RPC, but it is also more robust since there is no need
to use strings.Contains on the error returned from getblockhash
to detect if there is no …
```
=> client/asset/dcr: fix side chain and approval checks

client/asset/btc/btc.go, client/asset/btc/btc_test.go, client/asset/dcr/dcr.go, client/asset/dcr/dcr_test.go, client/core/account_test.go, client/core/core.go, client/core/core_test.go
<s>Rebased on https://github.com/decred/dcrdex/pull/1528</s>
This is stage 2 of the signature message truncation fix plan outlined in https://github.com/decred/dcrdex/pull/1526.
In these commits, client begins signing the hashed messages, but **continues to recognize the buggy signatures** from the server.  This is because the while the server understands the correct hashed message signatures [as of stage 1](https://github.com/decred/dcrdex/pull/1528), it is still sending the old signatures with its messages.
This work can be backported to a 0.4.3+ release if https://github.com/decred/dcrdex/pull/1528 has been deployed with 0.4.2.
In the next stage, the server begins sending the correct signatures.
=> client: sign and verify hashed messages (sig fix stage 2)
